import type { TechHub } from '../../lib/types';
import { resourceGrammarLesson } from './lessons/the-resource-grammar';
import { payloadEconomyLesson } from './lessons/the-payload-economy';
import { hierarchyCourtLesson } from './lessons/the-hierarchy-court';
import { transferAltarLesson } from './lessons/the-transfer-altar';
import { problemDocketLesson } from './lessons/the-problem-docket';
import { readingWindowLesson } from './lessons/the-reading-window';
import { epochLedgerLesson } from './lessons/the-epoch-ledger';
import { linkBazaarLesson } from './lessons/the-link-bazaar';
import { contractCourtLesson } from './lessons/the-contract-court';

export const restHub: TechHub = {
  slug: 'rest' as never,
  name: 'REST',
  icon: '🗂️',
  tagline: {
    en: 'Nouns name the world, methods move it, refusals have type, walks have bookmarks, eras have sunsets, and the contract has an address the machines can read.',
    bn: 'বিশেষ্য জগতের নামায়, পদ্ধতি তা সরায়, প্রত্যাখ্যানের ধরন আছে, ভ্রমণের বুকমার্ক আছে, যুগের অবসান আছে, আর চুক্তির এমন ঠিকানা আছে, যা যন্ত্র পড়তে পারে।',
  },
  intro: {
    en: 'REST is the web’s public grammar, and this hub walks it as a chained courtroom where every bench prices what the platform owes strangers. Lesson one, THE RESOURCE GRAMMAR, holds the noun system: collections and items alternate, PUT/POST’s naming asymmetry, the status grammar with its 201+Location birth certificate, and the router-lint that moves taste into CI. Lesson two, THE PAYLOAD ECONOMY, prices the traffic: cursor versus offset under writes, filter/sort/expand as server-side grammar, Idempotency-Key as retry treaty, 429+Retry-After as honest budgets, sparse fieldsets for cellular readers. Then the staircase deepens. THE HIERARCHY COURT tries naming’s second question — which noun owns which: the three-question diagnosis (dies-with, needs-name, inherits-permissions), the sovereignty default, path-is-identity/query-is-presentation, and the corridor as a legal claim priced per hop. THE TRANSFER ALTAR consecrates the verbs themselves: PUT’s whole-truth oath (omission is retraction, priced in wiped price-lists), PATCH’s two licensed dialects (Merge Patch’s scalpel-null against JSON Patch’s atomic script of tests), POST’s two lawful jurisdictions (creation at the collection, controller-as-exception), and the concurrency liturgy that connects 412s to re-reads. THE PROBLEM DOCKET gives the NO its citizenship: RFC 9457’s five fields (type/title/status/detail/instance), court-selection statutes, the add-only error catalog, and the two frauds executed in debug — silence-as-200 and folklore-by-message. THE READING WINDOW prices the sequence: offset’s snapshot myth versus cursor’s living bookmark, the seek pattern’s constant-depth work, page-size as capacity statute, deep-paging frauds and the 4-GB mornings. THE EPOCH LEDGER governs time itself: versions as named eras, additive vs breaking vs sneaky-breaking change classes, announce-inhabit-surface-inter with brownouts as scheduled rehearsals, and the zero-residence commandment before any era inters. THE LINK BAZAAR leases the map: hypermedia as next-moves-data, affordances against references, HAL and JSON:API and Siren priced as dialects, the chattiness invoice and the five back-office machines that keep the bazaar honest. And THE CONTRACT COURT closes the circuit: OpenAPI as the upstream statute every artifact derives from (docs, mocks, SDKs, validators, the scholar’s diff, contract tests), two rigs running north and south, consumer-driven expectations as the signature line, and the hub’s own verdict — what the platform owes, bench by bench, handed to the GraphQL bench where the client picks up the pen.',
    bn: 'REST হলো ওয়েবের প্রকাশ্য-ব্যাকরণ, আর এই হাব তা হাঁটায় শৃঙ্খলাকৃত-দরবাররূপে, যেখানে প্রতি বেঞ্চ মূল্য দেয় অপরিচিতদের কাছে প্ল্যাটফর্ম কী পাওনা। প্রথম পাঠ, রিসোর্স-ব্যাকরণ, ধরে রাখে বিশেষ্য-পদ্ধতি: সংগ্রহ আর একক পালাক্রমে, PUT/POST-এর নামকরণ-অপ্রতিসমতা, 201+Location জন্ম-সনদসহ স্ট্যাটাস-ব্যাকরণ, আর রাউটার-লিন্ট যা স্বাদ সরিয়ে নেয় CI-তে। দ্বিতীয় পাঠ, পেলোড-অর্থনীতি, মূল্য দেয় যানজটের: লেখার নিচে কার্সর বনাম অফসেট, সার্ভারপার্শ-ব্যাকরণরূপে ফিল্টার/সাজানো/expand, রিট্রাই-চুক্তিরূপে Idempotency-Key, সৎ-বাজেটরূপে 429+Retry-After, সেলুলার-পাঠকের জন্য স্পার্স-ফিল্ডসেট। তারপর সিঁড়ি গভীর হয়। স্তর-দরবার বিচার করে নামকরণের দ্বিতীয় প্রশ্ন — কোন বিশেষ্য কার মালিক: তিন-প্রশ্ন-রোগনির্ণয় (সাথে-মরে, নাম-চাই, অনুমতি-উত্তরাধিকার), সার্বভৌম-ডিফল্ট, পথ-পরিচয়/কোয়েরি-উপস্থাপন, আর মোড়প্রতি-মূল্যায়িত-দাবিরূপে করিডোর। স্থানান্তর-বেদী পবিত্র করে ক্রিয়াগুলোকেই: PUT-এর পূর্ণ-সত্য-শপথ (বাদ-পড়া হলো প্রত্যাহার, মুছে-ফেলা-মূল্য-তালিকায় মূল্যায়িত), PATCH-এর দুই লাইসেন্সকৃত-ভাষা (Merge Patch-এর কর্তন-null বনাম JSON Patch-এর পরীক্ষাসহ-পারমাণবিক-লিপি), POST-এর দুই বৈধ এখতিয়ার (সংগ্রহে সৃষ্টি, ব্যতিক্রমরূপে-কন্ট্রোলার), আর সমবর্তিতা-উপাসনা যা 412-কে পুনঃপাঠের সঙ্গে সংযুক্ত করে। সমস্যা-পর্ব না-কে দেয় নাগরিকতা: RFC 9457-এর পাঁচ ক্ষেত্র (type/title/status/detail/instance), আদালত-বাছাই-বিধান, কেবল-যোগ-ত্রুটি-সংকলন, আর ডিবাগে কার্যকরিত দুই প্রতারণা — 200-রূপে-নীরবতা আর বার্তায়-লোককথা। পাঠ-জানালা মূল্য দেয় ধারার: অফসেটের স্ন্যাপশট-কল্পকথা বনাম কার্সরের জীবন্ত-বুকমার্ক, সিক-প্যাটার্নের স্থির-গভীরতা-কাজ, ক্ষমতা-বিধানরূপে পৃষ্ঠা-আকার, গভীর-পৃষ্ঠায়ন-প্রতারণা আর ৪-গিগাবাইটের সকাল। যুগ-খাতা শাসন করে স্বয়ং সময়কে: নামকৃত-যুগরূপে সংস্করণ, সংযোজনমূলক বনাম ভাঙনকারী বনাম চুরচুরি-ভাঙনকারী-শ্রেণি, তপসিলকৃত-মহড়ারূপে ব্রাউনআউটসহ ঘোষণা-বসবাস-দৃশ্যমানকরণ-সমাধি, আর যে-কোনো যুগ সমাধিস্থ হওয়ার আগে শূন্য-বসবাস-আদেশ। সংযোগ-হাট মানচিত্র ইজারা দেয়: পরবর্তী-চাল-তথ্যরূপে হাইপারমিডিয়া, রেফারেন্সের বিনিময়ে সুবিধা, ভাষাদলরূপে মূল্যায়িত HAL আর JSON:API আর Siren, কথাবাহুল্য-চালান আর পাঁচটি পশ্চাদ্‌-কার্যালয়-যন্ত্র যা হাটকে সৎ রাখে। আর চুক্তি-দরবার বর্তনী বন্ধ করে: ঊর্ধ্বপ্রবাহের-বিধিগ্রন্থরূপে OpenAPI, যা থেকে প্রতি দলিল উদ্ভূত (ডক, মক, SDK, বৈধকরক, পণ্ডিতের ডিফ, চুক্তি-পরীক্ষা), উত্তরে ও দক্ষিণে চলমান দুই রিগ, স্বাক্ষর-রেখারূপে ভোক্তা-চালিত-প্রত্যাশা, আর হাবের নিজস্ব রায় — বেঞ্চপ্রতি প্ল্যাটফর্ম কী পাওনা, GraphQL-বেঞ্চে হস্তান্তর, যেখানে ক্লিয়েন্ট কলম তুলে নেয়।',
  },
  lessons: [
    resourceGrammarLesson,
    payloadEconomyLesson,
    hierarchyCourtLesson,
    transferAltarLesson,
    problemDocketLesson,
    readingWindowLesson,
    epochLedgerLesson,
    linkBazaarLesson,
    contractCourtLesson,
  ],
  references: [
    {
      group: { en: 'The naming benches', bn: 'নামকরণ-বেঞ্চ' },
      items: [
        { term: 'nouns own URIs', def: { en: '/products, /products/42, /orders/7/items — alternate collection/item, plural down the corridor, depth ≤ 3 advised, no verb segment ever. Cover the method; the URI alone must still name the thing.', bn: '/products, /products/42, /orders/7/items — সংগ্রহ/একক পালাক্রমে, করিডোরজুড়ে বহুবচন, গভীরতা ≤ 3 পরামর্শিত, কখনো ক্রিয়া-খণ্ড নয়। পদ্ধতি ঢাকুন; URI একাই জিনিসটার নাম বলবে।' } },
        { term: 'the three-question diagnosis', def: { en: 'Nesting lawful iff: child dies with parent, child needs ancestor in its name, permissions inherit down the corridor. Deny one → sovereign collection + relationship in the representation.', bn: 'নেস্টিং বৈধ যদি-কেবল: সন্তান অভিভাবকের সাথে মরে, নামে পূর্বসূরি চাই, অনুমতি করিডোর-নিচে উত্তরাধিকারে আসে। একটি অস্বীকৃত → সার্বভৌম-সংগ্রহ + রূপায়ণে সম্পর্ক।' } },
        { term: 'path is identity, query is presentation', def: { en: 'Left of the question-mark names WHICH resource; right of it shapes HOW the answer is engraved — filters, sorts, fields, pages live east of it, never verbs or identities.', bn: 'প্রশ্ন-চিহ্নের বাঁদিক নামায় কোন রিসোর্স; ডানদিক আকৃতি দেয় উত্তর কেমন খোদাই হবে — ছাঁকনি, সাজানো, ক্ষেত্র, পৃষ্ঠা থাকে পূর্বে, কভু ক্রিয়া বা পরিচয় নয়।' } },
        { term: 'POST↔PUT naming asymmetry', def: { en: 'POST at a collection mints server-named children (201+Location); PUT at the final name is client-named creation/replacement (safe under retry, If-None-Match:* for create-or-fail).', bn: 'সংগ্রহে POST মুদ্রণ করে সার্ভার-নামকৃত সন্তান (201+Location); চূড়ান্ত-নামে PUT হলো ক্লায়েন্ট-নামকৃত সৃষ্টি/প্রতিস্থাপন (রিট্রাইতে-নিরাপদ, সৃষ্টি-নয়তো-ব্যর্থের জন্য If-None-Match:*)।' } },
      ],
    },
    {
      group: { en: 'The verbs and the NO', bn: 'ক্রিয়া ও না' },
      items: [
        { term: 'PUT whole-truth oath', def: { en: 'PUT replaces the resource with the representation sent: omitted fields are retracted. A partial-PUT incident wipes siblings silently — 422 partial portraits at the schema door, always.', bn: 'PUT রিসোর্স প্রতিস্থাপন করে প্রেরিত-রূপায়ণে: বাদ-পড়া ক্ষেত্র প্রত্যাহৃত। আংশিক-PUT-ঘটনা ভাইবোন নীরবে মুছে দেয় — স্কিমা-দুয়ারে অর্ধ-প্রতিকৃতি 422, সবসময়।' } },
        { term: 'PATCH two dialects', def: { en: 'Merge Patch: objects merge, null scalpels, arrays replace whole. JSON Patch: a script of ops — test is the precondition, evaluation atomic all-or-nothing. Only JSON Patch reaches inside a positioned array.', bn: 'Merge Patch: অবজেক্ট মিলায়, null কর্তন করে, অ্যারে পুরো প্রতিস্থাপন করে। JSON Patch: কাজের লিপি — test হলো পূর্বশর্ত, মূল্যায়ন পারমাণবিক সব-নয়তো-কিছুই-নয়। অবস্থানযুক্ত-অ্যারের ভেতরে কেবল JSON Patch পৌঁছায়।' } },
        { term: 'problem+json citizens', def: { en: 'type (stable URI identity) · title (static per type) · status (mirrors the line) · detail (this docket’s sentence) · instance (subpoena address) + errors[] annex at 422. Refusals as rich as successes.', bn: 'type (স্থির URI-পরিচয়) · title (প্রতি-ধরনে-স্থির) · status (লাইনের প্রতিবিম্ব) · detail (এই দস্তুরের বাক্য) · instance (সমন-ঠিকানা) + 422-এ errors[] সংযোজনী। প্রত্যাখ্যান সাফল্যের মতোই সমৃদ্ধ।' } },
        { term: '412 is a queue slip', def: { en: 'Expired justification, not error: re-read (GET), re-decide (intent against the new world), resubmit with the new If-Match. Identical resubmission is the insanity verdict.', bn: 'মেয়াদোত্তীর্ণ-ন্যায়সংগততা, ত্রুটি নয়: পুনঃপাঠ (GET), পুনঃসিদ্ধান্ত (নতুন জগতের বিপরীতে অভিপ্রায়), নতুন If-Match-সহ পুনর্জমা। হুবহু পুনর্জমা হলো উন্মাদতা-রায়।' } },
      ],
    },
    {
      group: { en: 'The walk and its book', bn: 'ভ্রমণ ও তার বই' },
      items: [
        { term: 'cursor vs offset', def: { en: 'Offset addresses a frozen snapshot the world refuses to provide (duplicated encounters, missed rows under writes). Cursor is a living bookmark into a totally-ordered stable key — walk survives the writing.', bn: 'অফসেট ঠিকানা দেয় এমন হিমায়িত-স্ন্যাপশটে, যা জগৎ দিতে অস্বীকার করে (লেখার নিচে দ্বিগুণকৃত-সাক্ষাৎ, হারানো সারি)। কার্সর হলো পূর্ণ-ক্রমাঙ্কিত-স্থির-চাবিতে-ছেদকৃত জীবন্ত বুকমার্ক — ভ্রমণ লেখা টিকে থাকে।' } },
        { term: 'the seek pattern', def: { en: 'WHERE (created_at, id) < (?, ?) ORDER BY both DESC LIMIT n+1 — constant work per page at any depth, versus OFFSET scanning-then-dropping the skipped rows. The +1 row is the next-page probe, free of COUNT.', bn: 'WHERE (created_at, id) < (?, ?) ORDER BY দুটোই DESC LIMIT n+1 — যে-কোনো গভীরে পৃষ্ঠাপ্রতি স্থির কাজ, বনাম OFFSET স্ক্যান-করে-ফেলে-দেওয়া এড়ানো-সারি। যোগ-আরেক-সারি হলো পরের-পৃষ্ঠা-প্রোব, COUNT-মুক্ত।' } },
        { term: 'page size as capacity statute', def: { en: 'Default ≈50, max ≈200, measured at serialization cost and enforced at the LAST boundary (the response marshaller — an envelope circuit by size, never a bypassable route rule).', bn: 'ডিফল্ট ≈50, সর্বোচ্চ ≈200, সিরিয়ালাইজেশন-খরচে মাপা আর শেষ সীমান্তে জরুরিকৃত (প্রতিক্রিয়া-মার্শালার — আকারে খাম-বর্তনী, বাইপাসযোগ্য রুট-বিধি কভু নয়)।' } },
        { term: 'expired bookmark → 410', def: { en: 'Cursor expiry IS the consistency window. Answer expired tokens with 410 + restart token annex — the on-purpose court — never 400-generic.', bn: 'কার্সর-মেয়াদ হলোই সামঞ্জস্য-জানালা। মেয়াদোত্তীর্ণ টোকেনের উত্তর 410 + পুনঃসূচনা-টোকেন-সংযোজনী — ইচ্ছাকৃত-আদালত — কভু 400-সাধারণ নয়।' } },
      ],
    },
    {
      group: { en: 'Eras and their funerals', bn: 'যুগ ও তাদের অন্ত্যেষ্টি' },
      items: [
        { term: 'additive vs breaking', def: { en: 'Additive: any change the old assertion-set tolerates without client action (optional fields, endpoints, params). Breaking: any change demoting a lawful old client into rulebreaker (removals, renames, tightens, semantic flips).', bn: 'সংযোজনমূলক: যে পরিবর্তন পুরনো দাবি-সেট ক্লায়েন্ট-কর্মহীনভাবেও সহ্য করে (ঐচ্ছিক ক্ষেত্র, এন্ডপয়েন্ট, প্যারাম)। ভাঙনকারী: যে পরিবর্তন বৈধ পুরনো-ক্লায়েন্টকে নামিয়ে দেয় বিধিভাঙা অবস্থায় (অপসারণ, পুনর্নামকরণ, কঠোরীকরণ, অর্থ-উল্টো)।' } },
        { term: 'sneaky-breaking', def: { en: 'Additive-shaped, world-breaking: new enum values to strict deserializers, default changes, validation tightenings, faster 429s. Treated as breaking wherever the old assertion-set was strict.', bn: 'সংযোজন-আকৃতির, জগৎ-ভাঙা: গোঁড়া-ডিসিরিয়ালাইজারে নতুন enum-মান, ডিফল্ট-পরিবর্তন, বৈধকরণ-কঠোরীকরণ, দ্রুততর 429। গণ্য ভাঙনকারীরূপে, যেখানে পুরনো দাবি-সেট গোঁড়া ছিল।' } },
        { term: 'the lifecycle', def: { en: 'ANNOUNCE (Deprecation+Sunset headers, registry rows) → INHABIT (residence census per client-corridor) → SURFACE (scheduled brownouts) → INTER (410 + problem document) — zero-residence observed before anything is revoked.', bn: 'ঘোষণা (Deprecation+Sunset হেডার, রেজিস্ট্রি-সারি) → বসবাস (ক্লায়েন্ট-করিডোরপ্রতি বসবাস-পরিগণনা) → দৃশ্যমানকরণ (তপসিলকৃত ব্রাউনআউট) → সমাধি (410 + সমস্যা-দলিল) — কিছুই প্রত্যাহারের আগে পর্যবেক্ষিত শূন্য-বসবাস।' } },
        { term: 'four vehicles', def: { en: 'Path (/v1) visible & cache-native, header (X-API-Version) pure with iron Vary, media-type doctrinaire, date-epochs (Stripe-Version) client-pinned per account. Chosen per docket: long integrations get pinned eras.', bn: 'পথ (/v1) দৃশ্যমান ও ক্যাশ-জাত, হেডার (X-API-Version) লোহার-Varyসহ বিশুদ্ধ, মিডিয়া-টাইপ মতবাদীয়া, তারিখ-যুগ (Stripe-Version) অ্যাকাউন্টপ্রতি-ক্লায়েন্টপিনকৃত। দস্তুরমতো বাছাই: দীর্ঘ-ইন্টিগ্রেশন পায় পিনকৃত-যুগ।' } },
      ],
    },
    {
      group: { en: 'The map and the law', bn: 'মানচিত্র ও আইন' },
      items: [
        { term: 'rel is identity', def: { en: 'The link relation is the machine contract: aggregable, frozen at mint, add-only forever, versioned explicitly. href is the coordinate (mutable); title is display (volatile). rel outranks both in court.', bn: 'লিংক-সম্পর্ক হলো যন্ত্রে-চুক্তি: সমষ্টিযোগ্য, মুদ্রণে-হিমায়িত, চিরকাল কেবল-যোগ, স্পষ্টভাবে সংস্করণায়িত। href হলো স্থানাঙ্ক (পরিবর্তনযোগ্য); title হলো প্রদর্শন (উদ্দীপ্যমান)। দরবারে rel উভয়ের চেয়ে উচ্চপদস্থ।' } },
        { term: 'affordance vs reference', def: { en: 'Reference: WHERE a fact lives. Affordance: WHAT may change (method+fields as contract, edges minted per-envelope per-bearer — policy shipped per answer, never per deploy).', bn: 'রেফারেন্স: তথ্য থাকে কোথায়। সুবিধা: কী বদলাতে পারে (চুক্তিরূপে method+fields, প্রান্ত খামপ্রতি-বহনকারীপ্রতি মুদ্রিত — নীতি উত্তরপ্রতি চালিত, ডিপ্লয়প্রতি কভু নয়)।' } },
        { term: 'design-first spine', def: { en: 'The OpenAPI document as upstream law: handlers, docs, mocks, SDKs, validators, the diff, fixtures all derived — drift structurally impossible because disagreement is CI-visible from commit one.', bn: 'ঊর্ধ্বপ্রবাহ-আইনরূপে OpenAPI-দলিল: হ্যান্ডলার, ডক, মক, SDK, বৈধকরক, ডিফ, ফিক্সার সব উদ্ভূত — ড্রিফট কাঠামোগতভাবে অসম্ভব, কারণ অসম্মতি প্রথম কমিট থেকেই CI-দৃশ্যমান।' } },
        { term: 'two rigs', def: { en: 'North rig: spec→stub→validators→diff→fixtures (shapes honored by construction). South rig: consumer expectation documents in a broker, run in deploy CI (needs honored by vote). A contract with only one rig has one signature.', bn: 'উত্তর-রিগ: স্পেক→স্টাব→বৈধকরক→ডিফ→ফিক্সার (নির্মাণেই আকৃতি সম্মানিত)। দক্ষিণ-রিগ: ব্রোকারে ভোক্তা-প্রত্যাশা-দলিল, ডিপ্লয়-CI-তে চালিত (ভোটে চাহিদা সম্মানিত)। এক-রিগের চুক্তিতে একটি স্বাক্ষরই থাকে।' } },
      ],
    },
  ],
  roadmap: [
    { stage: 1, title: { en: 'Nouns before verbs', bn: 'ক্রিয়ার আগে বিশেষ্য' }, detail: { en: 'The resource grammar: collections/items alternation, the cover-test, POST/PUT naming asymmetry, status grammar with 201+Location and 204 civility, router-lint as CI data.', bn: 'রিসোর্স-ব্যাকরণ: সংগ্রহ/একক পর্যাবৃত্তি, কভার-পরীক্ষা, POST/PUT নামকরণ-অপ্রতিসমতা, 201+Location ও 204-সভ্যতাসহ স্ট্যাটাস-ব্যাকরণ, CI-ডেটারূপে রাউটার-লিন্ট।' } },
    { stage: 2, title: { en: 'Price the payload', bn: 'পেলোডের মূল্য' }, detail: { en: 'The payload economy: cursor vs offset, filter/sort/expand as URI grammar, Idempotency-Key treaty, 429+Retry-After budgets, sparse fieldsets.', bn: 'পেলোড-অর্থনীতি: কার্সর বনাম অফসেট, URI-ব্যাকরণরূপে ফিল্টার/সাজানো/expand, Idempotency-Key-চুক্তি, 429+Retry-After-বাজেট, স্পার্স-ফিল্ডসেট।' } },
    { stage: 3, title: { en: 'Try the corridor', bn: 'করিডোরের বিচার' }, detail: { en: 'The hierarchy court: three-question diagnosis, sovereignty default, path=identity/query=presentation, composite-key confessions, the route register and its five derived artifacts.', bn: 'স্তর-দরবার: তিন-প্রশ্ন-রোগনির্ণয়, সার্বভৌম-ডিফল্ট, পথ=পরিচয়/কোয়েরি=উপস্থাপন, সম্মিলিত-চাবি-স্বীকারোক্তি, রুট-রেজিস্টার ও পাঁচটি উদ্ভূত দলিল।' } },
    { stage: 4, title: { en: 'Swear at the altar', bn: 'বেদীতে শপথ' }, detail: { en: 'The transfer altar: PUT whole-truth oath; PATCH in Merge Patch + JSON Patch with test-ops; POST two jurisdictions; 412 as re-read-and-re-decide; 202 async liturgy for long mutations.', bn: 'স্থানান্তর-বেদী: PUT পূর্ণ-সত্য-শপথ; Merge Patch + test-কাজসহ JSON Patch-এ PATCH; POST দুই এখতিয়ার; পুনঃপাঠ-ও-পুনঃসিদ্ধান্তরূপে 412; দীর্ঘ-রূপান্তরে 202 অসিঙ্ক-উপাসনা।' } },
    { stage: 5, title: { en: 'Author the NO', bn: 'না রচনা' }, detail: { en: 'The problem docket: court-first court-selection (400/401/403/404/409/412/422/429), the five constitutional fields, errors[] annex, error catalog add-only, normalize middleware, observability by type.', bn: 'সমস্যা-পর্ব: আদালত-আগে-বাছাই (400/401/403/404/409/412/422/429), পাঁচ সাংবিধানিক ক্ষেত্র, errors[] সংযোজনী, কেবল-যোগ ত্রুটি-সংকলন, নরমালাইজ-মিডলওয়্যার, ধরনে পর্যবেক্ষণ।' } },
    { stage: 6, title: { en: 'Walk by bookmark', bn: 'বুকমার্কে ভ্রমণ' }, detail: { en: 'The reading window: cursor with stable key, limit+1 probe, page-size capacity statute, filters/sorts as declared contracts, seek under the hood, snapshot doctrine for exports.', bn: 'পাঠ-জানালা: স্থির-চাবিতে কার্সর, limit+1 প্রোব, পৃষ্ঠা-আকার ক্ষমতা-বিধান, ঘোষিত-চুক্তিরূপে ফিল্টার/সাজানো, নিচে সিক, এক্সপোর্টের জন্য স্ন্যাপশট-মতবাদ।' } },
    { stage: 7, title: { en: 'Keep the epochs', bn: 'যুগ রক্ষণ' }, detail: { en: 'The epoch ledger: additive/sneaky/breaking classification, deprecation lifecycle with brownouts, zero-residence commandment, vehicle choice per docket, projection layer honesty.', bn: 'যুগ-খাতা: সংযোজন/চুরচুরি/ভাঙনকারী-শ্রেণিবিন্যাস, ব্রাউনআউটসহ অবচিতকরণ-জীবনচক্র, শূন্য-বসবাস-আদেশ, দস্তুরমতো বাহন-বাছাই, প্রক্ষেপণ-স্তরের সততা।' } },
    { stage: 8, title: { en: 'Lease the map', bn: 'মানচিত্র ইজারা' }, detail: { en: 'The link bazaar: rel as identity, affordances as per-envelope state edges, HAL/JSON:API/Siren priced, embedding policy and depth caps, link integrity CI and the observability bridge.', bn: 'সংযোগ-হাট: পরিচয়রূপে rel, খামপ্রতি-অবস্থা-প্রান্তরূপে সুবিধা, মূল্যায়িত HAL/JSON:API/Siren, এম্বেডিং-নীতি ও গভীরতা-সীমা, লিংক-অখণ্ডতা-CI আর পর্যবেক্ষণ-সেতু।' } },
    { stage: 9, title: { en: 'Give law an address', bn: 'আইনকে ঠিকানা দিন' }, detail: { en: 'The contract court: design-first spine, stub-first development, mock pilots, scholar’s diff on every PR, two rigs + consumer expectations, the dashboard that displays the constitution in motion.', bn: 'চুক্তি-দরবার: নকশা-আগে মেরুদণ্ড, স্টাব-আগে-উন্নয়ন, মক-পাইলট, প্রতি PR-এ পণ্ডিতের ডিফ, দুই রিগ + ভোক্তা-প্রত্যাশা, চলমান সংবিধান প্রদর্শনকারী যন্ত্রফলক।' } },
  ],
  projects: [
    {
      title: { en: 'RouteCourt: the register-driven corridor linter', bn: 'রুটকোর্ট: রেজিস্টরিচালিত করিডোর-লিন্টার' },
      brief: { en: 'Build the audit wall as working software: a route-register file (path, methods, owner, nested-diagnosis verdict, alias tier) plus a CI linter that blocks PRs with verb-segments, singular-plural mixes, depth violations, query-shape trespasses — and a quarterly report that re-runs the three-question diagnosis per nested corridor. Ship fixtures: ten corridor rows, three convicts, two remands; the register must also generate the docs skeleton and the gateway path-rules from the same rows.', bn: 'নিরীক্ষণ-প্রাচীর বানান কার্যকর-সফটওয়্যারে: রুট-রেজিস্টার-ফাইল (পথ, পদ্ধতি, মালিক, নেস্টেড-রোগনির্ণয়-রায়, অ্যালিয়াস-স্তর) যোগ CI-লিন্টার, যা ক্রিয়া-খণ্ড, একবচন-বহুবচন-মিশ্রণ, গভীরতা-মূল্য, কোয়েরি-আকৃতি-অতিক্রমসহ PR বাধা দেয় — আর ত্রৈমাসিক প্রতিবেদন, যা প্রতি নেস্টেড-করিডোরে তিন-প্রশ্ন-রোগনির্ণয় পুনচালায়। ফিক্সার দিন: দশ করিডোর-সারি, তিন অভিযুক্ত, দুই প্রহরাকৃত; রেজিস্ট্রিকে একই সারি থেকে ডক-কাঠামো ও গেটওয়ে-পথ-বিধিও উৎপন্ন করতে হবে।' },
      difficulty: 'intermediate',
    },
    {
      title: { en: 'The Problem Mint: a refusal factory with a catalog', bn: 'সমস্যা-মুদ্রালয়: সংকলনসহ প্রত্যাখ্যান-কারখানা' },
      brief: { en: 'Implement the full problem-docket rig in your framework of choice: an error-catalog (add-only; type → title/status/retryable/remediation rows), a normalize middleware that converts every failure shape into problem+json with instance minting, the errors[] annex for 422s, registry-derived SDK error classes, and a metrics lint that flags any aggregate keyed on message text. Score with a test suite proving: status-honesty (never 200-with-failure), court-boundary discipline (400 vs 422 vs 409), and i18n-safe title localization with frozen types.', bn: 'আপনার বাছাইকৃত ফ্রেমওয়ার্কে পূর্ণ সমস্যা-দস্তুর-রিগ বাস্তবায়ন করুন: ত্রুটি-সংকলন (কেবল-যোগ; type → title/status/retryable/remediation সারি), নরমালাইজ-মিডলওয়্যার যা প্রতি ব্যর্থতা-আকৃতি problem+json-এ রূপান্তর করে instance-মুদ্রণসহ, 422-এর জন্য errors[] সংযোজনী, রেজিস্ট্রি-উদ্ভূত SDK-ত্রুটি-শ্রেণি, আর মেট্রিক্স-লিন্ট যা বার্তা-পাঠে-চাবিকৃত যে-কোনো সমষ্টি চিহ্নিত করে। পরীক্ষা-স্যুট দিয়ে প্রমাণ দিন: স্ট্যাটাস-সততা (কভু ত্রুটিসহ-200 নয়), আদালত-সীমানা-শৃঙ্খলা (400 বনাম 422 বনাম 409), আর হিমায়িত-type নিয়ে i18n-নিরাপদ title-স্থানীয়করণ।' },
      difficulty: 'intermediate',
    },
    {
      title: { en: 'Conductor: the sunset machine you can publish', bn: 'পরিচালক: প্রকাশযোগ্য অবসান-যন্ত্র' },
      brief: { en: 'Build the sunset conductor as a row-driven state machine: era registry rows (corridor, vehicle, sunset_at, grace), announcement headers computed from rows, a brownout scheduler with rollback timers, residence-furnace counters per (client-fingerprint, corridor, era), the 410 problem document generator emitting epoch-closed types with migration links, and the zero-residence revocation gate. The whole lifecycle must run end-to-end on fixtures (one 30-minute accelerated sunset) without a human touching anything after the registry write.', bn: 'অবসান-পরিচালক বানান সারিচালিত-অবস্থা-যন্ত্ররূপে: যুগ-রেজিস্ট্রি-সারি (করিডোর, বাহন, sunset_at, কৃপা), সারি থেকে গণিত ঘোষণা-হেডার, রোলব্যাক-টাইমারসহ ব্রাউনআউট-শিডিউলার, (ক্লায়েন্ট-ফিঙ্গারপ্রিন্ট, করিডোর, যুগ)-প্রতি বসবাস-চুল্লি-গণক, মাইগ্রেশন-লিংকসহ যুগ-সমাপ্ত-ধরন নির্গমনকারী 410 সমস্যা-দলিল-জেনারেটর, আর শূন্য-বসবাস-প্রত্যাহার-দুয়ার। পুরো জীবনচক্র অবশ্যই চলবে ফিক্সারে একেবারে-শেষে (৩০-মিনিটের ত্বরান্বিত অবসান), রেজিস্ট্রি-লিখনের পর মানুষের কিছু স্পর্শ ছাড়াই।' },
      difficulty: 'advanced',
    },
  ],
  bestPractices: [
    { en: 'Cover the method, read the URI aloud: if you cannot still name the thing, the name is smuggling a verb — and the cover test belongs in your lint, not in your onboarding documents.', bn: 'পদ্ধতি ঢেকে URI জোরে পড়ুন: তবুও জিনিসটির নাম বলতে না-পারলে, নামটি ক্রিয়া পাচার করছে — আর কভার-পরীক্ষা থাকা উচিৎ আপনার লিন্টে, অনবোর্ডিং-নথিতে নয়।' },
    { en: 'Swear the whole truth at PUT or leave the name alone: omissions are retractions on that wire; partial edits go to PATCH with its two licensed dialects, never to a forgiving PUT.', bn: 'PUT-এ পূর্ণ-সত্য শপথ করুন নয়তো নাম থেকে বিরত থাকুন: সেই তারে বাদ-পড়া হলো প্রত্যাহার; আংশিক-সম্পাদনা যায় PATCH-এ তার দুই লাইসেন্সকৃত-ভাষায়, ক্ষমাকারী PUT-এ কভু নয়।' },
    { en: 'Make every refusal a citizen: type (stable URI), title (static), status (mirrored), detail (docket sentence), instance (receipt) — and 422 always carries the prosecution annex with field addresses.', bn: 'প্রতি প্রত্যাখ্যান করুন নাগরিক: type (স্থির URI), title (স্থির), status (প্রতিবিম্বিত), detail (দস্তুরের বাক্য), instance (রসিদ) — আর 422 সবসময় বহন করে ক্ষেত্র-ঠিকানাসহ অভিযোগ-সংযোজনী।' },
    { en: 'Pick your page doctrine by write rate, never by taste: tables written while read get cursors (stable key, seek pattern, limit+1 probe); snapshots and shallow UI tables keep offset — depth-capped, always.', bn: 'পৃষ্ঠা-মতবাদ বাছুন লেখা-হারে, স্বাদে কভু নয়: পড়ার সময়ই লেখা সারণি পায় কার্সর (স্থির চাবি, সিক-প্যাটার্ন, limit+1 প্রোব); স্ন্যাপশট ও অগভীর UI-টেবিল রাখে অফসেট — গভীরতা-সীমিত, সবসময়।' },
    { en: 'Run every mutation through the mint: Idempotency-Key on POST creations and controllers, If-Match on PUT/PATCH — the first guards retry fraud, the second guards lost updates; both are cheap.', bn: 'প্রতি রূপান্তর চালান মুদ্রালয় দিয়ে: POST-সৃষ্টি ও কন্ট্রোলারে Idempotency-Key, PUT/PATCH-এ If-Match — প্রথমটি রিট্রাই-প্রতারণা রক্ষা করে, দ্বিতীয়টি হারানো-হালনাগাদ; দুটোই সস্তা।' },
    { en: 'Never close an era in silence: Deprecation+Sunset as wire instruments, residence counted by name, brownouts as scheduled rehearsals, and interment only after observed weeks of zero.', bn: 'কভু যুগ নীরবতায় শেষ করবেন না: তার-হিস্তনাদরূপে Deprecation+Sunset, নাম ধরে গণিত বসবাস, তপসিলকৃত-মহড়ারূপে ব্রাউনআউট, আর সমাধি কেবল শূন্যের পর্যবেক্ষিত সপ্তাহের পর।' },
    { en: 'Mint links per envelope, per bearer: rel as identity, edges only where state and policy allow, embedding policy registered with depth caps — the renderer at the boundary owns every link, and handlers never mint one.', bn: 'মুদ্রণ করুন লিংক খামপ্রতি, বহনকারীপ্রতি: পরিচয়রূপে rel, প্রান্ত কেবল সেখানে যেখানে অবস্থা ও নীতি অনুমতি দেয়, রেজিস্ট্রিকৃত এম্বেডিং-নীতি গভীরতা-সীমাসহ — সীমান্তের রেন্ডারার প্রতি লিংকের মালিক, হ্যান্ডলার কভু একটিও মুদ্রণ করে না।' },
    { en: 'Give the contract an address the machines read first: the OpenAPI spine as upstream law, stubs derived, mocks regenerated per commit, the scholar’s diff on every PR — and consumer expectations running in the same deploy pipeline.', bn: 'চুক্তিকে দিন এমন ঠিকানা, যা যন্ত্র আগে পড়ে: ঊর্ধ্বপ্রবাহ-আইনরূপে OpenAPI-মেরুদণ্ড, উদ্ভূত স্টাব, প্রতি কমিটে পুনরুৎপন্ন মক, প্রতি PR-এ পণ্ডিতের ডিফ — আর একই ডিপ্লয়-পাইপলাইনে চলমান ভোক্তা-প্রত্যাশা।' },
  ],
  interview: [
    {
      q: { en: 'When do you nest a resource — /users/1/orders versus /orders?user=1?', bn: 'কখন রিসোর্স নেস্ট করবেন — /users/1/orders বনাম /orders?user=1?' },
      a: { en: 'Ask the court’s three questions. Existence: does the child die with the parent (account deleted → orders deleted)? Identity: does the child need the ancestor inside its name to mean anything? Permission: do the parent’s permissions inherit straight down? Affirm all three and nesting is a contract (/orders/7/items is its canonical shape); deny even one and the resource is sovereign: top-level collection, relationship carried in the representation ({ user: "/users/1" }) or in a one-hop view corridor where authorization conveniently runs. The trap answers: nesting because “the schema has a foreign key” (a storage mirroring is not a naming claim), or flattening because “REST docs prefer shallow” (dogma, not doctrine). And the priced line from the bench: depth is rented — every hop re-derives permissions, multiplies cache-invalidation blast radius at renames, and sells your composite keys to every bookmark holder on earth.', bn: 'দরবারের তিন প্রশ্ন জিজ্ঞেস করুন। অস্তিত্ব: সন্তান কি অভিভাবকের সাথে মরে (অ্যাকাউন্ট মুছলে → অর্ডার মুছে)? পরিচয়: সন্তানের নামে পূর্বসূরি থাকা কি অর্থের জন্য দরকার-ই? অনুমতি: অভিভাবকের অনুমতি কি সোজা নিচে উত্তরাধিকারে আসে? তিনটিই সত্য হলে নেস্টিং চুক্ত (/orders/7/items তার প্রচলিত আকৃতি); একটি-ও অস্বীকৃত হলে রিসোর্স সার্বভৌম: শীর্ষ-স্তরীয় সংগ্রহ, সম্পর্ক বহিত রূপায়ণে ({ user: "/users/1" }) অথবা সুবিধাজনক-অনুমোদন-চালু এক-মোড়ের দৃষ্টি-করিডোরে। ফাঁদ-উত্তর: নেস্টিং কারণ “স্কিমাতে বিদেশি-চাবি আছে” (সঞ্চয়-আয়না নামকরণ-দাবি নয়), অথবা সমতলকরণ কারণ “REST-ডক অগভীর পছন্দ করে” (কুসংস্কার, মতবাদ নয়)। আর বেঞ্চের মূল্যায়িত পংক্তি: গভীরতা ভাড়া নেওয়া — প্রতি মোড় অনুমতি পুনরুদ্ভূত করে, পুনর্নামকরণে ক্যাশ-অকার্যকরণের ধ্বংস-ব্যাসার্ধ গুণায়, আর আপনার সম্মিলিত-চাবি পৃথিবীর প্রতি বুকমার্ক-ধারকের কাছে বিক্রি করে দেয়।' },
    },
    {
      q: { en: 'PUT vs PATCH — when each, and what breaks if you blur them?', bn: 'PUT বনাম PATCH — কখন কোনটি, আর গুলিয়ে ফেললে কী ভাঙে?' },
      a: { en: 'PUT is the whole-truth oath: the client proposes the resource’s complete next portrait; omitted fields are RETRACTIONS, so the sender must hold full state (which is why the loop is GET → compose → PUT with If-Match, and why the write is idempotent by statute — retrying the same portrait is free). PATCH is licensed surgery, and it has two dialects with different physics: Merge Patch for object shapes (merge recursively, null scalpels a field out, but arrays replace WHOLE — unreachable single elements) and JSON Patch for anything position-sensitive (a script of add/remove/replace/move/copy/test with the test op as precondition and all-or-nothing atomicity). Blur them and you inherit one of the two dockets: partial-PUT folklore nullifies every sibling the editor did not show (the price-list incident), or Merge Patch onto a positioned array forces a mini-PUT with different orthography — and never solves test-preconditions. Rule of thumb for the bench: replace-purpose with total state → PUT; edit-purpose on flat shapes → Merge Patch; anything touching arrays, invariants-in-script, or conditional edits → JSON Patch.', bn: 'PUT হলো পূর্ণ-সত্য-শপথ: ক্লায়েন্ট রিসোর্সের সম্পূর্ণ পরবর্তী-প্রতিকৃতি প্রস্তাব করে; বাদ-পড়া ক্ষেত্র প্রত্যাহার, তাই প্রেরককে পূর্ণ-অবস্থা ধরতেই হবে (তাই চক্র GET → রচনা → PUT সাথে If-Match, আর লেখাটি বিধানত-অবিচ্ছেদ্য — একই প্রতিকৃতি রিট্রাই বিনামূল্যে)। PATCH হলো লাইসেন্সকৃত শল্যক্রিয়া, আর তার দুই ভাষার পদার্থবিদ্যা আলাদা: অবজেক্ট-আকৃতিতে Merge Patch (পুনরাবৃত্তভাবে মিশ্রণ, null ক্ষেত্র কর্তন, কিন্তু অ্যারে সমগ্র প্রতিস্থাপন — একক উপাদানে পৌঁছানো যায় না) আর অবস্থান-সংবেদনশীল যা-কিছুতে JSON Patch (add/remove/replace/move/copy/test-এর লিপি, test-কাজ পূর্বশর্তরূপে আর সব-নয়তো-কিছুই-নয় পারমাণবিকতাসহ)। গুলিয়ে ফেললে দুই দস্তুরের একটি উত্তরাধিকার পান: আংশিক-PUT-লোকবিশ্বাস সম্পাদকের-না-দেখা প্রতি ভাইবোন শূন্য করে দেয় (মূল্য-তালিকা-ঘটনা), অথবা অবস্থানযুক্ত-অ্যারেতে Merge Patch আপনাকে জোর করে মিনি-PUT, ভিন্ন বানানরীতিতে — আর test-পূর্বশর্ত কভু সমাধান করে না। বেঞ্চের থাম্ব-রুল: পূর্ণ-অবস্থাসহ প্রতিস্থাপন-উদ্দেশ্য → PUT; সমতল আকৃতিতে সম্পাদনা-উদ্দেশ্য → Merge Patch; অ্যারে-স্পর্শী, লিপিতে-অপরিবর্তনীয়, বা শর্তসহ-সম্পাদনা → JSON Patch।' },
    },
    {
      q: { en: 'Offset or cursor pagination — and how do you defend the choice in review?', bn: 'অফসেট না কার্সর পৃষ্ঠায়ন — আর বাছাই রিভিউতে রক্ষা করবেন কীভাবে?' },
      a: { en: 'By write rate and by walk duration, stated as arithmetic. OFFSET is correct for snapshots and shallow human corridors (UI tables, page numbers people click, reads over frozen exports: SQL-native, bookmarkable, cheap to explain). It breaks exactly where its assumption breaks — position is a claim about a world that keeps moving: a mid-walk insert duplicates boundary rows into the next page (DUPLICATED ENCOUNTERS: real rows, counted twice), a delete skips rows entirely (MISSED ROWS: silent undercount, reconciliation labor forever), and deep pages are a fraud of work (OFFSET 40000×50 scans and consigns two million rows to serve fifty). CURSOR is correct for living datasets and machine walks: the key is a total order with a stable anchor (id or created_at+id), the server mints opaque expiring bookmarks, the page is WHERE key > last-seen ORDER BY key LIMIT n+1 — constant work at any depth, insert/delete tolerant, and the +1 row answers “is there a next page” without a COUNT. In review you defend it with the bench’s litmus: does the walk duration overlap the write rate? If yes → cursor or pinned snapshot (REPEATABLE READ at the replica); if the walk is three clicks of a shallow table → offset with a depth cap. And you state the honest deficit of cursor: no jump-to-page-37, expiry is a consistency window to design and document, and tokens are bearer positions, never credentials — page privacy must be re-acquired through the same authorization chain on every page.', bn: 'লেখা-হার আর ভ্রমণ-কাল দিয়ে, পাটিগণিতরূপে বর্ণিত। অফসেট সঠিক স্ন্যাপশট আর অগভীর মানব-করিডোরে (UI-টেবিল, ক্লিক করা পৃষ্ঠা-সংখ্যা, হিমায়িত-এক্সপোর্টের পাঠ: SQL-জাত, বুকমার্কযোগ্য, ব্যাখ্যা করা সস্তা)। তা ভাঙে হুবহু সেখানে যেখানে তার ধারণা ভাঙে — অবস্থান হলো চলমান-জগতের দাবি: মাঝ-ভ্রমণ-সন্নিবেশ সীমান্ত-সারি দ্বিগুণ করে পরের পৃষ্ঠায় (দ্বিগুণকৃত সাক্ষাৎ: প্রকৃত সারি, দুইবার গণিত), মুছে-ফেলা সম্পূর্ণ বাদ দেয় সারি (হারানো সারি: নীরব অধোগণনা, চিরকালের মিলকরণ-শ্রম), আর গভীর পৃষ্ঠা কাজের প্রতারণা (OFFSET 40000×50 স্ক্যান করে খালাস দেয় বিশ লাখ সারি, পরিবেশনের জন্য পঞ্চাশ)। কার্সর সঠিক জীবন্ত ডেটাসেট আর যান্ত্রিক-ভ্রমণে: চাবি স্থির-নোঙরযুক্ত পূর্ণ-ক্রম (id বা created_at+id), সার্ভার অস্বচ্ছ-মেয়াদী বুকমার্ক মুদ্রণ করে, পৃষ্ঠা হলো WHERE key > last-seen ORDER BY key LIMIT n+1 — যে-কোনো গভীরে স্থির কাজ, সন্নিবেশ/মুছে-ফেলা-সহ্য, আর যোগ-সারি উত্তর দেয় “পরের পৃষ্ঠা আছে কি” COUNT ছাড়াই। রিভিউতে তা রক্ষা বেঞ্চের লিটমাস দিয়ে: ভ্রমণ-কাল কি লেখা-হারের সাথে মিলে যায়? হ্যাঁ হলে → কার্সর বা পিনকৃত-স্ন্যাপশট (রেপ্লিকায় REPEATABLE READ); অগভীর টেবিলের তিন ক্লিক হলে → গভীরতা-সীমাসহ অফসেট। আর বলুন কার্সরের সৎ ঘাটতি: ৩৭-পৃষ্ঠায় ঝাঁপ নেই, মেয়াদ হলো নকশা-করা সামঞ্জস্য-জানালা যা নথি ভুক্ত করতেই হয়, আর টোকন হলো বহনকারী-অবস্থান, শংসাপত্র নয় — প্রতি পৃষ্ঠায় পৃষ্ঠা-গোপনীয়তা একই অনুমোদন-শৃঙ্খলা দিয়ে পুনর্অর্জন করতেই হয়।' },
    },
    {
      q: { en: 'How do you retire an API version without breaking your top partners?', bn: 'আপনার শীর্ষ পার্টনারদের না ভেঙে API-সংস্করণ অবসর করবেন কীভাবে?' },
      a: { en: 'By lifecycle, not by announcement. ANNOUNCE as wire data: Deprecation: true and Sunset: <http-date> on every response from the aging corridor, a registry row minted with the sunset date, migration doc published — inbox-based channels are the audiovisual side, never the instrument. INHABIT: stand up the residence census at the gateway — counters per (client-fingerprint, corridor, era), so “who still lives here” is a named dashboard list, not an estimate. SURFACE: scheduled brownouts — short deliberate 503 windows (e.g. ninety minutes every Tuesday, Retry-After set, problem body pointing at the migration doc) converting silent laggards into loud tickets while rollback is cheap; the last thirty days add concierge outreach to the top-N residents by name. INTER: at the sunset date, 410 Gone with a typed problem document (epoch-closed type, migration link, sunset timestamp logged). REVOKE: only after the resident-count-zero commandment — seven consecutive observed weeks of zero residence before the route rules are actually removed. The two counter-dockets worth citing: never a silent tightening (validation tightened inside one era is a breaking change — the Tuesday incident), and never a folklore sunset (blog posts and emails are what the zombie-epoch incident priced); everything lives in the registry, every instrument is code, the conductor survives the author’s vacation.', bn: 'জীবনচক্রে, ঘোষণায় নয়। তার-তথ্যরূপে ঘোষণা: প্রতি বার্ধক্যগত-করিডোর-প্রতিক্রিয়ায় Deprecation: true ও Sunset: <http-date>, অবসান-তারিখসহ মুদ্রিত রেজিস্ট্রি-সারি, প্রকাশিত মাইগ্রেশন-নথি — ইনবক্সভিত্তিক চ্যানেল হলো শ্রুতিগোচর-পার্শ, কভু হিস্তনাদ নয়। বসবাস: গেটওয়েতে বসবাস-পরিগণনা চালু করুন — (ক্লায়েন্ট-ফিঙ্গারপ্রিন্ট, করিডোর, যুগ)-প্রতি গণক, যাতে “এখানে এখনো কে বাস করে” হলো নামকৃত-ড্যাশবোর্ড-তালিকা, অনুমান নয়। দৃশ্যমানকরণ: তপসিলকৃত ব্রাউনআউট — সংক্ষিপ্ত ইচ্ছাকৃত-503-জানালা (যেমন প্রতি মঙ্গলবার দেড় ঘণ্টা, Retry-After বসানো, মাইগ্রেশন-ডকে নির্দেশকারী সমস্যা-বডি), নীরব পশ্চাদপদকে জোরালো টিকিটে বদলে দেয়, যখন রোলব্যাক সস্তা; শেষ ত্রিশ দিনে শীর্ষ-N-বাসিন্দাকে নাম ধরে দ্বারক-সহযোগিতা। সমাধি: অবসান-তারিখে 410 Gone, টাইপকৃত সমস্যা-দলিলসহ (যুগ-সমাপ্ত-ধরন, মাইগ্রেশন-লিংক, লগকৃত অবসান-টাইমস্ট্যাম্প)। প্রত্যাহার: কেবল শূন্য-বসবাস-আদেশের পর — সাত পরপর পর্যবেক্ষিত শূন্য-বসবাস-সপ্তাহের পর রুট-বিধি আসলে সরানো হয়। উদ্ধৃত-যোগ্য দুই প্রতি-দস্তুর: কভু নীরব-কঠোরীকরণ নয় (একই যুগের ভেতরে বৈধকরণ-কঠোরীকরণ হলো ভাঙনকারী-পরিবর্তন — মঙ্গলবারের ঘটনা), আর কভু লোককথা-অবসান নয় (ব্লগ-পোস্ট আর ইমেইল হলো সেটি, যাকে জম্বি-যুগ-ঘটনা মূল্য দিয়েছে); সবকিছু থাকে রেজিস্ট্রিতে, প্রতি যন্ত্র কোড, লেখকের ছুটি টিকিয়েও পরিচালক টিকে থাকে।' },
    },
    {
      q: { en: 'Server-driven (REST+HATEOAS) or client-driven (GraphQL): how do you actually decide?', bn: 'সার্ভারচালিত (REST+HATEOAS) না ক্লায়েন্টচালিত (GraphQL): আসলে সিদ্ধান্ত নেবেন কীভাবে?' },
      a: { en: 'By dominant constraint, never by theology. HYPERMEDIA wins where the work is governed workflows: your domain is state machines clients must traverse (order → payment → fulfillment; loan application → decision → disbursement), where the presently-lawful edges mutate per state, per bearer, per regulatory window. The document itself mints the edges (refund exists only when refundable; scope-filtered by caller), so clients follow relations instead of reconstructing flows — and your reorgs stop breaking their code. GRAPHQL wins where the dominant constraint is read-variance: thirty client surfaces each wanting a different grain of the same data (mobile three fields, ERP forty joins, analytics sub-feeds), where “one fixed shape per endpoint” bills everyone overfetch-and-chatty walks — the client composing its own question from a typed schema is the cheaper house. The rest of the verdict: internal-closed clients (your own SPA) profit least from either extreme (you carry both sides of the coupling), while public long-lived strangers profit most from whichever instrument keeps your evolution off their incident board: rel-stability for the bazaar, schema-add-only discipline for the graph. In review, you name the docket your dominant constraint lives in, you price the other philosophy’s three bills anyway (chattiness vs author-time; gate-duplication vs flow-decay), and you write it down as an ADR — the judge cares less about your verdict than about your court being open.', bn: 'প্রধান সীমাবদ্ধতায়, ধর্মতত্ত্বে কভু নয়। হাইপারমিডিয়া জেতে যেখানে কাজ শাসিত-কর্মপ্রবাহ: আপনার ডোমেইন হলো ক্লায়েন্টদের অতিক্রম্য অবস্থা-যন্ত্র (অর্ডার → পেমেন্ট → পূরণ; ঋণ-আবেদন → সিদ্ধান্ত → বিতরণ), যেখানে বর্তমান-বৈধ প্রান্ত বদলায় অবস্থাপ্রতি, বহনকারীপ্রতি, নিয়ন্ত্রক-জানালাপ্রতি। দলিলটিই প্রান্ত মুদ্রণ করে (কেবল রিফান্ডযোগ্য হলেই refund থাকে; আহ্বায়ক ধরে সুযোগ-ছাঁকনিকৃত), তাই ক্লায়েন্ট প্রবাহ পুনর্গঠনের বদলে সম্পর্ক অনুসরণ করে — আর আপনার পুনর্গঠন তাদের কোড ভাঙা থামায়। GraphQL জেতে যেখানে প্রধান সীমাবদ্ধতা পাঠ-বৈচিত্র্য: ত্রিশ ক্লায়েন্ট-পৃষ্ঠতল, প্রত্যেকে একই ডেটার ভিন্ন দানা চায় (মোবাইলে তিন ক্ষেত্র, ERP-তে চল্লিশ যোজনা, বিশ্লেষণ-উপফিড), যেখানে “প্রতি এন্ডপয়েন্টে এক স্থির আকৃতি” সবাইকে বিল দেয় অতি-ফেচ ও কথাবাহুল্য-ভ্রমণে — টাইপকৃত-স্কিমা থেকে নিজের প্রশ্ন রচনা করা ক্লিয়েন্ট-ই সস্তা ঘর। রায়ের বাকিটা: অভ্যন্তরীণ-সীমাবদ্ধ-ক্লায়েন্ট (নিজস্ব SPA) দুই চরম থেকেই সর্বনিম্ন লাভ করে (সংযোগের দুই পাড়ই আপনি বহন করেন), অথচ পাবলিক দীর্ঘায়ু-অপরিচিত সর্বাধিক লাভ করে যে-যন্ত্রই-হোক তার বিবর্তনকে তাদের ঘটনা-পাট থেকে দূরে রাখে: হাটের জন্য সম্পর্ক-স্থিতিশীলতা, গ্রাফের জন্য স্কিমার কেবল-যোগ-শৃঙ্খলা। রিভিউতে আপনি সেই দস্তুর নামান, যেখানে আপনার প্রধান সীমাবদ্ধতা বাস করে, যা-ই হোক অন্য দর্শনের তিনটি বিল মূল্য দিন (কথাবাহুল্য বনাম লেখক-কাল; দুয়ার-দ্বৈতকরণ বনাম প্রবাহ-ক্ষয়), আর তা লিখে রাখুন ADR হিসেবে — বিচারক আপনার রায়ের চেয়ে আপনার খোলা আদালতের বেশি যত্ন করে।' },
    },
  ],
  realWorld: [
    { en: 'Every public API bench already rules: GitHub’s sub-resource culture and 422+errors[] annex; Stripe’s date-epoch versioning and Idempotency-Key treaty; Slack’s unconditional cursor doctrine; Kubernetes’ mandated deprecation policy (alpha/beta/stable overlap as law); PayPal’s HAL documents with per-state affordances.', bn: 'প্রতি পাবলিক API-বেঞ্চ ইতোমধ্যে রায় দিচ্ছে: GitHub-এর উপ-রিসোর্স-সংস্কৃতি আর 422+errors[] সংযোজনী; Stripe-এর তারিখ-যুগ-সংস্করণকরণ আর Idempotency-Key-চুক্তি; Slack-এর নিঃশর্ত কার্সর-মতবাদ; Kubernetes-এর বাধ্যতামূলক অবচিতকরণ-নীতি (আইনরূপে আলফা/বিটা/স্থির-অধিক্রমণ); PayPal-এর অবস্থাপ্রতি-সুবিধাসহ HAL-দলিল।' },
    { en: 'Your own first corridor is one code review away: every /do or /handle appended in review is where you become the naming bench; every PUT body that sends diffs is where the altar’s oath gets signed or broken; every 200-with-error-body is where the silence-fraud docket opens.', bn: 'আপনার নিজের প্রথম করিডোর এক কোড-রিভিউ দূরে: রিভিউতে জোড়া-তলা প্রতি /do বা /handle সেই জায়গা, যেখানে আপনি নামকরণ-বেঞ্চ হয়ে ওঠেন; ডিফ পাঠানো প্রতি PUT-বডি সেই জায়গা, যেখানে বেদীর শপথ সই হয় নয়তো ভাঙে; ত্রুটি-বডিসহ প্রতি 200 সেই জায়গা, যেখানে নীরবতা-প্রতারণার দস্তুর খোলে।' },
    { en: 'Reconciliation flows are the reading window’s home market: exports, syncs and warehouse walks live or die by cursor doctrine + snapshot pinning + the verification card — a walk that cannot prove coverage becomes a compensations industry you staff forever.', bn: 'মিলকরণ-প্রবাহ হলো পাঠ-জানালার ঘরোয়া-বাজার: এক্সপোর্ট, সিঙ্ক আর গুদাম-ভ্রমণ বাঁচে বা মরে কার্সর-মতবাদ + স্ন্যাপশট-পিন + যাচাই-কার্ডে — যে ভ্রমণ কভারেজ প্রমাণ করতে পারে না, তা হয়ে যায় ক্ষতিপূরণ-শিল্প, যাতে আপনি চিরকাল জনশক্তি রাখেন।' },
    { en: 'The sunset that gets read is the sunset that runs: registries your conductor reads, headers your gateways stamp, brownouts your SRE calendar books — everything else is folklore priced quarterly at your biggest partner’s quarter-end.', bn: 'যে অবসান পড়া হয় সেটিই চালানো হয়: রেজিস্ট্রি যা আপনার পরিচালক পড়ে, হেডার যা আপনার গেটওয়ে ছাপে, ব্রাউনআউট যা আপনার SRE-পঞ্জিকা বুক করে — বাকি সব লোককথা, আপনার বৃহত্তম পার্টনারের ত্রৈমাসিক-সমাপনে ত্রৈমাসিক-শুল্কে মূল্যায়িত।' },
    { en: 'Support costs collapse exactly where errors become citizens: typed refusals with instance addresses turn “can you send the request-id?” archaeology into a dashboard query, and string-matched alerts turn into alert-on-type pipelines that tolerate copyedits.', bn: 'সাপোর্ট-খরচ হুবহু সেখানেই ভেঙে পড়ে, যেখানে ত্রুটি নাগরিক হয়: instance-ঠিকানাসহ টাইপকৃত-প্রত্যাখ্যান “রিকোয়েস্ট-আইডি পাঠাবেন?” প্রত্নতত্ত্বকে ড্যাশবোর্ড-প্রশ্নে বদলে দেয়, আর স্ট্রিং-মেলানো সতর্কতা হয়ে যায় type-এ-সতর্ক-পাইপলাইন, যা কপিএডিট সহ্য করে।' },
    { en: 'The OpenAPI spine is what makes the spec a teammate: mock pilots start partner integration before officer-hours, generated SDKs make sixty compilers enforce your schema, and the scholar’s diff is the only version of “we never break clients” that is a build failure instead of a promise.', bn: 'OpenAPI-মেরুদণ্ড-ই স্পেককে সত্যিকারের সতীর্থ বানায়: মক-পাইলট কর্মকর্তা-ঘণ্টার আগেই পার্টনার-ইন্টিগ্রেশন শুরু করে, উৎপন্ন SDK ষাট কম্পাইলার দিয়ে আপনার স্কিমা জরুরি করায়, আর পণ্ডিতের ডিফ-ই “আমরা ক্লায়েন্ট কভু ভাঙি না”-এ একমাত্র সংস্করণ, যা প্রতিশ্রুতি নয়, বিল্ড-ব্যর্থতা।' },
    { en: 'The state machine belongs in the answer, not the appendix: every refusable action hidden in client code is a 4xx support ticket in formation; per-envelope affordances move policy shipping from deploys to documents — the same document your client just read.', bn: 'অবস্থা-যন্ত্রের জায়গা উত্তরে, পরিশিষ্টে নয়: ক্লায়েন্ট-কোডে লুকানো প্রতি প্রত্যাখ্যানযোগ্য-কর্ম হলো গর্ভধারণকারী 4xx সাপোর্ট-টিকিট; খামপ্রতি-সুবিধা নীতি-চালান সরিয়ে নেয় ডিপ্লয় থেকে দলিলে — সেই একই দলিলে, যা আপনার ক্লায়েন্ট এইমাত্র পড়ে ফেলেছে।' },
    { en: 'Time is the contract: every field your clients store, every URL they bookmark, every error type they branch on is one more name you owe a lifespan to — and the platforms that last are the ones that price that lifespan in eras, lobbies and funerals, conducted in the open.', bn: 'সময়-ই চুক্তি: আপনার ক্লায়েন্টরা সংরক্ষণ করা প্রতি ক্ষেত্র, বুকমার্ক করা প্রতি URL, শাখা করা প্রতি ত্রুটি-ধরন হলো আরেকটি নাম, যার জন্য আপনি একটি আয়ুষ্কালের পাওনাদার — আর টিকে-যাওয়া প্ল্যাটফর্মগুলোই যারা সেই আয়ুষ্কাল মূল্য দেয় যুগে, লবিতে আর অন্ত্যেষ্টিতে, খোলামেলায় পরিচালিত।' },
  ],
};
