import type { LText } from './types';

/** Bilingual UI strings. Keys are dot-namespaced; values are hand-written, not machine-translated. */
export const UI: Record<string, LText> = {
  'app.name': { en: 'CodeShikhon', bn: 'কোডশিখন' },
  'app.tagline': {
    en: 'Learn development in English & বাংলা',
    bn: 'English ও বাংলা — দুই ভাষাতেই ডেভেলপমেন্ট শিখুন',
  },

  'nav.home': { en: 'Home', bn: 'হোম' },
  'nav.explore': { en: 'Explore', bn: 'এক্সপ্লোর' },
  'nav.roadmaps': { en: 'Roadmaps', bn: 'রোডম্যাপ' },
  'nav.labs': { en: 'Labs', bn: 'ল্যাব' },
  'nav.debug': { en: 'Debug', bn: 'ডিবাগ' },
  'nav.playground': { en: 'Playground', bn: 'প্লেগ্রাউন্ড' },
  'nav.glossary': { en: 'Glossary', bn: 'শব্দকোষ' },
  'nav.menu': { en: 'Menu', bn: 'মেনু' },
  'nav.close': { en: 'Close', bn: 'বন্ধ করুন' },

  'search.open': { en: 'Search…', bn: 'খুঁজুন…' },
  'search.placeholder': {
    en: 'Search technologies, lessons, glossary…',
    bn: 'টেকনোলজি, লেসন, শব্দকোষ খুঁজুন…',
  },
  'search.empty': { en: 'No results. Try another term.', bn: 'কিছু পাওয়া যায়নি। অন্য কিছু লিখে দেখুন।' },
  'search.hint': { en: 'Type to search · ↑↓ to move · Enter to open', bn: 'লিখে খুঁজুন · ↑↓ দিয়ে যান · Enter দিয়ে খুলুন' },

  'cta.start': { en: 'Start Learning', bn: 'শেখা শুরু করুন' },
  'cta.trycode': { en: 'Try Code', bn: 'কোড চালান' },
  'cta.explore': { en: 'Explore Technologies', bn: 'টেকনোলজি দেখুন' },
  'cta.open': { en: 'Open', bn: 'খুলুন' },
  'cta.back': { en: 'Back', bn: 'ফিরে যান' },

  'diff.beginner': { en: 'Beginner', bn: 'বিগিনার' },
  'diff.intermediate': { en: 'Intermediate', bn: 'ইন্টারমিডিয়েট' },
  'diff.advanced': { en: 'Advanced', bn: 'অ্যাডভান্সড' },
  'status.available': { en: 'Available', bn: 'উপলব্ধ' },
  'status.planned': { en: 'Planned', bn: 'শীঘ্রই আসছে' },

  'home.hero.badge': { en: 'Private bilingual learning platform', bn: 'নিজস্ব দ্বিভাষিক লার্নিং প্ল্যাটফর্ম' },
  'home.hero.title1': { en: 'Learn to code.', bn: 'কোড শিখুন।' },
  'home.hero.title2': { en: 'Understand how it works.', bn: 'ভেতরে কী ঘটে, তা বুঝুন।' },
  'home.hero.sub': {
    en: 'Tutorials, visual explanations, an interactive playground, exercises, debugging labs and real projects — in English and বাংলা.',
    bn: 'টিউটোরিয়াল, ভিজ্যুয়াল ব্যাখ্যা, ইন্টারঅ্যাক্টিভ প্লেগ্রাউন্ড, এক্সারসাইজ, ডিবাগিং ল্যাব আর রিয়েল প্রজেক্ট — English ও বাংলা দুই ভাষাতেই।',
  },
  'home.stats.tech': { en: 'Technologies', bn: 'টেকনোলজি' },
  'home.stats.lessons': { en: 'Lessons', bn: 'লেসন' },
  'home.stats.terms': { en: 'Glossary terms', bn: 'শব্দকোষের টার্ম' },
  'home.stats.labs': { en: 'Interactive labs', bn: 'ইন্টারঅ্যাক্টিভ ল্যাব' },

  'home.sec.explorer.t': { en: 'Technology Explorer', bn: 'টেকনোলজি এক্সপ্লোরার' },
  'home.sec.explorer.s': { en: 'Every major area of software development, organized.', bn: 'সফটওয়্যার ডেভেলপমেন্টের প্রতিটি ক্ষেত্র — সাজানো এক জায়গায়।' },
  'home.sec.paths.t': { en: 'Learning Paths', bn: 'লার্নিং পাথ' },
  'home.sec.paths.s': { en: 'Guided roadmaps from zero to professional.', bn: 'শূন্য থেকে প্রফেশনাল — ধাপে ধাপে রোডম্যাপ।' },
  'home.sec.popular.t': { en: 'Popular Tutorials', bn: 'জনপ্রিয় টিউটোরিয়াল' },
  'home.sec.popular.s': { en: 'Deep, bilingual lessons with runnable code.', bn: 'গভীর, দ্বিভাষিক লেসন — সাথে রানযোগ্য কোড।' },
  'home.sec.labs.t': { en: 'Interactive Labs', bn: 'ইন্টারঅ্যাক্টিভ ল্যাব' },
  'home.sec.labs.s': { en: 'See what happens inside the engine.', bn: 'ইঞ্জিনের ভেতরে আসলে কী ঘটে, চোখে দেখুন।' },
  'home.sec.play.t': { en: 'Code Playground', bn: 'কোড প্লেগ্রাউন্ড' },
  'home.sec.play.s': { en: 'Write HTML, CSS and JavaScript — run instantly.', bn: 'HTML, CSS, JavaScript লিখুন — সাথে সাথে রান করুন।' },
  'home.sec.projects.t': { en: 'Real-World Projects', bn: 'রিয়েল-ওয়ার্ল্ড প্রজেক্ট' },
  'home.sec.projects.s': { en: 'Syntax in isolation is not enough. Build things.', bn: 'শুধু সিনট্যাক্স যথেষ্ট নয় — বাস্তব কিছু বানান।' },
  'home.sec.arch.t': { en: 'Architecture Lab', bn: 'আর্কিটেকচার ল্যাব' },
  'home.sec.arch.s': { en: 'From a single request to a distributed system.', bn: 'একটি রিকোয়েস্ট থেকে ডিস্ট্রিবিউটেড সিস্টেম পর্যন্ত।' },
  'home.sec.tools.t': { en: 'Developer Tools', bn: 'ডেভেলপার টুলস' },
  'home.sec.tools.s': { en: 'Utilities that support daily learning.', bn: 'প্রতিদিনের শেখার সহায়ক টুল।' },
  'home.sec.progress.t': { en: 'Your Progress', bn: 'আপনার অগ্রগতি' },
  'home.sec.progress.s': { en: 'Stored privately in your browser.', bn: 'সব ডেটা আপনার ব্রাউজারেই সংরক্ষিত।' },
  'home.sec.recent.t': { en: 'Recently Learned', bn: 'সাম্প্রতিক শেখা' },
  'home.sec.continue.t': { en: 'Continue Learning', bn: 'শেখা চালিয়ে যান' },
  'home.sec.recommended.t': { en: 'Recommended Next', bn: 'পরবর্তী সাজেশন' },

  'hub.overview': { en: 'Overview', bn: 'ওভারভিউ' },
  'hub.roadmap': { en: 'Roadmap', bn: 'রোডম্যাপ' },
  'hub.tutorials': { en: 'Tutorials', bn: 'টিউটোরিয়াল' },
  'hub.exercises': { en: 'Exercises', bn: 'এক্সারসাইজ' },
  'hub.quiz': { en: 'Quiz', bn: 'কুইজ' },
  'hub.projects': { en: 'Projects', bn: 'প্রজেক্ট' },
  'hub.reference': { en: 'Reference', bn: 'রেফারেন্স' },
  'hub.debugging': { en: 'Debugging', bn: 'ডিবাগিং' },
  'hub.best': { en: 'Best Practices', bn: 'বেস্ট প্র্যাকটিস' },
  'hub.interview': { en: 'Interview Prep', bn: 'ইন্টারভিউ' },
  'hub.real': { en: 'Real World', bn: 'রিয়েল ওয়ার্ল্ড' },

  'lesson.minutes': { en: 'min read', bn: 'মিনিট পড়া' },
  'lesson.onpage': { en: 'On this page', bn: 'এই পেজে যা আছে' },
  'lesson.exercises': { en: 'Exercises', bn: 'এক্সারসাইজ' },
  'lesson.quiz': { en: 'Quiz', bn: 'কুইজ' },
  'lesson.complete': { en: 'Mark as complete', bn: 'সম্পন্ন হিসেবে চিহ্নিত করুন' },
  'lesson.completed': { en: 'Completed ✓', bn: 'সম্পন্ন ✓' },
  'lesson.next': { en: 'Next lesson', bn: 'পরবর্তী লেসন' },

  'ex.hint': { en: 'Hint', bn: 'হিন্ট' },
  'debug.hint': {
    en: 'Rule of evidence: say OUT LOUD what each line does before clicking. A wrong guess costs 50 points.',
    bn: 'প্রমাণের নিয়ম: ক্লিক করার আগে প্রতিটি লাইন কী করে জোরে বলুন। ভুল অনুমানে ৫০ পয়েন্ট কাটা যায়।',
  },
  'ex.check': { en: 'Check answer', bn: 'উত্তর দেখুন' },
  'ex.solution': { en: 'Solution', bn: 'সমাধান' },
  'ex.explanation': { en: 'Explanation', bn: 'ব্যাখ্যা' },
  'ex.correct': { en: 'Correct!', bn: 'সঠিক!' },
  'ex.incorrect': { en: 'Not quite — read the explanation.', bn: 'ঠিক হয়নি — ব্যাখ্যাটি পড়ুন।' },
  'ex.progress': { en: 'completed', bn: 'সম্পন্ন' },
  'ex.typeanswer': { en: 'Type your answer…', bn: 'উত্তর লিখুন…' },
  'ex.predict': { en: 'What will this output?', bn: 'আউটপুট কী হবে?' },

  'quiz.start': { en: 'Start quiz', bn: 'কুইজ শুরু করুন' },
  'quiz.score': { en: 'Your score', bn: 'আপনার স্কোর' },
  'quiz.accuracy': { en: 'Accuracy', bn: 'নির্ভুলতা' },
  'quiz.weak': { en: 'Topics to revise', bn: 'যে টপিকগুলো আবার দেখুন' },
  'quiz.retry': { en: 'Retry quiz', bn: 'আবার চেষ্টা করুন' },

  'play.run': { en: 'Run', bn: 'রান' },
  'play.reset': { en: 'Reset', bn: 'রিসেট' },
  'play.copy': { en: 'Copy', bn: 'কপি' },
  'play.copied': { en: 'Copied!', bn: 'কপি হয়েছে!' },
  'play.download': { en: 'Download', bn: 'ডাউনলোড' },
  'play.fullscreen': { en: 'Fullscreen', bn: 'ফুলস্ক্রিন' },
  'play.exitfs': { en: 'Exit fullscreen', bn: 'ফুলস্ক্রিন থেকে বের হন' },
  'play.console': { en: 'Console', bn: 'কনসোল' },
  'play.preview': { en: 'Preview', bn: 'প্রিভিউ' },
  'play.clear': { en: 'Clear', bn: 'ক্লিয়ার' },

  'viz.play': { en: 'Play', bn: 'প্লে' },
  'viz.pause': { en: 'Pause', bn: 'পজ' },
  'viz.step': { en: 'Step', bn: 'স্টেপ' },
  'viz.reset': { en: 'Reset', bn: 'রিসেট' },
  'viz.speed': { en: 'Speed', bn: 'স্পিড' },
  'viz.memory': { en: 'Memory (Variables)', bn: 'মেমোরি (ভেরিয়েবল)' },
  'viz.callstack': { en: 'Call Stack', bn: 'কল স্ট্যাক' },
  'viz.heap': { en: 'Heap', bn: 'হিপ' },
  'viz.output': { en: 'Output', bn: 'আউটপুট' },
  'viz.webapis': { en: 'Browser APIs', bn: 'ব্রাউজার API' },
  'viz.micro': { en: 'Microtask Queue', bn: 'মাইক্রোটাস্ক কিউ' },
  'viz.macro': { en: 'Task (Macrotask) Queue', bn: 'টাস্ক (ম্যাক্রোটাস্ক) কিউ' },
  'viz.loop': { en: 'Event Loop', bn: 'ইভেন্ট লুপ' },
  'viz.stepof': { en: 'of', bn: '/' },

  'gloss.simple': { en: 'Simple explanation', bn: 'সহজ ব্যাখ্যা' },
  'gloss.technical': { en: 'Technical explanation', bn: 'টেকনিক্যাল ব্যাখ্যা' },
  'gloss.related': { en: 'Related terms', bn: 'সম্পর্কিত টার্ম' },
  'gloss.search': { en: 'Filter terms…', bn: 'টার্ম খুঁজুন…' },

  'road.beginner': { en: 'Beginner', bn: 'বিগিনার' },
  'road.intermediate': { en: 'Intermediate', bn: 'ইন্টারমিডিয়েট' },
  'road.advanced': { en: 'Advanced', bn: 'অ্যাডভান্সড' },
  'road.pro': { en: 'Professional', bn: 'প্রফেশনাল' },

  'prog.lessons': { en: 'Lessons completed', bn: 'লেসন সম্পন্ন' },
  'prog.exercises': { en: 'Exercises solved', bn: 'এক্সারসাইজ সমাধান' },
  'prog.quiz': { en: 'Best quiz score', bn: 'সেরা কুইজ স্কোর' },
  'prog.streak': { en: 'Day streak', bn: 'দিনের স্ট্রিক' },
  'prog.empty': {
    en: 'No activity yet — start your first lesson below.',
    bn: 'এখনো কিছু করেননি — নিচ থেকে প্রথম লেসন শুরু করুন।',
  },

  'labs.eventloop': { en: 'Event Loop Lab', bn: 'ইভেন্ট লুপ ল্যাব' },
  'labs.eventloop.d': { en: 'Watch the JavaScript runtime juggle sync code, promises and timers.', bn: 'জাভাস্ক্রিপ্ট রানটাইম কীভাবে synchronous কোড, promise আর timer সামলায় — চোখে দেখুন।' },
  'labs.exec': { en: 'Code Execution Visualizer', bn: 'কোড এক্সিকিউশন ভিজ্যুয়ালাইজার' },
  'labs.exec.d': { en: 'Step through code line by line: variables, memory, call stack, output.', bn: 'লাইন বাই লাইন কোড দেখুন: ভেরিয়েবল, মেমোরি, কল স্ট্যাক, আউটপুট।' },
  'labs.browser': { en: 'Browser Pipeline', bn: 'ব্রাউজার পাইপলাইন' },
  'labs.browser.d': { en: 'From typing a URL to pixels on screen.', bn: 'URL লেখা থেকে স্ক্রিনে পিক্সেল — পুরো যাত্রা।' },
  'labs.planned': { en: 'Planned labs', bn: 'আসন্ন ল্যাব' },

  'planned.title': { en: 'This hub is on the roadmap', bn: 'এই হাবটি রোডম্যাপে আছে' },
  'planned.body': {
    en: 'The structure below shows exactly what this technology hub will contain when published. The JavaScript hub is the working reference implementation.',
    bn: 'নিচের কাঠামোটি দেখাচ্ছে এই টেকনোলজি হাবে কী কী থাকবে। জাভাস্ক্রিপ্ট হাবই এখন চালু রেফারেন্স ইমপ্লিমেন্টেশন।',
  },
  'planned.prereq': { en: 'Prerequisites', bn: 'পূর্বশর্ত' },

  'theme.label': { en: 'Theme', bn: 'থিম' },
  'theme.light': { en: 'Light', bn: 'লাইট' },
  'theme.dark': { en: 'Dark', bn: 'ডার্ক' },
  'theme.system': { en: 'System', bn: 'সিস্টেম' },
  'theme.midnight': { en: 'Midnight', bn: 'মিডনাইট' },
  'theme.ocean': { en: 'Ocean', bn: 'ওশান' },
  'theme.forest': { en: 'Forest', bn: 'ফরেস্ট' },
  'theme.solarized': { en: 'Solarized', bn: 'সোলারাইজড' },
  'theme.contrast': { en: 'High Contrast', bn: 'হাই কনট্রাস্ট' },

  'footer.note': {
    en: 'A private, bilingual developer-learning ecosystem. Content in English & বাংলা.',
    bn: 'একটি নিজস্ব, দ্বিভাষিক ডেভেলপার-লার্নিং ইকোসিস্টেম — English ও বাংলা।',
  },
  'notfound.title': { en: 'Page not found', bn: 'পেজটি পাওয়া যায়নি' },
  'notfound.body': { en: 'The link may be wrong, or this content is not published yet.', bn: 'লিংকটি ভুল হতে পারে, অথবা কনটেন্টটি এখনো প্রকাশিত হয়নি।' },
};
