import type { Lesson } from '../../../lib/types';

export const RailsAndTheRouteLesson: Lesson = {
  slug: 'rails-and-the-route',
  tech: 'ruby',
  title: {
    en: 'Ruby on Rails: RESTful Routing, MVC & Active Record',
    bn: 'Ruby on Rails: RESTful রাউটিং, MVC এবং অ্যাক্টিভ রেকর্ড'
  },
  summary: {
    en: 'Master web architecture with Ruby on Rails. Understand the "Convention over Configuration" philosophy, navigate the 7 canonical RESTful routes generated by "resources", trace the complete Model-View-Controller (MVC) request cycle, prevent mass assignment exploits with Strong Parameters, and execute database persistence and migrations via Active Record.',
    bn: 'Ruby on Rails দিয়ে ওয়েব আর্কিটেকচার সম্পূর্ণ আয়ত্ত করুন। "কনভেনশন ওভার কনফিগারেশন" দর্শন, "resources" দিয়ে তৈরি ৭ টি স্ট্যান্ডার্ড RESTful রুট, মডেল-ভিউ-কন্ট্রোলার (MVC) রিকোয়েস্ট সাইকেল, স্ট্রং প্যারামিটার দিয়ে ম্যাস-অ্যাসাইনমেন্ট আক্রমণ প্রতিরোধ এবং Active Record দিয়ে ডেটাবেস সংরক্ষণ ও মাইগ্রেশনের গভীর ব্যবহার শিখুন।'
  },
  minutes: 35,
  blocks: [
    {
      type: 'heading',
      id: 'rails-philosophy-and-routing-heading',
      text: {
        en: 'Convention over Configuration and RESTful Routing',
        bn: 'কনভেনশন ওভার কনফিগারেশন এবং RESTful রাউটিং'
      }
    },
    {
      type: 'para',
      text: {
        en: 'Building scalable web applications rapidly requires architectural clarity and standardized development patterns. In Ruby (the dynamic object-oriented programming language designed for programmer productivity), the premier web framework is Ruby on Rails. Rails is anchored by the philosophy of "Convention over Configuration", prioritizing sensible standardized defaults over endless XML configuration files. Web traffic enters through the central route configuration file. By writing a single declarative directive like "resources :articles", Rails automatically generates 7 canonical web routes (following "RESTful" resource conventions) mapping HTTP verbs and URL paths directly to controller actions.',
        bn: 'দ্রুত এবং টেকসই ওয়েব অ্যাপ্লিকেশন তৈরির জন্য দরকার সুনির্দিষ্ট স্থাপত্য কাঠামো ও প্রমিত ডেভেলপমেন্ট পদ্ধতি। কিন্তু Ruby (প্রোগ্রামারদের আনন্দের জন্য তৈরি ডাইনামিক অবজেক্ট-ওরিয়েন্টেড ভাষা)-তে সবচেয়ে জনপ্রিয় ও শক্তিশালী ওয়েব ফ্রেমওয়ার্ক হলো Ruby on Rails। Rails পরিচালিত হয় "কনভেনশন ওভার কনফিগারেশন" দর্শনের ওপর ভিত্তি করে, যা হাজারটা কনফিগারেশন ফাইলের বদলে স্ট্যান্ডার্ড নিয়মের ওপর জোর দেয়। সমস্ত ওয়েব ট্রাফিক অ্যাপ্লিকেশনের কেন্দ্রীয় রাউটিং কনফিগারেশন ফাইলের মাধ্যমে প্রবেশ করে। সেখানে কেবল "resources :articles" লিখলেই Rails স্বয়ংক্রিয়ভাবে ৭ টি স্ট্যান্ডার্ড ওয়েব রুট ("RESTful" রিসোর্স নীতিমালা অনুসারে) তৈরি করে ফেলে, যা HTTP মেথড ও URL-কে কন্ট্রোলার অ্যাকশনের সাথে যুক্ত করে।'
      }
    },
    {
      type: 'diagram',
      caption: {
        en: 'Figure 1: Complete Ruby on Rails Model-View-Controller (MVC) request lifecycle with RESTful routing and Strong Parameters validation.',
        bn: 'চিত্র ১: RESTful রাউটিং এবং স্ট্রং প্যারামিটার সহ Ruby on Rails মডেল-ভিউ-কন্ট্রোলার (MVC) রিকোয়েস্ট লাইফসাইকেলের পূর্ণাঙ্গ চিত্র।'
      },
      svg: `<svg viewBox="0 0 840 330" width="100%" height="auto" xmlns="http://www.w3.org/2000/svg">
  <rect width="840" height="330" rx="12" fill="#0f172a" />
  <text x="420" y="32" fill="#f8fafc" font-size="16" font-family="monospace" font-weight="bold" text-anchor="middle">RUBY ON RAILS MVC REQUEST-RESPONSE ARCHITECTURE</text>

  <!-- Step 1: HTTP Client & Router -->
  <g transform="translate(30, 65)">
    <rect width="170" height="235" rx="8" fill="#1e293b" stroke="#38bdf8" stroke-width="2" />
    <rect width="170" height="30" rx="8" fill="#0284c7" />
    <text x="85" y="20" fill="#ffffff" font-size="11" font-family="sans-serif" font-weight="bold" text-anchor="middle">1. RESTful Router</text>

    <rect x="10" y="45" width="150" height="50" rx="5" fill="#0f172a" stroke="#0284c7" />
    <text x="18" y="65" fill="#38bdf8" font-size="10" font-family="monospace">GET /articles/10</text>
    <text x="18" y="80" fill="#cbd5e1" font-size="9" font-family="sans-serif">Browser HTTP Request</text>

    <rect x="10" y="105" width="150" height="70" rx="5" fill="#0f172a" stroke="#10b981" />
    <text x="18" y="125" fill="#34d399" font-size="10" font-family="monospace">resources :articles</text>
    <text x="18" y="145" fill="#cbd5e1" font-size="8" font-family="sans-serif">7 Canonical REST routes:</text>
    <text x="18" y="160" fill="#fbbf24" font-size="8" font-family="monospace">index,show,new,create...</text>

    <rect x="10" y="185" width="150" height="35" rx="5" fill="#0284c7" fill-opacity="0.15" stroke="#38bdf8" />
    <text x="18" y="205" fill="#38bdf8" font-size="9" font-family="sans-serif">Dispatches to Controller</text>
  </g>

  <!-- Step 2: Controller & Strong Params -->
  <g transform="translate(230, 65)">
    <rect width="180" height="235" rx="8" fill="#1e293b" stroke="#f59e0b" stroke-width="2" />
    <rect width="180" height="30" rx="8" fill="#d97706" />
    <text x="90" y="20" fill="#ffffff" font-size="11" font-family="sans-serif" font-weight="bold" text-anchor="middle">2. ArticlesController</text>

    <rect x="10" y="45" width="160" height="55" rx="5" fill="#0f172a" stroke="#d97706" />
    <text x="18" y="65" fill="#fbbf24" font-size="10" font-family="monospace">def show</text>
    <text x="25" y="80" fill="#38bdf8" font-size="9" font-family="monospace">@article = Article.find(params[:id])</text>
    <text x="18" y="93" fill="#fbbf24" font-size="10" font-family="monospace">end</text>

    <rect x="10" y="110" width="160" height="65" rx="5" fill="#0f172a" stroke="#ef4444" />
    <text x="18" y="130" fill="#f87171" font-size="9" font-family="sans-serif" font-weight="bold">Strong Parameters:</text>
    <text x="18" y="148" fill="#cbd5e1" font-size="8" font-family="monospace">params.require(:article)</text>
    <text x="18" y="163" fill="#cbd5e1" font-size="8" font-family="monospace">  .permit(:title, :body)</text>

    <rect x="10" y="185" width="160" height="35" rx="5" fill="#d97706" fill-opacity="0.15" stroke="#f59e0b" />
    <text x="18" y="205" fill="#fbbf24" font-size="9" font-family="sans-serif">Blocks Mass-Assignment</text>
  </g>

  <!-- Step 3: Active Record Model & DB -->
  <g transform="translate(440, 65)">
    <rect width="185" height="235" rx="8" fill="#1e293b" stroke="#10b981" stroke-width="2" />
    <rect width="185" height="30" rx="8" fill="#059669" />
    <text x="92" y="20" fill="#ffffff" font-size="11" font-family="sans-serif" font-weight="bold" text-anchor="middle">3. Active Record Model</text>

    <rect x="10" y="45" width="165" height="55" rx="5" fill="#0f172a" stroke="#059669" />
    <text x="18" y="65" fill="#34d399" font-size="10" font-family="monospace">class Article &lt; AppRecord</text>
    <text x="25" y="80" fill="#cbd5e1" font-size="9" font-family="monospace">validates :title, presence: true</text>
    <text x="18" y="93" fill="#34d399" font-size="10" font-family="monospace">end</text>

    <rect x="10" y="110" width="165" height="65" rx="5" fill="#0f172a" stroke="#38bdf8" />
    <text x="18" y="130" fill="#38bdf8" font-size="9" font-family="sans-serif" font-weight="bold">Database Persistence:</text>
    <text x="18" y="148" fill="#cbd5e1" font-size="8" font-family="monospace">SELECT * FROM articles</text>
    <text x="18" y="163" fill="#cbd5e1" font-size="8" font-family="monospace">WHERE id = 10 LIMIT 1;</text>

    <rect x="10" y="185" width="165" height="35" rx="5" fill="#059669" fill-opacity="0.15" stroke="#10b981" />
    <text x="18" y="205" fill="#34d399" font-size="9" font-family="sans-serif">Transactions &amp; Migrations</text>
  </g>

  <!-- Step 4: View & Response -->
  <g transform="translate(655, 65)">
    <rect width="155" height="235" rx="8" fill="#1e293b" stroke="#a855f7" stroke-width="2" />
    <rect width="155" height="30" rx="8" fill="#7c3aed" />
    <text x="77" y="20" fill="#ffffff" font-size="11" font-family="sans-serif" font-weight="bold" text-anchor="middle">4. View / Response</text>

    <rect x="10" y="45" width="135" height="70" rx="5" fill="#0f172a" stroke="#7c3aed" />
    <text x="15" y="65" fill="#c084fc" font-size="9" font-family="monospace">show.html.erb</text>
    <text x="15" y="82" fill="#cbd5e1" font-size="9" font-family="monospace">&lt;h1&gt;&lt;%= @article.title %&gt;&lt;/h1&gt;</text>
    <text x="15" y="100" fill="#fbbf24" font-size="8" font-family="sans-serif">or render json: @article</text>

    <rect x="10" y="125" width="135" height="50" rx="5" fill="#0f172a" stroke="#10b981" />
    <text x="15" y="145" fill="#34d399" font-size="10" font-family="sans-serif" font-weight="bold">HTTP 200 OK</text>
    <text x="15" y="162" fill="#cbd5e1" font-size="8" font-family="sans-serif">Sent to client browser</text>

    <rect x="10" y="185" width="135" height="35" rx="5" fill="#7c3aed" fill-opacity="0.15" stroke="#a855f7" />
    <text x="15" y="205" fill="#c084fc" font-size="8" font-family="sans-serif">Sub-10ms response time</text>
  </g>
</svg>`
    },
    {
      type: 'heading',
      id: 'mvc-strong-params-and-active-record-heading',
      text: {
        en: 'The MVC Request Cycle, Strong Parameters, and Active Record',
        bn: 'MVC রিকোয়েস্ট সাইকেল, স্ট্রং প্যারামিটার এবং অ্যাক্টিভ রেকর্ড'
      }
    },
    {
      type: 'para',
      text: {
        en: 'When a web request matches a route, execution flows to the controller. The controller acts as the orchestrator: it inspects incoming params, interacts with models, and renders responses. To protect applications against mass-assignment vulnerabilities where malicious users inject forbidden fields like "is_admin: true", Rails requires "Strong Parameters". Controllers must explicitly permit fields ("params.require(:user).permit(:name, :email)"). Data persistence is driven by "Active Record", Rails\' Object-Relational Mapping (ORM) layer. Active Record maps database tables to Ruby classes, providing declarative validations, callbacks, and automated migrations.',
        bn: 'যখন কোনো ওয়েব রিকোয়েস্ট রুটের সাথে মেলে, তখন তা সরাসরি কন্ট্রোলারে চলে যায়। কন্ট্রোলার মূলত সমন্বয়কারীর কাজ করে: এটি আগত প্যারামিটার পরীক্ষা করে, মডেলের সাথে যোগাযোগ করে এবং রেসপন্স তৈরি করে। হ্যাকাররা যেন সরাসরি "is_admin: true"-র মতো নিষিদ্ধ ফিল্ড জোর করে সিস্টেমে ঢোকাতে না পারে, সেজন্য Rails "স্ট্রং প্যারামিটার" ব্যবহার বাধ্যতামূলক করে। কন্ট্রোলারে স্পষ্ট অনুমোদন দিতে হয় ("params.require(:user).permit(:name, :email)")। ডেটাবেসে ডেটা সংরক্ষণের দায়িত্ব পালন করে "Active Record", যা Rails-এর অবজেক্ট-রিলেশনাল ম্যাপিং (ORM) লেয়ার। এটি টেবিলকে ক্লাসের সাথে যুক্ত করে ভ্যালিডেশন, রিলেশনশিপ ও মাইগ্রেশন নিয়ন্ত্রণ করে।'
      }
    },
    {
      type: 'code',
      lang: 'typescript',
      caption: {
        en: 'TypeScript simulation of Rails RESTful routing, Strong Parameters whitelist filtering, and Active Record validations.',
        bn: 'Rails RESTful রাউটিং, স্ট্রং প্যারামিটার ফিল্টারিং এবং Active Record ভ্যালিডেশনের TypeScript রূপায়ণ।'
      },
      code: `// Simulation of Ruby on Rails MVC Request Flow and Strong Parameters Safety

export interface HTTPRequest {
  method: 'GET' | 'POST' | 'PATCH' | 'DELETE';
  path: string;
  bodyParams?: Record<string, any>;
}

export class RailsRoutingEngine {
  // Simulates "resources :articles" generating 7 RESTful routes
  public static route(req: HTTPRequest): { controller: string; action: string; id?: string } | null {
    if (req.method === 'GET' && req.path === '/articles') return { controller: 'Articles', action: 'index' };
    if (req.method === 'GET' && req.path.match(/^\\/articles\\/(\\d+)$/)) {
      const id = req.path.split('/')[2];
      return { controller: 'Articles', action: 'show', id };
    }
    if (req.method === 'POST' && req.path === '/articles') return { controller: 'Articles', action: 'create' };
    if (req.method === 'DELETE' && req.path.match(/^\\/articles\\/(\\d+)$/)) {
      const id = req.path.split('/')[2];
      return { controller: 'Articles', action: 'destroy', id };
    }
    return null;
  }

  // Simulates Strong Parameters: params.require(:user).permit(:name, :email)
  // Blocks malicious mass assignment (e.g. injected "is_admin: true")
  public static strongParameters(rawPayload: Record<string, any>, requiredKey: string, permittedKeys: string[]): Record<string, any> {
    const rootData = rawPayload[requiredKey];
    if (!rootData) throw new Error('ActionController::ParameterMissing: param is missing or the value is empty: ' + requiredKey);

    const safeParams: Record<string, any> = {};
    for (const key of permittedKeys) {
      if (key in rootData) {
        safeParams[key] = rootData[key];
      }
    }
    return safeParams;
  }
}

// Execution Demonstration
console.log('--- 1. Testing Rails RESTful Routing ---');
const showReq: HTTPRequest = { method: 'GET', path: '/articles/10' };
const routedAction = RailsRoutingEngine.route(showReq);
console.log('Incoming Request:', showReq.method, showReq.path);
console.log('Routed Controller & Action:', routedAction?.controller + '#' + routedAction?.action); // Articles#show
console.log('Extracted Entity ID:', routedAction?.id); // 10

console.log('\n--- 2. Testing Strong Parameters Mass-Assignment Defense ---');
const maliciousClientPayload = {
  user: {
    name: 'Karim',
    email: 'karim@codeshikhon.com',
    is_admin: true // MALICIOUS ATTACK PAYLOAD
  }
};

// Permitting only name and email
const permitted = RailsRoutingEngine.strongParameters(maliciousClientPayload, 'user', ['name', 'email']);
console.log('Raw Incoming Payload:', maliciousClientPayload.user);
console.log('Sanitized Whitelisted Parameters:', permitted);
console.log('Was is_admin field blocked successfully?:', permitted.is_admin === undefined); // true (Defense verified!)`
    },
    {
      type: 'keyterms',
      items: [
        {
          term: 'Convention over Configuration',
          def: {
            en: 'Design paradigm minimizing boilerplate by establishing sensible defaults for naming and folder structures.',
            bn: 'ডিজাইন দর্শন যা কনফিগারেশন ফাইলের বোঝা কমিয়ে প্রমিত নামকরণের মাধ্যমে স্বয়ংক্রিয় কাজ নিশ্চিত করে।'
          }
        },
        {
          term: 'RESTful Routing (resources)',
          def: {
            en: 'Standard Rails router macro generating 7 canonical routes for CRUD operations on an entity.',
            bn: 'রাউটার ম্যাক্রো যা কোনো রিসোর্সের CRUD অপারেশনের জন্য স্বয়ংক্রিয়ভাবে ৭ টি স্ট্যান্ডার্ড রুট বানায়।'
          }
        },
        {
          term: 'MVC Request Cycle',
          def: {
            en: 'Architectural separation: Router dispatches to Controller, which queries Model and renders View/JSON.',
            bn: 'আর্কিটেকচার যা রিকোয়েস্টকে রাউটার থেকে কন্ট্রোলারে পাঠায়, মডেল থেকে ডেটা নিয়ে ভিউ বা রেসপন্স দেখায়।'
          }
        },
        {
          term: 'Strong Parameters',
          def: {
            en: 'Controller security mechanism requiring explicit whitelisting of attributes to prevent mass-assignment exploits.',
            bn: 'কন্ট্রোলার নিরাপত্তা ব্যবস্থা যা অনুমোদিত ফিল্ডের তালিকা যাচাই করে ম্যাস-অ্যাসাইনমেন্ট আক্রমণ ঠেকায়।'
          }
        }
      ]
    }
  ],
  exercises: [
    {
      id: 'resources-seven-restful-routes-ex1',
      kind: 'mcq',
      topic: 'rails-resources-canonical-routes-count',
      question: {
        en: 'How many canonical RESTful routes does declaring "resources :articles" generate in a Rails routes.rb file?',
        bn: 'একটি Rails routes.rb ফাইলে "resources :articles" ঘোষণা করলে সুনির্দিষ্টভাবে কয়টি স্ট্যান্ডার্ড RESTful রুট তৈরি হয়?'
      },
      options: [
        {
          en: 'Exactly 7 routes: index, show, new, create, edit, update, and destroy across GET, POST, PATCH/PUT, and DELETE HTTP verbs',
          bn: 'ঠিক ৭ টি রুট: GET, POST, PATCH/PUT এবং DELETE মেথড জুড়ে index, show, new, create, edit, update এবং destroy'
        },
        {
          en: 'Only 1 single route for downloading an image',
          bn: 'একটি ছবি ডাউনলোড করার জন্য কেবল ১ টি মাত্র রুট'
        },
        {
          en: '100 routes including database backup scripts',
          bn: 'ডেটাবেস ব্যাকআপ স্ক্রিপ্ট সহ মোট ১০০ টি রুট'
        },
        {
          en: 'resources was replaced by direct URL strings in Rails 7',
          bn: 'Rails ৭ সংস্করণে resources ম্যাক্রো বাদ দেওয়া হয়েছিল'
        }
      ],
      answer: 0,
      hint: {
        en: 'resources generates the 7 standard RESTful actions.',
        bn: 'ওয়েব অ্যাপের সমস্ত CRUD কাজের জন্য প্রয়োজনীয় ৭টি আদর্শ রুট এক লাইনে তৈরি হয়।'
      },
      explanation: {
        en: 'The "resources" helper maps the 7 standard REST endpoints: index (GET), show (GET), new (GET), create (POST), edit (GET), update (PATCH/PUT), and destroy (DELETE).',
        bn: 'এর ফলে "resources" ব্যবহার করে আলাদা কোড না লিখে ৭ টি আদর্শ REST এন্ডপয়েন্ট এক লাইনেই তৈরি করা যায়।'
      }
    },
    {
      id: 'strong-parameters-mass-assignment-ex2',
      kind: 'mcq',
      topic: 'strong-parameters-mass-assignment-vulnerability',
      question: {
        en: 'What security vulnerability does Rails "Strong Parameters" ("params.require(:user).permit(:name, :email)") prevent?',
        bn: 'Rails-এর "স্ট্রং প্যারামিটার" ("params.require(:user).permit(:name, :email)") কোন গুরুতর নিরাপত্তা দুর্বলতা প্রতিহত করে?'
      },
      options: [
        {
          en: 'Mass-assignment vulnerabilities where malicious users inject unauthorized parameters like "is_admin: true" into database updates',
          bn: 'ম্যাস-অ্যাসাইনমেন্ট আক্রমণ যেখানে আক্রমণকারী ডেটাবেস আপডেটে অননুমোদিত প্যারামিটার যেমন "is_admin: true" জোর করে পাঠিয়ে দেয়'
        },
        {
          en: 'It stops cross-site scripting in email subject lines',
          bn: 'এটি ইমেইল সাবজেক্টে ক্রস-সাইট স্ক্রিপ্টিং বন্ধ করে'
        },
        {
          en: 'It prevents the server hard drive from getting hot',
          bn: 'এটি সার্ভারের হার্ডড্রাইভ গরম হওয়া রোধ করে'
        },
        {
          en: 'Strong Parameters is only required when building mobile games',
          bn: 'স্ট্রং প্যারামিটার কেবল মোবাইল গেম তৈরির সময়ই আবশ্যক'
        }
      ],
      answer: 0,
      hint: {
        en: 'Strong parameters whitelists allowable attributes to prevent privilege escalation.',
        bn: 'অনুমোদিত ফিল্ড ছাড়া অন্য কোনো ফিল্ড যেন ডেটাবেসে না পৌঁছায় তা নিশ্চিত করার ফিল্টার।'
      },
      explanation: {
        en: 'Without strong parameters, passing "User.create(params[:user])" allows attackers to grant themselves administrative rights. Requiring and permitting whitelists safe fields.',
        bn: 'এর মাধ্যমে আক্রমণকারী চাইলেও অ্যাডমিন ফিল্ড বা সংবেদনশীল ডেটা পরিবর্তন করতে পারে না।'
      }
    },
    {
      id: 'active-record-n-plus-one-includes-ex3',
      kind: 'mcq',
      topic: 'active-record-n-plus-one-query-problem',
      question: {
        en: 'How do Rails engineers eliminate the infamous "N+1 queries problem" when loading articles and their associated authors?',
        bn: 'আর্টিকেল এবং তাদের সাথে যুক্ত লেখকদের ডেটাবেস থেকে লোড করার সময় Rails ইঞ্জিনিয়াররা কীভাবে কুখ্যাত "N+1 কুয়েরি সমস্যা" সমাধান করেন?'
      },
      options: [
        {
          en: 'Using eager loading via "Article.includes(:author)", which fetches all articles and authors in 2 batched SQL queries instead of N+1 individual queries',
          bn: '"Article.includes(:author)" দিয়ে ইগার লোডিং ব্যবহার করে, যা N+১ টি আলাদা কুয়েরির বদলে মাত্র ২ টি অপটিমাইজড কুয়েরিতে সমস্ত ডেটা নিয়ে আসে'
        },
        {
          en: 'By disabling SQL caching on the PostgreSQL server',
          bn: 'পোস্টগ্রেস সার্ভারে এসকিউএল ক্যাশিং বন্ধ করে দিয়ে'
        },
        {
          en: 'By storing all author names in a local text file on the desktop',
          bn: 'সমস্ত লেখকের নাম ডেস্কটপের একটি টেক্সট ফাইলে রেখে দিয়ে'
        },
        {
          en: 'The N+1 problem does not occur in Active Record',
          bn: 'Active Record-এ N+১ সমস্যা কখনোই ঘটে না'
        }
      ],
      answer: 0,
      hint: {
        en: 'includes performs eager loading to consolidate database queries.',
        bn: 'লুপের ভেতরে বারবার ডেটাবেসে না গিয়ে একবারে সব ডেটা টেনে আনার আদর্শ সমাধান।'
      },
      explanation: {
        en: 'Without includes, iterating over 50 articles executes 1 query for the articles plus 50 queries for each author (51 queries). "includes(:author)" batches this into just 2 queries.',
        bn: 'ফলে ৫০ টি আর্টিকেলের জন্য ১ টি মূল কুয়েরি এবং ৫০ টি আলাদা কুয়েরি (মোট ৫১ টি) করার বদলে মাত্র ২ টি কুয়েরিতে কাজ শেষ হয়।'
      }
    },
    {
      id: 'active-record-migrations-reversible-ex4',
      kind: 'mcq',
      topic: 'active-record-migrations-change-method-reversibility',
      question: {
        en: 'Why do Active Record migrations use the "change" method instead of separate "up" and "down" methods whenever possible?',
        bn: 'Active Record মাইগ্রেশনে আলাদা "up" এবং "down" মেথড লেখার বদলে কেন বেশিরভাগ ক্ষেত্রে "change" মেথড ব্যবহার করা হয়?'
      },
      options: [
        {
          en: 'Active Record can automatically infer the reverse operation (e.g. rolling back add_column automatically drops the column) making migrations reversible with zero boilerplate',
          bn: 'Active Record স্বয়ংক্রিয়ভাবে বিপরীত অপারেশনটি বুঝতে পারে (যেমন add_column রোলব্যাক করলে কলামটি ডিলিট হয়ে যায়), ফলে কোনো বাড়তি কোড ছাড়াই রিভার্সিবল মাইগ্রেশন হয়'
        },
        {
          en: 'Because change migrations execute on the client\'s smartphone',
          bn: 'কারণ change মাইগ্রেশনগুলো ক্লায়েন্টের স্মার্টফোনে চলে'
        },
        {
          en: 'The change method prevents other developers from editing files',
          bn: 'change মেথড অন্য ডেভেলপারদের ফাইল এডিট করতে বাধা দেয়'
        },
        {
          en: 'up and down methods were banned in Rails 4.0',
          bn: 'Rails ৪.০ সংস্করণে up এবং down মেথড নিষিদ্ধ করা হয়েছিল'
        }
      ],
      answer: 0,
      hint: {
        en: 'The change method automatically determines how to reverse migrations on rollback.',
        bn: 'রোলব্যাক করার সময় উল্টো কাজটা নিজে থেকেই বুঝতে পারে স্মার্ট Rails ইঞ্জিন।'
      },
      explanation: {
        en: 'For standard operations (add_column, create_table), Rails knows the exact inverse. The "change" method lets developers write migrations once and roll back seamlessly.',
        bn: 'এর ফলে মাইগ্রেশন যেমন সহজে কার্যকর করা যায়, তেমনই কোনো সমস্যায় পূর্বের অবস্থায় ফিরিয়ে নেওয়াও সহজ হয়।'
      }
    }
  ],
  quiz: {
    id: 'quiz-rails-and-the-route',
    title: {
      en: 'Ruby on Rails & Active Record Quiz',
      bn: 'Ruby on Rails এবং অ্যাক্টিভ রেকর্ড কুইজ'
    },
    questions: [
      {
        id: 'quiz-rails-hotwire-turbo-drive',
        kind: 'mcq',
        topic: 'rails-hotwire-turbo-drive-spa-speed',
        question: {
          en: 'How does Rails 7 Hotwire (Turbo Drive) provide Single-Page-Application (SPA) navigation speeds without writing React or Vue client code?',
          bn: 'React বা Vue ক্লায়েন্ট কোড না লিখেও Rails ৭ Hotwire (Turbo Drive) কীভাবে সিঙ্গেল-পেজ-অ্যাপ্লিকেশনের (SPA) মতো সুপারফাস্ট স্পিড নিশ্চিত করে?'
        },
        options: [
          {
            en: 'It intercepts all standard link clicks and form submits, fetching HTML via fetch/XHR and surgically swapping only the <body> tag in the browser DOM without full page reloads',
            bn: 'এটি ব্রাউজারের সমস্ত লিংক ক্লিক ও ফর্ম সাবমিট আটকে দেয় এবং ব্যাকগ্রাউন্ডে HTML এনে পুরো পেজ রিলোড না করে কেবল <body> অংশটি নিখুঁতভাবে বদলে দেয়'
          },
          {
            en: 'It compiles the Rails backend into an iPhone application',
            bn: 'এটি Rails ব্যাকএন্ডকে একটি আইফোন অ্যাপ্লিকেশনে রূপান্তর করে'
          },
          {
            en: 'It downloads the entire database to the client browser memory',
            bn: 'এটি পুরো ডেটাবেস ক্লায়েন্টের ব্রাউজার মেমরিতে ডাউনলোড করে ফেলে'
          },
          {
            en: 'Hotwire was deprecated in Rails 7.1',
            bn: 'Rails ৭.১ সংস্করণে Hotwire বাদ দেওয়া হয়েছিল'
          }
        ],
        answer: 0,
        hint: {
          en: 'Turbo Drive intercepts navigation to swap HTML bodies without reloads.',
          bn: 'হেডার ও স্ক্রিপ্ট বারবার লোড না করে শুধু ভেতরের পরিবর্তিত অংশ নিমেষে বদলে দেওয়ার প্রযুক্তি।'
        },
        explanation: {
          en: 'Hotwire delivers HTML over the wire. Turbo Drive replaces the body seamlessly, eliminating CSS/JS parsing overhead on link transitions and delivering instant SPA performance.',
          bn: 'এর মাধ্যমে অতিরিক্ত জাভাস্ক্রিপ্ট ফ্রেমওয়ার্কের জটিলতা ছাড়াই অত্যন্ত দ্রুতগতির ইউজার এক্সপেরিয়েন্স পাওয়া যায়।'
        }
      },
      {
        id: 'quiz-active-record-scopes-chainability',
        kind: 'mcq',
        topic: 'active-record-scopes-lazy-evaluation',
        question: {
          en: 'What architectural benefit does declaring reusable "scope :published, -> { where(published: true) }" provide in an Active Record model?',
          bn: 'একটি Active Record মডেলে পুনর্ব্যবহারযোগ্য "scope :published, -> { where(published: true) }" ঘোষণা করলে কোন স্থাপত্যিক সুবিধা পাওয়া যায়?'
        },
        options: [
          {
            en: 'It returns an ActiveRecord::Relation that evaluates lazily, allowing scopes to be chained together cleanly (e.g. Article.published.recent.limit(10)) into a single SQL query',
            bn: 'এটি একটি ActiveRecord::Relation রিটার্ন করে যা লেজি মূল্যায়ন অনুসরণ করে, ফলে একাধিক স্কোপ একসাথে চেইন করে (যেমন Article.published.recent.limit(10)) একটিমাত্র SQL কুয়েরিতে চালানো যায়'
          },
          {
            en: 'It forces the database to shut down when queries return zero rows',
            bn: 'কুয়েরিতে কোনো ফলাফল না পেলে এটি ডেটাবেস বন্ধ করতে বাধ্য করে'
          },
          {
            en: 'It prints the entire database table to the local terminal',
            bn: 'এটি পুরো ডেটাবেস টেবিলটি লোকাল টার্মিনালে প্রিন্ট করে'
          },
          {
            en: 'Scopes cannot accept lambdas in modern Rails',
            bn: 'আধুনিক Rails-এ স্কোপে ল্যাম্বডা ব্যবহার করা যায় না'
          }
        ],
        answer: 0,
        hint: {
          en: 'Scopes return chainable ActiveRecord::Relation objects evaluated lazily.',
          bn: 'কুয়েরি শর্তগুলোকে ছোট ছোট অংশে ভাগ করে প্রয়োজনমতো জোড়া লাগানোর সেরা উপায়।'
        },
        explanation: {
          en: 'Active Record scopes compose seamlessly. Multiple scopes merge their WHERE clauses and execute a single consolidated database query only when data is accessed.',
          bn: 'এর ফলে কোড পুনর্ব্যবহারযোগ্য হয় এবং ডেটাবেসে অপ্রয়োজনীয় বাড়তি কুয়েরি যাওয়া বন্ধ হয়।'
        }
      },
      {
        id: 'quiz-rails-rack-middleware-pipeline',
        kind: 'mcq',
        topic: 'rails-rack-middleware-stack',
        question: {
          en: 'What is the function of the "Rack" middleware stack positioned between the web server (Puma) and the Rails controller?',
          bn: 'ওয়েব সার্ভার (Puma) এবং Rails কন্ট্রোলারের মাঝে অবস্থানকারী "Rack" মিডলওয়্যার স্ট্যাকের কাজ কী?'
        },
        options: [
          {
            en: 'A modular pipeline of components that process requests sequentially: managing SSL redirection, parsing cookies, handling sessions, and protecting against CSRF attacks before the controller executes',
            bn: 'একটি ধারাবাহিক মডুলার পাইপলাইন যা কন্ট্রোলারে যাওয়ার আগেই SSL রিডিরেকশন, কুকি পার্সিং, সেশন ব্যবস্থাপনা এবং CSRF আক্রমণ প্রতিহত করার কাজ করে'
          },
          {
            en: 'It measures the physical weight of server racks in the data center',
            bn: 'এটি ডেটা সেন্টারের সার্ভার র্যাকের প্রকৃত ওজন পরিমাপ করে'
          },
          {
            en: 'It converts HTTP requests into audio signals',
            bn: 'এটি HTTP রিকোয়েস্টগুলোকে অডিও সিগন্যালে রূপান্তর করে'
          },
          {
            en: 'Rack is strictly forbidden in Rails production servers',
            bn: 'Rails প্রোডাকশন সার্ভারে Rack ব্যবহার সম্পূর্ণ নিষিদ্ধ'
          }
        ],
        answer: 0,
        hint: {
          en: 'Rack middleware filters and enriches requests before they reach controllers.',
          bn: 'কন্ট্রোলারে পৌঁছানোর আগেই নিরাপত্তা ও সেশনের কাজগুলো সুশৃঙ্খলভাবে সম্পন্ন করার পাইপলাইন।'
        },
        explanation: {
          en: 'Rack is the universal interface standard between Ruby servers and web frameworks. Rails apps pass requests through a stack of Rack filters (Session, Cookies, CSRF, ETag).',
          bn: 'এটি সমস্ত সাধারণ ওয়েব ফিচারগুলোকে আলাদা ও মডুলার রেখে অ্যাপ্লিকেশন কন্ট্রোলারকে পরিচ্ছন্ন রাখে।'
        }
      },
      {
        id: 'quiz-active-job-background-processing',
        kind: 'mcq',
        topic: 'active-job-asynchronous-queue-adapters',
        question: {
          en: 'Why do production Rails applications offload long-running tasks (like sending emails or generating PDFs) to "ActiveJob" (backed by Sidekiq/Redis)?',
          bn: 'প্রোডাকশন Rails অ্যাপ্লিকেশনগুলো কেন দীর্ঘ সময়ের কাজগুলোকে (যেমন ইমেইল পাঠানো বা পিডিএফ তৈরি) "ActiveJob" (Sidekiq/Redis)-এ স্থানান্তরিত করে?'
        },
        options: [
          {
            en: 'To return immediate HTTP responses to the user without blocking web server worker threads, executing heavy background jobs asynchronously via worker pools',
            bn: 'ওয়েব সার্ভারের থ্রেড না আটকে ব্যবহারকারীকে সাথে সাথে রেসপন্স দিতে এবং ব্যাকগ্রাউন্ড ওয়ার্কার দিয়ে ভারী কাজগুলো আলাদাভাবে সম্পন্ন করতে'
          },
          {
            en: 'To bypass all database indexing rules',
            bn: 'সমস্ত ডেটাবেস ইনডেক্সিং নিয়ম এড়িয়ে যাওয়ার জন্য'
          },
          {
            en: 'Because web browsers do not allow PDF generation',
            bn: 'কারণ ওয়েব ব্রাউজার পিডিএফ তৈরি করার অনুমতি দেয় না'
          },
          {
            en: 'ActiveJob only runs on macOS development machines',
            bn: 'ActiveJob কেবল ম্যাক ডেভেলপমেন্ট মেশিনে চলে'
          }
        ],
        answer: 0,
        hint: {
          en: 'ActiveJob offloads slow tasks to background queues, keeping web responses fast.',
          bn: 'ব্যবহারকারীকে অপেক্ষায় না রেখে কাজগুলো ব্যাকগ্রাউন্ডে তুলে দিয়ে সাথে সাথে রেসপন্স দেওয়ার নিয়ম।'
        },
        explanation: {
          en: 'Puma threads should handle fast HTTP requests (< 50ms). Moving slow IO or network requests to background queues prevents request timeouts and server thread exhaustion.',
          bn: 'এর মাধ্যমে অ্যাপ্লিকেশনের স্কেলেবিলিটি বাড়ে এবং ট্রাফিক বাড়লেও সার্ভার মসৃণ থাকে।'
        }
      }
    ]
  },
  nextLesson: {
    slug: 'the-gem-serve',
    title: {
      en: 'Production Ruby: Puma, YJIT, RSpec Testing & Kamal Deployments',
      bn: 'প্রোডাকশন Ruby: Puma, YJIT, RSpec টেস্টিং এবং Kamal ডিপ্লয়মেন্ট'
    }
  }
};
