import type { TechHub } from '../../lib/types';
import { theHalvingPromiseLesson } from './lessons/the-halving-promise';
import { beyondHalvingLesson } from './lessons/beyond-halving';
import { theBoundAtelierLesson } from './lessons/the-bound-atelier';
import { theParametricVeinLesson } from './lessons/the-parametric-vein';
import { theUnimodalAtelierLesson } from './lessons/the-unimodal-atelier';
import { theTextMillLesson } from './lessons/the-text-mill';
import { theSkipParadeLesson } from './lessons/the-skip-parade';
import { theGridStairLesson } from './lessons/the-grid-stair';
import { theSearchPanoramaLesson } from './lessons/the-search-panorama';

export const searchingHub: TechHub = {
  slug: 'searching' as never,
  name: 'Searching',
  icon: '🔎',
  tagline: {
    en: 'One medieval question — which seat holds the target? — priced four ways, by the vow you can afford to sign.',
    bn: 'এক মধ্যযুগীয় প্রশ্ন — লক্ষ্য কোন চেয়ারে? — চারভাবে মূল্যায়িত, আপনার সই-সাধ্য শপথ দিয়ে।',
  },
  intro: {
    en: 'The sorting hub sold you the vow; this hub collects on it. Linear search is the licensed primitive when the row signs nothing at all; binary search is the log₂ miracle the SORTED vow purchases, with the invariant-not-the-loop doctrine and two industrial scars (Java’s mid overflow, the down-round dead-loop) tattooed on every branch. LOWER_BOUND rebuilds the same walk on half-open windows and answers “first seat ≥ x” questions membership cannot hear. Beyond halving sit the accountants: sentinel linear deleting one branch per seat, jump search vaulting √n blocks for cache physics, exponential gallop bracketing rows whose length you never read, and interpolation guessing by proportion on uniformly-painted worlds — O(log log n) until an allocator canyon demotes it, quietly, to linear with extra steps. The ledger closes with the trump audit: hash tables answer existence at O(1) by scrambling geometry; sorted strips keep the order-questions alive.',
    bn: 'সর্টিং-হাব আপনাকে শপথ বিক্রি করেছিল; এই হাব তা আদায় করে। লিনিয়ার সার্চ লাইসেন্সপ্রাপ্ত আদিম-ক্রিয়া যখন সারি কিছুই সই করে না; বাইনারি সার্চ log₂ অলৌকিকতা, যা সাজানো-শপথ কিনে দেয় — ইনভেরিয়ান্ট-নয়-লুপ মতবাদ আর দুই শিল্প-ক্ষত (Java-র mid-ওভারফ্লো, নিচে-গোলে-মৃত-লুপ) প্রতি শাখায় উল্কি। LOWER_BOUND একই চলা পুনর্গড়ে অর্ধ-উন্মুক্ত জানালায় আর উত্তর দেয় “প্রথম চেয়ার ≥ x” প্রশ্নে, যা সদস্যতা শুনতে পারে না। অর্ধেক-করণের ওপারে হিসাবরক্ষকরা: প্রহরী-লিনিয়ার চেয়ারপ্রতি একটি শাখা মোছে, জাম্প সার্চ √n ব্লক আক্রমণ করে ক্যাশ-পদার্থবিদ্যার জন্য, এক্সপোনেনশিয়াল তীব্রগতি বন্ধিবৎ করে এমন সারি যার দৈর্ঘ্য আপনি পড়েইনি, আর ইন্টারপোলেশন অনুমান করে অনুপাতে সমান-রঙা জগতে — O(log log n), যতক্ষণ না অ্যালোকেটর-গিরিখাদ তাকে নিঃশব্দে পদাবনত করে বাড়তি-ধাপসহ লিনিয়ারে। খাতা শেষ হয় ট্রাম্প-নিরীক্ষণে: হ্যাশ-টেবিল উত্তর দেয় অস্তিত্বে O(1)-এ, জ্যামিতি এলোমেলো করে; সাজানো সারি টিকিয়ে রাখে ক্রম-প্রশ্ন।',
  },
  lessons: [theHalvingPromiseLesson, beyondHalvingLesson, theBoundAtelierLesson, theParametricVeinLesson, theUnimodalAtelierLesson, theTextMillLesson, theSkipParadeLesson, theGridStairLesson, theSearchPanoramaLesson],
  references: [
    {
      group: { en: 'The halving machine', bn: 'অর্ধেক-করণ-যন্ত্র' },
      items: [
        { term: 'linear · O(n)', def: { en: 'No vow signed. Provably optimal under ignorance: worst and average both ask every seat.', bn: 'কোনো শপথ সই হয়নি। অজ্ঞানতায় প্রমাণযোগ্য-সর্বোত্তম: খারাপতম ও গড় উভয়েই প্রতি চেয়ার জিজ্ঞেস।' } },
        { term: 'binary · O(log n)', def: { en: 'Lives in [lo, hi]; the target-in-window invariant IS the algorithm. Equal → found, a[m] < x → lo = m+1, else hi = m−1.', bn: '[lo, hi]-তে বাস; লক্ষ্য-জানালায়-ইনভেরিয়ান্ট-ই অ্যালগরিদম। সমান → পাওয়া, a[m] < x → lo = m+1, নইলে hi = m−1।' } },
        { term: 'mid = lo + ((hi − lo) >> 1)', def: { en: 'Java’s Arrays.binarySearch overflowed (lo+hi)/2 for nine years. Sum-first arithmetic is the scar; difference-first is the tattoo.', bn: 'Java-র Arrays.binarySearch ওভারফ্লো করেছিল (lo+hi)/2 দিয়ে নয় বছর। যোগফল-আগে পাটিগণিত ক্ষত; পার্থক্য-আগে উল্কি।' } },
        { term: 'lower_bound', def: { en: 'Half-open [lo, hi); lo = m+1 on <, hi = m otherwise; collapse at lo === hi answers “first ≥ x” even when absent.', bn: 'অর্ধ-উন্মুক্ত [lo, hi); < হলে lo = m+1, নইলে hi = m; lo === hi-এ ভেঙে-পড়া উত্তর দেয় “প্রথম ≥ x”, অনুপস্থিতলেও।' } },
        { term: 'the three-move death table', def: { en: 'At least one bound must jump the probe seat EVERY step, or the window circulates forever. lo = m is the classic mortal sin.', bn: 'কমপক্ষে একটি সীমা প্রতি ধাপে প্রোব-চেয়ার লাফাতেই হবে, নইলে জানালা চিরকাল ঘুরবে। lo = m প্রচলিত ঘাতক অপরাধ।' } },
      ],
    },
    {
      group: { en: 'The accountants’ wing', bn: 'হিসাবরক্ষকদের প্রকোষ্ঠ' },
      items: [
        { term: 'sentinel linear', def: { en: 'Park the target at slot n; the end-test dies, one comparison per seat, one authenticity audit at the end.', bn: 'লক্ষ্য n স্লটে পার্ক করো; শেষ-পরীক্ষা মরে, চেয়ারপ্রতি এক তুলনা, শেষে এক সত্যতা-নিরীক্ষণ।' } },
        { term: 'jump · O(√n)', def: { en: 'Vault √n borders sequentially (prefetch-friendly), sweep one block. Worse arithmetic, better physics than halving.', bn: '√n সীমান্ত ধারাবাহিকে আক্রমণ (প্রিফেচ-বান্ধব), একটি ব্লক ঝাড়ু। অর্ধেকের চেয়ে খারাপ পাটিগণিত, ভালো পদার্থবিদ্যা।' } },
        { term: 'exponential gallop', def: { en: 'Bracket 1, 2, 4, 8… then hand to halving. O(log i) for a target at seat i — unbounded rows legalized.', bn: 'বন্ধনী 1, 2, 4, 8… তারপর অর্ধেক-করণে হস্তান্তর। i চেয়ারে লক্ষ্যে O(log i) — অসীমাভিমুখী সারি বৈধকৃত।' } },
        { term: 'interpolation', def: { en: 'pos = lo + ((x − a[lo])/(a[hi] − a[lo]))·(hi − lo). O(log log n) on uniform paint; honest O(n) on clusters. Ship the budget breaker.', bn: 'pos = lo + ((x − a[lo])/(a[hi] − a[lo]))·(hi − lo)। সমান রঙে O(log log n); গুচ্ছে সৎ O(n)। বাজেট-ব্রেকার শিপ করো।' } },
        { term: 'the trump audit', def: { en: 'Hash tables: O(1) existence, deaf to order. Sorted strips: O(log n), fluent in ranges. Choose by question class, never constants first.', bn: 'হ্যাশ-টেবিল: O(1) অস্তিত্ব, ক্রমে বধির। সাজানো সারি: O(log n), পরিসরে সাবলীল। বাছো প্রশ্ন-শ্রেণি দিয়ে, কখনো ধ্রুবক আগে নয়।' } },
      ],
    },
  ],
  roadmap: [
    { stage: 1, title: { en: 'The seat question', bn: 'চেয়ার-প্রশ্ন' }, detail: { en: 'Membership as geometry; why unsorted rows cap everyone at O(n) and linear is already provably optimal there.', bn: 'জ্যামিতি হিসেবে সদস্যতা; অসজ্জিত সারি কেন সবাইকে O(n)-এ বেঁধে রাখে আর লিনিয়ার সেখানে প্রমাণযোগ্য-সর্বোত্তম।' } },
    { stage: 2, title: { en: 'The sorted vow', bn: 'সাজানো-শপথ' }, detail: { en: 'The invariant IS the algorithm; the death table; mid arithmetic scars; window 16 → 8 → 3 → 1 walked by hand.', bn: 'ইনভেরিয়ান্ট-ই অ্যালগরিদম; মৃত্যু-তালিকা; mid-পাটিগণিতের ক্ষত; জানালা 16 → 8 → 3 → 1 হাতে-হাঁটা।' } },
    { stage: 3, title: { en: 'Boundary discipline', bn: 'সীমানা-শৃঙ্খলা' }, detail: { en: 'Half-open lower_bound; collapse semantics; “first ≥ x” answers membership cannot hear — insert position, range starts, dedup sentries.', bn: 'অর্ধ-উন্মুক্ত lower_bound; ভেঙে-পড়া-শব্দার্থ; “প্রথম ≥ x” উত্তর সদস্যতা শুনতে পায় না — সন্নিবেশ-অবস্থান, পরিসর-সূচনা, নকল-প্রহরী।' } },
    { stage: 4, title: { en: 'Beyond halving', bn: 'অর্ধেকের-ওপারে' }, detail: { en: 'Sentinel, jump, gallop, interpolation — four re-pricings of the same law; the distribution vow and its canyon; the hashing trump audit.', bn: 'প্রহরী, জাম্প, তীব্রগতি, ইন্টারপোলেশন — একই বিধানের চার পুনমূল্যায়ন; বণ্টন-শপথ ও তার গিরিখাদ; হ্যাশিং-ট্রাম্প-নিরীক্ষণ।' } },
  ],
  projects: [
    {
      title: { en: 'TraceBoard: walk the windows by hand', bn: 'ট্রেসবোর্ড: হাতে-হাঁটা জানালা' },
      brief: { en: 'Build a printable hunt sheet: a user types any sorted row and target, your tool narrates binary AND lower_bound side by side — every step’s window, probe seat, and the one-line invariant certificate. Deliberately feed a duplicate-heavy row: the two machines must visibly disagree about WHICH seat, and the sheet must explain why lower_bound’s answer is the canonical one.', bn: 'গড়ুন মুদ্রণযোগ্য শিকার-পত্র: ব্যবহারকারী যে-কোনো সাজানো সারি ও লক্ষ্য টাইপ করুক, আপনার টুল বর্ণনা করবে বাইনারি আর lower_bound পাশাপাশি — প্রতি ধাপের জানালা, প্রোব-চেয়ার, আর এক-লাইনের ইনভেরিয়ান্ট-সনদ। ইচ্ছাকৃতভাবে খাওয়ান নকল-ভারী সারি: দুই যন্ত্রকে দৃশ্যমানভাবে মতভেদ করতে হবে কোন চেয়ারে, আর পত্রকে ব্যাখ্যা করতে হবে কেন lower_bound-এর উত্তর প্রামাণিক।' },
      difficulty: 'beginner',
    },
    {
      title: { en: 'VowBench: the honest stopwatch', bn: 'ভোবেঞ্চ: সৎ স্টপওয়াচ' },
      brief: { en: 'Race all five machines across the row-size dial (16 → 1,048,576) with comparisons counted AND wall-clock measured. The chart must show binary’s flat line, jump’s √n hump, and the exact size where sentinel-linear starts losing — then a second chart where keys are production-shaped (cluster canyon inside) and interpolation quietly falls off its log log n pedestal without ever crashing.', bn: 'সারি-আকার-নবে (16 → 1,048,576) পাঁচ যন্ত্রের দৌড় করান, তুলনা-গণনা ও প্রাচীর-ঘড়ি উভয়েই মাপা। চার্টে দেখাতে হবে বাইনারির সমতল রেখা, জাম্পের √n উচ্চশৈল, আর হুবহু সে আকার যেখানে প্রহরী-লিনিয়ার হারা শুরু করে — তারপর দ্বিতীয় চার্ট, যেখানে চাবি প্রোডাকশন-আকৃতির (ভেতরে গুচ্ছ-গিরিখাদ) আর ইন্টারপোলেশন নিঃশব্দে পড়ে যায় তার log log n পীঠ থেকে, কখনো ভেঙে না-পড়ে।' },
      difficulty: 'intermediate',
    },
    {
      title: { en: 'BoundaryGuard: the breaker inside the compass', bn: 'বাউন্ডারিগার্ড: কম্পাসের-ভেতরের ব্রেকার' },
      brief: { en: 'Productionize the debug file: wrap interpolation search in a probe-budget circuit breaker that counts guesses and demotes to certified binary the moment the budget burns (default: 2×⌈log₂ n⌉ probes max). Add live key-shape telemetry — a tiny histogram of where queries land in the key space — and a replay harness feeding your historical canyon data. The deliverable is the fallback flipping mid-benchmark, logged, with zero wrong answers.', bn: 'ডিবাগ-ফাইল প্রোডাকশনে নিন: ইন্টারপোলেশন সার্চ মোড়ান প্রোব-বাজেট সার্কিট-ব্রেকারে, যা অনুমান গোনে আর বাজেট পোড়া মাত্র পদাবনত করে সনদপ্রাপ্ত-বাইনারিতে (ডিফল্ট: সর্বোচ্চ 2×⌈log₂ n⌉ প্রোব)। যোগ করুন লাইভ চাবি-আকৃতি-টেলিমেট্রি — কোয়েরি চাবি-পর্যায়ে কোথায় নামে তার ক্ষুদ্র হিস্টোগ্রাম — আর একটি রিপ্লে-হার্নেস, ঐতিহাসিক গিরিখাদ-ডেটা খাওয়ানো। প্রদেয় হলো বেঞ্চমার্কের মাঝে উল্টে-যাওয়া ফলব্যাক, লগকৃত, শূন্য ভুল উত্তরে।' },
      difficulty: 'advanced',
    },
  ],
  bestPractices: [
    { en: 'Price the vow before the loop. Unsorted row → pay O(n) proudly; sorted + membership → halving; sorted + “first ≥” → lower_bound; uniform keys → compass WITH a breaker.', bn: 'লুপের আগে শপথের মূল্য দাও। অসজ্জিত সারি → O(n) গর্বে শোধ; সাজানো + সদস্যতা → অর্ধেক-করণ; সাজানো + “প্রথম ≥” → lower_bound; সমান চাবি → কম্পাস, ব্রেকার-সহ।' },
    { en: 'mid = lo + ((hi − lo) >> 1) — difference-first, always. The sum-first formula overflowed Java’s own library for nine years; arithmetic carries scars too.', bn: 'mid = lo + ((hi − lo) >> 1) — পার্থক্য-আগে, সবসময়। যোগফল-আগে সূত্র Java-র নিজের লাইব্রেরি নয় বছর ডুবিয়েছিল; পাটিগণিতেও ক্ষত বহন করা যায়।' },
    { en: 'One kill line per branch, and never lo = m against a down-round mid. If both bounds can stall on the probe seat, the loop is immortal on the two-seat window.', bn: 'শাখাপ্রতি এক মৃত্যু-লাইন, আর নিচে-গোল-মিডের বিরুদ্ধে কখনো lo = m নয়। দুই সীমাই প্রোব-চেয়ারে আটকাতে পারলে লুপ দুই-চেয়ার-জানালায় অমর।' },
    { en: 'Answer boundary questions in half-open dialect only. [lo, hi) with collapse at lo === hi gives you presence, insert-position, and range-start in one walk — the closed-window dialect gives you three bugs.', bn: 'সীমানা-প্রশ্নের উত্তর দাও কেবল অর্ধ-উন্মুক্ত ভাষান্তরে। lo === hi-এ ভাঙা [lo, hi) দেয় উপস্থিতি, সন্নিবেশ-অবস্থান আর পরিসর-সূচনা এক চলায় — বদ্ধ-জানালা-ভাষান্তর দেয় তিনটি বাগ।' },
    { en: 'Compare cache lines, not just comparisons. Scattered probes pay the 64-bytes-fetched-8-read tax; sequential strides redeem it. On big rows, physics outbills arithmetic.', bn: 'শুধু তুলনা নয়, ক্যাশ-লাইন তুলনা করো। ছড়ানো প্রোব শোধ দেয় ৬৪-বাইট-আনা-৮-পড়া কর; ধারাবাহিক আক্রমণ তা মুকোদে। বড় সারিতে, পদার্থবিদ্যা পাটিগণিতের চেয়ে দামি বিল লেখে।' },
    { en: 'Distribution vows live in the data generator, not the code. Benchmark on production-sampled key shapes, ship probe-budget breakers, and keep key-shape telemetry alive.', bn: 'বণ্টন-শপথ থাকে ডেটা-জেনারেটরে, কোডে নয়। বেঞ্চমার্ক করো প্রোডাকশন-নমুনা চাবি-আকৃতিতে, শিপ করো প্রোব-বাজেট ব্রেকার, আর টিকিয়ে রাখো চাবি-আকৃতি-টেলিমেট্রি।' },
  ],
  interview: [
    {
      q: { en: 'Why is binary search “only” O(log n) — and why did Java own that bug for nine years?', bn: 'বাইনারি সার্চ “মাত্র” O(log n) কেন — আর Java কেন নয় বছর ধরে ঐ বাগের মালিক ছিল?' },
      a: { en: 'Halving law: each comparison retires half the live window, so n → ⌈log₂ n⌉ probes worst case — 1,048,576 seats in twenty questions. The invariant is what makes the proof one line: the target is ALWAYS in [lo, hi], every branch preserves or shrinks it, so termination at a one-seat window IS the certificate. The nine-year scar was arithmetic, not logic: mid = (lo + hi) / 2 overflows when both pointers live past 2^30, in 32-bit ints; Joshua Bloch published it in 2006, fixed in JDK 6 with difference-first mid. The lesson is layered: the algorithm was proven in 1960, the implementation was broken until 2006. Prove the loop, then audit the arithmetic — separately.', bn: 'অর্ধেক-বিধান: প্রতি তুলনা জীবিত-জানালার অর্ধেক অবসর দেয়, তাই n → ⌈log₂ n⌉ প্রোব খারাপতমে — ১০,৪৮,৫৭৬ চেয়ার কুড়ি প্রশ্নে। ইনভেরিয়ান্টই প্রমাণ এক-লাইনে রাখে: লক্ষ্য সবসময় [lo, hi]-এ, প্রতি শাখা তা রক্ষা নয়তো সংকোচিত করে, তাই এক-চেয়ার-জানালায় খতম-ই সনদ। নয়-বছরের ক্ষত ছিল যুক্তিতে নয়, পাটিগণিতে: mid = (lo + hi) / 2 ওভারফ্লো করে যখন দুই পয়েন্টারই 2^30 পেরিয়ে থাকে, ৩২-বিট int-এ; Joshua Bloch প্রকাশ করলেন ২০০৬-এ, JDK 6-এ সংশোধন পার্থক্য-আগে মিডে। শিক্ষা স্তরিত: অ্যালগরিদম প্রমাণিত ১৯৬০-এ, বাস্তবায়ন ভাঙা ছিল ২০০৬ পর্যন্ত। লুপ প্রমাণ করুন, তারপর পাটিগণিত নিরীক্ষণ করুন — আলাদাভাবে।' },
    },
    {
      q: { en: 'Lower-bound vs binary search — same walk, different soul. Explain.', bn: 'লোয়ার-বাউন্ড বনাম বাইনারি সার্চ — একই চলা, ভিন্ন আত্মা। ব্যাখ্যা করুন।' },
      a: { en: 'Binary hunt has three exits (less / greater / equal-stop) and answers membership; lower_bound has two (a[m] < x → lo = m+1, else hi = m) and answers POSITION: the first seat ≥ x, which exists as a well-defined slot even when x is absent — that slot is the insert position, the range start, the dedup sentry. The window dialects differ to match: binary lives closed [lo, hi] and dies at lo > hi; lower_bound lives half-open [lo, hi) and collapses AT lo === hi, with the answer readable off the collapsed bound and the witness checked at seat lo − or nothing if lo === n. Interviews love the “find first 5 in fives” drill; production loves git bisect, B-tree range scans, and versioned APIs — all lower_bound citizens.', bn: 'বাইনারি-শিকারে তিন প্রস্থান (কম / বড় / সমানে-থামা) আর উত্তর সদস্যতা; lower_bound-এ দুই (a[m] < x → lo = m+1, নইলে hi = m) আর উত্তর অবস্থান: প্রথম চেয়ার ≥ x, যা সুনির্ধারিত স্লটরূপে থাকে x অনুপস্থিত থাকলেও — সেই স্লট-ই সন্নিবেশ-অবস্থান, পরিসর-সূচনা, নকল-প্রহরী। জানালা-ভাষান্তর মিলেতো আলাদা: বাইনারি বাস করে বদ্ধ [lo, hi]-এ আর মরে lo > hi-তে; lower_bound বাস করে অর্ধ-উন্মুক্ত [lo, hi)-তে আর ভেঙে পড়ে lo === hi-তেই, উত্তর পড়া যায় ভাঙা সীমা থেকে আর সাক্ষী যাচাই lo চেয়ারে — অথবা কিছু নয় যদি lo === n। সাক্ষাৎকারে প্রিয় “পাচকে-প্রথম-৫ খোঁজো” অনুশীলন; প্রোডাকশনে প্রিয় git bisect, B-ট্রি রেঞ্জ-স্ক্যান, ভার্সনকৃত API — সবাই lower_bound নাগরিক।' },
    },
    {
      q: { en: 'When is O(√n) jump search BETTER than O(log n) binary? Defend the paradox.', bn: 'কখন O(√n) জাম্প সার্চ O(log n) বাইনারির চেয়ে ভালো? প্যারাডক্স প্রতিপন্ন করুন।' },
      a: { en: 'When the billing department is physics, not arithmetic. Binary’s probe seats scatter — mid, quarter, eighth — each a fresh cache line dragged in for eight bytes of comparison; on rows beyond cache capacity, every probe is a memory round-trip. Jump strides block borders SEQUENTIALLY (√n of them), which hardware prefetchers devour, then sweeps exactly one 128-ish-seat block, also sequentially. The comparison invoice grows (√n vs log n); the cycle invoice shrinks. Verdicts cross where rows stop fitting L2/L3 — empirically around a few hundred thousand small values — which is why SIMD-in-block variants sit inside production storage engines. The deeper answer: big-O prices the model; hardware pays the bill; interviews that stop at asymptotics have finished only half the argument.', bn: 'যখন বিলিং-বিভাগ পাটিগণিত নয়, পদার্থবিদ্যা। বাইনারির প্রোব-চেয়ার ছড়ায় — মাঝ, চতুর্থাংশ, অষ্টাংশ — প্রতিটি নতুন ক্যাশ-লাইন টেনে আনা আট বাইট তুলনার জন্য; ক্যাশ-ধারণক্ষমতা পেরোনো সারিতে প্রতি প্রোব একটি মেমোরি-রাউন্ডট্রিপ। জাম্প আক্রমণ করে ব্লক-সীমান্ত ধারাবাহিকে (√n-টি), যা হার্ডওয়্যার-প্রিফেচার গিলে, তারপর ঝাড়ু দেয় হুবহু একটি ~১২৮-চেয়ারের ব্লক, তাও ধারাবাহিকে। তুলনা-চালান বাড়ে (√n বনাম log n); চক্র-চালান কমে। রায় ছেদ করে যেখানে সারি L2/L3 ছাড়িয়ে যায় — অভিজ্ঞতামূলকভাবে কয়েক-লক্ষ ক্ষুদ্র মানের আশেপাশে — সেই কারণেই SIMD-ইন-ব্লক প্রকারভেদ বসে প্রোডাকশন স্টোরেজ-ইঞ্জিনে। গভীর উত্তর: big-O মডেলের মূল্য দেয়; হার্ডওয়্যার বিল শোধ দেয়; অ্যাসিম্পটোটিক্সে থেমে-যাওয়া সাক্ষাৎকার তর্কের অর্ধেকই শেষ করেছে।' },
    },
    {
      q: { en: 'Hash table gives you O(1). Why does your system still keep a sorted array?', bn: 'হ্যাশ-টেবিল দেয় O(1)। তাহুজে আপনার সিস্টেম কেন এখনো সাজানো অ্যারে রাখে?' },
      a: { en: 'Because my questions have a shape the table deliberately destroyed. The hash answers “does 47 exist?” at O(1) — the same O(1) cannot say what sits NEXT to 47, which keys live between 40 and 60, which five are smallest, or where 47 would go if absent. Those are order-questions: range scans, prefix walks, rank queries, dedup boundaries — the entire diet of databases (B-tree nodes are sorted strips with ranges inside), load balancers, and schedulers. Add the bills: a table at 0.7 load factor wastes ~30% of its chairs by design and costs O(n) to build; a strip wastes none and often arrives pre-sorted. My architecture keeps both citizens: the table at the existence-desk, the strip at the order-desk, and the boundary discipline (lower_bound) as the strip’s receptionist.', bn: 'কারণ আমার প্রশ্নের একটি আকৃতি আছে, যা টেবিল ইচ্ছাকৃতভাবে ধ্বংস করেছে। হ্যাশ উত্তর দেয় “47 আছে?” O(1)-এ — সেই একই O(1) বলতে পারে না 47-এর পাশে কী বসে, 40 থেকে 60-এর মধ্যে কোন চাবি বাস করে, কোন পাঁচটি ক্ষুদ্রতম, বা 47 অনুপস্থিত থাকলে কোথায় যেত। ওগুলো ক্রম-প্রশ্ন: রেঞ্জ-স্ক্যান, প্রিফিক্স-চলা, র‍্যাংক-কোয়েরি, নকল-সীমানা — ডেটাবেসের পুরো খোরাক (B-ট্রি নোড হলো সাজানো সারি, ভেতরে পরিসরসহ), লোড-ব্যালান্সার, শিডিউলার। সাথে বিল: 0.7 লোড-ফ্যাক্টরের টেবিল নকশায়ই নষ্ট করে ~30% চেয়ার আর নির্মাণে খরচ O(n); সারি নষ্ট করে শূন্য আর প্রায়ই আসে পূর্ব-সাজানো। আমার স্থাপত্য দুই নাগরিকই রাখে: টেবিল অস্তিত্ব-ডেস্কে, সারি ক্রম-ডেস্কে, আর সীমানা-শৃঙ্খলা (lower_bound) সারির রিসেপশনিস্টরূপে।' },
    },
  ],
  realWorld: [
    { en: 'Every standard library: lower_bound / binary_search / bisect — half-open, difference-first mid, certified on your behalf. Study their contracts before writing your own loop; the scars are already paid.', bn: 'প্রতি স্ট্যান্ডার্ড-লাইব্রেরি: lower_bound / binary_search / bisect — অর্ধ-উন্মুক্ত, পার্থক্য-আগে মিড, আপনার হয়ে সনদপ্রাপ্ত। নিজের লুপ লেখার আগে তাদের চুক্তি পড়ুন; ক্ষত অলরেডি পরিশোধিত।' },
    { en: 'git bisect: the halving machine pointed at history — every commit a seat, “good/bad” the comparison; the unbounded variant gallops first when the bug’s epoch is unknown.', bn: 'git bisect: ইতিহাসের দিকে তাকানো অর্ধেক-যন্ত্র — প্রতি কমিট একটি চেয়ার, “good/bad”-ই তুলনা; বাগের যুগ অজানা থাকলে আগে তীব্রগতিযুক্ত অসীমাভিমুখী প্রকারভেদ।' },
    { en: 'Database range scans: B-tree interior pages binary-search their key strips per hop; the “WHERE key BETWEEN” query is a lower_bound at the leaf plus a sequential walk — sorted geometry, industrial scale.', bn: 'ডেটাবেস রেঞ্জ-স্ক্যান: B-ট্রির অন্তর্ভাগ-পাতা প্রতি লাফে নিজের চাবি-সারিতে বাইনারি-সার্চ করে; “WHERE key BETWEEN” কোয়েরি হলো পাতায় একটি lower_bound যোগ ধারাবাহিক চলা — সাজানো জ্যামিতি, শিল্প-মাপে।' },
    { en: 'Streaming & log systems: append-only files searched by gallop-bracket + halving; LSM runs sweep blocks via jump-style economics — the two accountants the debugging file made famous.', bn: 'স্ট্রিমিং ও লগ-সিস্টেম: append-only ফাইল তীব্রগতি-বন্ধনী + অর্ধেক-করণে অনুসন্ধিত; LSM রান ব্লক ঝাড়ু দেয় জাম্প-রীতি অর্থনীতিতে — ডিবাগ-ফাইলের বিখ্যাতকারী দুই হিসাবরক্ষক।' },
  ],
};
