import type { Lesson } from '../../../lib/types';

export const ClockSpeedLesson: Lesson = {
  slug: 'clock-speed',
  tech: 'cpu',
  title: {
    en: 'Clock Speed, Frequency & Thermal Throttling',
    bn: 'ক্লক স্পিড, ফ্রিকোয়েন্সি এবং থার্মাল থ্রটলিং'
  },
  summary: {
    en: 'Understand the fundamental heartbeat of digital processors: quartz crystal oscillators, clock cycle time, Hertz and Gigahertz frequency metrics, and execution time formulas. Discover why raw frequency scaling hit the Power Wall at roughly 4 to 5 GHz, how dynamic overclocking operates, and how Dynamic Voltage and Frequency Scaling (DVFS) prevents silicon meltdown through thermal throttling.',
    bn: 'ডিজিটাল প্রসেসরের মৌলিক হৃদস্পন্দন আবিষ্কার করুন: কোয়ার্টজ ক্রিস্টাল অসিলেটর, ক্লক সাইকেল সময়, হার্টজ এবং গিগাহার্টজ ফ্রিকোয়েন্সি মেট্রিক এবং এক্সিকিউশন সময় গণনার সূত্র। কাঁচা ফ্রিকোয়েন্সি বৃদ্ধি কেন প্রায় ৪ থেকে ৫ গিগাহার্টজে এসে পাওয়ার ওয়ালে ধাক্কা খেল, কীভাবে ডায়নামিক ওভারক্লকিং কাজ করে এবং ডিভিএফএস (DVFS) কীভাবে থার্মাল থ্রটলিংয়ের মাধ্যমে সিলিকন গলন প্রতিরোধ করে তা জানুন।',
  },
  minutes: 20,
  blocks: [
    {
      type: 'heading',
      id: 'clock-oscillator-frequency',
      text: {
        en: 'The Clock Oscillator: Converting Time into Digital Beats',
        bn: 'ক্লক অসিলেটর: সময়কে ডিজিটাল স্পন্দনে রূপান্তর'
      },
    },
    {
      type: 'para',
      text: {
        en: 'A central processing unit requires a synchronized pulse to march billions of transistors in lockstep. This digital heartbeat is generated by a Quartz Crystal Oscillator on the motherboard. When energized with electric current, the piezoelectric quartz crystal vibrates at an exceptionally precise physical frequency, emitting a periodic square wave voltage that alternates continuously between binary 0 (ground) and binary 1 (supply voltage).',
        bn: 'কোটি কোটি ট্রানজিস্টরকে সুশৃঙ্খলভাবে একসাথে পরিচালনা করতে সেন্ট্রাল প্রসেসিং ইউনিটের একটি নিয়মিত স্পন্দনের প্রয়োজন হয়। এই ডিজিটাল হৃদস্পন্দন তৈরি করে মাদারবোর্ডে থাকা কোয়ার্টজ ক্রিস্টাল অসিলেটর। বিদ্যুৎ প্রবাহের মাধ্যমে পাইজোইলেকট্রিক কোয়ার্টজ ক্রিস্টাল অত্যন্ত নিখুঁত কম্পাঙ্কে কাঁপে এবং একটি নিয়মিত স্কয়ার ওয়েভ ভোল্টেজ তৈরি করে যা ক্রমাগত বাইনারি ০ এবং বাইনারি ১ এর মধ্যে পর্যায়ক্রমে ওঠানামা করে।'
      },
    },
    {
      type: 'para',
      text: {
        en: 'The speed of this oscillation is measured in Hertz (Hz), representing cycles per second. A 1 GHz processor ticks 1 billion times each second, giving each clock cycle a duration of exactly 1 nanosecond (1 ns = 1 / 1000000000 seconds). At 4 GHz, each clock cycle lasts only 0.25 nanoseconds (250 picoseconds). In 250 picoseconds, light in a vacuum travels barely 7.5 centimeters, illustrating the extreme physical constraints under which silicon signals must settle before the next clock pulse arrives.',
        bn: 'এই কম্পনের গতি হার্টজ (Hz) এককে মাপা হয়, যা প্রতি সেকেন্ডে সাইকেলের সংখ্যা প্রকাশ করে। একটি ১ গিগাহার্টজের প্রসেসর প্রতি সেকেন্ডে ১ বিলিয়ন বার স্পন্দিত হয়, ফলে প্রতিটি ক্লক সাইকেলের সময়কাল হয় ঠিক ১ ন্যানোসেকেন্ড ( ১ ns = ১ / ১000000000 সেকেন্ড )। ৪ গিগাহার্টজে প্রতিটি ক্লক সাইকেল স্থায়ী হয় মাত্র ০.২৫ ন্যানোসেকেন্ড ( ২৫০ পিকোসেকেন্ড )। ২৫০ পিকোসেকেন্ডে শূন্য মাধ্যমে আলো যেতে পারে মাত্র ৭.৫ সেন্টিমিটার, যা স্পষ্ট করে পরবর্তী ক্লক সংকেত আসার আগেই সিলিকন ট্রানজিস্টরে সিগন্যাল পৌঁছানোর চরম শারীরিক সীমাবদ্ধতা।'
      },
    },
    {
      type: 'diagram',
      title: {
        en: 'Clock Frequency Waveform and the Power Wall Thermal Curve',
        bn: 'ক্লক ফ্রিকোয়েন্সি ওয়েভফর্ম এবং পাওয়ার ওয়াল থার্মাল কার্ভ'
      },
      svg: `<svg viewBox="0 0 820 400" width="100%" height="auto" font-family="ui-monospace, monospace" role="img" aria-label="Clock square waveforms and thermal power wall curve chart">
  <rect width="820" height="400" fill="#0f172a" rx="12"/>
  
  <text x="410" y="32" fill="#38bdf8" font-size="14" font-weight="bold" text-anchor="middle">CLOCK OSCILLATION TIMING &amp; THE POWER WALL BARRIER</text>
  
  <!-- Left Side: Square Waves -->
  <g transform="translate(40, 60)">
    <rect width="360" height="300" rx="8" fill="#1e293b" stroke="#334155" stroke-width="2"/>
    <text x="180" y="28" fill="#38bdf8" font-size="12" font-weight="bold" text-anchor="middle">CLOCK VOLTAGE SQUARE WAVEFORMS</text>
    
    <!-- 1 GHz Waveform -->
    <text x="20" y="65" fill="#f8fafc" font-size="11" font-weight="bold">1 GHz Clock (Period = 1.0 ns):</text>
    <path d="M 30,110 L 80,110 L 80,75 L 140,75 L 140,110 L 200,110 L 200,75 L 260,75 L 260,110 L 320,110" fill="none" stroke="#0284c7" stroke-width="3"/>
    <text x="110" y="128" fill="#94a3b8" font-size="10" text-anchor="middle">&lt;--- 1.0 ns Cycle ---&gt;</text>
    
    <!-- 4 GHz Waveform -->
    <text x="20" y="170" fill="#f8fafc" font-size="11" font-weight="bold">4 GHz Clock (Period = 0.25 ns):</text>
    <path d="M 30,210 L 50,210 L 50,185 L 75,185 L 75,210 L 100,210 L 100,185 L 125,185 L 125,210 L 150,210 L 150,185 L 175,185 L 175,210 L 200,210 L 200,185 L 225,185 L 225,210 L 250,210 L 250,185 L 275,185 L 275,210 L 300,210 L 300,185 L 325,185" fill="none" stroke="#10b981" stroke-width="2"/>
    <text x="75" y="228" fill="#10b981" font-size="9" text-anchor="middle">&lt;-0.25ns-&gt;</text>
    
    <rect x="20" y="245" width="320" height="40" rx="4" fill="#0f172a"/>
    <text x="180" y="270" fill="#f59e0b" font-size="10" text-anchor="middle">Rising edges trigger internal D flip-flop state updates</text>
  </g>
  
  <!-- Right Side: The Power Wall Graph -->
  <g transform="translate(420, 60)">
    <rect width="360" height="300" rx="8" fill="#1e293b" stroke="#334155" stroke-width="2"/>
    <text x="180" y="28" fill="#ef4444" font-size="12" font-weight="bold" text-anchor="middle">THE POWER WALL (P = C * V^2 * f)</text>
    
    <!-- Axes -->
    <line x1="50" y1="230" x2="320" y2="230" stroke="#94a3b8" stroke-width="2"/>
    <line x1="50" y1="230" x2="50" y2="50" stroke="#94a3b8" stroke-width="2"/>
    
    <text x="310" y="250" fill="#94a3b8" font-size="10">Freq (GHz)</text>
    <text x="45" y="45" fill="#94a3b8" font-size="10" text-anchor="end">Power (W)</text>
    
    <!-- Frequency Tick Marks -->
    <text x="100" y="245" fill="#cbd5e1" font-size="9" text-anchor="middle">1 GHz</text>
    <text x="160" y="245" fill="#cbd5e1" font-size="9" text-anchor="middle">2 GHz</text>
    <text x="220" y="245" fill="#cbd5e1" font-size="9" text-anchor="middle">3 GHz</text>
    <text x="270" y="245" fill="#f59e0b" font-size="9" text-anchor="middle">4 GHz</text>
    
    <!-- Power Curve -->
    <path d="M 50,225 Q 180,215 240,160 T 300,55" fill="none" stroke="#ef4444" stroke-width="3"/>
    
    <!-- Power Wall Barrier Marker -->
    <line x1="270" y1="50" x2="270" y2="230" stroke="#f59e0b" stroke-width="2" stroke-dasharray="4,3"/>
    <text x="270" y="42" fill="#f59e0b" font-size="10" font-weight="bold" text-anchor="middle">Power Wall ~4 GHz</text>
    
    <!-- Thermal Warning Label -->
    <rect x="65" y="100" width="165" height="45" rx="4" fill="#0f172a" stroke="#ef4444"/>
    <text x="147" y="118" fill="#ef4444" font-size="10" font-weight="bold" text-anchor="middle">Thermal Throttling Zone</text>
    <text x="147" y="134" fill="#cbd5e1" font-size="9" text-anchor="middle">100°C Limit -> DVFS downclock</text>
  </g>
</svg>`,
      caption: {
        en: 'Higher clock frequencies shrink cycle duration to picoseconds, but power consumption escalates quadratically into the Power Wall.',
        bn: 'উচ্চতর ক্লক ফ্রিকোয়েন্সি সাইকেলের সময়কে পিকোসেকেন্ডে নামিয়ে আনে, তবে বিদ্যুৎ খরচ ঘাত হারে বেড়ে পাওয়ার ওয়ালে বাধা পায়।'
      },
    },
    {
      type: 'heading',
      id: 'iron-law-thermal-throttling',
      text: {
        en: 'The CPU Performance Equation & Dynamic Thermal Throttling',
        bn: 'সিপিইউ পারফরম্যান্স সমীকরণ এবং ডায়নামিক থার্মাল থ্রটলিং'
      },
    },
    {
      type: 'para',
      text: {
        en: 'In computer architecture, total program execution time is governed by the Iron Law of Processor Performance: Execution Time = Instruction Count * CPI * Clock Cycle Time. Chip designers improve system throughput through three distinct levers: optimizing software code, increasing superscalar parallelism, or boosting clock frequency.',
        bn: 'কম্পিউটার আর্কিটেকচারে একটি প্রোগ্রামের মোট কার্যকাল প্রসেসর পারফরম্যান্সের মৌলিক সূত্র দ্বারা নির্ধারিত হয়: এক্সিকিউশন টাইম = নির্দেশ সংখ্যা * CPI * ক্লক সাইকেল সময়। চিপ ডিজাইনাররা ৩ টি উপায়ে কর্মক্ষমতা বৃদ্ধি করেন: সফটওয়্যার কোড নিখুঁত করা, সুপারস্কেলার প্যারালেলিজম বাড়ানো অথবা ক্লক ফ্রিকোয়েন্সি বৃদ্ধি করা।'
      },
    },
    {
      type: 'para',
      text: {
        en: 'However, raising clock frequency requires increasing operating core voltage (Vcore) to switch transistors quickly enough. Because dynamic CMOS power scales according to P = C * V^2 * f, pushing clock speeds past 4 GHz causes silicon power consumption and heat generation to skyrocket. When on-die thermal sensors register junction temperatures reaching 100 degrees Celsius, Dynamic Voltage and Frequency Scaling (DVFS) engages thermal throttling, immediately reducing clock multiplier ratios to protect the chip from permanent burnout.',
        bn: 'তবে ক্লক ফ্রিকোয়েন্সি বাড়াতে ট্রানজিস্টরগুলোকে পর্যাপ্ত দ্রুত স্যুইচ করানোর জন্য অপারেটিং কোর ভোল্টেজ (Vcore) বাড়াতে হয়। যেহেতু সিএমওএস পাওয়ার P = C * V^2 * f সূত্র অনুসারে বৃদ্ধি পায়, তাই ৪ গিগাহার্টজের ওপরে ফ্রিকোয়েন্সি বাড়ালে সিলিকনের বিদ্যুৎ খরচ এবং তাপ উৎপাদন বিপুল পরিমাণে বেড়ে যায়। অন-ডাই থার্মাল সেন্সর যখন চিপের তাপমাত্রা ১০০ ডিগ্রি সেলসিয়াসে পৌঁছানোর সংকেত দেয়, তখন ডিভিএফএস (DVFS) থার্মাল থ্রটলিং শুরু করে ক্লক ফ্রিকোয়েন্সি কমিয়ে দেয় যাতে চিপটি স্থায়ী ক্ষতি থেকে রক্ষা পায়।'
      },
    },
    {
      type: 'code',
      lang: 'javascript',
      filename: 'cpu-frequency-benchmark.js',
      code: `// Deterministic CPU Performance Equation & Thermal Throttling Simulation
function calculateCpuExecutionTime(instructionCount, cpi, frequencyGhz) {
  // Cycle time in nanoseconds: T = 1 / f
  const cycleTimeNs = 1.0 / frequencyGhz;
  const totalCycles = instructionCount * cpi;
  const executionTimeSeconds = (totalCycles * cycleTimeNs) / 1e9;
  return { cycleTimeNs, totalCycles, executionTimeSeconds };
}

const INSTRUCTIONS = 1000000000; // 1 Billion instructions
const AVERAGE_CPI = 1.25;

console.log('--- CPU Performance Equation Comparison ---');
console.log('Workload: 1 Billion instructions, CPI = 1.25\\n');

// 1. Run at 1.0 GHz
const bench1Ghz = calculateCpuExecutionTime(INSTRUCTIONS, AVERAGE_CPI, 1.0);
console.log('1.0 GHz: Cycle = ' + bench1Ghz.cycleTimeNs.toFixed(2) + ' ns | Time = ' + bench1Ghz.executionTimeSeconds.toFixed(4) + ' s');

// 2. Run at 2.0 GHz
const bench2Ghz = calculateCpuExecutionTime(INSTRUCTIONS, AVERAGE_CPI, 2.0);
console.log('2.0 GHz: Cycle = ' + bench2Ghz.cycleTimeNs.toFixed(2) + ' ns | Time = ' + bench2Ghz.executionTimeSeconds.toFixed(4) + ' s');

// 3. Run at 4.0 GHz
const bench4Ghz = calculateCpuExecutionTime(INSTRUCTIONS, AVERAGE_CPI, 4.0);
console.log('4.0 GHz: Cycle = ' + bench4Ghz.cycleTimeNs.toFixed(2) + ' ns | Time = ' + bench4Ghz.executionTimeSeconds.toFixed(4) + ' s');

// 4. Thermal Throttling Scenario: Overheating triggers downclock from 4.0 GHz to 2.0 GHz
console.log('\\n--- Thermal Throttling Triggered (Die Temp = 102°C) ---');
console.log('DVFS hardware cuts frequency from 4.0 GHz down to 2.0 GHz.');
const throttledTime = bench2Ghz.executionTimeSeconds;
console.log('Throttled Execution Time = ' + throttledTime.toFixed(4) + ' s (Performance halved to protect silicon)');`,
      caption: {
        en: 'Simulating execution time across 1 GHz, 2 GHz, and 4 GHz frequencies, showing thermal throttling impact.',
        bn: '১ গিগাহার্টজ, ২ গিগাহার্টজ এবং ৪ গিগাহার্টজ ফ্রিকোয়েন্সিতে এক্সিকিউশন সময় এবং থার্মাল থ্রটলিং প্রভাবের সিমুলেশন।'
      },
    },
    {
      type: 'callout',
      kind: 'warning',
      title: {
        en: 'The Breakdown of Dennard Scaling & The Power Wall',
        bn: 'ডেনার্ড স্কেলিংয়ের সমাপ্তি এবং পাওয়ার ওয়াল'
      },
      text: {
        en: 'From 1974 until approximately 2005, computer engineering benefited from Dennard Scaling: as transistors grew smaller, their power density remained constant because supply voltages dropped in tandem. However, when voltage scaling stalled below 1 volt due to subthreshold leakage currents, Dennard scaling collapsed. Pushing clock frequencies above 4 GHz caused power densities to approach those of rocket nozzles, forcing chip architects away from clock scaling and toward multi-core parallelism.',
        bn: '১৯৭৪ থেকে প্রায় ২০০৫ সাল পর্যন্ত কম্পিউটার ইঞ্জিনিয়ারিং ডেনার্ড স্কেলিংয়ের সুবিধা পেয়েছিল: ট্রানজিস্টর ছোট হওয়ার সাথে সাথে বিদ্যুৎ খরচ স্থির ছিল কারণ সরবরাহ ভোল্টেজও কমেছিল। কিন্তু লিকেজ কারেন্টের কারণে ভোল্টেজ ১ ভোল্টের নিচে নামানো বন্ধ হয়ে গেলে ডেনার্ড স্কেলিং ভেঙে পড়ে। ৪ গিগাহার্টজের ওপরে ক্লক ফ্রিকোয়েন্সি বাড়ালে চিপের তাপ রকেটের নজেলের মতো বেড়ে যেত, যা প্রসেসর নির্মাতাদের ফ্রিকোয়েন্সি বাড়ানোর বদলে মাল্টি-কোর সমান্তরাল ব্যবস্থার দিকে যেতে বাধ্য করে।'
      },
    },
  ],
  exercises: [
    {
      id: 'cpu-clk-ex-1',
      kind: 'predict',
      question: {
        en: 'At a CPU clock frequency of 2 GHz (2 billion cycles per second), what is the clock cycle duration in nanoseconds? Formula: 1 / 2 = 0.5 nanoseconds. Type 0.5.',
        bn: 'একটি সিপিইউর ক্লক ফ্রিকোয়েন্সি ২ গিগাহার্টজ ( প্রতি সেকেন্ডে ২ বিলিয়ন সাইকেল ) হলে ন্যানোসেকেন্ডে ক্লক সাইকেলের সময়কাল কত? সূত্র: ১ / ২ = ০.৫ ন্যানোসেকেন্ড। ০.৫ টাইপ করুন।'
      },
      answer: '0.5',
      hint: {
        en: 'Divide 1 nanosecond by the frequency in GHz: 1 / 2 = 0.5.',
        bn: '১ ন্যানোসেকেন্ডকে গিগাহার্টজ ফ্রিকোয়েন্সি দিয়ে ভাগ করুন: ১ / ২ = ০.৫।'
      },
      explanation: {
        en: 'Cycle time is the inverse of frequency: 1 divided by 2 GHz yields 0.5 nanoseconds (500 picoseconds) per clock cycle.',
        bn: 'সাইকেল সময় হলো ফ্রিকোয়েন্সির বিপরীত: ১ কে ২ গিগাহার্টজ দিয়ে ভাগ করলে প্রতি সাইকেলে ০.৫ ন্যানোসেকেন্ড ( ৫০০ পিকোসেকেন্ড ) পাওয়া যায়।'
      },
    },
    {
      id: 'cpu-clk-ex-2',
      kind: 'mcq',
      question: {
        en: 'Which mathematical formula governs dynamic electrical power consumption in CMOS microprocessor circuits?',
        bn: 'সিএমওএস মাইক্রোপ্রসেসর সার্কিটে ডায়নামিক বিদ্যুৎ খরচের পরিমাণ কোন গাণিতিক সূত্র দ্বারা নির্ধারিত হয়?'
      },
      options: [
        {
          en: 'Power = Capacitance * Voltage^2 * Frequency (P = C * V^2 * f)',
          bn: 'পাওয়ার = ক্যাপাসিট্যান্স * ভোল্টেজ^২ * ফ্রিকোয়েন্সি (P = C * V^2 * f)',
        },
        {
          en: 'Power = Mass * Acceleration * Gravity',
          bn: 'পাওয়ার = ভর * ত্বরণ * অভিকর্ষ',
        },
        {
          en: 'Power = Distance / Speed of Sound',
          bn: 'পাওয়ার = দূরত্ব / শব্দের গতি',
        },
        {
          en: 'Power = Screen Resolution * Audio Volume',
          bn: 'পাওয়ার = স্ক্রিন রেজোলিউশন * অডিও ভলিউম',
        },
      ],
      answer: 0,
      hint: {
        en: 'Power scales linearly with frequency and quadratically with operating voltage.',
        bn: 'পাওয়ার ফ্রিকোয়েন্সির সাথে সরল অনুপাতে এবং ভোল্টেজের সাথে বর্গের অনুপাতে বৃদ্ধি পায়।',
      },
      explanation: {
        en: 'Dynamic power dissipation is proportional to capacitance times voltage squared times frequency: raising voltage to overclock causes exponential heat generation.',
        bn: 'ডায়নামিক পাওয়ার খরচ ক্যাপাসিট্যান্স, ভোল্টেজের বর্গ এবং ফ্রিকোয়েন্সির গুণফলের সমানুপাতিক: ফলে ভোল্টেজ বাড়ালে তাপ বিপুল হারে বৃদ্ধি পায়।'
      },
    },
    {
      id: 'cpu-clk-ex-3',
      kind: 'mcq',
      question: {
        en: 'What protective hardware mechanism activates when a CPU reaches dangerous thermal thresholds (such as 100 degrees Celsius)?',
        bn: 'সিপিইউ যখন বিপজ্জনক তাপমাত্রায় ( যেমন ১০০ ডিগ্রি সেলসিয়াস ) পৌঁছায় তখন কোন সুরক্ষামূলক হার্ডওয়্যার ব্যবস্থা সক্রিয় হয়?'
      },
      options: [
        {
          en: 'Dynamic Voltage and Frequency Scaling (DVFS) triggers thermal throttling, immediately reducing clock speeds to cool the silicon die',
          bn: 'ডিভিএফএস (DVFS) থার্মাল থ্রটলিং সক্রিয় করে তাৎক্ষণিকভাবে ক্লক গতি কমিয়ে সিলিকন ডাই শীতল করে',
        },
        {
          en: 'The CPU permanently deletes all operating system files from storage',
          bn: 'সিপিইউ স্টোরেজ থেকে সমস্ত অপারেটিং সিস্টেম ফাইল স্থায়ীভাবে মুছে ফেলে',
        },
        {
          en: 'The power supply inverts its polarity to turn electricity into cold air',
          bn: 'পাওয়ার সাপ্লাই বিদ্যুৎকে ঠান্ডা বাতাসে পরিণত করতে উল্টো দিকে চলতে শুরু করে',
        },
        {
          en: 'The CPU switches automatically from 64-bit mode to 8-bit mode forever',
          bn: 'সিপিইউ চিরতরে ৬৪-বিট মোড থেকে ৮-বিট মোডে চলে যায়',
        },
      ],
      answer: 0,
      hint: {
        en: 'Thermal throttling cuts operating frequency and voltage within microseconds.',
        bn: 'থার্মাল থ্রটলিং কয়েক মাইক্রোসেকেন্ডের মধ্যে ফ্রিকোয়েন্সি ও ভোল্টেজ কমিয়ে দেয়।',
      },
      explanation: {
        en: 'Thermal throttling monitors on-die temperature sensors, dynamically reducing clock multiplier ratios and voltages to prevent permanent semiconductor burnout.',
        bn: 'থার্মাল থ্রটলিং অন-ডাই তাপমাত্রা পর্যবেক্ষণ করে ক্লক মাল্টিপ্লায়ার ও ভোল্টেজ কমিয়ে সিলিকনের ক্ষতি রোধ করে।'
      },
    },
    {
      id: 'cpu-clk-ex-4',
      kind: 'predict',
      question: {
        en: 'If a CPU with an average CPI of 1 runs a program of 4 billion instructions at 4 GHz, how many seconds does the program take to complete? (4 billion / 4 billion = 1 second). Type 1.',
        bn: 'যদি ১ গড় CPI যুক্ত একটি সিপিইউ ৪ গিগাহার্টজে ৪ বিলিয়ন নির্দেশের একটি প্রোগ্রাম চালায়, তবে প্রোগ্রামটি সম্পন্ন হতে কত সেকেন্ড সময় লাগবে? ( ৪ বিলিয়ন / ৪ বিলিয়ন = ১ সেকেন্ড )। ১ টাইপ করুন।'
      },
      answer: '1',
      hint: {
        en: '4 billion instructions at 4 billion cycles per second takes exactly 1 second.',
        bn: 'প্রতি সেকেন্ডে ৪ বিলিয়ন সাইকেল গতিতে ৪ বিলিয়ন নির্দেশ সম্পন্ন করতে ঠিক ১ সেকেন্ড লাগে।'
      },
      explanation: {
        en: 'At 4 GHz (4 billion cycles per second) with a CPI of 1, the processor retires 4 billion instructions in exactly 1 second.',
        bn: '১ CPI এবং ৪ গিগাহার্টজ গতিতে প্রসেসরটি ঠিক ১ সেকেন্ডে ৪ বিলিয়ন নির্দেশ সম্পন্ন করে।'
      },
    },
  ],
  quiz: {
    title: {
      en: 'CPU Clock Frequency & Thermal Dynamics Quiz',
      bn: 'সিপিইউ ক্লক ফ্রিকোয়েন্সি এবং থার্মাল ডায়নামিক্স কুইজ'
    },
    questions: [
      {
        id: 'cpu-clk-qz-1',
        kind: 'mcq',
        topic: 'quartz-crystal-oscillator',
        question: {
          en: 'What electronic component generates the fundamental periodic clock signals that synchronize microprocessor datapath registers?',
          bn: 'কোন ইলেকট্রনিক উপাদানটি মাইক্রোপ্রসেসর ডাটাপাথ রেজিস্টার সমন্বয়কারী মৌলিক পর্যায়বৃত্ত ক্লক সংকেত তৈরি করে?'
        },
        options: [
          {
            en: 'A Piezoelectric Quartz Crystal Oscillator producing stable high-frequency voltage oscillations',
            bn: 'পাইজোইলেকট্রিক কোয়ার্টজ ক্রিস্টাল অসিলেটর যা স্থিতিশীল উচ্চ-ফ্রিকোয়েন্সির ভোল্টেজ স্পন্দন তৈরি করে',
          },
          {
            en: 'An analog water wheel powered by liquid cooling fluid',
            bn: 'লিকুইড কুলিং তরল দ্বারা চালিত একটি অ্যানালগ জলচক্র',
          },
          {
            en: 'A manual mechanical hand crank operated by the computer user',
            bn: 'কম্পিউটার ব্যবহারকারী দ্বারা পরিচালিত একটি হাতল ঘোরানো ক্র্যাঙ্ক',
          },
          {
            en: 'A copper radio antenna receiving timing signals from orbiting space satellites',
            bn: 'মহাকাশের স্যাটেলাইট থেকে সময় সংকেত গ্রহণকারী একটি তামার রেডিও অ্যান্টেনা',
          },
        ],
        answer: 0,
        hint: {
          en: 'The quartz crystal on the motherboard that vibrates at precise frequencies when voltage is applied.',
          bn: 'মাদারবোর্ডে থাকা কোয়ার্টজ ক্রিস্টাল যা ভোল্টেজ পেলে নির্দিষ্ট কম্পাঙ্কে স্পন্দিত হয়।',
        },
        explanation: {
          en: 'Motherboards utilize piezoelectric quartz crystal oscillators whose mechanical vibration produces highly stable clock reference frequencies, multiplied on-die by Phase-Locked Loops (PLLs).',
          bn: 'মাদারবোর্ড পাইজোইলেকট্রিক কোয়ার্টজ ক্রিস্টাল অসিলেটর ব্যবহার করে যা অত্যন্ত স্থিতিশীল ক্লক ফ্রিকোয়েন্সি তৈরি করে।'
        },
      },
      {
        id: 'cpu-clk-qz-2',
        kind: 'mcq',
        topic: 'iron-law-processor-performance',
        question: {
          en: 'What is the "Iron Law" formula that determines total CPU execution time for a given program workload?',
          bn: 'প্রদত্ত প্রোগ্রামের মোট সিপিইউ এক্সিকিউশন সময় নির্ধারণকারী "আয়রন ল" সূত্র কোনটি?'
        },
        options: [
          {
            en: 'Execution Time = Instruction Count * Cycles Per Instruction (CPI) * Clock Cycle Time',
            bn: 'এক্সিকিউশন সময় = নির্দেশ সংখ্যা * সাইকেল পার ইন্সট্রাকশন (CPI) * ক্লক সাইকেল সময়',
          },
          {
            en: 'Execution Time = Screen Brightness * Fan Speed / RAM Gigabytes',
            bn: 'এক্সিকিউশন সময় = স্ক্রিনের উজ্জ্বলতা * ফ্যানের গতি / র‍্যাম গিগাবাইট',
          },
          {
            en: 'Execution Time = Internet Download Speed * Hard Disk Capacity',
            bn: 'এক্সিকিউশন সময় = ইন্টারনেট ডাউনলোড স্পিড * হার্ড ডিস্কের ধারণক্ষমতা',
          },
          {
            en: 'Execution Time = Keyboard Key Count + Mouse Click Rate',
            bn: 'এক্সিকিউশন সময় = কিবোর্ডের বোতামের সংখ্যা + মাউস ক্লিকের হার',
          },
        ],
        answer: 0,
        hint: {
          en: 'The classic formula combining instruction count, CPI, and clock cycle period.',
          bn: 'নির্দেশ সংখ্যা, CPI এবং ক্লক সাইকেলের সময়কাল সমন্বিত মৌলিক সূত্র।',
        },
        explanation: {
          en: 'The processor performance equation states that runtime equals instructions executed multiplied by average cycles per instruction (CPI) multiplied by clock period (1/f).',
          bn: 'প্রসেসর পারফরম্যান্স সমীকরণ অনুসারে কার্যকাল হলো মোট নির্দেশ সংখ্যা, প্রতি নির্দেশের গড় সাইকেল এবং সাইকেলের সময়কালের গুণফল।'
        },
      },
      {
        id: 'cpu-clk-qz-3',
        kind: 'mcq',
        topic: 'power-wall-frequency-limit',
        question: {
          en: 'What engineering reality constitutes the "Power Wall" that prevented single-core CPU clock speeds from scaling indefinitely past 4 to 5 GHz?',
          bn: 'কোন প্রকৌশলগত বাস্তবতার কারণে "পাওয়ার ওয়াল" সৃষ্টি হয় যা একক কোরের সিপিইউ গতি ৪ থেকে ৫ গিগাহার্টজের ওপরে বাড়াতে বাধা দেয়?'
        },
        options: [
          {
            en: 'Transistor power consumption and thermal density scale quadratically with voltage, causing cooling limits to be exceeded above 4 GHz',
            bn: 'ট্রানজিস্টরের বিদ্যুৎ খরচ এবং তাপীয় ঘনত্ব ভোল্টেজের বর্গের অনুপাতে বাড়ে, ফলে ৪ গিগাহার্টজের ওপরে কুলিং ক্ষমতার সীমা পার হয়ে যায়',
          },
          {
            en: 'Operating systems cannot count numbers higher than 5 billion',
            bn: 'অপারেটিং সিস্টেম ৫ বিলিয়নের চেয়ে বড় সংখ্যা গণনা করতে পারে না',
          },
          {
            en: 'Motherboards physically melt into liquid water at room temperature',
            bn: 'ঘরের স্বাভাবিক তাপমাত্রায় মাদারবোর্ড গলে তরল পানিতে পরিণত হয়',
          },
          {
            en: 'Silicon atoms stop conducting electricity on Tuesdays',
            bn: 'মঙ্গলবার দিন সিলিকন পরমাণু বিদ্যুৎ পরিবহন বন্ধ করে দেয়',
          },
        ],
        answer: 0,
        hint: {
          en: 'Thermal power density rises beyond the heat dissipation capacity of air and liquid coolers.',
          bn: 'তাপের ঘনত্ব সাধারণ এয়ার বা লিকুইড কুলারের অপসারণ ক্ষমতার চেয়ে বেশি হয়ে যায়।',
        },
        explanation: {
          en: 'The Power Wall occurred because scaling clock frequency required higher voltages, driving power densities to hundreds of watts per square centimeter, making cooling impossible.',
          bn: 'পাওয়ার ওয়াল সৃষ্টি হয়েছিল কারণ ক্লক বাড়াতে উচ্চ ভোল্টেজের প্রয়োজন হতো, যা তাপের ঘনত্বকে শত শত ওয়াটে নিয়ে যেত এবং চিপ ঠান্ডা রাখা অসম্ভব করে তুলত।'
        },
      },
      {
        id: 'cpu-clk-qz-4',
        kind: 'mcq',
        topic: 'dvfs-thermal-protection',
        question: {
          en: 'How does Dynamic Voltage and Frequency Scaling (DVFS) preserve processor silicon integrity under heavy sustained workloads?',
          bn: 'ভারী কাজের সময় ডায়নামিক ভোল্টেজ অ্যান্ড ফ্রিকোয়েন্সি স্কেলিং (DVFS) কীভাবে প্রসেসর সিলিকনের সুস্থতা বজায় রাখে?'
        },
        options: [
          {
            en: 'By dynamically dropping clock frequency multipliers and core voltages when thermal diodes detect excessive silicon heat',
            bn: 'থার্মাল সেন্সর অতিরিক্ত তাপমাত্রা শনাক্ত করলে ক্লক ফ্রিকোয়েন্সি এবং কোর ভোল্টেজ দ্রুত কমিয়ে দিয়ে',
          },
          {
            en: 'By turning on internal silicon refrigerators that consume zero electricity',
            bn: 'কোনো বিদ্যুৎ খরচ না করা অভ্যন্তরীণ সিলিকন রেফ্রিজারেটর চালু করে',
          },
          {
            en: 'By ejecting the processor chip out of the motherboard socket automatically',
            bn: 'মাদারবোর্ড সকেট থেকে প্রসেসর চিপটিকে স্বয়ংক্রিয়ভাবে বাইরে ফেলে দিয়ে',
          },
          {
            en: 'By reversing the flow of data packets across the internet connection',
            bn: 'ইন্টারনেট সংযোগের মধ্য দিয়ে ডাটা প্যাকেটের প্রবাহ বিপরীতমুখী করে',
          },
        ],
        answer: 0,
        hint: {
          en: 'Downclocking clock multipliers and dropping Vcore reduces heat production.',
          bn: 'ক্লক মাল্টিপ্লায়ার ও ভোল্টেজ কমিয়ে তাপ উৎপাদন হ্রাস করা।',
        },
        explanation: {
          en: 'DVFS dynamically adjusts frequency and voltage to keep operating temperatures within the safe thermal envelope, preventing silicon degradation.',
          bn: 'ডিভিএফএস তাপমাত্রা নিরাপদ সীমার মধ্যে রাখতে ফ্রিকোয়েন্সি ও ভোল্টেজ স্বয়ংক্রিয়ভাবে কমিয়ে সিলিকনকে সুরক্ষিত রাখে।'
        },
      },
    ],
  },
  next: {
    slug: 'pipelining',
    title: {
      en: 'Instruction Pipelining & Superscalar Execution',
      bn: 'ইন্সট্রাকশন পাইপলাইনিং এবং সুপারস্কেলার এক্সিকিউশন'
    },
  },
};
