import type { TechHub } from '../../lib/types';
import { verbLedgerLesson } from './lessons/the-verb-ledger';
import { freshnessExchangeLesson } from './lessons/the-freshness-exchange';
import { theHeaderCourtLesson } from './lessons/the-header-court';
import { theNegotiationSalonLesson } from './lessons/the-negotiation-salon';
import { theCookieJarLesson } from './lessons/the-cookie-jar';
import { theCredentialTribunal } from './lessons/the-credential-tribunal';
import { thePartialLedgerLesson } from './lessons/the-partial-ledger';
import { theRedirectBenchLesson } from './lessons/the-redirect-bench';
import { theIdempotencyBenchLesson } from './lessons/the-idempotency-bench';

export const httpHub: TechHub = {
  slug: 'http' as never,
  name: 'HTTP',
  icon: '📨',
  tagline: {
    en: 'Knock-knock, but make it law: the web runs on envelopes whose every crease — verb, header, seal, cookie, challenge, redirect, retry — is a statute some intermediary is reading while you sleep.',
    bn: 'ধক-ধক, কিন্তু আইন বানিয়ে: ওয়েব চলে এমন খামের ওপর, যার প্রতি ভাঁজ — ক্রিয়া, হেডার, সিল, কুকি, চ্যালেঞ্জ, রিডাইরেক্ট, রিট্রাই — একটি বিধান, যা কোনো মধ্যবর্তী আপনার ঘুমের মধ্যে পড়ছে।',
  },
  intro: {
    en: 'HTTP is the web’s official etiquette: a plain-text envelope contract between one client, an infinite cast of intermediaries it never meets, and an origin out of sight. This hub is nine benches chained into one staircase. THE VERB LEDGER reads the request side: methods as contracts (safe, idempotent, cacheable-by-default — or not), the status grammar (2xx/3xx/4xx/5xx and why 401 is a doorway while 403 is a wall), and the borrowed-semantics demotion that made 302 rewrite POSTs into GETs. THE FRESHNESS EXCHANGE reads the response side: the lease (Cache-Control budgets staleness) and the seal (ETag prices rightness — the 304, cheapest truthful answer on the web), with the lab counting the whole difference out loud across twelve knocks. THE HEADER COURT resumes the profession itself: Host as the prix-fixe header that carries multiplexing, Content-Type as the body’s passport, and the typography statutes (lowercase keys, no invisible bytes) under which headers are spelled at all. THE NEGOTIATION SALON convenes the bazaar: Accept families bargaining with q-values, server-driven versus agent-driven discipline, the selection fallacies that 300 resolves, and the emigration taxonomy by which a resource announces it moved before anyone bargains. THE COOKIE JAR decants possession into ceremonies: seven inscriptions (Domain, Path, Expires/Max-Age, Secure, HttpOnly, SameSite ×3), the jar’s mechanical jurisdiction, rotation as the login ritual’s only lawful move, and the debugging gospel of silent eviction and 431. THE CREDENTIAL TRIBUNAL seats the second great profession: 401 as a challenge carrying WWW-Authenticate, Bearer versus Basic tried in open court, 403 as the wall, and CORS as the cross-origin injunction with preflights and credentials priced. THE PARTIAL LEDGER prices the partial: Content-Range, the 206 response, multipart byteranges, and resumption arithmetic for interrupted transfers and streaming archives. THE REDIRECT BENCH tries the whole migration protocol: 301/302/307/308 as demotion law, each campaign priced — hop-arithmetic, spider arithmetic, multiplexing deadlines — with the eviction notice as capstone ceremony. And THE IDEMPOTENCY BENCH closes the staircase: f∘f = f as the theorem priced in worlds not receipts, the Idempotency-Key mint with its unique-claim atomicity and replayed-bytes verdicts, the three-shape retry taxonomy (first-knock free / rhythm tithe after Retry-After / three-case silence stood down), jitter as de-synchronization, breakers as per-office law, and the statute the whole hub collapses into — retry policy is fleet policy. Read them in order and every wire you touch will speak back in verdicts you already know how to read.',
    bn: 'HTTP হলো ওয়েবের সরকারি শিষ্টাচার: এক ক্লায়েন্ট, তার অদেখা-মাধ্যমদের অসীম নাট্যশালা, আর দৃষ্টির বাইরের একটি অরিজিনের মাঝে সরল-পাঠ্য খাম-চুক্তি। এই হাব হলো একটি সিঁড়িতে বাঁধা নয়টি বেঞ্চ। ক্রিয়া-খাতা পড়ে অনুরোধ-দিক: চুক্তি হিসেবে পদ্ধতি (নিরাপদ, আইডেমপোটেন্ট, ডিফল্টে-ক্যাশযোগ্য — বা নয়), স্ট্যাটাস-ব্যাকরণ (2xx/3xx/4xx/5xx, এবং কেন 401 প্রবেশপথ অথচ 403 প্রাচীর), আর সেই ধার-করা-অর্থের পদাবনতি, যা 302-কে বানিয়েছিল POST→GET পুনর্লিখনকারী। সতেজতা-বিনিময় পড়ে প্রতিক্রিয়া-দিক: লিজ (Cache-Control বাসিতার বাজেট) আর সিল (ETag সঠিকতার মূল্য — 304, ওয়েবের সস্তা-সত্য-উত্তর), ল্যাবের বারো-ধকে পুরো পার্থক্য গণনাসহ। হেডার-দরবার পেশা নিজেই পুনরায় চালু করে: মাল্টিপ্লেক্সিং-বহনকারী বাধ্যতামূলক হেডাররূপে Host, বডির পাসপোর্টরূপে Content-Type, আর টাইপোগ্রাফি-বিধান (ছোট-হাতের কী, অদৃশ্য বাইটের নিষেধ), যার অধীনে হেডার বানানই করা হয়। আলোচনা-রুঁদ বাজার বসায়: q-মানের দর-কষাকষিতে Accept-পরিবারগণ, সার্ভার-চালিত বনাম এজেন্ট-চালিত শৃঙ্খলা, 300 যে মীমাংসা করে সেই বাছাই-ভ্রম, আর আস্থানান্তর-শ্রেণিবিন্যাস, যা দিয়ে সম্পদ দর-কষাকষির আগেই ঘোষণা করে সরে যাওয়া। কুকি-পাত্র দখল ঢেলে দেয় অনুষ্ঠানে: সাত খোদাই (Domain, Path, Expires/Max-Age, Secure, HttpOnly, SameSite ×3), পাত্রের যান্ত্রিক এখতিয়ার, লগইন-অনুষ্ঠানের একমাত্র বৈধ অঙ্গরূপে আবর্তন, আর নীরব-বহিষ্কার ও 431-এর ডিবাগিং-সুসমাচার। শংসাপত্র-ট্রাইব্যুনাল দ্বিতীয় মহাপেশায় আসন দেয়: WWW-Authenticate-বহনকারী চ্যালেঞ্জরূপে 401, খোলা আদালতে বিচারিত Bearer বনাম Basic, প্রাচীররূপে 403, আর প্রিফ্লাইট-ও-শংসাপত্র-মূল্যায়িত ক্রস-অরিজিন-নিষেধাজ্ঞারূপে CORS। আংশিক-খাতা আংশিকের মূল্য দেয়: Content-Range, 206-প্রতিক্রিয়া, মাল্টিপার্ট-বাইটরেঞ্জ, আর ছেঁড়া-স্থানান্তর ও স্ট্রিমিং-আর্কাইভের পুনর্গ্রহণ-পাটিগণিত। রিডাইরেক্ট-বেঞ্চ বিচার করে পুরো স্থানান্তর-প্রোটোকল: পদাবনতি-বিধিরূপে 301/302/307/308, প্রতিটি অভিযান মূল্যায়িত — ফলো-পাটিগণিত, মাকড়-পাটিগণিত, মাল্টিপ্লেক্সিং-সময়সীমা — শেষাংশ-অনুষ্ঠানরূপে উচ্ছেদ-নোটিশসহ। আর অবিচ্ছেদ্য-বেঞ্চ সিঁড়ি বন্ধ করে: f∘f = f উপপাদ্যরূপে, রসিদে নয় জগতে মূল্যিত; মুদ্রালয়রূপে Idempotency-Key — অনন্য-দাবি-পারমাণবিকতা আর বাইটে-বাজানো-রায়সহ; তিন-আকৃতির রিট্রাই-শ্রেণিবিন্যাস (প্রথম-ধক বিনামূল্যে / Retry-After-পরবর্তী লয়-কর / দাঁড়-করানো তিন-ঘটনার-নীরবতা); অ-সমলয়করণরূপে জিটার, অফিসপ্রতি-বিধিরূপে ব্রেকার, আর সেই বিধান যাতে পুরো হাব সঙ্কুচিত হয় — রিট্রাই-নীতি হলোই বহর-নীতি। ক্রমে পড়ুন, আর আপনার স্পর্শ করা প্রতি তার আপনাকে এমন রায়ে উত্তর দেবে, যা পড়তে আপনি আগেই জানেন।',
  },
  lessons: [
    verbLedgerLesson,
    freshnessExchangeLesson,
    theHeaderCourtLesson,
    theNegotiationSalonLesson,
    theCookieJarLesson,
    theCredentialTribunal,
    thePartialLedgerLesson,
    theRedirectBenchLesson,
    theIdempotencyBenchLesson,
  ],
  references: [
    {
      group: { en: 'The verb ledger', bn: 'ক্রিয়া-খাতা' },
      items: [
        { term: 'safe / idempotent', def: { en: 'GET, HEAD, OPTIONS: read-only envelopes (safe ✓ idempotent ✓). PUT/DELETE: (✗ ✓) — retries free. POST/PATCH: (✗ ✗) — retries priced.', bn: 'GET, HEAD, OPTIONS: পঠনমাত্র-খাম (নিরাপদ ✓ অবিচ্ছেদ্য ✓)। PUT/DELETE: (✗ ✓) — রিট্রাই মুক্ত। POST/PATCH: (✗ ✗) — রিট্রাই মূল্যায়িত।' } },
        { term: 'status grammar', def: { en: '2xx done · 3xx relocate (301 permanent / 302 borrowed / 303 lawful-demotion / 307–308 method-kept) · 4xx your envelope (401 doorway+WWW-Authenticate / 403 wall / 404 unknown / 410 gone-on-purpose / 429 budget) · 5xx my room (502 bad upstream / 503 resting+Retry-After).', bn: '2xx সম্পন্ন · 3xx স্থানান্তর (301 স্থায়ী / 302 ধারকরা / 303 বৈধ-পদাবনতি / 307–308 পদ্ধতি-রক্ষিত) · 4xx আপনার খাম (401 প্রবেশপথ+WWW-Authenticate / 403 প্রাচীর / 404 অজানা / 410 ইচ্ছাকৃত-অন্তর্হিত / 429 বাজেট) · 5xx আমার ঘর (502 খারাপ আপস্ট্রিম / 503 বিশ্রাম+Retry-After)।' } },
        { term: 'envelope anatomy', def: { en: 'request line + headers + body ⇄ status line + headers + body. The only words intermediaries are guaranteed to parse; frameworks never leave the building.', bn: 'অনুরোধ-লাইন + হেডার + বডি ⇄ স্ট্যাটাস-লাইন + হেডার + বডি। মাধ্যমরা পার্সের গ্যারান্টি পায় কেবল এই শব্দগুলোই; ফ্রেমওয়ার্ক ভবন ছাড়ে না।' } },
        { term: 'Host & typography', def: { en: 'Host is the mandatory first header — vhosts, CDNs, and multiplexing all resolve through it; header names are case-insensitive-lowercased, whitespace is not invisible here, and no intermediary owes you leniency.', bn: 'Host হলো বাধ্যতামূলক প্রথম হেডার — vhost, CDN ও মাল্টিপ্লেক্সিং সবই তার মধ্য দিয়ে সমাধান হয়; হেডার-নাম কেস-অসংবেদনশীল-ছোটাহাতের, ফাঁকা-স্থান এখানে অদৃশ্য নয়, আর কোনো মধ্যবর্তী ক্ষমার ঋণী নয়।' } },
      ],
    },
    {
      group: { en: 'The freshness exchange', bn: 'সতেজতা-বিনিময়' },
      items: [
        { term: 'lease (Cache-Control)', def: { en: 'max-age = seconds the seat may answer unasked; public/private = who may hold it; no-store = cremation; no-cache = keep-but-always-revalidate (the badly-named one).', bn: 'max-age = আসন না-জিজ্ঞেসে-উত্তর-দেওয়ার সেকেন্ড; public/private = কে ধরতে পারে; no-store = দহন; no-cache = রাখো-কিন্তু-সবসময়-যাচাই (অপনামটি)।' } },
        { term: 'seal (ETag / 304)', def: { en: 'Content identity; If-None-Match initiates the duel: equal → 304 (0 body bytes, lease renewed), different → 200 with the new body. Protocol’s cheapest true answer.', bn: 'কনটেন্ট-পরিচয়; If-None-Match দ্বৈরথ শুরু করে: সমান → 304 (০ বডি-বাইট, লিজ নবায়িত), ভিন্ন → নতুন বডিসহ 200। প্রোটোকলের সস্তা-সত্য-উত্তর।' } },
        { term: 'Vary + naming', def: { en: 'Vary extends the freshness key per dimension (Accept/Authorization); versioned names (logo-v2, content-hash) make stale seats irrelevant-not-wrong; immutable lawful there only.', bn: 'Vary সতেজতা-কী-কে মাত্রাপ্রতি বর্ধিত করে (Accept/Authorization); সংস্করণকৃত-নাম (logo-v2, কনটেন্ট-হ্যাশ) বাসি-আসন করে ভুল-নয়-কিন্তু-নিরীহ; immutable কেবল সেখানেই বৈধ।' } },
        { term: 'negotiated identity', def: { en: 'Accept (with q), Accept-Language, Accept-Encoding/Charset bargain per representation; the Winning representation must name itself with Vary — or every seat aliases one answer to another question.', bn: 'Accept (q-সহ), Accept-Language, Accept-Encoding/Charset প্রতিনিধিত্বপ্রতি দর কষাকষি করে; বিজয়ী প্রতিনিধিত্বকে অবশ্যই Vary দিয়ে নিজের নাম বলতে হবে — নইলে প্রতি আসন এক উত্তর অন্য প্রশ্নে অ্যালিয়াস করে।' } },
      ],
    },
    {
      group: { en: 'The possession cabinets', bn: 'দখল-ক্যাবিনেট' },
      items: [
        { term: 'the seven inscriptions', def: { en: 'Domain (jurisdiction sandhi), Path, Expires/Max-Age (the twin clocks), Secure (transit seal), HttpOnly (script seal), SameSite=Strict|Lax|None+Secure (the sending policy). A cookie absent inscriptions is a riot waiting for a journalist.', bn: 'Domain (এখতিয়ার-সন্ধি), Path, Expires/Max-Age (জমজ-ঘড়ি), Secure (পরিবহন-সিল), HttpOnly (স্ক্রিপ্ট-সিল), SameSite=Strict|Lax|None+Secure (প্রেরণ-নীতি)। খোদাইহীন কুকি হলো দাঙ্গা, সাংবাদিকের অপেক্ষায়।' } },
        { term: 'jar arithmetic', def: { en: '~4KB per cookie, ~50 minimum / ~180 observed per domain, eviction sorts by least-recently-used with no appeal. Prefixes: __Host- (no Domain + Secure), __Secure- (Secure) — the two writs forged to never lie about their seals.', bn: 'কুকিপ্রতি ~4KB, ডোমেইনপ্রতি ~50 ন্যূনতম / ~180 পর্যবেক্ষিত, বহিষ্কার সবচেয়ে-কম-সম্প্রতি-ব্যবহৃত অনুসারে মীমাংসিত, কোনো আপিল ছাড়া। উপসর্গ: __Host- (Domain-ছাড়া + Secure), __Secure- (Secure) — দুটি লিপি, তাদের সিল নিয়ে মিথ্যা বলার অযোগ্য বানানো।' } },
        { term: 'the login rotation', def: { en: 'Pre-auth and post-auth session ids must differ; fixation dies by rotation and nothing else. Logout burns server-side; deleting client-side alone is shredding your own copy while the bank still honors it.', bn: 'প্রাক-প্রমাণ ও প্রমাণোত্তর সেশন-আইডি আলাদা হতেই হবে; ফিক্সেশন কেবল আবর্তনেই মরে, অন্য কিছুতে নয়। লগআউট সার্ভার-পার্শ্বে পোড়ায়; শুধু ক্লায়েন্ট-পার্শ্ব মোছা হলো নিজের কপি ছিঁড়ে ফেলা, যখন ব্যাংক তা এখনো মানে।' } },
        { term: '401 vs 403 vs 402', def: { en: '401 = who are you (WWW-Authenticate names the scheme); 403 = I know who you are, and no; 402 = toll-booth, still dusty. Sending a bearer to a 403 fixes nothing — the wall does not read nicer tokens.', bn: '401 = আপনি কে (WWW-Authenticate স্কিমের নাম বলে); 403 = আমি জানি আপনি কে, আর তা না; 402 = টোলবুথ, এখনো ধুলোমাখা। 403-এ বিয়ারার পাঠানো কিছু ঠিক করে না — প্রাচীর সুন্দর টোকেন পড়ে না।' } },
      ],
    },
    {
      group: { en: 'The arithmetic cabinet', bn: 'পাটিগণিত-ক্যাবিনেট' },
      items: [
        { term: 'redirect demotion law', def: { en: '301/302 may demote POST→GET (borrowed semantics, UA-fossilized); 303 mandates demotion; 307/308 forbid it. For APIs: declare method-bearing redirects (307/308); for forms: 303 the PRG pattern, always.', bn: '301/302 POST→GET পদাবনত করতে পারে (ধারকরা-অর্থ, ক্লায়েন্টে ফসিলকৃত); 303 পদাবনতি আদেশ করে; 307/308 নিষেধ করে। API-তে: পদ্ধতি-রক্ষণকারী রিডাইরেক্ট ঘোষণা করুন (307/308); ফর্মে: 303-এ PRG-প্যাটার্ন, সবসময়।' } },
        { term: 'hop & spider arithmetic', def: { en: 'Every redirect costs a full round trip per follower and a crawl-budget reinvestment for spiders; chains compound both. Internal links owe updates, not the new location’s charity.', bn: 'প্রতি রিডাইরেক্ট ফলোয়ারপ্রতি একটি পূর্ণ রাউন্ড-ট্রিপ খরচ করে আর মাকড়ের জন্য ক্রল-বাজেট-পুনবিনিয়োগ; শৃঙ্খল দুটোকেই চক্রবৃদ্ধি করে। অভ্যন্তরীণ লিংক হালনাগাদের পাওনাদার, নতুন অবস্থানের দানের নয়।' } },
        { term: '206 & resumption', def: { en: 'Range: bytes=start-end negotiates partial bodies; the seal (ETag/If-Range) keeps resumption honest; a 200 replacing a resumed 206 is an invoice for full re-delivery.', bn: 'Range: bytes=start-end আংশিক বডির দর কষাকষি করে; সিল (ETag/If-Range) পুনর্গ্রহণ সৎ রাখে; পুনর্গ্রহণিত 206-এর জায়গায় 200 হলো পূর্ণ-পুনঃসরবরাহের চালান।' } },
        { term: 'Content-Length discipline', def: { en: 'The promise on the envelope: too long hangs readers at the court; too short amputates the letter; mismatches on streaming platforms are the classic truncated-response incident class.', bn: 'খামের ওপর প্রতিশ্রুতি: অতিরিক্ত দীর্ঘ পাঠকদের দরবারে ঝুলিয়ে দেয়; খুব ছোট উত্তর বিভঙ্গ করে; স্ট্রিমিং-প্ল্যাটফর্মে অমিল হলো ছেঁড়া-প্রতিক্রিয়া-ঘটনার প্রচলিত শ্রেণি।' } },
      ],
    },
    {
      group: { en: 'The resilience cabinet', bn: 'সহনশীলতা-ক্যাবিনেট' },
      items: [
        { term: 'f∘f = f (world-priced)', def: { en: 'Idempotent means the world prices the operation once however many knocks arrive; receipts (status codes) may differ — DELETE twice → 204 then 404 both honest. Caching responses while re-running handlers is the fraud wearing the theorem’s robe.', bn: 'অবিচ্ছেদ্য মানে জগৎ অপারেশনের মূল্য একবারই ধরে, যত ধকই আসুক; রসিদ (স্ট্যাটাস-কোড) ভিন্ন হতে পারে — DELETE দুইবার → 204 তারপর 404, দুটোই সৎ। হ্যান্ডলার পুনঃচালু করে রেসপন্স ক্যাশ করা হলো উপপাদ্যের আবরণ পরা প্রতারণা।' } },
        { term: 'the mint (Idempotency-Key)', def: { en: 'Client mints a key per operation; server claims it with a unique-insert pending row, blocks or 409s concurrent duplicates, stores the verdict with the effect in one commit, replays bytes for the window (~24h). Payload mismatch on a key → 422, loudly.', bn: 'ক্লায়েন্ট অপারেশনপ্রতি কী মুদ্রণ করে; সার্ভার অনন্য-সন্নিবেশ-মুলতুবি-সারিতে দাবি করে, সমবর্তী অনুলিপি অবরোধ বা 409 করে, রায়-ও-প্রভাব এক কমিটে জমা রাখে, জানালায় (~24h) বাইট পুনঃবাজায়। কী-তে পেলোড-অমিল → জোরে 422।' } },
        { term: 'retry taxonomy', def: { en: 'First knock free (connection refused, TLS reset, HTTP/2 GOAWAY); 5xx/timeout priced by the three-case silence (never arrived / arrived-executed-audited / arrived-executed-unaudited); 429 pays tithe after Retry-After; 4xx verdicts stand.', bn: 'প্রথম ধক বিনামূল্যে (connection refused, TLS রিসেট, HTTP/2 GOAWAY); 5xx/টাইমআউট মূল্যায়িত তিন-ঘটনার-নীরবতায় (পৌঁছায়নি / পৌঁছে-কার্যকর-নথিভুক্ত / পৌঁছে-কার্যকর-অনথিভুক্ত); 429 Retry-After-পরে কর দেয়; 4xx রায় দৃঢ়।' } },
        { term: 'jitter & breakers', def: { en: 'Capped exponential without full jitter = metronome with amnesia; jitter = uniform[0, base×2^n] smears waves into weather. Breakers are per-office law: after N failures the office hears silence until the single probe returns.', bn: 'পূর্ণ-জিটারবিহীন সীমিত-সূচকীয় = স্মৃতিহীন তালকলঘড়ি; জিটার = uniform[0, ভিত্তি×2^n] ঢেউকে ছড়িয়ে দেয় আবহাওয়ায়। ব্রেকার হলো অফিসপ্রতি-বিধি: N ব্যর্থতার পর অফিস শোনে নীরবতা, যতক্ষণ না একক অনুসন্ধানী ফেরে।' } },
      ],
    },
  ],
  roadmap: [
    { stage: 1, title: { en: 'Read envelopes, not frameworks', bn: 'ফ্রেমওয়ার্ক নয়, খাম পড়ুন' }, detail: { en: 'request line three-fields; Host as the multiplexing passport; response mirrors; curl -v as the x-ray machine.', bn: 'অনুরোধ-লাইনের তিন-ক্ষেত্র; মাল্টিপ্লেক্সিং-পাসপোর্টরূপে Host; প্রতিক্রিয়া-প্রতিবিম্ব; এক্স-রে-যন্ত্র হিসেবে curl -v।' } },
    { stage: 2, title: { en: 'Verbs as contracts', bn: 'চুক্তি হিসেবে ক্রিয়া' }, detail: { en: 'safe/idempotent/cacheable-by-default per method; the 302 demotion family (301/302/303/307/308); the 401-challenge doorway.', bn: 'পদ্ধতিভেদে নিরাপদ/অবিচ্ছেদ্য/ডিফল্টে-ক্যাশযোগ্য; 302 পদাবনতি-পরিবার (301/302/303/307/308); 401-চ্যালেঞ্জ-প্রবেশপথ।' } },
    { stage: 3, title: { en: 'Lease and seal', bn: 'লিজ আর সিল' }, detail: { en: 'max-age budgets staleness; public/private ownership; no-cache decoded; ETag duels and the 304 cheapest-answer arithmetic; Vary names every true variance.', bn: 'max-age বাসিতার বাজেট; public/private মালিকানা; no-cache সমাধান; ETag দ্বৈরথ আর 304 সস্তা-উত্তর-পাটিগণিত; প্রতি প্রকৃত-পার্থক্য নামায় Vary।' } },
    { stage: 4, title: { en: 'Header typography & the salon', bn: 'হেডার-টাইপোগ্রাফি ও রুঁদ' }, detail: { en: 'header casing/case-insensitivity; Content-Type as the body’s passport; Accept/*.q weights, agent- vs server-driven discipline, self-naming representations.', bn: 'হেডার-কেসিং/কেস-অসংবেদনশীলতা; বডির পাসপোর্টরূপে Content-Type; Accept/*.q ওজন, এজেন্ট বনাম সার্ভার-চালিত শৃঙ্খলা, নিজের-নামকরণকারী প্রতিনিধিত্ব।' } },
    { stage: 5, title: { en: 'The seven inscriptions', bn: 'সাত খোদাই' }, detail: { en: 'Domain/Path sandhi; twin clocks; Secure/HttpOnly seals; SameSite sending policy; __Host- prefix forgery-resistance; rotation at login; eviction and 431 as debug surface.', bn: 'Domain/Path সন্ধি; জমজ-ঘড়ি; Secure/HttpOnly সিল; SameSite প্রেরণ-নীতি; __Host- উপসর্গের জাল-প্রতিরোধ; লগইনে আবর্তন; ডিবাগ-তলরূপে বহিষ্কার ও 431।' } },
    { stage: 6, title: { en: 'The credential tribunal', bn: 'শংসাপত্র-ট্রাইব্যুনাল' }, detail: { en: '401 as challenge + WWW-Authenticate scheme grammar; Bearer vs Basic; 403 the wall; CORS method/Origin/preflight/credentials courtroom.', bn: 'চ্যালেঞ্জরূপে 401 + WWW-Authenticate স্কিম-ব্যাকরণ; Bearer বনাম Basic; প্রাচীর 403; CORS পদ্ধতি/Origin/প্রিফ্লাইট/শংসাপত্র কোর্টরুম।' } },
    { stage: 7, title: { en: 'partial-body arithmetic', bn: 'আংশিক-বডি-পাটিগণিত' }, detail: { en: 'Content-Range invoices; single & multipart byteranges; resumption seals; synchronized charging with the offset ledger.', bn: 'Content-Range চালান; একক ও মাল্টিপার্ট বাইটরেঞ্জ; পুনর্গ্রহণ-সিল; অফসেট-খাতায় সমলয়িত চার্জিং।' } },
    { stage: 8, title: { en: 'migration protocols', bn: 'আস্থানান্তর-প্রোটোকল' }, detail: { en: 'redirect as load-bearing change control; campaigns (apex, HTTPS, rebrands, pagination, SPA); multiplexing deadlines and per-protocol redirect case law.', bn: 'ভারবহন পরিবর্তন-নিয়ন্ত্রণরূপে রিডাইরেক্ট; অভিযান (মূল-ডোমেইন, HTTPS, পুনঃব্র্যান্ডিং, পৃষ্ঠাঙ্কন, SPA); মাল্টিপ্লেক্সিং-সময়সীমা ও প্রোটোকলপ্রতি রিডাইরেক্ট-মামলাবিধি।' } },
    { stage: 9, title: { en: 'Retry is fleet policy', bn: 'রিট্রাই হলো বহর-নীতি' }, detail: { en: 'f∘f in worlds; the mint’s atomicity parts; retry taxonomy three shapes; jitter/breakers/feedback as the three synchronization dissolvers; closing statute.', bn: 'জগতে f∘f; মুদ্রালয়ের পারমাণবিকতার অংশ; রিট্রাই-শ্রেণিবিন্যাসের তিন আকৃতি; তিন সমলয়করণ-বিলোপকারীরূপে জিটার/ব্রেকার/প্রতিক্রিয়া; সমাপনী-বিধান।' } },
  ],
  projects: [
    {
      title: { en: 'EnvelopeCourt: the twelve-beat harness', bn: 'খাম-আদালত: বারো-ছন্দ হার্নেস' },
      brief: { en: 'Reimplement the hub’s conversation as an event-driven harness: one request script, four client plugins (amnesiac, validator, clerk, purist), one origin emulator with the ledger law table. The harness must emit the counter board per run (origin hits, origin bytes, cache hits, 304s, rewrites) and REFUSE to mark a run green unless the purist’s rewrite counter is zero — the method purity run becomes executable code review.', bn: 'হাবের কথোপকথন পুনর্নির্মাণ করুন ঘটনা-চালিত হার্নেসে: একটি অনুরোধ-স্ক্রিপ্ট, চার ক্লায়েন্ট-প্লাগিন (বিস্মৃত, পরীক্ষক, কেরানি, খাঁটিয়াল), খাতা-বিধি-তালিকাসহ একটি অরিজিন-এমুলেটর। হার্নেসকে প্রতি রানে গণক-বোর্ড নির্গমন করতে হবে (অরিজিন-ধক, অরিজিন-বাইট, ক্যাশ-হিট, 304, পুনর্লিখন) আর কোনো রান সবুজ চিহ্নিত করতে অস্বীকার করবে, যতক্ষণ না খাঁটিয়ালের পুনর্লিখন-গণক শূন্য।' },
      difficulty: 'beginner',
    },
    {
      title: { en: 'JarInquisitor: the cookie audit', bn: 'পাত্র-জিজ্ঞাসাকার: কুকি নিরীক্ষণ' },
      brief: { en: 'Write a devtools-style auditor that records every Set-Cookie a session emits and files charges: missing Secure on HTTPS, missing HttpOnly on session ids, Domain widening beyond the minting host, SameSite=absent on auth cookies, size >4KB, count >100. Then run it against three real sign-in flows and write the one-page verdict — charges cited per inscription, ranked by incident class (session fixation → rider-collision → silent logout loop).', bn: 'ডেভটুলস-শৈলীর নিরীক্ষক লিখুন, যা সেশনের প্রতি Set-Cookie রেকর্ড করে অভিযোগ দায়ের করে: HTTPS-এ Secure-বিহীন, সেশন-আইডিতে HttpOnly-বিহীন, মুদ্রণকারী-হোস্ট ছাড়িয়ে Domain-প্রসারণ, প্রমাণ-কুকিতে SameSite-বিহীন, >4KB, >100। তারপর তিনটি বাস্তব সাইন-ইন-ধারায় চালিয়ে এক-পাতার রায় লিখুন — খোদাইপ্রতি উদ্ধৃত অভিযোগ, ঘটনা-শ্রেণিতে সাজানো।' },
      difficulty: 'intermediate',
    },
    {
      title: { en: 'The Mint: a key store that survives itself', bn: 'মুদ্রালয়: নিজেকে টেকানো কী-ভাণ্ডার' },
      brief: { en: 'Build the Idempotency-Key service the capstone benches: unique-insert pending claim, verdict written in the same commit as the effect, concurrent-duplicates blocked or 409, payload-mismatch 422, TTL sweep, replayed-byte responses. Then try to break it: kill the leader post-effect pre-verdict, replay with mutated bodies, two pods racing one key. The tests, not the writeup, are the deliverable — price each failure shape.', bn: 'শেষাংশ-বেঞ্চের Idempotency-Key সেবাটি বানান: অনন্য-সন্নিবেশ-মুলতুবি-দাবি, প্রভাবের একই কমিটে লেখা রায়, অবরুদ্ধ/409 সমবর্তী-অনুলিপি, পেলোড-অমিলে 422, TTL সুইপ, বাইটে-বাজানো প্রতিক্রিয়া। তারপর ভাঙার চেষ্টা করুন: প্রভাবোত্তর-রায়পূর্ব নেতা হত্যা, বদলানো-বডি-পুনঃবাজানো, এক কী-তে দুই পড-দৌড়। প্রতিবেদন নয়, পরীক্ষাগুলোই বাজেয়াপ্ত — প্রতি ব্যর্থতা-আকৃতি মূল্যায়িত।' },
      difficulty: 'advanced',
    },
  ],
  bestPractices: [
    { en: 'End every verb with its contract in mind: GET for reads (safe, prefetchable), PUT for full replaces, POST for actions/creations, DELETE for removals — lie once and the intermediaries settle the bill.', bn: 'প্রতি ক্রিয়া শেষ করুন চুক্তি মাথায় রেখে: পাঠে GET (নিরাপদ, প্রিফেচযোগ্য), পূর্ণ-প্রতিস্থাপনে PUT, ক্রিয়া/সৃষ্টিতে POST, অপসারণে DELETE — একবার মিথ্যা বললেই মধ্যবর্তীরা বিল মেটায়।' },
    { en: 'Say your max-age out loud and mint ETags wherever they’re cheap: leases over a day justify immutability in the PR; sealed duels (304) replace stampedes.', bn: 'max-age জোরে বলুন আর সস্তা যেখানেই ETag খন্ডন করুন: দিনের-বেশি-লিজ পিআর-এ immutable-তা ন্যায়সংগত করবে; মোহরযুক্ত দ্বৈরথ (304) স্ট্যাম্পিডের জায়গা নেয়।' },
    { en: 'Vary wherever the answer truly varies — Accept, Accept-Language, Authorization, Accept-Encoding — and let versioned names make stale seats irrelevant rather than wrong.', bn: 'উত্তর যেখানেই সত্যিকারে বদলায় Vary দিন — Accept, Accept-Language, Authorization, Accept-Encoding — আর সংস্করণকৃত-নাম দিয়ে বাসি-আসন করুন ভুল-নয়-কিন্তু-নিরীহ।' },
    { en: 'Write headers like a protocol citizen: lowercase names, single spaces, ASCII values, Content-Type on every body — typography is the one profession every intermediary charges at the door.', bn: 'প্রোটোকল-নাগরিকের মতো হেডার লিখুন: ছোট-হাতের নাম, একক ফাঁক, ASCII মান, প্রতি বডিতে Content-Type — টাইপোগ্রাফিই সেই পেশা, যার ফি প্রতি মধ্যবর্তী দরজায় নেয়।' },
    { en: 'Mint cookies with all seven inscriptions present and deliberate; absent Domain or SameSite is a default someone else wrote for you. Rotate session ids at every authentication state change, without exception.', bn: 'সাত খোদাই উপস্থিত ও সচেতন রেখে কুকি মুদ্রণ করুন; অনুপস্থিত Domain বা SameSite হলো অন্য কারো লেখা ডিফল্ট। প্রতিটি প্রমাণীকরণ-অবস্থা-পরিবর্তনে সেশন-আইডি আবর্তন করুন, ব্যতিক্রম ছাড়া।' },
    { en: 'Treat 401 as a door, not a verdict: always answer with WWW-Authenticate and a scheme the client can answer to. And send tokens only where they’re owed — a bearer to the wrong Origin is public performance of your secret.', bn: '401-কে দুয়ার মনে করুন, রায় নয়: সবসময় WWW-Authenticate-সহ উত্তর দিন, এমন স্কিম যার জবাব ক্লায়েন্ট দিতে পারে। আর টোকেন পাঠান কেবল যেখানে পাওনা — ভুল Origin-এ বিয়ারার মানে আপনার গোপনীয়তার জনসম্মুখ-প্রদর্শন।' },
    { en: 'Design every mutating endpoint for the three-case silence: POSTs carry Idempotency-Key, PUTs carry complete representations, retries after 429/503 pay tithe after Retry-After with full jitter — never the metronome.', bn: 'প্রতিটি রূপান্তরকারী এন্ডপয়েন্ট নকশা করুন তিন-ঘটনার-নীরবতার জন্য: POST বহন করে Idempotency-Key, PUT বহন করে পূর্ণ-প্রতিনিধিত্ব, 429/503-পরবর্তী রিট্রাই Retry-After-পরে কর দেয় পূর্ণ-জিটারসহ — কভু তালকলঘড়ি নয়।' },
    { en: 'Instrument retry fleets as policy, not defaults: breaker thresholds per office, shed-based backpressure (X-RateLimit-Remaining) honored before blind exponential, and dead-letter queues instead of infinite retries.', bn: 'রিট্রাই-বহর যন্ত্রাঙ্কিত করুন নীতিরূপে, ডিফল্টরূপে নয়: অফিসপ্রতি ব্রেকার-প্রান্তিক, অন্ধ-সূচকীয়ের আগে মেনে-চলা শেড-ভিত্তিক-ব্যাকপ্রেশার (X-RateLimit-Remaining), আর অসীম-রিট্রাইয়ের বদলে ডেড-লেটার-কিউ।' },
  ],
  interview: [
    {
      q: { en: 'Explain GET vs POST “like I’m five”, then like an interviewer wants.', bn: 'GET বনাম POST ব্যাখ্যা করুন “পাঁচবছরীর মতো”, তারপর যেভাবে সাক্ষাৎকারক চান।' },
      a: { en: 'Five: GET asks the librarian to SHOW you a book — nothing changes, so anyone may repeat it; POST HANDS her a new book to shelve — the library differs afterwards. Interviewer: the difference is contract, not payload: GET is safe + idempotent (crawlable, prefetchable, blind-retry free); POST is neither — idempotency must be supplied by key or verb-design. Follow-ups write themselves: can POST ever be cached? (explicit freshness opt-in) and what happens to a timed-out POST? (idempotency keys / dedupe constraints, never blind re-knocks).', bn: 'পাঁচবর্ষী: GET গ্রন্থাগারিককে বই দেখাতে বলে — কিছু বদলায় না, তাই যে-কেউ পুনরাবৃত্তি করতে পারে; POST তাঁর হাতে নতুন বই তুলে দেয় তাকে-বসাতে — পরে গ্রন্থাগার আলাদা। সাক্ষাৎকারক-ভাষায়: পার্থক্য চুক্তির, পেলোডের নয়: GET নিরাপদ + অবিচ্ছেদ্য (ক্রল, প্রিফেচ, অন্ধ-রিট্রাই-মুক্ত); POST কোনোটিই নয় — অবিচ্ছেদ্যতা আনতে হয় কী বা ক্রিয়া-নকশায়। ফলো-আপ নিজেই লেখা: POST কি কখনো ক্যাশ হয়? (স্পষ্ট সতেজতা-অপ্ট-ইন) আর টাইমআউট-খাওয়া POST-এর কী হয়? (অবিচ্ছেদ্য-কী / ডিডিউপ-সীমাবদ্ধতা, কভু অন্ধ পুনঃধক নয়)।' },
    },
    {
      q: { en: 'Design the authentication exchange for a cross-origin SPA hitting your API.', bn: 'আপনার API-তে আঘাত করা ক্রস-অরিজিন SPA-র জন্য প্রমাণীকরণ-বিনিময় নকশা করুন।' },
      a: { en: 'Layers, from the court outward. Credentials: bearer tokens in memory where possible; first-party cookie fallback means HttpOnly + Secure + SameSite=Lax and rotation at login. The challenge language: 401 with WWW-Authenticate: Bearer consistent everywhere, 403 reserved for authenticated-but-forbidden so clients never retry a wall. Cross-origin: CORS allowlist per Origin (never reflect *), method list honest, credentials flag only when the SPA truly sends cookies, and a priced preflight cache (Access-Control-Max-Age). Then failure shape: expired token → 401 once, refresh flow single-flight, refresh rotated, logout invalidated server-side. The answer a senior gives ends in the incident classes the design refuses: session fixation, token reflection, preflight stampedes.', bn: 'স্তরভেদে, দরবার থেকে বাইরে। শংসাপত্র: যথাসম্ভব মেমরিতে বিয়ারার-টোকেন; একপক্ষীয়-কুকি-বিকল্প মানে HttpOnly + Secure + SameSite=Lax এবং লগইনে আবর্তন। চ্যালেঞ্জ-ভাষা: সর্বত্র 401 সাথে সামঞ্জস্যপূর্ণ WWW-Authenticate: Bearer, 403 সংরক্ষিত প্রমাণিত-কিন্তু-নিষিদ্ধের জন্য, যাতে ক্লায়েন্ট প্রাচীরে রিট্রাই না করে। ক্রস-অরিজিন: Origin-প্রতি CORS অনুমতি-তালিকা (কভু * প্রতিফলন নয়), সৎ পদ্ধতি-তালিকা, শংসাপত্র-পতাকা কেবল কুকি পাঠালে, মূল্যায়িত প্রিফ্লাইট-ক্যাশ (Access-Control-Max-Age)। ব্যর্থতা-আকৃতি: মেয়াদোত্তীর্ণ টোকেন → একবার 401, একক-উড়ান-রিফ্রেশ-ধারা, আবর্তিত রিফ্রেশ, সার্ভার-পার্শ্বে বাতিলকৃত লগআউট। জ্যেষ্ঠের উত্তর শেষ হয় সেই ঘটনা-শ্রেণিতে যা নকশা অস্বীকার করে: সেশন-ফিক্সেশন, টোকেন-প্রতিফলন, প্রিফ্লাইট-স্ট্যাম্পিড।' },
    },
    {
      q: { en: 'A timed-out POST to /charges. Walk me through your retry decision.', bn: '/charges-এ টাইমআউট-খাওয়া POST। আপনার রিট্রাই-সিদ্ধান্ত ধাপে ধাপে দেখান।' },
      a: { en: 'Three-case silence first: did it arrive? Executed and audited, or executed and not? The wire owed me an answer and declined, so uncertainty is priced. Verdict: POST has no statute, so blind re-knock is an illegal gamble on case one. Lawful paths: (a) client carries an Idempotency-Key — retry identical, any outcome: fresh verdict, replayed bytes, or 422 on mismatch; key minted per OPERATION (checkout click), not per attempt. (b) no key → consult a reconciliation channel (GET charge-status?key=, ledger lookup) before any re-knock. Posture details that separate seniors: retry must be exponential with FULL jitter (uniform[0, base×2^n]), count-limited, breaker-aware, and dead-lettered past the policy envelope — and the server side of the answer is what makes (a) possible: unique claim row, verdict stored with effect, replayed bytes. Retry policy is fleet policy — name who owns the ceiling.', bn: 'আগে তিন-ঘটনার-নীরবতা: পৌঁছেছিল কি? কার্যকর হয়ে নথিভুক্ত, না কার্যকর-কিন্তু-অনথিভুক্ত? তার আমাকে উত্তরের ঋণী ছিল আর অস্বীকার করেছে, তাই অনিশ্চয়তা মূল্যায়িত। রায়: POST-এর বিধান নেই, তাই অন্ধ পুনঃধক প্রথম-ঘটনার ওপর অবৈধ জুয়া। বৈধ পথ: (ক) ক্লায়েন্ট বহন করে Idempotency-Key — হুবহু রিট্রাই, যে-ফলই আসুক: নতুন রায়, বাজানো-বাইট, বা অমিলে 422; কী মুদ্রিত অপারেশনপ্রতি (চেকআউট-ক্লিক), প্রচেষ্টাপ্রতি নয়। (খ) কী নেই → মিলকরণ-পথে (GET charge-status?key=, খাতা-অনুসন্ধান) যান পুনঃধকের আগে। জ্যেষ্ঠ-সাধারণ পার্থক্যকারী মনোভঙ্গি: রিট্রাই পূর্ণ-জিটারসহ সূচকীয় (uniform[0, ভিত্তি×2^n]), গণনা-সীমিত, ব্রেকার-সচেতন, নীতির বাইরে ডেড-লেটার — আর সার্ভার-পার্শ্বই (ক)-কে সম্ভব করে: অনন্য-দাবি-সারি, প্রভাবসহ জমাকৃত রায়, বাজানো বাইট। রিট্রাই-নীতি হলো বহর-নীতি — সিলিংয়ের মালিকের নাম বলুন।' },
    },
    {
      q: { en: 'Why is caching after re-running the handler — but returning a stored response — NOT idempotency?', bn: 'হ্যান্ডলার পুনঃচালু করে কিন্তু জমা-কৃত রেসপন্স ফেরত দেওয়া কেন অবিচ্ছেদ্যতা নয়?' },
      a: { en: 'Because idempotency prices worlds, and the world changed twice. The response cache is the receipt drawer: returning the replayed receipt while the handler burned money — stock decreased, audit rows doubled, alerts fired — gives you consistent bytestreams from an inconsistent world, the worst of both artifacts. The common traps this exposes: “same response twice” tests that pass while the ledger lies, retry frameworks that 404-cache themselves into serving tombstones, middleware that memorizes POST responses to look safe. The lawful version: the claim row and verdict INSIDE the transaction with the effect (or outbox+reconciliation), so the world changes once and the receipt merely replays. If you can only repeat one line: same WORLD twice, never same answer twice.', bn: 'কারণ অবিচ্ছেদ্যতা জগৎ মূল্যায়ন করে, আর জগৎ দুইবার বদলেছে। রেসপন্স-ক্যাশ হলো রসিদের টানা: হ্যান্ডলার যখন অর্থ পোড়ায় — স্টক কমল, নিরীক্ষণ-সারি দ্বিগুণ, সতর্কতা বাজল — তখন বাজানো-রসিদ ফেরত দেওয়া দেয় অসামঞ্জস্যপূর্ণ জগতের সামঞ্জস্যপূর্ণ বাইটধারা, দুটি দ্রব্যেরই নিকৃষ্টতম। এর যে ফাঁদগুলো উন্মোচিত হয়: “দুইবার একই রেসপন্স” পরীক্ষা, যা পাস করে অথচ খাতা মিথ্যা বলে; 404-ক্যাশ করে সমাধি-পরিবেশন শুরু করা রিট্রাই-ফ্রেমওয়ার্ক; নিরাপদ দেখানোর জন্য POST-রেসপন্স মুখস্থ করা মিডলওয়্যার। বৈধ রূপ: দাবি-সারি ও রায় প্রভাবের সঙ্গে লেনদেনের ভেতরে (বা outbox+মিলকরণ), যাতে জগৎ বদলায় একবার আর রসিদ কেবল বাজে। এক পংক্তি মনে রাখলে: একই জগৎ দুইবার, কভু একই উত্তর দুইবার নয়।' },
    },
    {
      q: { en: 'How do you decide whether a redirect should be 301, 302, 303, 307, or 308?', bn: 'রিডাইরেক্ট 301, 302, 303, 307 না 308 হবে, ঠিক করেন কীভাবে?' },
      a: { en: 'Two questions pick the row: is the move permanent, and may the method be demoted? Permanence is a caching question (may every seat keep the new address?), demotion is a method question (may POST arrive as GET?). Then the four lawful combinations: permanent+demotable → 301; temporary+demotable → 302 (the borrowed-semantics fossil, acceptable in GET-spaces); lawful-demote → 303 (see-other: PRG after forms); method-preserved → 307/308 (API-traffic, where demotion is corruption). Spider arithmetic and hop arithmetic are the pricing — every hop costs a round trip per client and crawl-budget reinvestment, so internal links owe updates rather than riding the redirect. Senior follow-ups: how long for caches? (301 is sticky — plan before you ink), and dead-ends? (410 teaches amnesia faster than 404).', bn: 'দুই প্রশ্ন সারি বাছে: স্থানান্তর স্থায়ী কি, আর পদ্ধতি পদাবনত হতে পারে কি? স্থায়িত্ব ক্যাশের প্রশ্ন (প্রতি আসন কি নতুন ঠিকানা রাখতে পারে?), পদাবনতি পদ্ধতির প্রশ্ন (POST কি GET হয়ে আসতে পারে?)। চার বৈধ সংমিশ্রণ: স্থায়ী+পদাবনমন → 301; অস্থায়ী+পদাবনমন → 302 (ধারকরা-অর্থের ফসিল, GET-জায়গায় গ্রহণযোগ্য); বৈধ-পদাবনতি → 303 (see-other: ফর্ম-পরবর্তী PRG); পদ্ধতি-রক্ষণ → 307/308 (API-ট্র্যাফিক, যেখানে পদাবনতি বিভ্রান্তি)। মূল্য নির্ধারণ মাকড়-পাটিগণিত ও ফলো-পাটিগণিতের — প্রতি ফলো ক্লায়েন্টপ্রতি রাউন্ড-ট্রিপ ও ক্রল-বাজেট-পুনবিনিয়োগ খরচ করে, তাই অভ্যন্তরীণ লিংক রিডাইরেক্টে না চড়ে হালনাগাদের পাওনাদার। জ্যেষ্ঠ-ফলো-আপ: ক্যাশে কতদিন? (301 আঠালো — কালি দেওয়ার আগে পরিকল্পনা), আর অবসান-স্থান? (410 404-এর চেয়ে তাড়াতাড়ি বিস্মৃতি শেখায়)।' },
    },
  ],
  realWorld: [
    { en: 'Every fetch() call is the envelope contract: verbs audit your API, statuses speak to the user’s browser, headers decide what the intermediaries may do without asking.', bn: 'প্রতি fetch() কল হলো খাম-চুক্তি: ক্রিয়া আপনার API নিরীক্ষণ করে, স্ট্যাটাস ব্যবহারকারীর ব্রাউজারে কথা বলে, হেডার ঠিক করে মধ্যবর্তী না-জিজ্ঞেসে কী করতে পারে।' },
    { en: 'CDNs and proxies are protocol citizens, not magic boxes: max-age/public/s-maxage/Vary is how you legislate them; a misused private/public is the most common confidentiality incident in audits.', bn: 'CDN আর প্রক্সি প্রোটোকলের নাগরিক, জাদুর বাক্স নয়: max-age/public/s-maxage/Vary দিয়েই আপনি তাদের আইন করেন; ভুল-ব্যবহৃত private/public হলো নিরীক্ষণে সবচেয়ে সাধারণ গোপনীয়তা-ঘটনা।' },
    { en: 'Cookie hygiene is breach prevention: HttpOnly on session ids, SameSite set with intent, rotation at every privilege change, and a hard eye on __Host- prefixing for anything touching auth.', bn: 'কুকি-স্বাস্থ্যবিধি হলো ভঙ্গ-প্রতিরোধ: সেশন-আইডিতে HttpOnly, অভিপ্রায়ে-কৃত SameSite, প্রতি সুবিধা-পরিবর্তনে আবর্তন, আর প্রমাণ-স্পর্শী যা-কিছুতে __Host- উপসর্গে কঠোর দৃষ্টি।' },
    { en: 'CORS triage is weekly bread: “blocked by CORS policy” is never fixed by reflecting Origins — it is fixed by asking which court enjoined which method+header pair and legislating precisely that.', bn: 'CORS-ট্রায়াজ সাপ্তাহিক রুটি: “blocked by CORS policy” কভু ঠিক হয় না Origin প্রতিফলনে — ঠিক হয় জিজ্ঞেসে, কোন আদালত কোন পদ্ধতি+হেডার-জোড়া নিষিদ্ধ করেছে, আর হুবহু সেটিই আইন করায়।' },
    { en: 'Retry storms take down healthy services after the outage ends: the resume-wave with no jitter is the classic second outage; fleet breakers and backoff budgets are launch-gate items.', bn: 'বিভ্রাট-শেষেও সুস্থ সার্ভিস ফেলে দেয় রিট্রাই-ঝড়: জিটারহীন পুনঃসংযোগ-ঢেউ হলো প্রচলিত দ্বিতীয় বিভ্রাট; বহর-ব্রেকার ও ব্যাকঅফ-বাজেট হলো লঞ্চ-গেট-বিষয়।' },
    { en: 'Payment, booking, inventory — every money endpoint ships an Idempotency-Key story or it ships double-charges: key generation, store, replay, TTL, and the 422-mismatch are one acceptance criterion, not five.', bn: 'পেমেন্ট, বুকিং, ইনভেন্টরি — প্রতি অর্থ-এন্ডপয়েন্ট Idempotency-Key-কাহিনি সহযোগে পাঠায়, নয়তো ডাবল-চার্জ পাঠায়: কী-জনন, ভাণ্ডার, পুনঃবাজানো, TTL আর 422-অমিল — একটি গ্রহণযোগ্যতা-মানদণ্ড, পাঁচটি নয়।' },
    { en: 'Range requests are what make video scrub bars, resumable downloads, and mobile PDFs tolerable; a CDN that strips Range breaks halfway markets you never sampled.', bn: 'ভিডিও-স্ক্রাব-বার, পুনরায়-শুরুযোগ্য ডাউনলোড আর মোবাইল-পিডিএফ সহনীয় করে রেঞ্জ-রিকোয়েস্ট; Range খুলে নেওয়া CDN ভেঙে দেয় সেই মাঝপথের বাজারগুলো, যা আপনি কভু নমুনা করেননি।' },
    { en: 'Health-checked fleets: HEAD probes, 503+Retry-After as civilized rest, 429 as honestly-named budgets — the protocol has a status for every operationally truthful sentence.', bn: 'হেলথ-চেককৃত বহর: HEAD অনুসন্ধান, সভ্য-বিশ্রামরূপে 503+Retry-After, সত্যিকারে-নামকৃত বাজেটরূপে 429 — প্রোটোকলের প্রতিটি অপারেশনাল-সত্য-বাক্যের জন্য স্ট্যাটাস আছে।' },
  ],
};
