import type { Lesson } from '../../../lib/types';

export const SaltingPepperLesson: Lesson = {
  slug: 'salting-pepper',
  tech: 'hashing',
  title: {
    en: 'Salting & Pepper Architecture: Defeating Rainbow Tables',
    bn: 'সল্ট ও পেপার আর্কিটেকচার: রেইনবো টেবিল প্রতিরোধ'
  },
  summary: {
    en: 'Master cryptographic salting and pepper strategies: understand why unsalted password hashes leak identical credentials, how 128-bit CSPRNG salts defeat precomputed rainbow tables, and how isolated HSM peppers provide defense-in-depth against database leaks.',
    bn: 'ক্রিপ্টোগ্রাফিক সল্ট ও পেপারের কৌশল আয়ত্ত করুন: কেন সল্টবিহীন পাসওয়ার্ড একই ক্রেডেনশিয়াল ফাঁস করে, কীভাবে ১২৮-বিট CSPRNG সল্ট রেইনবো টেবিলকে অকার্যকর করে এবং কীভাবে সুরক্ষিত HSM পেপার ডাটাবেস ফাঁসের বিরুদ্ধে বহুস্তরীয় প্রতিরক্ষা দেয় তা শিখুন।'
  },
  minutes: 25,
  blocks: [
    {
      type: 'heading',
      id: 'the-unsalted-hash-catastrophe',
      text: {
        en: 'The Catastrophe of Unsalted Password Hashes',
        bn: 'সল্টবিহীন পাসওয়ার্ড হ্যাশের মারাত্মক বিপর্যয়'
      }
    },
    {
      type: 'para',
      text: {
        en: 'In web application engineering, millions of users inevitably choose identical common passwords such as "password123", "letmein", or "admin". If a database stores unsalted hashes, every user sharing that password will have the exact same hash digest stored in the database table. An attacker who steals the database dump can immediately see which accounts share credentials. More critically, the attacker only needs to crack the hash once to compromise thousands of user accounts simultaneously.',
        bn: 'ওয়েব অ্যাপ্লিকেশন ইঞ্জিনিয়ারিংয়ে লক্ষ লক্ষ ব্যবহারকারী প্রায়ই একই ধরনের সাধারণ পাসওয়ার্ড বেছে নেন, যেমন "password123", "letmein" বা "admin"। কোনো ডাটাবেস যদি সল্ট ছাড়া সাধারণ হ্যাশ সংরক্ষণ করে, তবে একই পাসওয়ার্ড ব্যবহারকারী প্রত্যেকের ডাটাবেস রো-তে হুবহু একই হ্যাশ ডাইজেস্ট জমা হবে। আক্রমণকারী ডাটাবেসের ডাম্প চুরি করলে সাথে সাথে বুঝতে পারবে কোন কোন অ্যাকাউন্টের পাসওয়ার্ড এক। সবচেয়ে বিপজ্জনক বিষয় হলো, আক্রমণকারীকে কষ্ট করে মাত্র একবার হ্যাশটি ভাঙতে হয় এবং সাথে সাথে একই পাসওয়ার্ডের হাজার হাজার অ্যাকাউন্ট হ্যাক হয়ে যায়।'
      }
    },
    {
      type: 'keyterms',
      items: [
        {
          term: 'Cryptographic Salt',
          def: {
            en: 'A unique sequence of cryptographically random bytes generated per user and stored alongside the password hash.',
            bn: 'প্রতিটি ব্যবহারকারীর জন্য আলাদাভাবে তৈরি করা অবিন্যস্ত র্যান্ডম বাইট যা ডাটাবেসে পাসওয়ার্ড হ্যাশের পাশেই সংরক্ষিত থাকে।'
          }
        },
        {
          term: 'Application Pepper',
          def: {
            en: 'A high-entropy secret key kept strictly outside the database (in an HSM or KMS) and combined with the hash.',
            bn: 'একটি অত্যন্ত সুরক্ষিত গোপন চাবি যা ডাটাবেসের সম্পূর্ণ বাইরে (HSM বা KMS-এ) রেখে হ্যাশের সাথে যুক্ত করা হয়।'
          }
        },
        {
          term: 'Rainbow Table',
          def: {
            en: 'A precomputed space-time tradeoff database of millions of common password hashes used for instantaneous cracking.',
            bn: 'কোটি কোটি সাধারণ পাসওয়ার্ড ও তাদের পূর্ব-গণনাকৃত হ্যাশের একটি বিশাল ডাটাবেস যা তাৎক্ষণিক ক্র্যাকিংয়ের জন্য ব্যবহৃত হয়।'
          }
        },
        {
          term: 'CSPRNG Randomness',
          def: {
            en: 'Cryptographically Secure Pseudo-Random Number Generator producing unpredictable entropy for salt generation.',
            bn: 'ক্রিপ্টোগ্রাফিক্যালি নিরাপদ সিউডো-র্যান্ডম সংখ্যা জেনারেটর যা সল্ট তৈরির জন্য সম্পূর্ণ পূর্বানুমান-অযোগ্য এন্ট্রপি প্রদান করে।'
          }
        }
      ]
    },
    {
      type: 'heading',
      id: 'how-salting-works',
      text: {
        en: 'How Cryptographic Salting Neutralizes Rainbow Tables',
        bn: 'ক্রিপ্টোগ্রাফিক সল্ট কীভাবে রেইনবো টেবিলকে অকার্যকর করে'
      }
    },
    {
      type: 'para',
      text: {
        en: 'A cryptographic salt is a minimum 16-byte (128-bit) random string generated by a secure random generator (CSPRNG). When a user registers or changes their password, a fresh salt is generated and appended to the password: Hash = H(Password || Salt). The salt is stored in cleartext in the database alongside the user account record. The salt does not need to be secret: its sole purpose is to guarantee uniqueness.',
        bn: 'ক্রিপ্টোগ্রাফিক সল্ট হলো একটি নিরাপদ র্যান্ডম জেনারেটর (CSPRNG) থেকে তৈরি ন্যূনতম ১৬-বাইট (১২৮-বিট) অবিন্যস্ত স্ট্রিং। ব্যবহারকারী যখন একাউন্ট তৈরি বা পাসওয়ার্ড পরিবর্তন করেন, তখন একটি নতুন সল্ট তৈরি করে পাসওয়ার্ডের সাথে জুড়ে দেওয়া হয়: Hash = H(Password || Salt)। সল্টটি প্লেইনটেক্সট আকারেই ডাটাবেসে ব্যবহারকারীর রেকর্ডের সাথে সংরক্ষিত থাকে। সল্ট গোপন রাখার কোনো প্রয়োজন নেই: এর একমাত্র উদ্দেশ্য হলো বৈচিত্র্য ও অনন্যতা নিশ্চিত করা।'
      }
    },
    {
      type: 'diagram',
      title: {
        en: 'Unsalted Hashes vs Salted and Peppered Architecture',
        bn: 'সল্টবিহীন হ্যাশ বনাম সল্ট ও পেপার আর্কিটেকচার'
      },
      svg: `<svg viewBox="0 0 880 390" width="100%" height="auto" xmlns="http://www.w3.org/2000/svg" font-family="system-ui, sans-serif">
  <rect width="880" height="390" rx="16" fill="#090d16" stroke="#1e293b" stroke-width="2"/>

  <!-- Left: Unsalted Flaw -->
  <g transform="translate(40, 30)">
    <rect width="370" height="330" rx="12" fill="#450a0a" fill-opacity="0.3" stroke="#ef4444" stroke-width="1.5"/>
    <text x="185" y="30" text-anchor="middle" fill="#f87171" font-size="14" font-weight="bold">Unsalted Hashes (Fatal Flaw)</text>
    <text x="185" y="50" text-anchor="middle" fill="#ef4444" font-size="11">VULNERABLE TO RAINBOW TABLES</text>

    <rect x="25" y="70" width="320" height="40" rx="6" fill="#18181b" stroke="#71717a"/>
    <text x="40" y="95" fill="#e4e4e7" font-size="11">User 1: "secret123" →</text>
    <text x="210" y="95" fill="#ef4444" font-size="11" font-family="monospace">Hash: 0x9f2a8b...</text>

    <rect x="25" y="125" width="320" height="40" rx="6" fill="#18181b" stroke="#71717a"/>
    <text x="40" y="150" fill="#e4e4e7" font-size="11">User 2: "secret123" →</text>
    <text x="210" y="150" fill="#ef4444" font-size="11" font-family="monospace">Hash: 0x9f2a8b...</text>

    <rect x="25" y="180" width="320" height="40" rx="6" fill="#18181b" stroke="#71717a"/>
    <text x="40" y="205" fill="#e4e4e7" font-size="11">User 3: "secret123" →</text>
    <text x="210" y="205" fill="#ef4444" font-size="11" font-family="monospace">Hash: 0x9f2a8b...</text>

    <rect x="25" y="240" width="320" height="65" rx="6" fill="#27272a" stroke="#ef4444"/>
    <text x="185" y="265" text-anchor="middle" fill="#fca5a5" font-size="11" font-weight="bold">Single Rainbow Table Lookup:</text>
    <text x="185" y="285" text-anchor="middle" fill="#f87171" font-size="10">0x9f2a8b... matches "secret123" in 1 microsecond!</text>
    <text x="185" y="318" text-anchor="middle" fill="#f87171" font-size="10" font-weight="bold">All 3 accounts cracked simultaneously!</text>
  </g>

  <!-- Right: Salted + Peppered Architecture -->
  <g transform="translate(470, 30)">
    <rect width="370" height="330" rx="12" fill="#064e3b" fill-opacity="0.3" stroke="#10b981" stroke-width="2"/>
    <text x="185" y="30" text-anchor="middle" fill="#34d399" font-size="14" font-weight="bold">Salted + Peppered Architecture</text>
    <text x="185" y="50" text-anchor="middle" fill="#10b981" font-size="11" font-weight="bold">RAINBOW TABLES COMPLETELY USELESS</text>

    <rect x="25" y="70" width="320" height="40" rx="6" fill="#022c22" stroke="#10b981"/>
    <text x="35" y="87" fill="#a7f3d0" font-size="10">User 1: "secret123" + Salt_A (128-bit) + Pepper</text>
    <text x="35" y="102" fill="#6ee7b7" font-size="10" font-family="monospace">→ Hash: 0x4c81fa... (Unique)</text>

    <rect x="25" y="125" width="320" height="40" rx="6" fill="#022c22" stroke="#10b981"/>
    <text x="35" y="142" fill="#a7f3d0" font-size="10">User 2: "secret123" + Salt_B (128-bit) + Pepper</text>
    <text x="35" y="157" fill="#6ee7b7" font-size="10" font-family="monospace">→ Hash: 0xb92e33... (Unique)</text>

    <rect x="25" y="180" width="320" height="40" rx="6" fill="#022c22" stroke="#10b981"/>
    <text x="35" y="197" fill="#a7f3d0" font-size="10">User 3: "secret123" + Salt_C (128-bit) + Pepper</text>
    <text x="35" y="212" fill="#6ee7b7" font-size="10" font-family="monospace">→ Hash: 0x1f74dd... (Unique)</text>

    <rect x="25" y="240" width="320" height="65" rx="6" fill="#064e3b" stroke="#34d399"/>
    <text x="185" y="262" text-anchor="middle" fill="#ecfdf5" font-size="11" font-weight="bold">Rainbow Tables Defeated:</text>
    <text x="185" y="278" text-anchor="middle" fill="#a7f3d0" font-size="9">Requires 2^128 distinct precomputed tables</text>
    <text x="185" y="293" text-anchor="middle" fill="#34d399" font-size="9" font-weight="bold">+ Pepper in HSM stops offline GPU cracking</text>
    <text x="185" y="318" text-anchor="middle" fill="#34d399" font-size="10" font-weight="bold">Every single account must be cracked independently!</text>
  </g>
</svg>`,
      caption: {
        en: 'Unsalted identical passwords produce identical digests crackable by a single lookup. 128-bit salts guarantee unique digests, and HSM peppers shield hashes against offline database dumps.',
        bn: 'সল্টবিহীন একই পাসওয়ার্ড হুবহু একই ডাইজেস্ট তৈরি করে যা এক ক্লিকেই ভাঙা যায়। ১২৮-বিট সল্ট অনন্য ডাইজেস্ট নিশ্চিত করে এবং HSM পেপার ডাটাবেস চুরি হলেও অফলাইন ক্র্যাকিং রুখে দেয়।'
      }
    },
    {
      type: 'heading',
      id: 'salt-versus-pepper',
      text: {
        en: 'Salt vs Pepper: Architectural Comparison',
        bn: 'সল্ট বনাম পেপার: স্থাপত্যগত তুলনা'
      }
    },
    {
      type: 'table',
      head: [
        { en: 'Architectural Dimension', bn: 'স্থাপত্যগত মাত্রা' },
        { en: 'Cryptographic Salt', bn: 'ক্রিপ্টোগ্রাফিক সল্ট' },
        { en: 'Application Pepper', bn: 'অ্যাপ্লিকেশন পেপার' }
      ],
      rows: [
        [
          { en: 'Core Purpose', bn: 'মূল উদ্দেশ্য' },
          { en: 'Guarantees uniqueness across identical passwords; destroys rainbow tables', bn: 'একই পাসওয়ার্ডের জন্য ভিন্ন হ্যাশ নিশ্চিত করে; রেইনবো টেবিল ধ্বংস করে' },
          { en: 'Provides defense-in-depth against SQL injection and database dumps', bn: 'এসকিউএল ইনজেকশন ও ডাটাবেস ফাঁসের বিরুদ্ধে বহুস্তরীয় সুরক্ষা দেয়' }
        ],
        [
          { en: 'Secrecy Level', bn: 'গোপনীয়তার স্তর' },
          { en: 'Public: Stored in cleartext in the database alongside the user row', bn: 'উন্মুক্ত: ডাটাবেসে ব্যবহারকারীর সারিতে প্লেইনটেক্সট আকারে থাকে' },
          { en: 'Strictly Secret: Stored in an external HSM, Cloud KMS, or environment variable', bn: 'কঠোরভাবে গোপন: ডাটাবেসের বাইরে সুরক্ষিত HSM বা KMS-এ থাকে' }
        ],
        [
          { en: 'Generation Frequency', bn: 'তৈরির পৌনঃপুনিকতা' },
          { en: 'Generated uniquely per user upon registration or password reset', bn: 'প্রতি রেজিস্ট্রেশন বা পাসওয়ার্ড পরিবর্তনের সময় নতুন করে তৈরি হয়' },
          { en: 'System-wide or rotated quarterly per tenant via KMS', bn: 'পুরো সিস্টেমে একটি থাকে অথবা KMS দ্বারা নির্দিষ্ট সময় পর রোটেট হয়' }
        ],
        [
          { en: 'Recommended Length', bn: 'সুপারিশকৃত দৈর্ঘ্য' },
          { en: 'Minimum 16 bytes (128 bits) of CSPRNG entropy', bn: 'ন্যূনতম ১৬ বাইট (১২৮ বিট) CSPRNG এন্ট্রপি' },
          { en: 'Minimum 32 bytes (256 bits) of high-entropy key material', bn: 'ন্যূনতম ৩২ বাইট (২৫৬ বিট) উচ্চমানের গোপন কি' }
        ]
      ]
    },
    {
      type: 'heading',
      id: 'defense-in-depth-with-pepper',
      text: {
        en: 'The Pepper Security Advantage: Guarding Database Dumps',
        bn: 'পেপার ব্যবহারের নিরাপত্তা সুবিধা: ডাটাবেস ডাম্প রক্ষা'
      }
    },
    {
      type: 'list',
      items: [
        {
          en: 'SQL Injection Containment: In the event of an SQL injection vulnerability or accidental backup snapshot exposure, the adversary captures the user database (including usernames, emails, salts, and password hashes). Because the pepper lives solely inside the application KMS/HSM, the attacker cannot run hashcat or GPU brute-force attacks offline.',
          bn: 'এসকিউএল ইনজেকশন প্রতিরোধ: কোনো এসকিউএল ইনজেকশন বা ব্যাকআপ ফাঁসের কারণে আক্রমণকারী পুরো ডাটাবেস (ইউজারনেম, সল্ট ও হ্যাশ) চুরি করলেও সে অফলাইনে জিপিইউ ক্র্যাকিং চালাতে পারে না, কারণ গোপন পেপারটি কেবল ক্লাউড KMS বা HSM-এ সুরক্ষিত থাকে।'
        },
        {
          en: 'Precomputed Table Impossibility: A rainbow table attacker relies on generating precomputed lookup tables once and using them against multiple targets. A 128-bit salt forces the attacker to build a separate table for every individual user, which would require more digital storage than exists on Earth.',
          bn: 'পূর্ব-গণনাকৃত টেবিলের অসম্ভবতা: আক্রমণকারী একবার রেইনবো টেবিল বানিয়ে একাধিক ভিকটিমের উপর প্রয়োগ করতে চায়। ১২৮-বিট সল্ট আক্রমণকারীকে প্রতি ব্যবহারকারীর জন্য আলাদা টেবিল বানাতে বাধ্য করে, যার জন্য পৃথিবীতে বিদ্যমান মেমরির চেয়েও বেশি জায়গার প্রয়োজন হবে।'
        },
        {
          en: 'Constant-Time Verification: When checking a password during login, always compute the expected hash and compare it with the stored hash using crypto.timingSafeEqual. Standard string comparisons leak character matching times, creating a timing side-channel.',
          bn: 'কনস্ট্যান্ট-টাইম যাচাইকরণ: লগইনের সময় পাসওয়ার্ড পরীক্ষা করার ক্ষেত্রে সর্বদা crypto.timingSafeEqual ব্যবহার করে সংরক্ষিত হ্যাশের সাথে মেলান। সাধারণ স্ট্রিং তুলনা সময়ের পার্থক্য তৈরি করে টাইমিং সাইড-চ্যানেল ফাঁসের ঝুঁকি তৈরি করে।'
        }
      ]
    },
    {
      type: 'callout',
      kind: 'warn',
      title: {
        en: 'Never Reuse Salts Across Different Users',
        bn: 'কখনোই একাধিক ব্যবহারকারীর জন্য একই সল্ট ব্যবহার করবেন না'
      },
      text: {
        en: 'A static hardcoded salt shared across all users (e.g. const SALT = "my_app_salt_123") provides virtually zero protection against rainbow tables. An attacker simply precomputes a rainbow table with that specific static salt and cracks all passwords in bulk. Always generate a fresh, unique 128-bit salt for every single password using crypto.randomBytes(16).',
        bn: 'সমস্ত ব্যবহারকারীর জন্য একটিমাত্র স্ট্যাটিক সল্ট (যেমন const SALT = "my_app_salt_123") ব্যবহার করা সল্ট না থাকার মতোই অনিরাপদ। আক্রমণকারী কেবল সেই নির্দিষ্ট সল্টটি দিয়ে একটি রেইনবো টেবিল বানিয়ে একসাথে সবার পাসওয়ার্ড ক্র্যাক করে ফেলবে। সর্বদা crypto.randomBytes(১৬) দিয়ে প্রতিটি পাসওয়ার্ডের জন্য আলাদা ১২৮-বিট সল্ট তৈরি করুন।'
      }
    },
    {
      type: 'heading',
      id: 'executable-salting-engine',
      text: {
        en: 'Executable Node.js Salt & Pepper Authentication Engine',
        bn: 'এক্সিকিউটেবল Node.js সল্ট ও পেপার অথেনটিকেশন ইঞ্জিন'
      }
    },
    {
      type: 'para',
      text: {
        en: 'Below is a complete, runnable Node.js engine demonstrating production salt and pepper architecture. It registers 3 user accounts with identical passwords ("CorrectHorseBatteryStaple!"), proves that all 3 generated salts and hashes are 100% unique, and validates 3/3 user logins cleanly using constant-time verification.',
        bn: 'নিচে একটি স্বয়ংসম্পূর্ণ এবং কার্যকর Node.js ইঞ্জিন দেওয়া হলো যা আদর্শ সল্ট ও পেপার আর্কিটেকচার প্রদর্শন করে। এটি হুবহু একই পাসওয়ার্ড ("CorrectHorseBatteryStaple!") দিয়ে ৩টি অ্যাকাউন্ট রেজিস্টার করে, প্রমাণ করে যে সবকটি ৩টি সল্ট ও হ্যাশ ১০০% স্বতন্ত্র এবং কনস্ট্যান্ট-টাইম যাচাইয়ের মাধ্যমে ৩/৩ টি লগইন সফলভাবে নিশ্চিত করে।'
      }
    },
    {
      type: 'code',
      lang: 'javascript',
      caption: {
        en: 'Run with node: Per-user 128-bit CSPRNG salting, HSM pepper wrapping, and constant-time login verification',
        bn: 'node দিয়ে চালান: প্রতি ব্যবহারকারীর জন্য ১২৮-বিট CSPRNG সল্ট, HSM পেপার এবং কনস্ট্যান্ট-টাইম লগইন যাচাইকরণ'
      },
      code: `const crypto = require('crypto');

// Simulated secure KMS/HSM Application Pepper (never stored in database)
const pepper = crypto.randomBytes(32);

// User registration: generates unique 128-bit salt per account
function registerUser(email, password) {
  const salt = crypto.randomBytes(16); // 128-bit CSPRNG
  const hash = crypto.createHmac('sha256', pepper)
    .update(Buffer.concat([Buffer.from(password, 'utf8'), salt]))
    .digest('hex');
  return { email, salt: salt.toString('hex'), hash };
}

// User login verification using constant-time comparison
function verifyLogin(user, inputPassword) {
  const salt = Buffer.from(user.salt, 'hex');
  const computed = crypto.createHmac('sha256', pepper)
    .update(Buffer.concat([Buffer.from(inputPassword, 'utf8'), salt]))
    .digest('hex');
  return crypto.timingSafeEqual(Buffer.from(computed, 'hex'), Buffer.from(user.hash, 'hex'));
}

// 3 accounts registered with the IDENTICAL common password
const sharedPassword = "CorrectHorseBatteryStaple!";
const users = [
  registerUser("alice@codeshikhon.com", sharedPassword),
  registerUser("bob@codeshikhon.com", sharedPassword),
  registerUser("charlie@codeshikhon.com", sharedPassword)
];

// Verify uniqueness: salts and hashes must be 100% distinct
const uniqueSalts = new Set(users.map(u => u.salt)).size === 3;
const uniqueHashes = new Set(users.map(u => u.hash)).size === 3;

let loginOk = 0;
users.forEach(u => {
  if (verifyLogin(u, sharedPassword)) loginOk++;
});

console.log(\`[Salt Engine] 3 accounts tested with identical password: all 3 salts and hashes are 100% unique (\${uniqueSalts && uniqueHashes}).\`);
console.log(\`[Auth Verification] Verified \${loginOk}/3 user logins cleanly using per-user salts and pepper.\`);`
    },
    {
      type: 'tryit',
      title: {
        en: 'Interactive Salt & Pepper Playground',
        bn: 'ইন্টারেক্টিভ সল্ট ও পেপার প্লেগ্রাউন্ড'
      },
      html: `<h3>Salt & Pepper Credential Vault</h3>
<p>Register 3 users with the same password and observe how salts enforce distinct hash digests.</p>
<div style="display:flex;gap:10px;margin-bottom:12px;">
  <button id="registerBtn" style="padding:8px 14px;background:#6366f1;color:#fff;border:none;border-radius:6px;cursor:pointer;font-weight:600;">Register 3 Accounts</button>
</div>
<pre id="saltOut" style="background:#0f172a;color:#38bdf8;padding:12px;border-radius:8px;font-family:monospace;white-space:pre-wrap;font-size:13px;border:1px solid #1e293b;min-height:90px;">Click "Register 3 Accounts" to inspect unique salt and hash generation...</pre>`,
      css: `body { font-family: system-ui, sans-serif; padding: 12px; margin: 0; }`,
      js: `document.getElementById('registerBtn').addEventListener('click', () => {
  const commonPw = "SecurePassword2026!";
  const accounts = ["alice@codeshikhon.com", "bob@codeshikhon.com", "charlie@codeshikhon.com"];
  
  const results = accounts.map((email, i) => {
    const salt = Array.from(crypto.getRandomValues(new Uint8Array(16))).map(b => b.toString(16).padStart(2, '0')).join('');
    const fakeHash = "0x" + Array.from(crypto.getRandomValues(new Uint8Array(20))).map(b => b.toString(16).padStart(2, '0')).join('');
    return "Account " + (i + 1) + " (" + email + "):\\n" +
           "  • Password: \\"" + commonPw + "\\"\\n" +
           "  • Unique Salt: " + salt + "\\n" +
           "  • Stored Hash: " + fakeHash + " [DISTINCT DIGEST]";
  });
  
  document.getElementById('saltOut').textContent = 
    "[Salt & Pepper Vault Simulation]\\n" +
    results.join("\\n\\n") + "\\n\\n" +
    "[Verdict] Despite sharing identical passwords, all 3 accounts have completely distinct digests! Rainbow tables defeated 100%.";
});`
    }
  ],
  exercises: [
    {
      id: 'hsh-sp-ex-1',
      kind: 'mcq',
      topic: 'salt-primary-purpose',
      question: {
        en: 'What is the primary architectural purpose of adding a unique cryptographic salt to each user password before hashing?',
        bn: 'পাসওয়ার্ড হ্যাশ করার পূর্বে প্রতিটি ব্যবহারকারীর জন্য একটি অনন্য ক্রিপ্টোগ্রাফিক সল্ট যোগ করার প্রধান স্থাপত্যগত উদ্দেশ্য কী?'
      },
      options: [
        {
          en: 'To ensure identical passwords produce completely different hash digests, forcing attackers to crack each account individually and rendering precomputed rainbow tables useless',
          bn: 'একই পাসওয়ার্ডের জন্য সম্পূর্ণ ভিন্ন ভিন্ন হ্যাশ ডাইজেস্ট তৈরি করা, যার ফলে আক্রমণকারী প্রতিটি অ্যাকাউন্ট আলাদাভাবে ক্র্যাক করতে বাধ্য হয় এবং রেইনবো টেবিল অকার্যকর হয়'
        },
        {
          en: 'To compress the password string so it takes up zero bytes in the database',
          bn: 'পাসওয়ার্ড সংকুচিত করা যাতে এটি ডাটাবেসে শূন্য বাইট জায়গা দখল করে'
        },
        {
          en: 'To automatically send an SMS confirmation message to the user phone',
          bn: 'ব্যবহারকারীর ফোনে স্বয়ংক্রিয়ভাবে একটি নিশ্চিতকরণ এসএমএস পাঠানো'
        },
        {
          en: 'To change the website font color to white whenever the user logs in',
          bn: 'ব্যবহারকারী লগইন করলে ওয়েবসাইটের ফন্টের রং সাদা করে দেওয়া'
        }
      ],
      answer: 0,
      hint: {
        en: 'Salts eliminate duplicate hashes and make rainbow tables impractical.',
        bn: 'সল্ট ডুপ্লিকেট হ্যাশ দূর করে এবং রেইনবো টেবিল ব্যবহার অসম্ভব করে তোলে।'
      },
      explanation: {
        en: 'Salts do not need to be secret: their purpose is uniqueness. A 128-bit salt guarantees that two users with "password123" receive completely different digests.',
        bn: 'সল্ট গোপন রাখার প্রয়োজন নেই: এর কাজ হলো ভিন্নতা আনা। ১২৮-বিট সল্ট নিশ্চিত করে যে দুজন ব্যবহারকারী একই পাসওয়ার্ড দিলেও সম্পূর্ণ ভিন্ন হ্যাশ তৈরি হবে।'
      }
    },
    {
      id: 'hsh-sp-ex-2',
      kind: 'mcq',
      topic: 'pepper-storage-location',
      question: {
        en: 'Where must an application pepper be stored to provide true defense-in-depth against data breaches?',
        bn: 'ডাটা ফাঁসের বিরুদ্ধে প্রকৃত বহুস্তরীয় সুরক্ষা নিশ্চিত করতে অ্যাপ্লিকেশন পেপার কোথায় সংরক্ষণ করা উচিত?'
      },
      options: [
        {
          en: 'Strictly outside the user database: in a secure Hardware Security Module (HSM), Cloud KMS (AWS KMS, GCP KMS), or isolated secrets manager',
          bn: 'কঠোরভাবে ইউজার ডাটাবেসের বাইরে: একটি সুরক্ষিত হার্ডওয়্যার সিকিউরিটি মডিউল (HSM), ক্লাউড KMS বা সিক্রেট ম্যানেজারে'
        },
        {
          en: 'Directly in the public user table as a cleartext column visible to all users',
          bn: 'সবার কাছে দৃশ্যমান সাধারণ কলাম আকারে সরাসরি ইউজার টেবিলে'
        },
        {
          en: 'Printed on physical stickers glued to the office whiteboard',
          bn: 'অফিসের হোয়াইটবোর্ডে ডাকটিকিটের মতো আঠা দিয়ে লাগিয়ে'
        },
        {
          en: 'In the website CSS stylesheet so all web browsers can download it',
          bn: 'ওয়েবসাইটের সিএসএস ফাইলে যাতে সব ওয়েব ব্রাউজার এটি ডাউনলোড করতে পারে'
        }
      ],
      answer: 0,
      hint: {
        en: 'If the pepper is stored in the database, stealing the database steals the pepper too.',
        bn: 'পেপার ডাটাবেসে থাকলে ডাটাবেস চুরির সাথে সাথে পেপারও চুরি হয়ে যাবে।'
      },
      explanation: {
        en: 'The security value of a pepper comes from isolation. If an SQL injection dumps the database, the attacker still cannot begin offline cracking without the KMS-protected pepper.',
        bn: 'পেপারের মূল শক্তি হলো এর বিচ্ছিন্নতা। ডাটাবেস চুরি হলেও আক্রমণকারী KMS-এ সংরক্ষিত পেপার ছাড়া অফলাইনে পাসওয়ার্ড ভাঙতে পারে না।'
      }
    },
    {
      id: 'hsh-sp-ex-3',
      kind: 'mcq',
      topic: 'shared-static-salt-fallacy',
      question: {
        en: 'What dangerous vulnerability occurs if a developer uses a single static hardcoded salt across all user accounts in an application?',
        bn: 'একজন ডেভেলপার যদি পুরো অ্যাপ্লিকেশনে সব ব্যবহারকারীর জন্য একটিমাত্র ফিক্সড হার্ডকোডেড সল্ট ব্যবহার করেন, তবে কোন মারাত্মক ঝুঁকি তৈরি হয়?'
      },
      options: [
        {
          en: 'It completely fails to prevent rainbow tables: an attacker precomputes a single rainbow table using that specific static salt and cracks all user accounts in bulk',
          bn: 'এটি রেইনবো টেবিল ঠেকাতে সম্পূর্ণ ব্যর্থ হয়: আক্রমণকারী সেই নির্দিষ্ট সল্টটি দিয়ে একটি রেইনবো টেবিল বানিয়ে একসাথে সবার অ্যাকাউন্ট ক্র্যাক করে ফেলে'
        },
        {
          en: 'The server power supply automatically explodes after thirty seconds',
          bn: 'ত্রিশ সেকেন্ড পর সার্ভারের পাওয়ার সাপ্লাই নিজে থেকেই বিস্ফোরিত হয়'
        },
        {
          en: 'The website displays all user photos upside down',
          bn: 'ওয়েবসাইট সমস্ত ব্যবহারকারীর ছবি উল্টো করে প্রদর্শন করে'
        },
        {
          en: 'The database server changes all user passwords to the word "coffee"',
          bn: 'ডাটাবেস সার্ভার সবার পাসওয়ার্ড পরিবর্তন করে "coffee" বানিয়ে ফেলে'
        }
      ],
      answer: 0,
      hint: {
        en: 'A static salt provides zero protection because the attacker only needs to precompute one table.',
        bn: 'স্থির সল্ট কোনো সুরক্ষা দেয় না কারণ আক্রমণকারী কেবল একটি টেবিল হিসাব করলেই কাজ হয়ে যায়।'
      },
      explanation: {
        en: 'Salts only defeat rainbow tables when they are unique per user. A single static salt reduces the defense to zero against an adversary targeting that application.',
        bn: 'সল্ট কেবল তখনই রেইনবো টেবিল ঠেকায় যখন তা প্রতি ব্যবহারকারীর জন্য আলাদা হয়। একটিমাত্র সল্ট আক্রমণকারীর কাছে সাধারণ সল্টবিহীন ব্যবস্থার মতোই সহজ।'
      }
    },
    {
      id: 'hsh-sp-ex-4',
      kind: 'predict',
      topic: 'salting-engine-verification-results',
      question: {
        en: 'In our live Node.js Salt & Pepper script, how many user logins with identical passwords were confirmed unique and successfully authenticated (e.g. 3/3)?',
        bn: 'আমাদের লাইভ Node.js সল্ট ও পেপার স্ক্রিপ্টে একই পাসওয়ার্ড বিশিষ্ট কতটি ইউজার লগইন সফলভাবে অনন্য প্রমাণিত ও যাচাই করা হয়েছিল (যেমন ৩/৩)?'
      },
      answer: '3/3',
      accept: ['3/3', '3', 'three', '৩/৩', '৩'],
      hint: {
        en: 'All 3 user accounts were verified cleanly.',
        bn: 'সবকটি ৩ টি অ্যাকাউন্টই নিখুঁতভাবে যাচাই হয়েছিল।'
      },
      explanation: {
        en: 'All 3 user accounts produced 100% unique salts and hashes, and 3/3 successfully verified during login using constant-time equality checks.',
        bn: 'সবকটি ৩ টি অ্যাকাউন্টই ১০০% অনন্য সল্ট ও হ্যাশ তৈরি করেছিল এবং কনস্ট্যান্ট-টাইম সমতার মাধ্যমে ৩/৩ টি লগইন সফলভাবে নিশ্চিত হয়েছিল।'
      }
    }
  ],
  quiz: {
    id: 'salting-pepper-quiz',
    title: {
      en: 'Salting & Pepper Architecture Quiz',
      bn: 'সল্ট ও পেপার আর্কিটেকচার কুইজ'
    },
    questions: [
      {
        id: 'hsh-sp-qz-1',
        kind: 'mcq',
        topic: 'salt-length-minimum-standard',
        question: {
          en: 'What is the universally accepted minimum cryptographic salt length recommended by NIST and modern security standards?',
          bn: 'NIST এবং আধুনিক নিরাপত্তা মানদণ্ড অনুযায়ী ক্রিপ্টোগ্রাফিক সল্টের সর্বজনীন ন্যূনতম গ্রহণযোগ্য দৈর্ঘ্য কত?'
        },
        options: [
          {
            en: 'At least 16 bytes (128 bits) of true cryptographically secure random entropy (CSPRNG)',
            bn: 'ন্যূনতম ১৬ বাইট (১২৮ বিট) বিশুদ্ধ ক্রিপ্টোগ্রাফিক র্যান্ডম এন্ট্রপি (CSPRNG)'
          },
          {
            en: '1 bit consisting of either a zero or a one',
            bn: 'মাত্র ১ বিট যা শূন্য অথবা এক হতে পারে'
          },
          {
            en: 'Four thousand gigabytes of text files',
            bn: 'চার হাজার গিগাবাইটের বিশাল টেক্সট ফাইল'
          },
          {
            en: 'Zero bytes because salts are entirely optional in production',
            bn: 'শূন্য বাইট কারণ প্রোডাকশনে সল্ট ব্যবহার সম্পূর্ণ ঐচ্ছিক'
          }
        ],
        answer: 0,
        hint: {
          en: '16 bytes (128 bits) provides 2^128 possible salt variations, making rainbow tables impossible.',
          bn: '১৬ বাইট (১২৮ বিট) ২^১২৮ টি ভিন্ন সল্টের সম্ভাবনা তৈরি করে যা রেইনবো টেবিল অসম্ভব করে।'
        },
        explanation: {
          en: '128 bits of salt entropy guarantees that even if a system stores billions of credentials, the mathematical probability of 2 users sharing a salt is practically zero.',
          bn: '১২৮ বিট এন্ট্রপি নিশ্চিত করে যে কোটি কোটি ব্যবহারকারীর ডাটাবেসেও ২ জন ব্যবহারকারীর সল্ট এক হওয়ার সম্ভাবনা কার্যত শূন্য।'
        }
      },
      {
        id: 'hsh-sp-qz-2',
        kind: 'mcq',
        topic: 'linkedin-breach-root-cause',
        question: {
          en: 'In the infamous 2012 LinkedIn security breach, what specific cryptographic failure allowed adversaries to crack millions of user passwords in days?',
          bn: '২০১২ সালের বিখ্যাত লিঙ্কডইন নিরাপত্তা বিপর্যয়ে কোন সুনির্দিষ্ট ক্রিপ্টোগ্রাফিক ভুলের কারণে আক্রমণকারীরা কয়েক দিনের মধ্যে লক্ষ লক্ষ পাসওয়ার্ড ক্র্যাক করতে পেরেছিল?'
        },
        options: [
          {
            en: 'LinkedIn stored passwords as raw unsalted SHA-1 hashes, allowing attackers to use precomputed rainbow tables to look up millions of common passwords almost instantly',
            bn: 'লিঙ্কডইন কোনো সল্ট ছাড়া সাধারণ SHA-১ হ্যাশ ব্যবহার করে পাসওয়ার্ড সংরক্ষণ করেছিল, ফলে হ্যাকাররা রেইনবো টেবিল দিয়ে নিমিষেই কোটি পাসওয়ার্ড উদ্ধার করে'
          },
          {
            en: 'LinkedIn accidentally mailed printed passwords to all internet users',
            bn: 'লিঙ্কডইন ভুলবশত সব ব্যবহারকারীর কাছে কাগজে প্রিন্ট করা পাসওয়ার্ড পাঠিয়েছিল'
          },
          {
            en: 'The LinkedIn office building was struck by lightning, wiping all encryption keys',
            bn: 'লিঙ্কডইনের অফিসে বজ্রপাত হয়ে সমস্ত এনক্রিপশন কি পুড়ে গিয়েছিল'
          },
          {
            en: 'The passwords were encrypted with Caesar cipher shift minus one',
            bn: 'পাসওয়ার্ডগুলো সিজার সাইফারের শিফট মাইনাস ১ দিয়ে এনক্রিপ্ট করা হয়েছিল'
          }
        ],
        answer: 0,
        hint: {
          en: 'Unsalted SHA-1 hashes were trivially cracked with precomputed tables.',
          bn: 'সল্টবিহীন SHA-১ হ্যাশ পূর্ব-গণনাকৃত টেবিল দিয়ে অতি সহজেই ভেঙে ফেলা হয়েছিল।'
        },
        explanation: {
          en: 'Over 6.5 million unsalted SHA-1 hashes were leaked. Because no salts were used, adversaries downloaded public rainbow tables and recovered over 90% of the passwords rapidly.',
          bn: '৬৫ লক্ষেরও বেশি সল্টবিহীন SHA-১ হ্যাশ ফাঁস হয়েছিল। কোনো সল্ট না থাকায় পাবলিক রেইনবো টেবিল ব্যবহার করে ৯০% পাসওয়ার্ড মুহূর্তেই বের করে ফেলা হয়।'
        }
      },
      {
        id: 'hsh-sp-qz-3',
        kind: 'mcq',
        topic: 'pepper-rotation-capability',
        question: {
          en: 'How can an enterprise rotate an application pepper without invalidating all existing user passwords?',
          bn: 'বিদ্যমান ব্যবহারকারীদের পাসওয়ার্ড বাতিল না করেই একটি প্রতিষ্ঠান কীভাবে অ্যাপ্লিকেশন পেপার পরিবর্তন বা রোটেট করতে পারে?'
        },
        options: [
          {
            en: 'By versioning the pepper (e.g. pepper_v1, pepper_v2) and wrapping the password hash with an outer HMAC/KMS layer that can be systematically re-wrapped when the pepper updates',
            bn: 'পেপারের ভার্সন তৈরি করে (যেমন pepper_v১, pepper_v২) এবং পাসওয়ার্ড হ্যাশকে একটি বহিরাগত HMAC/KMS স্তর দিয়ে মোড়কবদ্ধ করে যা পেপার বদলালে সহজে নতুন করে মোড়ানো যায়'
          },
          {
            en: 'By forcing all users to delete their email accounts permanently',
            bn: 'সমস্ত ব্যবহারকারীকে তাদের ইমেইল অ্যাকাউন্ট চিরতরে মুছে ফেলতে বাধ্য করে'
          },
          {
            en: 'By resetting all database tables to empty text files',
            bn: 'ডাটাবেসের সমস্ত টেবিল মুছে খালি ফাইলে রূপান্তর করে'
          },
          {
            en: 'Pepper rotation is impossible under international computer laws',
            bn: 'আন্তর্জাতিক কম্পিউটার আইনে পেপার রোটেট করা সম্পূর্ণ বেআইনি'
          }
        ],
        answer: 0,
        hint: {
          en: 'Wrapping the inner hash with an outer KMS pepper key allows rotating the outer layer without knowing the raw password.',
          bn: 'KMS পেপার দিয়ে বাইরের স্তর তৈরি করলে মূল পাসওয়ার্ড না জেনেই বাইরের স্তরটি পরিবর্তন করা যায়।'
        },
        explanation: {
          en: 'Using an outer HMAC wrap with the KMS pepper allows background batch jobs to re-wrap all stored hashes from pepper_v1 to pepper_v2 without requiring users to log in.',
          bn: 'KMS পেপার দিয়ে বহিরাগত HMAC ব্যবহার করলে ব্যবহারকারীর লগইন ছাড়াই ব্যাকগ্রাউন্ড প্রসেসের মাধ্যমে v১ থেকে v২ পেপারে রূপান্তর করা সম্ভব।'
        }
      },
      {
        id: 'hsh-sp-qz-4',
        kind: 'mcq',
        topic: 'timing-attacks-on-password-comparison',
        question: {
          en: 'Why must password hash verification routines always execute in constant time (e.g. using crypto.timingSafeEqual)?',
          bn: 'পাসওয়ার্ড হ্যাশ যাচাইকরণ কোড কেন সর্বদা কনস্ট্যান্ট-টাইমে (যেমন crypto.timingSafeEqual) চলতে হবে?'
        },
        options: [
          {
            en: 'Because non-constant-time comparisons return false early on the first mismatched byte, creating nanosecond response differences that allow remote attackers to guess password hashes character-by-character',
            bn: 'কারণ নন-কনস্ট্যান্ট-টাইম তুলনা প্রথম অমিল বাইটেই থেমে যায়, যা ন্যানোসেকেন্ড সময়ের ব্যবধান তৈরি করে হ্যাকারদের অক্ষর ধরে ধরে হ্যাশ অনুমান করার সুযোগ দেয়'
          },
          {
            en: 'Because constant-time functions make web pages load fifty percent faster',
            bn: 'কারণ কনস্ট্যান্ট-টাইম ফাংশন ওয়েব পেজকে পঞ্চাশ শতাংশ দ্রুত লোড হতে সাহায্য করে'
          },
          {
            en: 'Because standard comparisons cause database hard drives to overheat',
            bn: 'কারণ সাধারণ তুলনা চালালে ডাটাবেসের হার্ডডিস্ক অতিরিক্ত গরম হয়ে যায়'
          },
          {
            en: 'Because constant time is required by the World Clock Synchronization committee',
            bn: 'কারণ আন্তর্জাতিক ঘড়ি সমন্বয় কমিটি কনস্ট্যান্ট-টাইম বাধ্যতামূলক করেছে'
          }
        ],
        answer: 0,
        hint: {
          en: 'Early termination creates measurable timing side channels.',
          bn: 'তাড়াতাড়ি কাজ বন্ধ করলে পরিমাপযোগ্য সময়ের ফাঁক তৈরি হয়।'
        },
        explanation: {
          en: 'Timing side channels are completely eliminated by comparing every byte in fixed time, ensuring that invalid guesses take the exact same number of CPU cycles as valid credentials.',
          bn: 'নির্দিষ্ট সময়ে সব বাইট তুলনা করলে টাইমিং সাইড-চ্যানেল সম্পূর্ণ বন্ধ হয়, ফলে ভুল অনুমানেও ঠিক সঠিক অনুমানের মতোই সমান সিপিইউ সময় ব্যয় হয়।'
        }
      }
    ]
  },
  next: {
    slug: 'password-storage',
    title: {
      en: 'Password Storage: Argon2id, bcrypt, scrypt & Work Factors',
      bn: 'পাসওয়ার্ড স্টোরেজ: Argon2id, bcrypt, scrypt ও ওয়ার্ক ফ্যাক্টর'
    }
  }
};
