/**
 * Authoring spec for the Kubernetes hub, rewritten on 2026-09-26 from the old chant-style pages.
 * The bar for this hub: a reader who has used Docker once can follow it. Every page opens with two
 * or three plain sentences that name the situation before any YAML appears; every claim carries a
 * real number, a real field name, or a real kubectl command; nothing is explained with a metaphor.
 * Coverage: 8 lessons, beginner (what a cluster is) to operational (upgrades, RBAC, autoscaling),
 * which is wider than any single w3schools track — they do not have Kubernetes at all.
 */
export const meta = {
  exportName: 'kubernetesHub',
  name: 'Kubernetes',
  nameBn: 'কুবারনেটস',
  icon: '☸️',
  tagline: {
    en: 'Keep the right number of containers running, reachable, configured and safe — that is all a cluster does, and this hub walks through it one object at a time.',
    bn: 'সঠিক সংখ্যক container চালু, পৌঁছানো যায় এমন, সঠিক মান-সহ আর নিরাপদ রাখাই cluster-এর কাজ — এই হাবে বস্তু ধরে ধরে সেটাই দেখানো হচ্ছে।',
  },
  intro: {
    en: 'Kubernetes is a program that keeps being told what you want, compares it with what exists, and does the difference. You write a small file naming the image and the count; a controller notices the gap and creates or deletes pods until the numbers agree. Everything else in this hub is a detail of that loop: how pods are placed, how they are found, how they get their settings, and how you keep the whole thing safe to change.',
    bn: 'Kubernetes একটা প্রোগ্রাম, যা বারবার শোনে আপনি কী চান, দেখে বাস্তবে কী আছে, আর ফারাকটুকু মেটায়। আপনি একটি ছোট ফাইলে image আর সংখ্যা লিখেন; একজন controller তফাত দেখে সেই মতো pod বানায় বা মুছে ফেলে, সংখ্যা মিলে যাওয়া পর্যন্ত। এই হাবের বাকি সব কথা সেই ঘুরন্ত কাজেরই বিস্তারিত: pod কোথায় বসে, কীভাবে খুঁজে পাওয়া যায়, মান পায় কোথা থেকে, আর পুরো জিনিসটা বদলানো নিরাপদ কীভাবে থাকে।',
  },
  stages: [
    { title: { en: 'Stage 1 — Running workloads', bn: 'ধাপ ১ — কাজ চালানো' }, at: 0, to: 3 },
    { title: { en: 'Stage 2 — Traffic, settings and disk', bn: 'ধাপ ২ — যাতায়াত, মান আর ডিস্ক' }, at: 3, to: 6 },
    { title: { en: 'Stage 3 — Placing, protecting, operating', bn: 'ধাপ ৩ — বসানো, রক্ষা আর পরিচালনা' }, at: 6, to: 8 },
  ],
  bestPractices: [
    { en: 'Always ask for CPU and memory. A pod with no requests can be placed anywhere and evicted first; with requests it is scheduled against real space.', bn: 'CPU আর memory সবসময় চান। requests না-থাকা pod যেখানেই বসাতে পারে আর প্রথমেই বের করে দিতে পারে; requests থাকলে জায়গা মেপে বসায়।' },
    { en: 'Tag images with something immutable — a commit sha, not latest. A rollout you cannot roll back is only a restart.', bn: 'image-এর tag এমন হোক যা বদলায় না — commit sha, latest নয়। যে rollout ফিরিয়ে আনা যায় না, সেটি আসলে শুধু restart।' },
    { en: 'Set readiness and liveness probes differently. Readiness stops traffic; liveness restarts the container. One value for both turns slow starts into a crash loop.', bn: 'readiness আর liveness probe আলাদা ভাবে দিন। readiness যাতায়াত থামায়, liveness container restart করে। দুটির জন্য এক মান দিলে ধীর শুরুই crash loop হয়ে যায়।' },
    { en: 'Put a namespace and a label set on everything, before you need them for a policy, a quota or a search.', bn: 'namespace আর label আগেই দিয়ে ফেলুন — কখনো policy, quota বা খোঁজার জন্য দরকার হবে, তার আগেই।' },
    { en: 'Run one process per container, in the foreground, logging to stdout. Side effects that need a second daemon usually want a second container in the same pod.', bn: 'এক container-এ এক-ই প্রসেস, সামনে (foreground), log stdout-এ। দ্বিতীয় daemon-এর দরকার হলে সেটি একই pod-এর দ্বিতীয় container হোক।' },
    { en: 'Never hand-edit a live Deployment that a Git repository also owns. The controller will undo your work in seconds, and nobody will know who did it.', bn: 'যে Deployment একটা Git repository-এর অধীনে, সেটি হাতে বদলানো যাবে না। controller কয়েক সেকেন্ডে আপনার কাজ ফিরিয়ে দেবে, আর কে করেছিস বোঝা যাবে না।' },
  ],
  interview: [
    { q: { en: 'What actually happens when you run kubectl apply -f deploy.yaml?', bn: 'kubectl apply -f deploy.yaml চালানো হলে আসলে কী ঘটে?' },
      a: { en: 'kubectl sends the object to the API server, which authenticates you, authorises the verb, validates the schema, and writes the object into etcd. Nothing is done yet. From then on controllers do the work: the Deployment controller sees the new spec and creates a ReplicaSet, which creates pods, which the scheduler binds to nodes, which the kubelet on each node starts. Your file is a wish list, not a script.', bn: 'kubectl বস্তুটি API server-এ পাঠায়; server আপনাকে চেনে, কাজটির অনুমতি দেখে, গড়ন যাচাই করে etcd-তে লিখে রাখে। এ পর্যন্ত কিছুই করা হয়নি। এরপর controllers কাজ করে: Deployment controller নতুন spec দেখে একটা ReplicaSet বানায়, সেটি pod বানায়, scheduler সেগুলোকে node-এ বসায়, ঐ node-এর kubelet চালু করে। আপনার ফাইল একটি ইচ্ছের তালিকা, script নয়।' } },
    { q: { en: 'Difference between a Service and an Ingress?', bn: 'Service আর Ingress-এর তফাত কী?' },
      a: { en: 'A Service is a stable virtual IP and DNS name in front of a set of pods, chosen by label, and it works at layer 4 — TCP ports. An Ingress is a routing rule read by a controller: host names and URL paths on one HTTP port, mapped to Services. You need a Service for any traffic; you need an Ingress when many HTTP services share one entry point.', bn: 'Service হলো label দিয়ে বেছে নেওয়া এক দল pod-এর সামনে একটা স্থির virtual IP আর DNS নাম; এটি layer 4-এ কাজ করে, অর্থাৎ TCP port। Ingress একটা controller-এর পড়া routing নিয়ম: একটি HTTP port-এ একাধিক নাম ও path থেকে Service-এ যাওয়া। যেকোনো traffic-এর জন্য Service লাগবে; অনেক HTTP service এক প্রবেশপথে চাইলে Ingress লাগে।' } },
    { q: { en: 'A pod is CrashLoopBackOff. What do you read, in order?', bn: 'একটি pod CrashLoopBackOff-এ। কোন ক্রমে কী পড়বেন?' },
      a: { en: 'First kubectl describe pod — the Events at the bottom say whether the image failed to pull or the container exited. Then kubectl logs --previous for the last crashed copy; a missing config key or an unbound volume shows here. Only then read the manifest: command, args, env, probe paths, and the image tag. A probe pointing at a port the app never listens on is the most common answer, and it looks like a crash.', bn: 'আগে kubectl describe pod — নিচের Events বলে image টানা যায়নি নাকি container বেরিয়ে গেছে। তারপর kubectl logs --previous, শেষে crash-হওয়া কপিটির log; ভুল config-এর চাবি বা volume না-বাঁধার কথা এখানে দেখা যায়। এরপর manifest পড়ুন: command, args, env, probe-এর path, image tag। app যে port-এ কখনো কান না-দেয় সেই port-এ probe দেওয়াই সবচেয়ে বেশি উত্তর, আর সেটিও crash-এর মতোই দেখায়।' } },
    { q: { en: 'Why does a pod with limits=1 memory get killed, and what does requests change?', bn: 'memory limit ১ দেওয়া pod মারা যায় কেন, আর requests কী বদলায়?' },
      a: { en: 'Limits are the ceiling enforced at runtime: the container\u2019s memory use is counted against 1 GiB, and above it the kernel kills the process, which the node reports as OOMKilled with exit code 137. Requests are only what the scheduler believes you will use — they decide placement and, with a namespace quota, how much of the node you may reserve. Raising requests does not protect you from being killed; raising the limit does.', bn: 'limit হলো চালুকালীন ছাদ: container-এর memory ব্যবহার ১ GiB-এর বিপরীতে মাপা হয়, ছাড়ালে kernel প্রসেস মারে, node সেটি OOMKilled, exit code 137 বলে জানায়। requests শুধু scheduler-কে আপনি কত নেবেন বলে দেয় — সেটি বসানের জায়গা ঠিক করে, namespace quota থাকলে কত आरাক্ষিত থাকবেও। requests বাড়ালে মারা যাওয়া থামে না; থামে limit বাড়ালে।' } },
    { q: { en: 'How does a rolling update avoid downtime, and which two fields decide it?', bn: 'rolling update কীভাবে থামার আগে সেরে ফেলে, আর কোন দুটি field ঠিক করে?' },
      a: { en: 'The Deployment controller adds a new ReplicaSet and grows it while shrinking the old one, so the service always has ready replicas. maxSurge says how many pods above the desired count may exist during the change, maxUnavailable says how many may be missing. With replicas: 3, maxSurge: 1 and maxUnavailable: 0 you always have three serving; with maxUnavailable: 1 you can drop to two, which is a real outage if only one pod answers per node.', bn: 'Deployment controller নতুন ReplicaSet যোগ করে বড় করতে থাকে, পুরোনোট ছোট করে, ফলে service-এর হাতে সবসময়ই ready replica থাকে। maxSurge বলে বদলানোর সময়ে কাঙ্ক্ষিত সংখ্যার থেকে কত বেশি pod থাকতে পারে, maxUnavailable বলে কত কম থাকতে পারে। replicas: 3, maxSurge: 1, maxUnavailable: 0 দিলে তিনটিই সবসময় চলে; maxUnavailable: 1 দিলে দুই-এ নামা যায়, আর একটি node-তে একটি pod থাকলে সেটিই আসল বিচ্ছেদ।' } },
    { q: { en: 'What is a sidecar container used for in Kubernetes?', bn: 'Kubernetes-এ sidecar container কীসের জন্য?' },
      a: { en: 'A second container in the same pod that shares the network namespace and any mounted volumes with the main one, so it can read its files, talk to it on localhost, and start and stop with it. Real uses: a log or metrics shipper, a service-proxy with mTLS, a config reloader watching the same volume, an initContainer-like file fetcher in an ephemeral form. It is not a way to run two unrelated services.', bn: 'একই pod-এর দ্বিতীয় container, যা মূলটির সাথে network namespace আর mount করা volume শেয়ার করে — তাই তার ফাইল পড়তে পারে, localhost-এ কথা বলতে পারে, সাথেই ওঠে-নামে। আসল কাজ: log বা metrics পাঠানো, mTLS সহ proxy, একই volume দেখা config reloader, অস্থায়ীভাবে ফাইল আনা initContainer-সদৃশ জিনিস। অসম্পর্কিত দুই service একসাথে চালানোর কৌশল নয় এটি।' } },
  ],
  realWorld: [
    { en: 'A shop runs 3 pods of a checkout API behind a Service, with requests 250m CPU and 256Mi memory, so a node failure costs one replica, not the checkout.', bn: 'এক দোকানের checkout API Service-এর পেছনে ৩টি pod, requests CPU 250m আর memory 256Mi — তাই একটি node গেলে এক replica হারায়, checkout নয়।' },
    { en: 'A database in StatefulSet with one PVC per replica: the pods may be recreated, the disks and names are kept.', bn: 'StatefulSet-এ database, প্রতি replica-র জন্য আলাদা PVC: pod নতুন করে বানানো যায়, ডিস্ক আর নাম থেকে যায়।' },
    { en: 'A nightly job runs in a CronJob with concurrencyPolicy: Forbid, because two copies of the same report write to the same table.', bn: 'রাতের কাজ CronJob-এ, concurrencyPolicy: Forbid সহ — একই report-এর দুটি কপি একই টেবিলে লিখতে বসে।' },
    { en: 'Developers get a namespace with a ResourceQuota of 4 CPU and 8Gi memory, so one runaway deployment cannot fill the shared cluster.', bn: 'developer-দের namespace-এ ResourceQuota ৪ CPU আর 8Gi memory — একটি পাগল deployment যাতে শেয়ার-করা cluster ভরে দিতে না পারে।' },
  ],
  references: [
    { group: { en: 'Read the API, not a blog', bn: 'blog নয়, API পড়ুন' }, items: [
      { term: 'kubernetes.io/docs/reference', def: { en: 'Every field of every object, with the version it appeared in. When a tutorial says “set this”, check it exists for your cluster version.', bn: 'প্রতিটি বস্তুর প্রতিটি field, কোন সংস্করণে এসেছিল তা লিখে। কোনো টিউটোরিয়াল “এটি দিন” বললে নিজের cluster-এর সংস্করণে আছে কি না দেখে নিন।' } },
      { term: 'kubectl explain', def: { en: 'The same reference in your terminal: kubectl explain deployment.spec.strategy — the real fields of your real cluster.', bn: 'আপনার terminal-এ সেই রেফারেন্স: kubectl explain deployment.spec.strategy — আসল cluster-এর আসল field গুলো।' } },
    ] },
    { group: { en: 'When something is stuck', bn: 'কিছু আটকালে' }, items: [
      { term: 'kubectl get events -A --sort-by=.lastTimestamp', def: { en: 'The cluster\u2019s own diary of what it tried and failed at, newest last.', bn: 'cluster-র নিজের ডায়েরি — কী চেষ্টা করেছিল, কোথায় ব্যর্থ, শেষেরটি সবচেয়ে নতুন।' } },
      { term: 'kubectl auth can-i', def: { en: 'Asks the same authoriser the API server uses: kubectl auth can-i delete pods -n staging.', bn: 'API server যে অনুমতি-পরীক্ষাই চালায় সেটিই জিজ্ঞেস করে: kubectl auth can-i delete pods -n staging।' } },
    ] },
  ],
};

export const lessons = [
  {
    slug: 'what-a-cluster-actually-is',
    title: { en: 'What a Cluster Actually Is', bn: 'একটা cluster আসলে কী' },
    minutes: 9,
    summary: {
      en: 'A control plane that remembers what you asked for, and worker nodes that run containers. Learn the five parts, the one command that talks to them, and how to read the state of the whole thing in one line.',
      bn: 'একটা control plane যা মনে রাখে আপনি কী চেয়েছেন, আর worker node যা container চালায়। অংশ পাঁচটি, সেগুলোর সাথে কথা বলার একটাই কমান্ড, আর পুরো অবস্থা এক লাইনে পড়া — এই পাঠে।',
    },
    lead: {
      en: 'You have one Docker container on a laptop, and now you need forty of them, on five machines, running tomorrow as well as today. That is the whole reason Kubernetes exists: something has to remember “forty” and keep it true. This page names the parts that do the remembering and the running.',
      bn: 'ল্যাপটপে আপনার একটি Docker container আছে, আর এখন চাই চল্লিশটি, পাঁচটি মেশিনে, আগামীকালও যেন চলে। পুরো Kubernetes-এর জন্মের কারণটুকুই এটি: কারও তো মনে রাখতে হবে “চল্লিশ” আর সত্যি রাখতে হবে। কোন অংশ মনে রাখে, কোন অংশ চালায় — এই পাতায় সেগুলোর নাম।',
    },
    why: [
      { e: 'You never start a container yourself; you write the wanted state, and a controller makes reality match it.', b: 'আপনি নিজে container চালু করেন না; যা চান তা লিখে দেন, আর একজন controller বাস্তবকে মিলিয়ে দেয়।' },
      { e: 'etcd is just a small key-value store holding that wish list, which is why backing it up is the entire disaster plan.', b: 'etcd আসলে একটা ছোট key-value সংরক্ষণ, যেখানে সেই ইচ্ছের তালিকা থাকে — তাই এর backup নিলেই বিপদের প্রায় সব প্রস্তুতি হয়ে যায়।' },
      { e: 'kubectl only edits objects in the API server. Anything it can do, you can do from any program that can send HTTPS.', b: 'kubectl শুধু API server-এর বস্তু বদলায়। এটি যা পারে, HTTPS পাঠাতে পারে এমন যেকোনো প্রোগ্রাম থেকেও তা করা যায়।' },
    ],
    blocks: [
      { type: 'code', lang: 'bash', filename: 'first-look.sh', code: [
        '# your kubeconfig points at one cluster; check what you are about to touch',
        'kubectl config current-context',
        '',
        '# the control-plane members, running as pods in kube-system',
        'kubectl get pods -n kube-system -o wide',
        '',
        '# every node, with the CPU and memory it reports',
        'kubectl get nodes -o custom-columns=NAME:.metadata.name,CPU:.status.capacity.cpu,MEM:.status.capacity.memory',
        '# NAME      CPU   MEM',
        '# node-1    4     7730280Ki',
        '# node-2    4     7730280Ki',
        '',
        '# one deployment, four objects deep',
        'kubectl create deployment web --image=nginx:1.27 --replicas=2 --dry-run=client -o yaml',
      ].join('\n'), caption: {
        en: 'kubectl create with --dry-run=client -o yaml prints the object it would have sent. Read the YAML it prints: that is the API, not a file format.',
        bn: 'kubectl create-এর সাথে --dry-run=client -o yaml দিলে যে বস্তুটি পাঠানো হত তা ছেপে দেখায়। সেটি পড়ুন — এটিই API, কোনো ফাইলের গড়ন নয়।',
      } },
      { type: 'table', head: [
        { en: 'part', bn: 'অংশ' }, { en: 'what it holds', bn: 'কী ধরে রাখে' }, { en: 'if it dies', bn: 'মরে গেলে' },
      ], rows: [
        [ { en: 'API server (kube-apiserver)', bn: 'API server (kube-apiserver)' }, { en: 'the front door: validates, authorises, writes', bn: 'সামনের দরজা: যাচাই করে, অনুমতি দেয়, লেখে' }, { en: 'nothing can be read or changed; running pods keep running', bn: 'কিছুই পড়া বা বদলানো যায় না; চলমান pod তবু চলে' } ],
        [ { en: 'etcd', bn: 'etcd' }, { en: 'every object, as keys and values', bn: 'প্রতিটি বস্তু, key আর মান হিসেবে' }, { en: 'the cluster forgets your wish list; restore from backup', bn: 'cluster আপনার ইচ্ছের তালিকা ভুলে যায়; backup থেকে ফেরান' } ],
        [ { en: 'scheduler (kube-scheduler)', bn: 'scheduler (kube-scheduler)' }, { en: 'decides which node each new pod may use', bn: 'ঠিক করে নতুন pod কোন node-এ যাবে' }, { en: 'new pods stay Pending; existing ones are fine', bn: 'নতুন pod Pending-এ থাকে; আগেরগুলো ঠিক' } ],
        [ { en: 'controller manager', bn: 'controller manager' }, { en: 'the loops that compare wanted to actual', bn: 'যে ঘেরগুলোর লুপ কাঙ্ক্ষিত আর বাস্তব মেলায়' }, { en: 'no rollouts, no self-healing; pods are not replaced', bn: 'কোনো rollout নয়, নিজে সারা নয়; pod বদলানো হয় না' } ],
        [ { en: 'kubelet + kube-proxy, per node', bn: 'kubelet + kube-proxy, প্রতি node-এ' }, { en: 'starts containers; programs the network rules', bn: 'container চালায়; network-এর নিয়ম বসায়' }, { en: 'that node\u2019s pods are not restarted or reachable by IP', bn: 'ঐ node-এর pod নতুন করে ওঠে না, IP-তে পাওয়া যায় না' } ],
      ], caption: {
        en: 'Note what is not here: no message queue, no database of your rows, no build system. Kubernetes stores objects and runs containers, nothing else.',
        bn: 'এখানে যা নেই সেটি দেখুন: কোনো message queue নেই, আপনার data-র কোনো database নেই, build system নেই। Kubernetes বস্তু রাখে আর container চালায়, আর কিছু নয়।',
      } },
      { type: 'keyterms', items: [
        { term: 'control plane', def: { en: 'The parts that store and decide: API server, etcd, scheduler and controllers, usually on 3 machines so one can die.', bn: 'যে অংশগুলো মনে রাখে আর ঠিক করে: API server, etcd, scheduler আর controllers, সাধারণত ৩টি মেশিনে, যাতে একটি গেলেও চলে।' } },
        { term: 'node', def: { en: 'One machine, virtual or real, that runs the kubelet and therefore runs your containers.', bn: 'একটি মেশিন, আসল বা ছবি-দেখানো, যেখানে kubelet আছে — মানে আপনার container এখানেই চলে।' } },
        { term: 'manifest', def: { en: 'A YAML or JSON file describing one object: apiVersion, kind, metadata and a spec.', bn: 'একটি বস্তুর বর্ণনা লেখা YAML বা JSON ফাইল: apiVersion, kind, metadata আর একটি spec।' } },
        { term: 'reconcile loop', def: { en: 'The controller\u2019s one idea: read the wanted state, read the actual state, act on the difference, repeat.', bn: 'controller-এর একটাই ধারণা: যা চাওয়া হয়েছে পড়ুন, যা আছে পড়ুন, ফারাক মেটান, আবার করুন।' } },
      ] },
    ],
    steps: [
      { t: 'Point kubectl at a cluster', tb: 'kubectl-কে cluster-এর দিকে মুখ ঘোরাতে বলুন', e: 'A kubeconfig file lists contexts; kubectl config use-context names the one you mean. Do this before any other command.', b: 'একটি kubeconfig ফাইলে context গুলোর তালিকা; kubectl config use-context দিয়ে কোনটি বুঝিয়েছেন বলুন। বাকি কমান্ডের আগেই এটি করুন।' },
      { t: 'Ask for the current state', tb: 'এখনকার অবস্থা জিজ্ঞেস করুন', e: 'kubectl get pods -A and kubectl describe on the odd one. The Events section at the bottom of describe is the cluster talking about its own attempts.', b: 'kubectl get pods -A, আর যা অদ্ভুত তার উপর kubectl describe। describe-এর একেবারে নিচের Events অংশটি cluster-এর নিজের চেষ্টার কথা।' },
      { t: 'Send a wanted state, dry-run first', tb: 'কাঙ্ক্ষিত অবস্থা পাঠান, আগে dry-run', e: 'Write the manifest, then kubectl apply --dry-run=server -f file.yaml. The server validates it against the real API without storing anything.', b: 'manifest লিখে দিন, তারপর kubectl apply --dry-run=server -f file.yaml। server কিছু না-রেখে আসল API-র সাথে মেলালেই যাচাই করে দেবে।' },
      { t: 'Apply, then watch it settle', tb: 'apply করুন, তারপর স্থির হওয়া দেখুন', e: 'kubectl rollout status deployment/web prints progress and returns non-zero if it never settles. That exit code belongs in a CI script.', b: 'kubectl rollout status deployment/web অগ্রগতি দেখায়, কখনো স্থির না-হলে non-zero ফেরত দেয়। ঐ exit code-টি CI script-এ বসানো চাই।' },
    ],
    visual: 'kubernetes',
    note: 'Treat every kubectl verb as a small HTTP request with a name on it. Once that is obvious, the CLI stops being a spell list and becomes a way to read the API.',
    noteb: 'প্রতিটি kubectl ক্রিয়াকে নাম-সহ এক একটি ছোট HTTP request ভাবুন। এটি বোঝা গেলে CLI আর মন্ত্রের তালিকা থাকে না — তখন সেটি API পড়ার একটা উপায় মাত্র।',
    pitfall: { t: 'Thinking kubectl apply creates the file', tb: 'ভাবা kubectl apply নাকি ফাইলটি তৈরি করে রাখে',
      e: 'apply sends the object and forgets the file. If you delete the file and change nothing else, the object stays — and a later apply from a different file with the same name overwrites it.',
      b: 'apply বস্তুটি পাঠায়, ফাইলটি ভুলে যায়। ফাইল মুছে দিয়ে আর কিছু না-বদলালে বস্তু থেকেই যায় — আর পরে অন্য ফাইল থেকে একই নামে apply করলে সেটি চাপা পড়ে।' },
    exercises: [
      { kind: 'mcq', q: 'You need to know which machine a pod is running on. Which command?', qb: 'একটি pod কোন মেশিনে চলছে জানতে হবে। কোন কমান্ড?',
        options: [ { en: 'kubectl get pod web-123 -o wide', bn: 'kubectl get pod web-123 -o wide' },
          { en: 'kubectl describe node', bn: 'kubectl describe node' },
          { en: 'docker ps on the master', bn: 'master-এর উপর docker ps' },
          { en: 'kubectl get events --all-namespaces', bn: 'kubectl get events --all-namespaces' } ],
        answer: 0, hint: 'One flag adds the node column to the same line you already read.', hintb: 'একটি flag বসলেই পড়া লাইনটির সাথে node-এর column যোগ হয়।',
        why: '-o wide prints NODE (and the pod IP) for the exact pod. describe node answers the opposite question: what is on that machine.',
        whyb: '-o wide ঠিক সেই pod-এর NODE (আর pod IP) ছাপে। describe node উল্টো প্রশ্নের জবাব দেয়: ঐ মেশিনে কী কী আছে।' },
      { kind: 'predict', q: 'etcd is lost with no backup, the API server and 20 running pods are healthy. What do users still see for a few minutes?', qb: 'backup ছাড়া etcd হারিয়ে গেল, API server আর চলমান ২০টি pod ঠিক। কয়েক মিনিট ব্যবহারকারীরা কী দেখতে থাকেন?',
        answer: 'traffic still works', accept: ['traffic continues', 'it keeps working', 'the site keeps serving', 'users see nothing', 'same as before', 'yes', 'traffic still works', 'যাতায়াত চলতেই থাকে', 'সাইট চলতে থাকে'],
        hint: 'What actually answers a request: the controller, or the running container?', hintb: 'request-এর জবাব আসলে দেয় কে — controller, নাকি চলমান container?',
        why: 'The data plane is already programmed: pods run, kube-proxy rules route, DNS resolves. Only changes are impossible — no scaling, no rollout, no self-healing — until etcd is restored.',
        whyb: 'data plane আগেই বসানো আছে: pod চলে, kube-proxy-এর নিয়ম রুটিং করে, DNS নাম মেলায়। শুধু নতুন সিদ্ধান্ত নেওয়া যায় না — scale নয়, rollout নয়, নিজে সারা নয় — etcd ফিরে না-আসা পর্যন্ত।' },
      { kind: 'mcq', q: 'Where is the desired number of replicas stored?', qb: 'replica-র কাঙ্ক্ষিত সংখ্যাটি কোথায় লেখা থাকে?',
        options: [ { en: 'In each pod', bn: 'প্রতিটি pod-এর ভেতর' }, { en: 'In etcd, as a field of the Deployment object', bn: 'etcd-তে, Deployment বস্তুটির একটি field হিসেবে' }, { en: 'In the scheduler\u2019s memory', bn: 'scheduler-এর memory-তে' }, { en: 'In the container image', bn: 'container image-এর ভেতর' } ],
        answer: 1, hint: 'Everything durable in the cluster lives in one place.', hintb: 'cluster-এর টেকসয় জিনিস এক জায়গাতেই থাকে।',
        why: 'spec.replicas is part of the Deployment object, which is stored in etcd. The ReplicaSet and the pods are the controller\u2019s answer to that number, not the record of it.',
        whyb: 'spec.replicas Deployment বস্তুটির অংশ, আর সেটি থাকে etcd-তে। ReplicaSet আর pod গুলো সেই সংখ্যার জবাব, নথি নয়।' },
    ],
    quiz: [
      { q: 'Which component writes to etcd?', qb: 'etcd-তে কে লেখে?',
        options: [ { en: 'Any controller that needs to', bn: 'যে controller-এর দরকার, সে-ই' }, { en: 'Only the API server', bn: 'শুধু API server' }, { en: 'kubelet, once per pod', bn: 'kubelet, pod প্রতি একবার' }, { en: 'etcd itself, from the log', bn: 'etcd নিজে, নিজের log থেকে' } ],
        answer: 1, hint: 'There is one front door on purpose.', hintb: 'একটাতেই ইচ্ছে করেই একটি দরজা।',
        why: 'Controllers and kubectl all talk HTTPS to the API server, and it is the only client of etcd. That is how auth, validation and webhooks get applied to every change.',
        whyb: 'controllers আর kubectl সবাই API server-এর সঙ্গে HTTPS-এ কথা বলে, আর etcd-র একমাত্র গ্রাহকও সে। এভাবেই সব বদলে অনুমতি, যাচাই আর webhook লাগে।' },
      { q: 'What is the kubelet\u2019s job?', qb: 'kubelet-এর কাজ কী?',
        options: [ { en: 'Decide which node a pod belongs to', bn: 'ঠিক করা pod কোন node-এ যাবে' },
          { en: 'Make the containers described in a bound pod actually run, and report back', bn: 'বাঁধা pod-এ লেখা container সত্যিই চালানো, আর ফিরে জানানো' },
          { en: 'Balance traffic between pods', bn: 'pod গুলোর মধ্যে traffic ভাগ করা' },
          { en: 'Store objects durably', bn: 'বস্তু টেকসইভাবে রাখা' } ],
        answer: 1, hint: 'It is the node\u2019s agent, not the cluster\u2019s brain.', hintb: 'এটি node-এর এজেন্ট, cluster-এর মস্তিষ্ক নয়।',
        why: 'The scheduler chooses the node; the kubelet starts the containers through a runtime, mounts volumes, runs the probes, and reports status. kube-proxy handles the traffic rules.',
        whyb: 'node বাছাই করে scheduler; kubelet runtime দিয়ে container ওঠায়, volume mount করে, probe চালায় আর অবস্থা জানায়। যাতায়াতের নিয়ম চালায় kube-proxy।' },
      { q: 'Why is a 3-node control plane better than one?', qb: '৩টি node-এর control plane একটির চেয়ে ভালো কেন?',
        options: [ { en: 'It is faster', bn: 'দ্রুত চলে' }, { en: 'etcd needs a majority of voters to write, so 2 of 3 can survive', bn: 'leখার জন্য etcd-কে ভোটারদের সংখ্যাগরিষ্ঠ লাগে, তাই ৩-এর ২টি থাকলেই চলে' }, { en: 'Each node holds a full copy of the pods', bn: 'প্রতিটি node-তে pod-এর পুরো কপি থাকে' }, { en: 'It removes the need for backups', bn: 'তাহলে backup-এর দরকারই থাকে না' } ],
        answer: 1, hint: 'Quorum maths: 1 of 1, 2 of 3, 3 of 5.', hintb: 'গণিত: ১-এর ১, ৩-এর ২, ৫-এর ৩।',
        why: 'Raft consensus writes only when most members agree. With one member, any restart blocks writes; with three, one can die mid-upgrade and the cluster still accepts changes.',
        whyb: 'Raft consensus সংখ্যাগরিষ্ঠ রাজি হলেই লেখে। একজন থাকলেই restart-এ লেখা আটকে যায়; তিনজন থাকলে upgrade-এর মাঝে একজন গেলেও cluster বদল নিতে থাকে।' },
      { q: 'A colleague says “the manifest is the source of truth”. What is wrong with that?', qb: 'এক সহকর্মী বললেন “manifest-ই আসল সত্য”। এতে ভুল কী?',
        options: [ { en: 'Nothing, that is the design', bn: 'কিছুই না, নকশাই তাই' },
          { en: 'The cluster state is the truth; the file is a wish that may not have been applied yet', bn: 'সত্যি হলো cluster-এর অবস্থা; ফাইল একটা ইচ্ছে, যেটি হয়তো এখনো প্রয়োগই হয়নি' },
          { en: 'Manifests are YAML, so they cannot be versioned', bn: 'manifest YAML, তাই version করা যায় না' },
          { en: 'Truth lives only in the container image', bn: 'সত্যি থাকে শুধু image-এর ভেতর' } ],
        answer: 1, hint: 'Someone can kubectl edit, or apply from another repo.', hintb: 'কেউ kubectl edit করতে পারে, অন্য repo থেকে apply করতে পারে।',
        why: 'Two files or a hand edit can drift from what is stored in etcd, which is why diff tools compare the live object to the repository, not the other way around.',
        whyb: 'দুটি ফাইল বা একটা হাতে-করা বদল etcd-তে যা লেখা আছে তার থেকে সরে যেতে পারে; তাই diff হাতিয়ার repo-র সাথে জীবন্ত বস্তু মেলায়, উল্টোটা নয়।' },
    ],
  },

  {
    slug: 'the-pod-and-its-containers',
    title: { en: 'The Pod: One Group of Containers', bn: 'pod: একসাথে রাখা কয়েকটি container' },
    minutes: 10,
    summary: {
      en: 'A pod is a group of containers that share an IP address, a set of volume names, and their fate. Read that sentence twice: most beginner confusion about Kubernetes is a wrong guess about what a pod is.',
      bn: 'pod মানে এমন container-এর দল যাদের IP এক, volume-এর নাম এক, আর ওঠা-নমাও এক। বাক্যটি দুবার পড়ুন: বিগিনারের গোলমালের বেশিরভাগই এই ধারণা ভুল হওয়া যে pod আসলে কী।',
    },
    lead: {
      en: 'You deploy an app that needs two things: your web server, and a small program that rewrites its config file whenever it changes. In Docker you would run two containers and link them. In Kubernetes the answer is one pod holding both, because they need the same localhost and the same folder. This page is what a pod shares and what it does not.',
      bn: 'আপনার app-এর দুটি জিনিস দরকার: web server, আর একটা ছোট প্রোগ্রাম যে তার config ফাইল বদলালেই নতুন করে লেখে। Docker-এ দুটি container নিয়ে জুড়ে দিতেন। Kubernetes-এর জবাব একটি pod-এ দুটোই — কারণ দুটির দরকার একই localhost আর একই ফোল্ডার। pod কী কী শেয়ার করে আর কী করে না, এই পাতায় সেটিই।',
    },
    why: [
      { e: 'Containers in one pod share a network namespace: one IP, and localhost really is the other container.', b: 'এক pod-এর container গুলোর network namespace এক: IP এক, আর localhost সত্যিই অন্য container-টি।' },
      { e: 'They are scheduled as one unit onto one node, and if one dies, the kubelet restarts it while the pod object survives.', b: 'একই সাথে এক node-এ বসানো হয়, আর একটি মরলে pod বস্তুটি বেঁচে থাকতে kubelet সেটি নতুন করে তোলে।' },
      { e: 'A pod has no self-healing of its own: it is a pet, not a herd. Deployments and StatefulSets are what keep the count right.', b: 'pod-এর নিজের কোনো সারানোর ব্যবস্থা নেই: এটি পুষা প্রাণী, পাল নয়। সংখ্যা ঠিক রাখে Deployment আর StatefulSet।' },
    ],
    blocks: [
      { type: 'code', lang: 'yaml', filename: 'pod.yaml', code: [
        'apiVersion: v1',
        'kind: Pod',
        'metadata:',
        '  name: web-7c9d8',
        '  labels: { app: web, tier: front }',
        'spec:',
        '  restartPolicy: Always          # the only sane choice for a server',
        '  containers:',
        '    - name: nginx',
        '      image: nginx:1.27',
        '      ports: [ { containerPort: 8080 } ]',
        '      resources:',
        '        requests: { cpu: 100m, memory: 64Mi }',
        '        limits:   { cpu: 500m, memory: 128Mi }',
        '    - name: config-watcher',
        '      image: busybox:1.36',
        '      command: ["sh", "-c", "while true; do cp /src/config.json /etc/app/; sleep 5; done"]',
        '      volumeMounts:',
        '        - { name: shared, mountPath: /etc/app }',
        '        - { name: src,    mountPath: /src, readOnly: true }',
        '  volumes:',
        '    - name: shared',
        '      emptyDir: {}               # a scratch folder, dies with the pod',
        '    - name: src',
        '      configMap: { name: app-config }',
      ].join('\n'), caption: {
        en: 'Both containers see /etc/app because the emptyDir volume is mounted in both. The nginx process can reach the watcher on localhost — same network namespace, same IP.',
        bn: 'emptyDir volume দুটিতেই mount করা বলে দুজনেই /etc/app দেখে। nginx প্রসেস localhost-এ watcher-কে পায় — network namespace এক, IP-ও এক।',
      } },
      { type: 'keyterms', items: [
        { term: 'restartPolicy', def: { en: 'Always, OnFailure or Never: what the node does when a container exits. A Job wants OnFailure; a long-running server wants Always.', bn: 'Always, OnFailure বা Never: container বেরিয়ে গেলে node কী করবে। Job-এর দরকার OnFailure, চলমান server-এর দরকার Always।' } },
        { term: 'emptyDir', def: { en: 'A folder created for the pod and deleted with it; two containers use it as shared scratch space.', bn: 'pod-এর জন্য বানানো ফোল্ডার, pod গেলে মুছে যায়; দুটি container একসাথে কাজের জায়গা হিসেবে ব্যবহার করে।' } },
        { term: 'initContainer', def: { en: 'A container that must finish successfully, in order, before the app containers start — the place for “wait for the database” loops.', bn: 'যে container আগে, ক্রমে, সফলভাবে শেষ হতেই হবে app container ওঠার আগে — “database-এর জন্য অপেক্ষা করো” লুপ এখানেই বসে।' } },
        { term: 'terminationGracePeriodSeconds', def: { en: 'How long a pod gets between the SIGTERM and the kill, default 30; an app that drains connections needs more.', bn: 'SIGTERM আর বলপূর্বক মরার মধ্যে pod কত সময় পায়, ডিফল্ট ৩০; যে app সংযোগ মিটিয়ে বেরোয় তার বেশি দরকার।' } },
      ] },
      { type: 'callout', kind: 'warn', title: { en: 'A pod you create by hand has no owner', bn: 'হাতে বানানো pod-এর কোনো মালিক নেই' },
        text: { en: 'kubectl run --restart=Never or a bare Pod object means nothing will recreate it: delete it and it is gone, and it cannot be rolled forward or back.', bn: 'kubectl run --restart=Never বা খালি Pod বস্তু মানে কেউ সেটি নতুন করে বানাবে না: মুছে দিলে gone, আর সামনে-পেছনে ঘোরানোও যায় না।' } },
    ],
    steps: [
      { t: 'Say what one copy does', tb: 'একটি কপি কী করে তা বলুন', e: 'One process, one job: an HTTP server, a worker reading a queue. If you find yourself wanting two daemons in one container, you usually want two containers in one pod.', b: 'এক প্রসেস, এক কাজ: এক HTTP server, এক queue পড়া worker। একটি container-এ দুটি daemon দরকার মনে হলে, প্রায়ই আসল চাওয়া হলো এক pod-এ দুটি container।' },
      { t: 'Give it room and a name it can be found by', tb: 'জায়গা আর খোঁজার নাম দিন', e: 'requests and limits on every container, plus labels — app: web, tier: front — because Services and policies match on labels, not names.', b: 'প্রতি container-এ requests আর limits, সাথে labels — app: web, tier: front — কারণ Service আর policy নামে মেলায় না, label-এ মেলায়।' },
      { t: 'Share files through a volume, not the image', tb: 'volume দিয়ে ফাইল শেয়ার করুন, image দিয়ে নয়', e: 'Two containers reading the same emptyDir is explicit and debuggable; writing to a shared path in a built image is neither.', b: 'দুটি container একই emptyDir পড়া স্পষ্ট আর ডিবাগ-যোগ্য; বানানো image-এর ভেতর শেয়ার পথের উপর লেখা দুটোই নয়।' },
      { t: 'Read it as a process, not a machine', tb: 'মেশিন নয়, প্রসেস ভাবুন', e: 'Ask: does this need a stable name and disk (then a StatefulSet), or is any copy interchangeable (then a Deployment)?', b: 'জিজ্ঞেস করুন: এর কি স্থির নাম আর ডিস্ক দরকার (তাহলে StatefulSet), নাকি যেকোনো কপি বদলানো যায় (তাহলে Deployment)?' },
    ],
    visual: null,
    note: 'Pods are cattle with a short memory: their IP changes when they are recreated, and their files are gone unless they live on a volume. Everything later in this hub exists because of those two facts.',
    noteb: 'pod ভুলে যাওয়া গরুর মতো: নতুন করে বানালে IP বদলায়, volume-তে না-থাকলে ফাইলও উবে যায়। পরে এই হাবে যা কিছু আছে, তার কারণ এই দুটি কথাই।',
    pitfall: { t: 'Treating the pod IP as stable', tb: 'pod-এর IP স্থির ভাবা',
      e: 'A client that caches 10.4.2.17 keeps calling a dead address the moment the pod is recreated. Services exist to hide this; the fix is never “pin the IP”.',
      b: 'যে ক্লায়েন্ট 10.4.2.17 মনে রেখেছে, pod নতুন করে বানানো মাত্রই সে মrt address-এ কল করতে থাকে। এই ঢাকা দিতেই Service; সমাধান কখনোই “IP আঁটে দেওয়া” নয়।' },
    exercises: [
      { kind: 'mcq', q: 'Two containers in one pod must exchange a 2 MB file every few seconds. Cheapest correct way?', qb: 'এক pod-এর দুটি container কয়েক সেকেন্ড পর পর ২ MB ফাইল বদল করবে। সস্তা সঠিক উপায়?',
        options: [ { en: 'A shared emptyDir volume mounted in both', bn: 'দুটিতেই mount করা shared emptyDir volume' },
          { en: 'Write to localhost over HTTP', bn: 'localhost-এর উপর HTTP-তে লিখে দেওয়া' },
          { en: 'Both read the same image layer', bn: 'দুজনেই একই image layer পড়ে' },
          { en: 'A PersistentVolume with ReadWriteMany', bn: 'ReadWriteMany একটা PersistentVolume দিয়ে' } ],
        answer: 0, hint: 'They already share a filesystem view if you let them.', hintb: 'দিতে চাইলে তারা আগে থেকেই এক file system দেখে।',
        why: 'emptyDir lives on the node for the pod\u2019s lifetime, so a 2 MB write is a page cache touch. HTTP adds serialisation, a port and a crash mode for no benefit; RWX storage adds a network filesystem.',
        whyb: 'emptyDir থাকে node-এর উপর পুরো pod-এর জীবনকাল, তাই ২ MB লেখা মানে একটা page cache স্পর্শ। HTTP যোগ করে serialisation, একটা port আর একটা নতুন crash, বিনা লাভে; RWX storage যোগ করে network filesystem।' },
      { kind: 'predict', q: 'The nginx container exits with code 0, restartPolicy is Always. What happens to the other container?', qb: 'nginx container 0 code-এ বেরিয়ে এল, restartPolicy Always। অন্য container-টির কী হয়?',
        answer: 'nothing, it keeps running', accept: ['nothing', 'it keeps running', 'no restart', 'stays running', 'only nginx restarts', 'কিছু হয় না', 'চলতেই থাকে', 'শুধু nginx ওঠে'],
        hint: 'Restarts are per container, not per pod.', hintb: 'restart হয় container-প্রতি, pod-প্রতি নয়।',
        why: 'The kubelet restarts the exited container with a back-off, and the other container is untouched. The pod object and its IP stay the same, which is why an exiting 0 can loop quietly.',
        whyb: 'kubelet ব্যাক-অফ দিয়ে বেরিয়ে-পড়া container-টি আবার তোলে, অন্যটি অক্ষত থাকে। pod বস্তু আর তার IP একই থাকে — তাই 0 দিয়ে বেরিয়ে আসা চুপচাপ loop হতে পারে।' },
      { kind: 'mcq', q: 'Your app needs the database reachable before it starts. Where does that wait belong?', qb: 'app-এর শুরুতে database পৌঁছানো যায় কি না দেখতে হয়। সেই অপেক্ষা কোথায় বসবে?',
        options: [ { en: 'In the app entrypoint script', bn: 'app-এর entrypoint script-এ' },
          { en: 'An initContainer that connects and exits 0', bn: 'একটি initContainer যে সংযোগ দিয়ে 0 ফেরত দেয়' },
          { en: 'A readinessProbe on the main container', bn: 'মূল container-এর readinessProbe' },
          { en: 'A second pod that runs first', bn: 'আগে চলা দ্বিতীয় একটি pod' } ],
        answer: 1, hint: 'Something that must finish before the app starts.', hintb: 'যেটি app ওঠার আগে শেষ হতেই হবে।',
        why: 'initContainers run in order and the pod stays in Init until each returns 0, so the wait is visible in kubectl get pods. A probe only gates traffic; the app would still start and crash.',
        whyb: 'initContainers ক্রমে চলে আর প্রতিটি 0 ফেরত না-দেওয়া পর্যন্ত pod Init-এই থাকে, তাই অপেক্ষা kubectl get pods-এ দেখা যায়। probe শুধু যাতায়াত আটকে, app তবু উঠে crash করত।' },
    ],
    quiz: [
      { q: 'What do all containers in a pod share?', qb: 'এক pod-এর সব container কী কী শেয়ার করে?',
        options: [ { en: 'Memory and CPU limits', bn: 'memory আর CPU limit' },
          { en: 'Network namespace and volume names', bn: 'network namespace আর volume-এর নাম' },
          { en: 'Filesystem and image', bn: 'file system আর image' },
          { en: 'Everything except ports', bn: 'port বাদে সব' } ],
        answer: 1, hint: 'Two namespaces, one of them is the one you reach over localhost.', hintb: 'দুটি namespace, যার একটি localhost-এ পৌঁছানো যায়।',
        why: 'Network, IPC and UTS namespaces, and each declared volume can be mounted into any container. Each keeps its own filesystem and its own resource numbers.',
        whyb: 'network, IPC আর UTS namespace, আর ঘোষণা করা প্রতিটি volume যেকোনো container-এ mount করা যায়। নিজ নিজ file system আর নিজ নিজ resource সংখ্যা আলাদা।' },
      { q: 'Why must containerPort not be treated as a declaration?', qb: 'containerPort-কে ঘোষণা ভাবা যাবে না — কেন?',
        options: [ { en: 'It is ignored by the runtime and only documents intent; the app still binds whatever it binds', bn: 'runtime এটা উপেক্ষা করে, শুধু ইচ্ছা লেখে; app যে port-এ বসে সেটিই বসে' },
          { en: 'It opens the port on the node', bn: 'এটি node-এর port খুলে দেয়' },
          { en: 'It reserves the port so nothing else uses it', bn: 'port আঁটে রাখে, কেউ নেবে না' },
          { en: 'It is required for probes', bn: 'probe-এর জন্য বাধ্যতামূলক' } ],
        answer: 0, hint: 'Removing it changes nothing about listening.', hintb: 'বাদ দিলেও শোনার ব্যাপার কিছু বদলায় না।',
        why: 'The container listens because the process binds a port. The field is used to pass information to Services and to the image metadata; nginx on 80 still answers on 80 with no containerPort at all.',
        whyb: 'process একটি port বাঁধে বলেই container শোনে। field-টি তথ্য হিসেবে Service-তে আর image metadata-তে যায়; containerPort না-থাকলেও 80-এ nginx 80-তেই জবাব দেয়।' },
      { q: 'A pod is stuck in Pending with no events about images. First suspicion?', qb: 'একটি pod Pending-এ আটকে, image নিয়ে কোনো event নেই। প্রথম সন্দেহ?',
        options: [ { en: 'The container crashed at start', bn: 'container শুরুতেই crash করেছে' },
          { en: 'No node has the free requests it asks for', bn: 'যত requests চেয়েছে তত ফাঁকা নেই এমন node খালি নেই' },
          { en: 'The readiness probe fails', bn: 'readiness probe ফেল করছে' },
          { en: 'The namespace is missing', bn: 'namespace নেই' } ],
        answer: 1, hint: 'Pending means not yet bound to a node.', hintb: 'Pending মানে এখনো কোনো node-এর সঙ্গে বাঁধেনি।',
        why: 'Scheduling is the last thing before a pod runs. kubectl describe shows 0/5 nodes are available: 3 Insufficient memory — a request of 512Mi on 256Mi nodes. A probe failure cannot leave a pod Pending; it leaves it unready.',
        whyb: 'chalার ঠিক আগে শেষ ধাপ scheduling। kubectl describe দেখায় 0/5 nodes are available: 3 Insufficient memory — 256Mi node-এ 512Mi চাওয়া। probe ফেল করলে pod unready হয়, Pending নয়।' },
      { q: 'Why is a bare pod discouraged even for a quick test?', qb: 'দ্রুত পরীক্ষার জন্যও খালি pod কেন পছন্দ নয়?',
        options: [ { en: 'Bare pods cannot mount volumes', bn: 'খালি pod volume নিতে পারে না' },
          { en: 'Nothing owns it, so no rollout, no restart count in a Deployment, no labels managed for you', bn: 'কারও মালিকানায় নেই, তাই rollout নেই, Deployment-এর হিসাবে নেই, labelও কেউ সাজিয়ে দেয় না' },
          { en: 'They run with lower privileges', bn: 'কম অধিকারে চলে' },
          { en: 'They cannot have two containers', bn: 'দুটি container রাখা যায় না' } ],
        answer: 1, hint: 'Who recreates it when the node dies?', hintb: 'node গেলে কে নতুন করে বানাবে?',
        why: 'A Deployment of one replica costs you four more lines of YAML and gives you the label selector, the rollout history and self-healing. kubectl run without --dry-run already does this for you.',
        whyb: 'এক replica-র Deployment চারটি লাইন বেশি খরচে দেয় label selector, rollout ইতিহাস আর নিজেকে সারানোর ব্যবস্থা। kubectl run --dry-run ছাড়াই সেটি আগেই করে দেয়।' },
    ],
  },
];
