import type { TechHub } from '../../lib/types';
import { loopLedgerLesson } from './lessons/the-loop-ledger';
import { middlewareVowsLesson } from './lessons/the-middleware-vows';
import { firstServerLesson } from './lessons/the-first-server';
import { moduleGrainLesson } from './lessons/the-module-grain';
import { fileEconomyLesson } from './lessons/the-file-economy';
import { dependencyLedgerLesson } from './lessons/the-dependency-ledger';
import { eventedBackboneLesson } from './lessons/the-evented-backbone';
import { productionLedgerLesson } from './lessons/the-production-ledger';

export const nodeHub: TechHub = {
  slug: 'node' as never,
  name: 'Node.js & Express',
  icon: '🧵',
  tagline: {
    en: 'One register, one chain, one process — every stall, vow, boundary, byte, author, topic and signature priced.',
    bn: 'এক রওকদারি, এক চেইন, এক প্রক্রিয়া — প্রতি স্থবিরতা, শপথ, সীমান্ত, বাইট, লেখক, বিষয় আর সই মূল্যায়িত।',
  },
  intro: {
    en: 'Node.js is the server inversion: one thread that never waits receives every client, and every convenience (async I/O, frameworks, clusters) is arithmetic on that single bet. This hub walks the full curriculum A to Z in eight lessons, all priced by one fixed 8-beat docket (health, login-bcrypt, 2MB orders, 400ms report, 50MB download, tampered order, async crash, 50-client burst) whose lab walks four runtime disciplines — the Blocker (sync hostage-taker), the Careless (async with no contract), the Chain-Keeper (vows without speed) and the Streamer (pacing plus ceilings). THE LOOP LEDGER prices the register: phases, microtask lanes, libuv pool, blocking arithmetic. THE MIDDLEWARE VOWS prices the chain: next(err) custody, the 4-arg home, backpressure, queue ceilings. THE FIRST SERVER holds the bare register: http.createServer, URL parsing, dispatch tables, the listen vow. THE MODULE GRAIN signs every boundary: CJS wrapper vs ESM link, caches, cycles, type gates. THE FILE ECONOMY owns every byte: fs trio, sealed paths, Buffer, transactional uploads. THE DEPENDENCY LEDGER owns every author: package.json spec, lock+integrity seal, hoisting phantoms, semver version trains. THE EVENTED BACKBONE prices emit as a for-loop — custody topics, listener velocity, warning meters. THE PRODUCTION LEDGER signs the process: boot-validated config, signal custody, graceful drains, supervised clusters, observability as algebra. Beginner to expert: run the docket, sign each vow, own every line.',
    bn: 'Node.js হলো সার্ভার-উল্টানো: একটি থ্রেড, যা কখনো অপেক্ষা করে না, গ্রহণ করে প্রতি ক্লায়েন্ট, আর প্রতি সুবিধা (অ্যাসিঙ্ক I/O, ফ্রেমওয়ার্ক, ক্লাস্টার) সেই একক বাজির পাটিগণিত। এই হাব সম্পূর্ণ কারিকুলাম হাঁটে A থেকে Z, আট পাঠে, সবই মূল্যায়িত একটি স্থির ৮-ছন্দের ডকেট দিয়ে (স্বাস্থ্য, লগইন-bcrypt, 2MB অর্ডার, 400ms রিপোর্ট, 50MB ডাউনলোড, বিকৃত-অর্ডার, অ্যাসিঙ্ক-বিপর্যয়, 50-ক্লায়েন্ট-বিস্ফোরণ), যার ল্যাব চার রানটাইম-শৃঙ্খলা হাঁটায় — অবরোধকারী (সিঙ্ক-জিম্মিকারী), উদাসীন (চুক্তিহীন অ্যাসিঙ্ক), শৃঙ্খল-রক্ষী (গতিহীন শপথ) আর স্রোতধারী (গতিনিয়ন্ত্রণ সহ ছাদ)। লুপ-খাতা মূল্য দেয় রওকদারির: পর্যায়, মাইক্রোটাস্ক-লেন, libuv-পুল, ব্লকিং-পাটিগণিত। মিডলওয়্যার-শপথ মূল্য দেয় চেইনের: next(err) তত্ত্বাবধান, 4-আর্গ বাসা, ব্যাকপ্রেশার, সারি-ছাদ। প্রথম সার্ভার ধরে রাখে উদঘাটিত-রওকদারি: http.createServer, URL-পার্সিং, ডিসপ্যাচ-সারণি, শ্রবণ-শপথ। মডিউল-দানা প্রতি সীমান্তে সই করে: CJS-মোড়ক বনাম ESM-সংযোগ, ক্যাশ, চক্র, টাইপ-ফাটক। ফাইল-অর্থনীতি প্রতি বাইটের মালিক: fs-ত্রয়ী, সিলকৃত-পথ, Buffer, লেনদেনগত-আপলোড। নির্ভরতা-খাতা প্রতি লেখকের মালিক: package.json-স্পেক, লক+সততা-সীল, উত্তোলন-ভূত, semver সংস্করণ-ট্রেন। ইভেন্টেড-মেরুদণ্ড মূল্য দেয় for-লুপরূপে emit — তত্ত্বাবধান-বিষয়, শ্রোতা-বেগ, সতর্কতা-মিটার। উৎপাদন-খাতা প্রক্রিয়ায় সই করে: বুট-যাচাইকৃত কনফিগ, সিগন্যাল-তত্ত্বাবধান, সৌম্য-নিষ্কাশন, তত্ত্বাবধানকৃত-ক্লাস্টার, বীজগণিতরূপে পর্যবেক্ষণযোগ্যতা। নবীন থেকে দক্ষ: ডকেট চালান, প্রতি শপথে সই করুন, প্রতি লাইনের মালিক হোন।',
  },
  lessons: [
    loopLedgerLesson, middlewareVowsLesson, firstServerLesson, moduleGrainLesson,
    fileEconomyLesson, dependencyLedgerLesson, eventedBackboneLesson, productionLedgerLesson,
  ],
  references: [
    {
      group: { en: 'The register & the chain', bn: 'রওকদারি ও চেইন' },
      items: [
        { term: 'event loop', def: { en: 'Four queues (timers → pending → poll → check), two VIP lanes (nextTick, promises), one cashier — never wait at the register, never cook at the register.', bn: 'চার সারি (টাইমার → পেন্ডিং → পোল → চেক), দুই ভিআইপি-লেন (nextTick, প্রতিশ্রুতি), এক রওকদারি — রওকদারিতে কখনো অপেক্ষা নয়, কখনো রান্না নয়।' } },
        { term: 'libuv pool', def: { en: 'fs/DNS/crypto/zlib routes to 4 worker threads by default; pool × duration = throughput arithmetic, docket-priced.', bn: 'fs/DNS/ক্রিপ্টো/zlib যায় ডিফল্টে 4 কর্মীর থ্রেডে; পুল × সময়কাল = থ্রুপুট পাটিগণিত, ডকেটে মূল্যায়িত।' } },
        { term: 'middleware & next(err)', def: { en: 'Express as a FIFO chain: END / PASS / PUNT; 4-arg error homes classified by arity; every async handler wrapped.', bn: 'FIFO-শৃঙ্খল হিসেবে Express: শেষ / চলে যাও / দায়চুঁড়ি; আর্গুমেন্ট-সংখ্যায় শ্রেণিবদ্ধ 4-আর্গ ত্রুটি-বাসা; প্রতি async হ্যান্ডলার মোড়ককৃত।' } },
        { term: 'streams & backpressure', def: { en: 'write() false means pause until drain: pipeline() composes with cleanup; memory = watermark × concurrent, never file size.', bn: 'write() মিথ্যা মানে নিষ্কাশন পর্যন্ত বিরতি: pipeline() পরিষ্কারকরণসহ রচনা করে; স্মৃতি = জলছাপ × সমকালীন, ফাইল-আকার কখনো নয়।' } },
      ],
    },
    {
      group: { en: 'Files, packages & the process', bn: 'ফাইল, প্যাকেজ ও প্রক্রিয়া' },
      items: [
        { term: 'fs trio + sealed paths', def: { en: 'sync at boot only; promises at request time; resolve → startsWith at root: every traversal variant cremated in one geometry contract.', bn: 'কেবল বুটে সিঙ্ক; অনুরোধ-কালে প্রতিশ্রুতি; মূলে resolve → startsWith: একটি জ্যামিতি-চুক্তিতে দহনকৃত প্রতি অতিক্রমণ-রূপ।' } },
        { term: 'upload ritual', def: { en: 'Stream to tmp (same filesystem) → sniff magic bytes → atomic rename: the three verbs, one grammar, one EXDEV-proof vow.', bn: 'tmp-তে স্ট্রিম (একই ফাইল-সিস্টেম) → ম্যাজিক-বাইট ঘাঁড়া → পারমাণবিক-নামান্তর: তিন ক্রিয়া, এক ব্যাকরণ, একটি EXDEV-প্রমাণ-শপথ।' } },
        { term: 'lock + integrity', def: { en: 'package-lock.json as the sealed ledger: exact versions, resolved URLs, SHA-512 content hashes; npm ci replays byte-for-byte.', bn: 'সিলকৃত-খাতা হিসেবে package-lock.json: হুবহু সংস্করণ, resolved URL, SHA-512 বিষয়বস্তু-হ্যাশ; npm ci বাইটপ্রতি পুনরাভাজন করে।' } },
        { term: 'graceful shutdown', def: { en: 'SIGTERM heard → server.close() → in-flight drained under the grace window → resources flushed → honest exit code.', bn: 'SIGTERM শ্রুত → server.close() → সৌম্য-উইন্ডোর নিচে উড়ন্তটি নিষ্কাশিত → সম্পদ ফ্লাশকৃত → সৎ প্রস্থান-কোড।' } },
        { term: 'cluster', def: { en: 'N processes behind one kernel accept queue; primary supervises, restarts staggered; state outside workers by rule.', bn: 'একটি কার্নেল-গ্রহণ-সারির আড়ালে N প্রক্রিয়া; প্রাথমিক তত্ত্বাবধান করে, রিস্টার্ট পাশাপাশি; অবস্থা নিয়মে কর্মীর বাইরে।' } },
      ],
    },
  ],
  roadmap: [
    { stage: 1, title: { en: 'The register', bn: 'রওকদারি' }, detail: { en: 'loop phases & VIP lanes, pool routing, stall arithmetic, the crash doctrine: never wait, never cook — the docket’s 898ms and 51 starved clients.', bn: 'লুপ-পর্যায় ও ভিআইপি-লেন, পুল-রাউটিং, স্থবিরতা-পাটিগণিত, বিপর্যয়-মতবাদ: কখনো অপেক্ষা নয়, কখনো রান্না নয় — ডকেটের 898ms আর 51 অনাহারী ক্লায়েন্ট।' } },
    { stage: 2, title: { en: 'The chain & the first server', bn: 'চেইন ও প্রথম সার্ভার' }, detail: { en: 'middleware vows (wrap, one error home, pacing, ceilings), then the bare register: createServer, URL values, dispatch tables, listen as an async vow.', bn: 'মিডলওয়্যার-শপথ (মোড়ক, এক ত্রুটি-বাসা, গতিনিয়ন্ত্রণ, ছাদ), তারপর উদঘাটিত-রওকদারি: createServer, URL-মান, ডিসপ্যাচ-সারণি, অ্যাসিঙ্ক-শপথ হিসেবে শ্রবণ।' } },
    { stage: 3, title: { en: 'Boundaries & bytes', bn: 'সীমান্ত ও বাইট' }, detail: { en: 'module grain (two worlds, one loader, caches, cycles), file economy (fs trio, sealed paths, upload ritual), dependency ledger (spec, seal, phantom, trains).', bn: 'মডিউল-দানা (দুই জগৎ, এক লোডার, ক্যাশ, চক্র), ফাইল-অর্থনীতি (fs-ত্রয়ী, সিলকৃত-পথ, আপলোড-আচার), নির্ভরতা-খাতা (স্পেক, সীল, ভৌত, ট্রেন)।' } },
    { stage: 4, title: { en: 'Topics & the process', bn: 'বিষয় ও প্রক্রিয়া' }, detail: { en: 'evented backbone (emit as for-loop, custody, listener meters), production ledger (config, signals, drains, cluster, observability) — the service signed at every register.', bn: 'ইভেন্টেড-মেরুদণ্ড (for-লুপরূপে emit, তত্ত্বাবধান, শ্রোতা-মিটার), উৎপাদন-খাতা (কনফিগ, সিগন্যাল, নিষ্কাশন, ক্লাস্টার, পর্যবেক্ষণযোগ্যতা) — প্রতি রওকদারিতে সইকৃত সেবা।' } },
  ],
  projects: [
    {
      title: { en: 'DocketServer: the lab realized end-to-end', bn: 'ডকেটসার্ভার: প্রান্তে-থেকে-প্রান্তে বাস্তবায়িত ল্যাব' },
      brief: { en: 'Implement the lab’s exact 8-beat docket as a real Express service: bcrypt login route, 2MB orders payload, 400ms aggregate (Piscina pool with maxQueue = 12), 50MB receipt download, order validation with a tamper test, an async-throw debug route wrapped by the lesson-one vow, and a /load endpoint firing the 50-client burst. Ship a recorder printing the exact lab counters (blockedMs, maxLatencyMs, hungRequests, swallowedErrors, errorHandlerHits, memoryPeakMB, throughputRps) — your acceptance gate reproduces the pinned table for all four laws before any further optimization is allowed.', bn: 'ল্যাবের হুবহু ৮-ছন্দের ডকেট বাস্তবায়ন করুন প্রকৃত Express-সেবায়: bcrypt-লগইন-রুট, 2MB অর্ডার-পেলোড, 400ms সংহতকরণ (Piscina-পুল, maxQueue = 12 সহ), 50MB রশিদ-ডাউনলোড, বিক্ষোভ-পরীক্ষাসহ অর্ডার-বৈধতা, পাঠ-একের-শপথে মোড়ককৃত async-ছোঁড়া ডিবাগ-রুট, আর একটি /load এন্ডপয়েন্ট, যা 50-ক্লায়েন্ট-বিস্ফোরণ চালায়। একটি রেকর্ডার দিন, যা হুবহু ল্যাব-গণক ছাপে (blockedMs, maxLatencyMs, hungRequests, swallowedErrors, errorHandlerHits, memoryPeakMB, throughputRps) — আপনার গ্রহণযোগ্যতা-ফাটক পিনকৃত-টেবিল পুনরুত্পাদন করে চার বিধানেই, কোনো অতিরিক্ত-অপ্টিমাইজেশনের অনুমতির আগে।' },
      difficulty: 'beginner',
    },
    {
      title: { en: 'ByteCourt: the sealed-file ritual as a library', bn: 'বাইটকোর্ট: লাইব্রেরি হিসেবে সিলকৃত-ফাইল-আচার' },
      brief: { en: 'Package the sealed-path + upload-ritual into a drop-in middleware: serveStatic(root) with resolve/startsWith/MIME-by-extension/streaming baked in (zero traversal surface, full watermark pacing), receiveUpload({ tmpDir, allowedMimes, byteCeiling }) performing tmp-stream → magic-byte sniff → atomic rename with EXDEV boot assertion, plus a codemod-style scanner that greps a codebase for path.resolve-adjacent handler code and reports all unsealed file paths in CI. Attach the debug file’s full test suite: cross-device tmp, extension liars, concurrent bursts, byte-ceiling breaches.', bn: 'মধ্যস্থ-মিডলওয়্যারে সিলকৃত-পথ + আপলোড-আচার প্যাকেজ করুন: serveStatic(root) যার ভেতরে resolve/startsWith/এক্সটেনশনভেদে-MIME/স্ট্রিমিং বর্ণিত (শূন্য অতিক্রমণ-পৃষ্ঠ, পূর্ণ জলছাপ-গতিনিয়ন্ত্রণ), receiveUpload({ tmpDir, allowedMimes, byteCeiling }) যা করে tmp-স্ট্রিম → ম্যাজিক-বাইট-ঘাঁড়া → EXDEV-বুট-অভিযোগসহ পারমাণবিক-নামান্তর, সঙ্গে একটি কোডমড-শৈলীর স্ক্যানার যা কোডবেস গ্রেপ করে path.resolve-সংলগ্ন হ্যান্ডলার-কোডের জন্য আর CI-তে সব অসীলকৃত-ফাইল-পথ রিপোর্ট করে। ডিবাগ-ফাইলের পূর্ণ পরীক্ষা-স্যুট সংযুক্ত করুন: ক্রস-ডিভাইস-tmp, এক্সটেনশন-মিথ্যাবাদী, সমকালীন-বিস্ফোরণ, বাইট-ছাদ-অতিক্রম।' },
      difficulty: 'intermediate',
    },
    {
      title: { en: 'GavelOps: production ledger checklist as code', bn: 'গেভেলঅপস: কোডরূপে উৎপাদন-খাতা-চেকলিস্ট' },
      brief: { en: 'Build the service template the capstone lesson recites: boot-validated config (zod gate, frozen singleton), signal subscription adjacent to listen, drain arithmetic with in-flight tracking and grace-window enforcement, supervised cluster with staggered restarts, structured logging with request-id flow, livez/readyz as two distinct vows, plus the CI regression that replays the staging crash-loop debug file: listener-per-request leak planting, SIGTERM parrot handlers, conflated health routes — all three caught automatically. The acceptance gate: one kubernetes rolling update proves zero dropped requests across the whole drain.', bn: 'চূড়ান্ত-পাঠ যে সেবা-টেমপ্লেট পাঠ করে তা নির্মাণ করুন: বুট-যাচাইকৃত কনফিগ (zod-ফাটক, হিমায়িত-সিঙ্গলটন), listen-এর সংলগ্ন সিগন্যাল-সাবস্ক্রিপশন, উড়ন্ত-ট্র্যাকিং আর সৌম্য-উইন্ডো-জারিসহ নিষ্কাশন-পাটিগণিত, পাশাপাশি-রিস্টার্টসহ তত্ত্বাবধানকৃত ক্লাস্টার, রিকোয়েস্ট-id-প্রবাহসহ কাঠামোকৃত লগিং, দুই স্বতন্ত্র শপথ হিসেবে livez/readyz, সঙ্গে CI-রিগ্রেশন যা স্টেজিং-বিপর্যয়-চক্র-ডিবাগ-ফাইল পুনরাভাজন করে: প্রতি-অনুরোধ-শ্রোতা-লিক-রোপণ, SIGTERM-তোতা-হ্যান্ডলার, গুলানো স্বাস্থ্য-রুট — তিনটিই সয়ংক্রিয়ভাবে ধরা পড়ে। গ্রহণযোগ্যতা-ফাটক: একটি kubernetes রোলিং-আপডেট প্রমাণ করে পুরো নিষ্কাশন জুড়ে শূন্য বাদ-পড়া অনুরোধ।' },
      difficulty: 'intermediate',
    },
  ],
  bestPractices: [
    { en: 'Never wait at the register, never cook at the register: sync APIs at boot only, CPU on worker threads, I/O by OS notification or the pool — the 898ms hostage arithmetic of the docket is the price of breaking this once.', bn: 'রওকদারিতে কখনো অপেক্ষা নয়, কখনো রান্না নয়: সিঙ্ক-API কেবল বুটে, CPU ওয়ার্কার-থ্রেডে, I/O অপারেটিং-সিস্টেম-বিজ্ঞপ্তি বা পুলে — ডকেটের 898ms জিম্মি-পাটিগণিত হলো একবার ভাঙার মূল্য।' },
    { en: 'Wrap every async handler the day the file is created: one registration-discipline (wrap = fn => (req,res,next) => Promise.resolve(fn(req,res,next)).catch(next)) deletes hung sockets and swallowed truths forever.', bn: 'ফাইল তৈরির দিনেই প্রতি async হ্যান্ডলার মোড়কে আবৃত করুন: একটি নিবন্ধন-শৃঙ্খলা (wrap = fn => (req,res,next) => Promise.resolve(fn(req,res,next)).catch(next)) চিরকাল মুছে দেয় ঝুলন্ত-সকেট আর গিলে-ফেলা সত্য।' },
    { en: 'Seal every path at its root and every package at its lock: resolve+startsWith for files, lock+integrity for dependencies — two single lines that retire two entire CVE taxonomies.', bn: 'প্রতি পথ সিল করুন তার মূলে আর প্রতি প্যাকেজ তার লকে: ফাইলের জন্য resolve+startsWith, নির্ভরতার জন্য লক+সততা — দুই একক-লাইন, যা দুই পূর্ণ CVE-শ্রেণীবিভাগ অবসারিত করে।' },
    { en: 'Stream every large answer and count every influx: pacing for outputs (watermark × concurrent), ceilings for intakes (byte caps, queue limits, honest 503s) — politeness you cannot price is debt by another name.', bn: 'প্রতি বড় উত্তর স্ট্রিম করুন আর প্রতি অনুপ্রবাহ গোনুন: আউটপুটের জন্য গতিনিয়ন্ত্রণ (জলছাপ × সমকালীন), গ্রহণের জন্য ছাদ (বাইট-ছাদ, সারি-সীমা, সৎ 503) — যে বিনয় মূল্য দিতে পারেন না, তা অন্য নামে ঋণ।' },
    { en: 'Treat every listener as memory debt with a lifecycle owner: once for completions, constructor↔disposal for standing ears, never inside request handlers, listener slopes read as meters not decoration.', bn: 'প্রতি শ্রোতাকে ধরুন জীবনচক্র-মালিকসম্পন্ন স্মৃতি-ঋণ হিসেবে: সমাপ্তিতে once, স্থায়ী কর্নের জন্য নির্মাণ↔অবসারণ, অনুরোধ-হ্যান্ডলারের ভেতরে কখনো নয়, শ্রোতা-ঢাল পঠিত মিটার হিসেবে, সজ্জা নয়।' },
    { en: 'Validate config at boot, subscribe signals at listen, drain at exits: the process is the final register — every environment secret parsed once, every SIGTERM answered by grammar, every in-flight request answered before the gavel falls.', bn: 'কনফিগ যাচাই করুন বুটে, সিগন্যাল সাবস্ক্রাইব করুন listen-এ, নিষ্কাশন করুন বহির্গমনে: প্রক্রিয়া হলো চূড়ান্ত রওকদারি — প্রতি পরিবেশ-গোপনীয়তা একবার পার্সকৃত, প্রতি SIGTERM ব্যাকরণ দিয়ে উত্তরকৃত, প্রতি উড়ন্ত-অনুরোধ হাতুড়ি পড়ার আগে উত্তরকৃত।' },
    { en: 'One error home stamps one shape: (err, req, res, next) with {type, message, requestId}, typed statuses, secrets never leaked — error shapes are observability capability, not aesthetics.', bn: 'এক ত্রুটি-বাসা একটি আকৃতি ছাপে: (err, req, res, next) সহ {type, message, requestId}, টাইপকৃত স্ট্যাটাস, গোপনীয়তা কখনো ফাঁস নয় — ত্রুটি-আকৃতি হলো পর্যবেক্ষণ-ক্ষমতা, নান্দনিকতা নয়।' },
  ],
  interview: [
    {
      q: { en: '“Node is single-threaded, so it can’t be fast under load.” Price the argument with the docket.', bn: '“Node এক-থ্রেডিক, তাই চাপের নিচে দ্রুত হতে পারে না।” ডকেট দিয়ে যুক্তির মূল্য দিন।' },
      a: { en: 'The counter is arithmetic, not adjectives: the register’s one thread pays ZERO context-switch and ZERO thread-per-connection RAM (a socket is a registered interest, not a hostage stack), so for I/O-dominant load — which is what servers mostly ARE — the loop out-serves thread societys per byte. The docket measures the other half: CPU routes. The blocker pays 898ms of stolen loop in one 8-beat docket and dies at beat 7; the streamer pays 8ms for the same traffic by moving 400ms aggregates onto a 4-worker Piscina pool with a queue ceiling (503 past 12) and streaming files at watermark instead of RAM — throughput 19 rps vs 0 for a dead process. So the claim is falsifiable: single-THREAD brakes on CPU-heavy traffic, but the architecture that sells the thread ALSO sells the escape (pool, sharding, cluster), which is why the honest pricing is: Node is slow under CPU-confusion, not under load-discipline. I would grade any “single-thread means slow” claim as untested against the loop ledger.', bn: 'পাল্টা-উত্তর হলো পাটিগণিত, বিশেষণ নয়: রওকদারির এক থ্রেড শোধ দেয় শূন্য প্রেক্ষাপট-বিনিময় আর শূন্য থ্রেড-প্রতি-সংযোগ RAM (সকেট হলো নিবন্ধিত-স্বার্থ, জিম্মি-স্ট্যাক নয়), তাই I/O-উজানের চাপে — সার্ভার বেশিরভাগ সময় যা-ই হয় — লুপ থ্রেড-সমাজকে বাইটপ্রতি হারায়। ডকিট অন্য অর্ধেক মাপে: CPU-রুট। অবরোধকারী শোধ দেয় 898ms চুরি-করা-লুপ, একটি ৮-ছন্দের ডকেটে, আর মরে ৭ ছন্দে; স্রোতধারী একই ট্রাফিকে শোধ দেয় 8ms, 400ms সংহতকরণ 4-কর্মীর Piscina-পুলে সরিয়ে (12 ছাড়িয়ে 503 ছাদসহ) আর RAM-এর বদলে জলছাপে ফাইল স্ট্রিম করে — থ্রুপুট 19 rps বনাম মৃত-প্রসেসের 0। তাই দাবিটি মিথ্যাকরণযোগ্য: এক-থ্রেড CPU-ভারী ট্রাফিকে ব্রেক কষে, কিন্তু সেই স্থাপত্য, যা থ্রেড বিক্রি করে, পালানোও বিক্রি করে (পুল, শার্ডিং, ক্লাস্টার), এইজন্যই সৎ-মূল্যায়ন: Node ধীর CPU-বিভ্রান্তিতে, চাপ-শৃঙ্খলায় নয়। যে-কোনো "এক-থ্রেড মানে ধীর" দাবি আমি মূল্য দেব লুপ-খাতার বিরুদ্ধে অপরীক্ষিত হিসেবে।' },
    },
    {
      q: { en: 'Walk me through your error-handling strategy for an Express service at production scale.', bn: 'উৎপাদন-স্কেলে একটি Express-সেবার জন্য আপনার ত্রুটি-পরিচালনা-কৌশল হেঁটে দেখান।' },
      a: { en: 'Three nesting artefacts, all voted at registration time. (1) THE WRAP: every async handler wrapped the day the file is created — every rejection converted to next(err) at one seam; with Express 5 that vow is native. (2) THE CHAIN: ordered middleware (logger → limits → auth → parse → routes → not-found → error home), order as the security model; arity-classified 4-arg handler as the ONE error home, stamping one shape ({type, message, requestId}), status from type, internals never leaked, every error witnessed on the log line that matches the request id. (3) THE CHECKS measured against the docket: the careless law’s 2 hangs/2 swallowed/0 error-home hits vs the chain-keeper’s 0/0/2 is my interview-proof arithmetic — and the health-check assertion that error-home hits match the status-code distribution in dashboards. At scale add decay paths: fatal domain errors are vow-shaped enums (typed 4xx ladder), infrastructure errors are instrumented against a circuit-breaker ledger outside the chain, and the uncaught-but-armed tail is crash-fast with the supervisor restarting — subscribe-or-die custody applied at the process register too. Everything else (retry budgets, error telemetry, alert slopes) is measured arithmetic on those three artefacts.', bn: 'তিনটি নীড়-নথি, সবই নিবন্ধন-কালে ভোটকৃত। (1) মোড়ক: প্রতি async হ্যান্ডলার ফাইল তৈরির দিনেই মোড়ককৃত — প্রতি রিজেকশন একটি সেলাইতে next(err)-এ রূপান্তরিত; Express 5-এ সেই শপথ নেটিভ। (2) চেইন: সাজানো মিডলওয়্যার (লগার → সীমা → প্রমাণীকরণ → পার্স → রুট → নট-ফাউন্ড → ত্রুটি-বাসা), নিরাপত্তা-মডেল হিসেবে ক্রম; আর্গুমেন্ট-সংখ্যা-শ্রেণিবদ্ধ 4-আর্গ হ্যান্ডলার এক ত্রুটি-বাসা হিসেবে, একটি আকৃতি ছাপে ({type, message, requestId}), টাইপ থেকে স্ট্যাটাস, অভ্যন্তর কখনো ফাঁস নয়, প্রতি ত্রুটি লগ-লাইনে প্রত্যক্ষকৃত, যা রিকোয়েস্ট-id মেলায়। (3) ডকেটের বিরুদ্ধে মাপা চেকগুলো: careless-বিধানের 2 ঝুলন্ত/2 গিলে-ফেলা/0 ত্রুটি-বাসা-হিট বনাম শৃঙ্খল-রক্ষীর 0/0/2 হলো আমার সাক্ষাৎকার-প্রমাণ-পাটিগণিত — আর স্বাস্থ্য-চেক-অভিযোগ যে ত্রুটি-বাসা-হিট ড্যাশবোর্ডের স্ট্যাটাস-কোড-বণ্টন মেলায়। স্কেলে ক্ষয়-পথ যোগ করুন: মারাত্মক ডোমেইন-ত্রুটি শপথ-আকৃতির enum (টাইপকৃত 4xx মই), অবকাঠামো-ত্রুটি চেইনের বাইরের সার্কিট-ব্রেকার-খাতার বিপরীতে যন্ত্রাংশকৃত, আর অধৃত-কিন্তু-সজ্জিত পুচ্ছ হলো দ্রুত-পতন, পরিচালক রিস্টার্ট করে — প্রক্রিয়া-রওকদারিতেও প্রয়োগকৃত সাবস্ক্রাইব-নয়-মরো তত্ত্বাবধান। বাকি সবকিছু (রিট্রাই-বাজেট, ত্রুটি-টেলিমেট্রি, সতর্কতা-ঢাল) সেই তিন নথির উপর মাপা পাটিগণিত।' },
    },
    {
      q: { en: 'Your service suddenly moves 5MB/sec of memory growth that won’t stop. How do you diagnose it?', bn: 'আপনার সেবা হঠাৎ প্রতি সেকেন্ডে 5MB স্মৃতি-বৃদ্ধি চালু করেছে, যা থামছে না। আপনি কীভাবে রোগনির্ণয় করবেন?' },
      a: { en: 'Three-class differential first, because Node leaks are exactly three breeds and each has a fingerprints-pattern: (1) CLOSURE leaks — listener closures added per lifecycle-less subscription (the evented backbone debug file’s breed): symptom = listenerCount slopes on the bus, warnings past MaxListeners; proof = events.getEventListeners histograms per topic, heap snapshot showing closure counts climbing with request rate. (2) CACHE/unbounded-store leaks — singleton Map registries with no eviction (module lesson’s caches rearmed): symptom = map sizes growing monotonic; proof = heapdump diff showing object-count ranks. (3) BUFFER/slab leaks — views holding parents (Buffer.slice, lesson five’s shared-parent arithmetic): symptom = Total ArrayBuffer count climbing underwater; proof = ArrayBuffer bucket histograms, RSS/heap malalignment. Diagnostic order: take a heap snapshot baseline, replay load 60s, snapshot again, diff by retainer — the retainer chain names the ledger. The chronic fix always follows the velocity math: sign every closure with lifecycle owners, make every cache a bounded ledger (LRU or TTL), detach views at the seam with explicit copies — and validate against the same 60s load replay BEFORE shipping, because leak invoices are always paid at crash time, never at code-review time.', bn: 'প্রথমে তিন-শ্রেণির পার্থক্য-নির্ণয়, কারণ Node-লিক হুবহু তিন জাতের আর প্রতিটির আঙুলের-ছাপ-ধরন আছে: (1) ক্লোজার-লিক — জীবনচক্রহীন-সাবস্ক্রিপশনে যুক্ত শ্রোতা-ক্লোজার (ইভেন্টেড-মেরুদণ্ড-ডিবাগ-ফাইলের জাত): উপসর্গ = বাসে listenerCount-ঢাল, MaxListeners ছাড়িয়ে সতর্কতা; প্রমাণ = বিষয়প্রতি events.getEventListeners হিস্টোগ্রাম, হিপ-স্ন্যাপশট দেখাচ্ছে অনুরোধ-হারের সাথে ক্লোজার-গণনা বাড়ছে। (2) ক্যাশ/সীমাহীন-ভাণ্ডার-লিক — অবসারণহীন সিঙ্গলটন-Map-রেজিস্ট্রি (মডিউল-পাঠের ক্যাশ পুনসজ্জিত): উপসর্গ = মানচিত্র-আকার একরৈখিক বাড়ছে; প্রমাণ = বস্তু-গণনা-স্তর দেখাচ্ছে heapdump-ডিফ। (3) BUFFER/স্ল্যাব-লিক — অভিভাবক ধরে রাখা দৃশ্য (Buffer.slice, পাঠ-পাঁচের ভাগকৃত-অভিভাবক-পাটিগণিত): উপসর্গ = Total ArrayBuffer-সংখ্যা পানির নিচে বাড়ছে; প্রমাণ = ArrayBuffer বাকেট-হিস্টোগ্রাম, RSS/হিপ-অসাম্য। রোগনির্ণয়-ক্রম: হিপ-স্ন্যাপশট বেসলাইন নিন, 60 সে লোড পুনচালান, আরেকটি স্ন্যাপশট নিন, ধারকভেদে ডিফ করুন — ধারক-শৃঙ্খল খাতার নাম বলে। দীর্ঘস্থায়ী মেরামত সর্বদা বেগ-গণিত অনুসরণ করে: প্রতি ক্লোজার জীবনচক্র-মালিকসহ সই করুন, প্রতি ক্যাশ সীমাবদ্ধ-খাতা করুন (LRU বা TTL), সেলাইতে দৃশ্য বিচ্ছিন্ন করুন স্পষ্ট-অনুলিপি দিয়ে — আর একই 60-সেকেন্ডের লোড-রিপ্লের বিরুদ্ধে যাচাই করুন পাঠানোর আগে, কারণ লিক-চালান সবসময় পরিশোধিত হয় বিপর্যয়ের কালে, কোড-রিভিউর কালে নয়।' },
    },
    {
      q: { en: 'Should this new microservice be written in raw Node or Express? Defend both answers.', bn: 'এই নতুন মাইক্রোসার্ভিসটি কাঁচা Node-এ নাকি Express-এ লিখতে হবে? দুই উত্তরই রক্ষা করুন।' },
      a: { en: 'Both, and the seam-count decides. RAW wins when the unit of work fits three seams: one dispatch table (5–10 routes), one parser (health-probe JSON or tiny bodies), zero auth/sharing flows; the service is a deployment shape first (sidecar, metric proxy, health lane) — 3 lines answer the docket’s beat 1 with no chain cost, image sizes stay exact, dependency-ledger debts stay zero, and the register’s stall counters are pinned at zero by a handful of owned lines. EXPRESS wins the moment the dispatch table owns more than three seams: auth + multiple parsers + an error home + a route census above twenty, because that table is now REWRITING lesson two’s chain in your own dialect, and every re-discovery is a debt paid twice (implementation + security review time). The seam arithmetic in one sentence: raw → chain when rewriting becomes re-discovery; chain → shared by the ecosystem. I would name the thresholds (route count, seam inventory, team familiarity, patching cadence of Express itself as a sealed dependency) and make the choice measurable: lines of ownership vs. packages of debt — and the same pricing covers koa/fastify/hono as different vow collections on the same chain discipline, judged by their vetting evidence and bundle arithmetic.', bn: 'দুটোই, আর সেলাই-গণনা ঠিক করে দেয়। কাঁচা জেতে যখন কাজের ইক তিনটি সেলাইয়ে মাপা যায়: একটি ডিসপ্যাচ-সারণি (5–10 রুট), একটি পার্সার (হেলথ-প্রোব JSON বা ক্ষুদ্র বডি), শূন্য অথ/ভাগ-প্রবাহ; সেবাটি আগে ডিপ্লয়মেন্ট-আকৃতি (সাইডকার, মেট্রিক-প্রক্সি, স্বাস্থ্য-লেন) — 3 লাইন উত্তর দেয় ডকেটের ১ ছন্দে, কোনো চেইন-খরচ ছাড়া, ইমেজ-আকার থাকে হুবহু, নির্ভরতা-খাতা-ঋণ থাকে শূন্য, আর রওকদারির স্থবিরতা-গণক পিনকৃত থাকে শূন্যে, মুঠোয়-মালিকানাধীন-লাইন দিয়ে। EXPRESS জেতে সেই মুহূর্তে, যখন ডিসপ্যাচ-সারণি তিনের বেশি সেলাইয়ের মালিক হয়: প্রমাণীকরণ + একাধিক পার্সার + একটি ত্রুটি-বাসা + বিশের উপর রুট-গণনা, কারণ সেই সারণি এখন পাঠ-দুইয়ের চেইন পুনর্লিখন করছে আপনার নিজস্ব উপভাষায়, আর প্রতি পুনঃআবিষ্কার হলো দুইবার শোধ দেওয়া ঋণ (বাস্তবায়ন + নিরাপত্তা-রিভিউ-সময়)। এক বাক্যে সেলাই-গণিত: কাঁচা → চেইন, যখন পুনর্লিখন হয়ে ওঠে পুনঃআবিষ্কার; চেইন → ইকোসিস্টেমের ভাগকৃত। আমি সীমারেখা নামাব (রুট-গণনা, সেলাই-তালিকা, দলের পরিচিতি, Express-এর নিজের প্যাচিং-ছন্দ, সিলকৃত-নির্ভরতা হিসেবে) আর পছন্দটি মাপার যোগ্য করব: মালিকানার লাইন বনাম ঋণের প্যাকেজ — আর একই মূল্যায়ন koa/fastify/hono-কেও ঢাকে, একই চেইন-শৃঙ্খলার বিভিন্ন শপথ-সংগ্রহ হিসেবে, তাদের যাচাই-সাক্ষ্য আর বান্ডিল-পাটিগণিত দিয়ে বিচারিত।' },
    },
  ],
  realWorld: [
    { en: 'uber.js & Netflix: entire dispatch layers priced the register way — I/O-dominant workloads on the evented register with cluster as supervised duplication, CPU offloaded to service boundaries, loop-lag as the standing SLO that pages engineers.', bn: 'uber.js ও Netflix: পুরো ডিসপ্যাচ-স্তর মূল্যায়িত রওকদারি-পথে — ইভেন্টেড-রওকদারিতে I/O-উজানের কাজের-চাপ, তত্ত্বাবধানকৃত-দ্বৈতকরণ হিসেবে ক্লাস্টার, CPU সেবা-সীমান্তে অফলোডকৃত, লুপ-ল্যাগ স্থায়ী SLO হিসেবে, যা প্রকৌশলীদের জাগায়।' },
    { en: 'npm left-pad & the lockfile era: the 11-line incident rewrote installation economics — lock+integrity are now the default seal, npm ci is the CI verb, and enterprise registries vendor packages we cannot outreview — dependency-ledger arithmetic as industry default.', bn: 'npm left-pad ও লকফাইল-যুগ: 11-লাইনের ঘটনা ইনস্টলেশন-অর্থনীতি পুনর্লিখন করল — লক+সততা এখন ডিফল্ট-সীল, npm ci হলো CI-ক্রিয়া, আর এন্টারপ্রাইজ-রেজিস্ট্রি এমন প্যাকেজ ভেন্ডর করে, যা আমরা রিভিউ করতে পারি না — শিল্প-ডিফল্ট হিসেবে নির্ভরতা-খাতা-পাটিগণিত।' },
    { en: 'Express 5’s async-rejection routing & Fastify’s schema-first chains: the ecosystem canonized the wrap as native machinery and the validation-as-chain as compiler discipline — every production service rides one of these two forms of the middleware vows today.', bn: 'Express 5-এর অ্যাসিঙ্ক-রিজেকশন-রাউটিং ও Fastify-এর স্কিমা-প্রথম চেইন: ইকোসিস্টেম মোড়ককে নেটিভ-যন্ত্র হিসেবে মূলমতবাদী করল আর চেইনরূপে-বৈধতাকে সংকলক-শৃঙ্খলা — প্রতি উৎপাদন-সেবা আজ চলে মিডলওয়্যার-শপথের এই দুই রূপের একটির উপর।' },
    { en: 'Kubernetes terminationGracePeriodSeconds & PM2 backoff: orchestrators carry the production ledger as config — signals as control channels, drain windows as budgets, restart policies as staggered arithmetic; the service file and the YAML file sign the same vow, one process apart.', bn: 'Kubernetes terminationGracePeriodSeconds ও PM2-ব্যাকঅফ: অর্কেস্ট্রেটর কনফিগ হিসেবে উৎপাদন-খাতা বহন করে — নিয়ন্ত্রণ-চ্যানেল হিসেবে সিগন্যাল, বাজেট হিসেবে নিষ্কাশন-উইন্ডো, পাশাপাশি-গণিত হিসেবে রিস্টার্ট-নীতি; সেবা-ফাইল আর YAML-ফাইল একই শপথে সই করে, এক প্রক্রিয়া ব্যবধানে।' },
  ],
};
