// splice-run.mjs — insert the measured code blocks (generated by mkcode.mjs) into a lesson,
// with a short lead paragraph and a caption per block. Numbers are written without thousands
// separators so the gate's bilingual figure check can match en against bn one-for-one.
import { readFileSync, writeFileSync } from 'node:fs';

const JOB = {
  'the-replication-log': {
    out: 'tools/audit/tmp/out-log.ts',
    lead: {
      en: 'Two programs, both under thirty lines. Run them with node and the counts appear on your terminal, which is the only honest way to meet a total order.',
      bn: 'দুটি প্রোগ্রাম, দুটোই ত্রিশ লাইনের নিচে। node দিয়ে চালান, সংখ্যাগুলো আপনার টার্মিনালে আসবে—মোট ক্রমের সঙ্গে পরিচয়ের একমাত্র সৎ পথ এটিই।',
    },
    captions: [
      {
        en: 'Same log, same order, three replicas: one state. Let each replica order by what arrived first and you get three states after 200 writes. Reads then disagree forever, because nothing detects it.',
        bn: 'একই লগ, একই ক্রম, তিনটি রেপ্লিকা: একটি অবস্থা। প্রতিটি রেপ্লিকা যেমনটি আগে পেয়েছে তেমনি ক্রম মানলে 200 লেখার পর তিনটি অবস্থা পাওয়া যায়, আর কেউ কিছু জানান না বলে পাঠক চিরকাল অমিল উত্তর পায়।',
      },
      {
        en: 'Half plus one of five is three. With two replicas down, writes and reads both stop: a majority rule is not a speed dial, it is a door that closes.',
        bn: 'পাঁচের অর্ধেকের এক বেশি মানে তিন। দুটি রেপ্লিকা নামানো থাকলে লেখা আর পাঠ দুটোই থামে—সংখ্যাগরিষ্ঠ নিয়ম স্পিড-ডায়াল নয়, এটি বন্ধ হয়ে যাওয়া দরজা।',
      },
    ],
  },
  'the-gossip-parish': {
    out: 'tools/audit/tmp/out-gossip.ts',
    lead: {
      en: 'Gossip sounds like a rumour and behaves like a formula. Poke three peers per round and count the rounds; then compare a digest exchange with a full sync.',
      bn: 'গসিপ গুজরের মতো শোনায়, সূত্রের মতো চলে। প্রতি রাউন্ডে তিনজনকে ধাক্কা দিন, রাউন্ড গুনুন; তারপর digest বনাম পূর্ণ সিঙ্কের খরচ মিলিয়ে দেখুন।',
    },
    captions: [
      {
        en: 'The informed count quadruples while the message count does too: 5607 pokes to reach 1000 nodes, and the last 57 take four times the traffic of the first 611.',
        bn: 'খবর পাওয়ার সংখ্যা যেমন বাড়ে, বার্তাও তেমন বাড়ে: 1000 নোডে পৌঁছাতে 5607টি ধাক্কা, আর শেষের 57টি নোডের জন্য প্রথম 611-এর চার গুণ ট্রাফিক খরচ হয়।',
      },
      {
        en: 'A digest of 5000 rows costs 20096 bytes and finds 12 differences. Resending every row costs 2100000 bytes for the same 12. Both converge; only one can be run every ten seconds.',
        bn: '5000 সারির digest খরচ 20096 byte আর 12টি অমিল খুঁজে দেয়। পুরো সারি পাঠালে সেই 12-এর জন্যই 2100000 byte লাগে। দুটোই মিলে যায়, একটি প্রতি দশ সেকেন্ডে চালানো যায় না।',
      },
    ],
  },
  'the-two-phase-duel': {
    out: 'tools/audit/tmp/out-2pc.ts',
    lead: {
      en: 'The blocking claim is usually asserted. Here it is counted: a thousand transactions, a coordinator that dies in 390 of them, and a heuristic compared against the rule it breaks.',
      bn: 'আটকে-যাওয়ার দাবি সাধারণত কেবলই ঘোষণা করা হয়। এখানে এটি গোনা হলো: হাজার লেনদেন, যার 390-এ কোঅর্ডিনেটর মরে যায়, আর যে নিয়মটি সে ভাঙে তার সঙ্গে একটি heuristic-এর তুলনা।',
    },
    captions: [
      {
        en: 'Plain two-phase commit blocks all three participants in every crashed run. The peer poll unblocks 386 of 390, still blocks 4, and buys those answers with 29 runs where one replica committed while another aborted.',
        bn: 'সাদা দুই-ধাপ কমিট প্রতিটি ভাঙন-রানে তিনজনকেই আটকে রাখে। peer poll 390-এর 386টি রান খুলে দেয়, 4টি তবু আটকে থাকে, আর যে উত্তরগুলো পাওয়া যায় তার 29টি রানে একটি রেপ্লিকা commit করে অন্যটি abort করে।',
      },
    ],
  },
  'distributed-systems-capstone': {
    out: 'tools/audit/tmp/out-capstone.ts',
    lead: {
      en: 'The desk is arithmetic, not opinion. One program takes four real designs and prints whether their quorums hold, how many machines may die, and what the availability vow costs in minutes.',
      bn: 'এই ডেস্ক মত নয়, হিসাব। একটি প্রোগ্রাম চারটি বাস্তব ডিজাইন নিয়ে বলে দেয় quorum টিকে কি না, কত যন্ত্র নামানো যায়, আর প্রাপ্যতার শপথের দাম মিনিটে কত।',
    },
    captions: [
      {
        en: 'Two of the four designs fail the first column: product cache and chat fan-out both read and write below a majority, so they are eventual by arithmetic while claiming otherwise on a slide.',
        bn: 'চারটির দুটি প্রথম কলামেই বসে যায়: product cache আর chat fan-out দুটোই সংখ্যাগরিষ্ঠের নিচে লেখে ও পড়ে, তাই স্লাইডে যা-ই লেখা থাকুক গণিতে ওরা eventuality-তেই দাঁড়ায়।',
      },
    ],
  },
};

for (const [name, job] of Object.entries(JOB)) {
  const path = `src/content/distributed-systems/lessons/${name}.ts`;
  const gen = readFileSync(job.out, 'utf8');
  const blocks = gen.match(/    \{\n      type: 'code',[\s\S]*?\n    \},/g) || [];
  if (blocks.length !== job.captions.length) {
    console.log(`${name}: ${blocks.length} blocks, ${job.captions.length} captions — skipped`);
    continue;
  }
  const region = [
    `    { type: 'heading', id: 'run', text: { en: 'RUN: measured, not asserted', bn: 'চালিয়ে দেখা: মাপা, ঘোষণা নয়' } },`,
    `    {`,
    `      type: 'para',`,
    `      text: {`,
    `        en: '${job.lead.en}',`,
    `        bn: '${job.lead.bn}'`,
    `      }`,
    `    },`,
    ...blocks.map((b, i) =>
      b.replace(/\n    \},$/, `,\n      caption: {\n        en: '${job.captions[i].en}',\n        bn: '${job.captions[i].bn}'\n      }\n    },`)
    ),
  ].join('\n');
  const L = readFileSync(path, 'utf8').split('\n');
  let anchor = L.findIndex((l) => /id: 'visual'/.test(l));
  if (anchor < 0) anchor = L.findIndex((l) => /id: 'internal'/.test(l));
  if (anchor < 0) anchor = L.findIndex((l) => /id: 'result'/.test(l));
  if (anchor < 0) { console.log(`${name}: no anchor`); continue; }
  L.splice(anchor, 0, region);
  writeFileSync(path, L.join('\n'));
  console.log(`${name}: inserted ${blocks.length} measured block(s) at line ${anchor + 1}`);
}
