import type { TechHub } from '../../lib/types';
import { residenceLesson } from './lessons/the-residence-vow';
import { invalidationLesson } from './lessons/the-invalidation-discipline';
import { theTowerOfLayersLesson } from './lessons/the-tower-of-layers';
import { theMissClerksLesson } from './lessons/the-miss-clerks';
import { theEvictionCourtLesson } from './lessons/the-eviction-court';
import { theStampedeWallLesson } from './lessons/the-stampede-wall';
import { theReplicationAccordsLesson } from './lessons/the-replication-accords';
import { theRedisDistrictLesson } from './lessons/the-redis-district';
import { theCapstoneTribunalLesson } from './lessons/the-capstone-tribunal';

export const cchHub: TechHub = {
  slug: 'caching' as never,
  name: 'Caching',
  icon: '🧊',
  tagline: {
    en: 'Who may live near the door — and when an answer must die even so.',
    bn: 'দুয়ারের কাছে কে বাস করবে — আর কখন উত্তরকে মরতেই হবে তবুও।',
  },
  intro: {
    en: 'Caching is the oldest performance bargain in computing: a small, fast, expensive residence beside a large, slow, cheap homeland, where every byte lives on a vow — when the seat is wanted by a worthier citizen, you leave. This hub takes that vow through its full certification, nine sessions, one town. THE RESIDENCE VOW opens the books: cache-aside as ceremony, the hit rate priced twice (tail latency AND origin headroom), the three clauses every resident signs — presence, proximity, freshness. THE INVALIDATION DISCIPLINE arms every lie: the lease priced from the staleness budget, the warrant that deletes on write, the version that never reuses a name, the plea of stale-while-revalidate. THE TOWER OF LAYERS climbs the real hierarchy — browser, CDN, gateway, app, shared register, buffer pool — pricing distance in hops and discipline in tiers. THE MISS CLERKS staff the empty shelf: cache-through/refresh-ahead/refresh-through, negative caching, the memo board of every fill errand. THE EVICTION COURT convenes the four verdicts over one judicial trace — LRU (2 hits of 11), FIFO (1, Belady’s anomaly pinned), LFU (2, counters decay), TTL (2; graves swept first). THE STAMPEDE WALL faces the herd: synchronized deaths, dogpiles priced at rate×latency, coalescing, jitter, probabilistic expiry. THE REPLICATION ACCORDS bind five hundred mirrors: stamps and vectors, the consistency spectrum priced in user seconds, read-your-writes immunity, the broadcast bus, quorum statutes at the split. THE REDIS DISTRICT opens the shared registry itself: the 90-byte framing ceremony, the single clerk and his queue law, sampled eviction uniforms, the two coroners, the two testaments (RDB photographs, AOF ledgers), and the drill instruments from SLOWLOG to client tracking. And THE CAPSTONE TRIBUNAL closes the town: one write subpoenaed from browser to disk, every district’s doctrine seated at one bar, the whole machine certified as a single invoice. Nine lessons, one tribunal, zero magical “just add Redis.”',
    bn: 'ক্যাশিং কম্পিউটিংয়ের প্রাচীনতম পারফরম্যান্স-তছরুপ: ছোট, দ্রুত, দামি বাসস্থান বড়, ধীর, সস্তা জায়রবাড়ির পাশে, যেখানে প্রতি বাইট বাস করে শপথে — আসন যখন যোগ্যতর নাগরিক চায়, তুমি চলে যাবে। এই হাব সেই শপথ নিয়ে-যায় পূর্ণ সনদে — নয় অধিবেশন, এক শহর। বাসস্থান-শপথ খাতা খোলে: অনুষ্ঠানরূপে ক্যাশ-অ্যাসাইড, হিট-রেট দুইবার মূল্যিত (টেইল-লেটেন্সি ও অরিজিন-হেডরুম), প্রতি বাসিন্দার সইকৃত তিন ধারা — উপস্থিতি, নৈকট্য, সতেজতা। অকার্যকরণ-শৃঙ্খলা প্রতি মিথ্যাকে সশস্ত্র করে: বাসি-বাজেট থেকে মূল্যিত লিজ, লেখায়-মোছা পরোয়ানা, নাম কভু-না-পুনব্যবহৃত সংস্করণ, স্টেল-হোয়াইল-রিভ্যালিডেট মিনতি। স্তর-মিনার প্রকৃত স্তরবিন্যাসে ওঠে — ব্রাউজার, CDN, গেটওয়ে, অ্যাপ, ভাগকৃত-রেজিস্টার, বাফার-পুল — দূরত্ব মূল্যিত হপে, শৃঙ্খলা স্তরে। মিস-করণিকেরা ফাঁকা তাক জনবল দেয়: ক্যাশ-থ্রু/রিফ্রেশ-অ্যাহেড, নেতিবাচক-ক্যাশ, প্রতি পূরণ-দৌড়ের মেমো-বোর্ড। উচ্ছেদ-আদালত চার রায় অধিবেশন করায় একটি বিচারিক ট্রেসে — LRU (১১-এর ২ হিট), FIFO (১; Belady-বৈপরীত্য পিণ্ডকৃত), LFU (২; গণনা ক্ষয় হয়), TTL (২; আগে কবর ঝাড়ু)। স্ট্যাম্পিড-প্রাচীর পালের মুখোমুখি: সমলয়ী-মৃত্যু, হার×লেটেন্সিতে মূল্যিত ডগপাইল, কুণ্ডলীপন, জিটার, দৈব-মেয়াদ। প্রতিলিপি-অ্যাকর্ড পাঁচশো আয়না বাঁধে: ছাপ ও ভেক্টর, ব্যবহারকারী-সেকেন্ডে মূল্যিত সামঞ্জস্য-বর্ণালী, read-your-writes অনাক্রম্যতা, সম্প্রচার-বাস, ফাঁকে কোরাম-বিধান। Redis-জেলা ভাগকৃত রেজিস্ট্রি নিজেই উন্মোচন করে: ৯০-বাইট কাঠামো-আনুষ্ঠানিকতা, একক করণিক আর তার কাতার-বিধি, নমুনাকৃত বহিষ্কার-ইউনিফর্ম, দুই মৃত্যু-নির্ধারক, দুই উইল (RDB আলোকচিত্র, AOF খাতা) আর SLOWLOG থেকে ক্লায়েন্ট-ট্র্যাকিং পর্যন্ত মহড়া-যন্ত্র। আর ক্যাপস্টোন-ট্রাইব্যুনাল শহর বন্ধ করে: একটি লেখা সমন-পাঠানো ব্রাউজার থেকে ডিস্ক পর্যন্ত, প্রতি জেলার মতবাদ এক বারে বসানো, পুরো যন্ত্র প্রত্যয়িত এক চালানরূপে। নয়টি পাঠ, একটি ট্রাইব্যুনাল, শূন্য জাদুকরী “Redis বসিয়ে দাও।”',
  },
  lessons: [residenceLesson, invalidationLesson, theTowerOfLayersLesson, theMissClerksLesson, theEvictionCourtLesson, theStampedeWallLesson, theRedisDistrictLesson, theReplicationAccordsLesson, theCapstoneTribunalLesson],
  references: [
    {
      group: { en: 'The residence court', bn: 'বসবাস-আদালত' },
      items: [
        { term: 'the three clauses', def: { en: 'presence (in the vault), proximity (near the door), freshness (still true). Eviction buys 1–2; invalidation owns 3.', bn: 'উপস্থিতি (তিজোরিতে), নৈকট্য (দুয়ার-কাছে), সতেজতা (এখনো সত্য)। বহিষ্কার কেনে ১–২; অকার্যকরণ মালিক ৩-এর।' } },
        { term: 'hit-rate pricing', def: { en: 'avg ≈ h×1ms + (1−h)×101ms. 90% → 11ms & 1,000 fetches/s at 10K rps; 99% → 2ms & 100 fetches/s. Each nine is bought twice.', bn: 'গড় ≈ h×1ms + (1−h)×101ms। ৯০% → 11ms ও 10K rps-এ 1,000 আনয়ন/সে; ৯৯% → 2ms ও 100। প্রতি নাইন কেনা দুইবার।' } },
        { term: 'LRU machinery', def: { en: 'hash-map × doubly-linked list, all O(1); production approximates (Redis samples N, evicts idlest of sample; CLOCK: one bit + sweeping hand).', bn: 'হ্যাশ-ম্যাপ × দ্বি-লিঙ্কযুক্ত তালিকা, সব O(1); উৎপাদন আনুমানিক (Redis নমুনা N, নমুনার অলসতম বহিষ্কৃত; CLOCK: এক বিট + ঘূর্ণায়মান হাত)।' } },
        { term: "Belady’s anomaly", def: { en: 'FIFO, 1 2 3 4 1 2 5 1 2 3 4 5: 3 seats → 9 faults, 4 seats → 10. Arrival order is not knowledge; stack laws (LRU) are immune.', bn: 'FIFO, 1 2 3 4 1 2 5 1 2 3 4 5: ৩ আসন → ৯ ভুল, ৪ আসন → ১০। আগমন-ক্রম জ্ঞান নয়; স্ট্যাক-বিধান (LRU) অনাক্রম্য।' } },
        { term: 'scan-resistance treaties', def: { en: '2Q, ARC, SIEVE, TinyLFU admission windows — sequential scans wipe LRU; frequency/probation is the antidote lineage.', bn: '2Q, ARC, SIEVE, TinyLFU ভর্তি-জানালা — ধারাবাহিক-স্ক্যান LRU মুছে দেয়; পুনরাবৃত্তি/শর্তাধীনতা-ই প্রতিশোধ-বংশ।' } },
        { term: 'the tribunal trace (this hub)', def: { en: 'A B C A D E A B C D E on 3 seats → LRU 2h/9m final E D C · FIFO 1h/10m · LFU 2h/9m final E×1 D×1 A×3 · TTL 2h/9m, 5 reclaims, 1 execution (A@10).', bn: 'A B C A D E A B C D E, ৩ আসনে → LRU 2h/9m শেষ E D C · FIFO 1h/10m · LFU 2h/9m শেষ E×1 D×1 A×3 · TTL 2h/9m, ৫ কবর-ঝাড়ু, ১ মৃত্যুদণ্ড (A@10)।' } },
      ],
    },
    {
      group: { en: 'The invalidation court', bn: 'অকার্যকরণ-আদালত' },
      items: [
        { term: 'four instruments', def: { en: 'lease (TTL from staleness budget) · warrant (delete on write) · version (never reuse a name) · plea (stale-while-revalidate).', bn: 'লিজ (বাসি-বাজেট-জাত TTL) · পরোয়ানা (লেখায় মোছা) · সংস্করণ (নাম কখনো পুনব্যবহার নয়) · মিনতি (স্টেল-হোয়াইল-রিভ্যালিডেট)।' } },
        { term: 'key anatomy', def: { en: 'scope:tenant:subject:resource:variant — name every dimension the answer varies along, or serve a stranger’s portrait.', bn: 'scope:tenant:subject:resource:variant — উত্তর যে যে মাত্রায় বদলায় সব নামাও, নইলে পরের প্রতিকৃতি পরিবেশন করো।' } },
        { term: 'jitter', def: { en: 'TTL = base × (1 ± 0.1). Synchronized births are a design smell: one birth date + one lease constant = one scheduled funeral.', bn: 'TTL = base × (1 ± 0.1)। সমলয়ী জন্ম নকশা-দুর্গন্ধ: এক জন্মতারিখ + এক লিজ-ধ্রুবক = এক তফসিলি জানাজা।' } },
        { term: 'dogpile price', def: { en: 'One death books rate×latency errands: 5,000 rps × 8 ms ≈ 40 concurrent fetches for ONE key — coalescing makes it 1.', bn: 'এক মৃত্যু বুক করে হার×লেটেন্সি দৌড়: 5,000 rps × 8 ms ≈ এক কী-তে ৪০ সমবর্তী আনয়ন — কুণ্ডলীপন তা করে ১।' } },
        { term: 'write treaties', def: { en: 'through (never a lie; both fares) · behind (tsunami absorber; unflushed-truth funeral) · aside+DEL (one cold miss per write) · around (scan-proof; first read always misses).', bn: 'থ্রু (কখনো মিথ্যা নয়; দুই ভাড়া) · বিহাইন্ড (সুনামি-শোষক; অপঠেলা-সত্য-জানাজা) · অ্যাসাইড+DEL (লেখাপ্রতি এক শীতল-মিস) · অ্যারাউন্ড (স্ক্যান-প্রমাণ; প্রথম পাঠ সদা মিস)।' } },
        { term: 'stale-while-revalidate', def: { en: 'Serveable-but-suspect at ~80% of lease; one usher rebuilds, everyone else reads. RFC 5861; React Query staleTime; Go singleflight.', bn: 'লিজের ~৮০%-এ পরিবেশনযোগ্য-কিন্তু-সন্দেহজনক; এক উষের নির্মাণ করে, বাকিরা পড়ে। RFC 5861; React Query staleTime; Go singleflight।' } },
      ],
    },
  ],
  roadmap: [
    { stage: 1, title: { en: 'The vow & the currency', bn: 'শপথ ও মুদ্রা' }, detail: { en: 'Cache-aside ceremony; hit rate priced as tail-latency AND origin headroom; the three clauses audited out loud.', bn: 'ক্যাশ-অ্যাসাইড অনুষ্ঠান; হিট-রেট মূল্যায়িত টেইল-লেটেন্সি ও অরিজিন-হেডরুমরূপে; তিন ধারা জোরে নিরীক্ষিত।' } },
    { stage: 2, title: { en: 'Four laws, one trace', bn: 'চার বিধান, এক ট্রেস' }, detail: { en: 'LRU/FIFO/LFU/TTL personalities; O(1) machinery under the robes; Belady pinned; scan-resistance lineage named.', bn: 'LRU/FIFO/LFU/TTL ব্যক্তিত্ব; পোশাকতলে O(1) যন্ত্রপাতি; Belady পিণ্ডকৃত; স্ক্যান-প্রতিরোধী বংশ নামকৃত।' } },
    { stage: 3, title: { en: 'Key anatomy & ghosts', bn: 'কী-বিন্যাস ও ভূত' }, detail: { en: 'scope:tenant:subject:resource:variant enforced; cross-read banned structurally; never fix a lying key with a shorter TTL.', bn: 'scope:tenant:subject:resource:variant জোরকৃত; কাঠামোগত ক্রস-রিড-নিষেধ; মিথ্যাবাদী কী কখনো ছোট TTL দিয়ে ঠিক নয়।' } },
    { stage: 4, title: { en: 'Four instruments & the stampede', bn: 'চার অস্ত্র ও স্ট্যাম্পিড' }, detail: { en: 'Staleness budget → TTL; jitter the births; coalesce the re-fetches; version the names; ushers revalidate early.', bn: 'বাসি-বাজেট → TTL; জন্মে জিটার; পুনঃআনয়নে কুণ্ডলীপন; নামে সংস্করণ; উষেরেরা আগে রিভ্যালিডেট করে।' } },
  ],
  projects: [
    {
      title: { en: 'TribunalBench: law vs trace harness', bn: 'ট্রাইব্যুনালবেঞ্চ: বিধান-বনাম-ট্রেস হার্নেস' },
      brief: { en: 'Reimplement all four laws behind one Vault interface and replay five reference strings: the hub’s eleven, the Belady string, a loop (1 2 3 4 5 × 4), a scan (1..100 once then hot 7 repeated), and a Zipf stream. Produce a verdict table per (law × trace): hits, evictions, final vault. The harness must flag Belady automatically (faults increase when you raise capacity) and must render the TTL undertaker’s grave roll per reference.', bn: 'চার বিধানই পুনর্নির্মাণ করুন একটি Vault-ইন্টারফেসের পেছনে আর পাঁচটি রেফারেন্স-স্ট্রিং চালান: হাবের এগারোটি, Belady-স্ট্রিং, একটি লুপ (1 2 3 4 5 × 4), একটি স্ক্যান (1..100 একবার তারপে গরম 7 বারবার), আর একটি Zipf-ধারা। প্রতি (বিধান × ট্রেস)-এ রায়-সারণি দিন: হিট, বহিষ্কার, শেষ তিজোরি। হার্নেসকে Belady স্বয়ংক্রিয় চিহ্নিত করতে হবে (ধারণক্ষমতা বাড়ালে ভুল বাড়ে) আর TTL-কবরখেকোর কবর-তালিকা রেফারেন্সপ্রতি দেখাতে হবে।' },
      difficulty: 'beginner',
    },
    {
      title: { en: 'GhostHunter: the key-anatomy linter', bn: 'গোস্টহান্টার: কী-বিন্যাস লিন্টার' },
      brief: { en: 'Write a static analyzer that walks an Express/Hono codebase, finds every redis.set/cache-write, and scores the key template against the anatomy: does it name scope? tenant? subject? variant? Any cache of a per-user response whose key names fewer dimensions than the response varies over is flagged with the exact ghost-dashboard narrative. Ship a fixture suite: five guilty routes, five innocent; the linter must convict precisely the guilty five.', bn: 'একটি স্ট্যাটিক-অ্যানালাইজার লিখুন যা Express/Hono কোডবেস হেঁটে প্রতি redis.set/ক্যাশ-লেখা খুঁজে বের করে আর কী-টেমপ্লেটকে বিন্যাসের বিপরীতে স্কোর করে: সুযোগ নামায় কি? ভাড়াটিয়া? কর্তা? ভ্যারিয়েন্ট? যে-কোনো ব্যবহারকারীভিত্তিক-প্রতিক্রিয়ার ক্যাশ, যার কী কম মাত্রা নামায় প্রতিক্রিয়া-বৈচিত্র্যের চেয়ে, হবে পতাকাঙ্কিত হুবহু ভূত-ড্যাশবোর্ড বর্ণনায়। ফিক্সচার-স্যুট দিন: পাঁচ দোষী রুট, পাঁচ নির্দোষ; লিন্টারকে অবশ্যই হুবহু দোষী পাঁচকে দোষী সাব্যস্ত করতে হবে।' },
      difficulty: 'intermediate',
    },
    {
      title: { en: 'StampedeLab: the midnight rehearsal', bn: 'স্ট্যাম্পিডল্যাব: মধ্যরাত-মহড়া' },
      brief: { en: 'On a local rig (one SQLite homeland with a tuned 10 ms sleep, one in-process vault), script the stampede: fill 10K keys with one TTL at t0, then replay 50 rps/key. Measure homeland QPS across the funeral second for four configs: raw; +jitter(10%); +coalescing; +jitter&coalescing. Then add the warm sidecar for the top 1% keys and publish the four QPS curves’ peaks — the delta between curve 1 and curve 4, with units, is your thesis defense.', bn: 'স্থানীয় রিগে (সুরকৃত 10 ms ঘুমযুক্ত একটি SQLite জায়রবাড়ি, একটি ইন-প্রসেস তিজোরি) স্ট্যাম্পিড স্ক্রিপ্ট করুন: t0-তে এক TTL দিয়ে 10,000 কী ভরুন, তারপর 50 rps/কী পুনঃচালান। চার কনফিগে জানাজা-সেকেন্ডজুড়ে জায়রবাড়ি-QPS মাপুন: কাঁচা; +জিটার(10%); +কুণ্ডলীপন; +জিটার&কুণ্ডলীপন। তারপর শীর্ষ ১% কী-তে উষ্ণ-পার্শ্ববর্তী জুড়ে চারটি QPS-বক্রের শিখর ছাপান — একক-সহ ১ নম্বর ও ৪ নম্বর বক্রের ব্যবধানই আপনার থিসিস-প্রতিরক্ষা।' },
      difficulty: 'advanced',
    },
  ],
  bestPractices: [
    { en: 'Price every cache on its hit rate first, not its existence. A vault under its own tollbooth tax is decommissioned, not celebrated.', bn: 'প্রতি ক্যাশ মূল্যায়ন করুন আগে হিট-রেটে, অস্তিত্বে নয়। নিজের টোলবুথ-করের নিচের তিজোরি উদ্‌যাপিত নয়, অবসরপ্রাপ্ত।' },
    { en: 'Choose the eviction law for the workload, and say the choice aloud: recency for sessions and feeds, frequency for stable catalogs, deadline for truth leases.', bn: 'কাজের-ভার অনুযায়ী বহিষ্কার-বিধান বাছুন, আর বাছাইটা জোরে বলুন: সেশন আর ফিডে সতেজতা, স্থির-ক্যাটালগে পুনরাবৃত্তি, সত্য-লিজে মেয়াদ।' },
    { en: 'Keys are primary keys: scope:tenant:subject:resource:variant. Any personal answer under a URL-only key is a confidentiality incident rehearsing.', bn: 'কী হলো প্রাইমারি-কী: scope:tenant:subject:resource:variant। কেবল-URL কী-এর নিচের যে-কোনো ব্যক্তিগত উত্তর মহড়ারত গোপনীয়তা-ঘটনা।' },
    { en: 'Every TTL gets jitter at seating; every fleet-wide fill gets it double. Synchronized births are the only cache smell you can schedule to the second.', bn: 'প্রতি TTL পায় জিটার বসানোর সময়; প্রতি বহরজুড়ে-ভর্তি দ্বিগুণ। সমলয়ী জন্ম একমাত্র ক্যাশ-দুর্গন্ধ যা সেকেন্ডপর্যন্ত তফসিল করা যায়।' },
    { en: 'Coalesce every re-fetch: one death, one errand, the fleet waits on the usher. The inflight map is the cheapest 40× in engineering.', bn: 'প্রতি পুনঃআনয়ন কুণ্ডলী করুন: এক মৃত্যু, এক দৌড়, বহর অপেক্ষা করে উষেরের জন্য। ইনফ্লাইট-ম্যাপ প্রকৌশলের সবচেয়ে সস্তা ৪০×।' },
    { en: 'Version names that must never lie; cache content hashes forever; and never “fix” a lying cache by shortening the TTL — that is renting safety.', bn: 'সংস্করণ করুন সেই নাম যা কখনো মিথ্যা বলা চলে না; কনটেন্ট-হ্যাশ ক্যাশ করুন চিরকাল; আর মিথ্যা-ক্যাশ কখনো TTL ছোট করে “ঠিক” করবেন না — সেটা নিরাপত্তা ভাড়া।' },
  ],
  interview: [
    {
      q: { en: 'Design the caching layer for a product feed at 50K rps. Ask me three questions before you answer.', bn: '50K rps-এর প্রোডাক্ট-ফিডের জন্য ক্যাশিং-স্তর নকশা করুন। উত্তরের আগে আমাকে তিন প্রশ্ন করুন।' },
      a: { en: 'The three questions ARE the answer’s shape: (1) What is the staleness budget per field? — price and inventory rent seconds, badges rent minutes, images rent forever-as-hash. (2) What is the read:write ratio and working-set size? — it prices the tier and chooses the law: recency for the feed, frequency with decay for the catalog, TTL as truth-floor everywhere. (3) Which writes exist and where do they land? — it chooses the warrant discipline: versioned keys per product so edits rename truth, delete-on-write as the workhorse, and coalesced refills with jitter so sale-midnight death-spikes cost one errand each. After the questions, the design is mostly arithmetic: hot-slice memory estimate, hit-rate target named (99% ⇒ origin sees 500 rps), and the named failure rehearsed: cache primary dies → standby, coalesced cold-fill, jitter smeared repopulation.', bn: 'তিন প্রশ্নই উত্তরের আকৃতি: (1) ক্ষেত্রপ্রতি বাসি-বাজেট কত? — দাম ও ইনভেন্টরি ভাড়া দেয় সেকেন্ড, ব্যাজ মিনিট, ছবি চিরকাল-হ্যাশরূপে। (2) পাঠ:লেখা অনুপাত আর ওয়ার্কিং-সেট-মাপ কত? — তা স্তরের দাম দেয় আর বিধান বাছে: ফিডে সতেজতা, ক্যাটালগে ক্ষয়যুক্ত-পুনরাবৃত্তি, সর্বত্র সত্য-মেঝেরূপে TTL। (3) কোন লেখাগুলো আছে আর কোথায় পড়ে? — তা পরোয়ানা-শৃঙ্খলা বাছে: প্রোডাক্টপ্রতি সংস্করণকৃত কী, যাতে সম্পাদনা সত্যের নামান্তর করে, ভারতুর্যাসরূপে লেখায়-মোছা, আর কুণ্ডলিত পুনঃভর্তি জিটারসহ, যাতে সেল-মধ্যরাত মৃত্যু-স্পাইক খরচ করে প্রতি একটি দৌড়। প্রশ্নগুলোর পর নকশা মূলত পাটিগণিত: গরম-অংশ-স্মৃতি-অনুমান, নামকৃত হিট-রেট-লক্ষ্য (99% ⇒ অরিজিন দেখে 500 rps), আর নামকৃত ব্যর্থতা মহড়াকৃত: ক্যাশ-প্রাইমারি মরে → স্ট্যান্ডবাই, কুণ্ডলিত শীতল-ভর্তি, জিটার-ছড়ানো পুনর্বাসন।' },
    },
    {
      q: { en: 'LRU or LFU for a general-purpose cache? Defend the choice like an exam.', bn: 'সাধারণ-উদ্দেশ্য ক্যাশে LRU নাকি LFU? পরীক্ষার মতো বাছাই রক্ষা করুন।' },
      a: { en: 'Default to approximated LRU and defend the DEFAULT, not the dogma. LRU wins generality: O(1) true and sampled, bounded metadata, immune to Belady, and its failure class — scans — is visible and understandable. LFU wins where popularity is stable (catalogs, dictionaries) and loses catastrophically to fashion drift unless its counters decay, which is why production LFU is always decayed LFU. The exam-shaped sentence: “I pick LRU with scan-proofing (SIEVE-style probation or a TinyLFU admission filter) before I reach for raw LFU, because the admission window buys frequency’s scan-immunity without frequency’s immortal-celebrity bug” — and then the counter-question about YOUR workload’s churn, because the clerk who cannot name the workload’s trace has not earned the choice either.', bn: 'ডিফল্ট আনুমানিক LRU, আর রক্ষা করুন ডিফল্টটাকে, মতাদর্শ নয়। LRU জেতে সাধারণতায়: O(1) খাঁটি ও নমুনাকৃত, সীমিত মেটাডেটা, Belady-অনাক্রম্য, আর তার ব্যর্থতা-শ্রেণি — স্ক্যান — দৃশ্যমান ও বোধগম্য। LFU জেতে স্থির-জনপ্রিয়তায় (ক্যাটালগ, অভিধান) আর হারে বিপর্যয়ে ফ্যাশন-প্রবাহে, গণনা-ক্ষয় ছাড়া, এই কারণেই উৎপাদন-LFU সবসময় ক্ষয়কারী LFU। পরীক্ষা-আকৃতির বাক্য: “আমি বাছি LRU স্ক্যান-প্রতিরোধসহ (SIEVE-শৈলী শর্তাধীনতা বা TinyLFU ভর্তি-ছাঁকনি), কাঁচা LFU-এর আগে, কারণ ভর্তি-জানালা কিনে দেয় পুনরাবৃত্তির স্ক্যান-অনাক্রম্যতা, পুনরাবৃত্তির অমর-তারকা-বাগ ছাড়াই” — আর তারপর পাল্টা-প্রশ্ন আপনার কাজের-ভারের প্রবাহ নিয়ে, কারণ যে কেরানি কাজের-ভারের ট্রেস নামাতে পারে না, সে বাছাইয়ের অধিকারও উপার্জন করেনি।' },
    },
    {
      q: { en: 'Your cache hit rate is 99.9% and users still report stale data. Where do you look FIRST?', bn: 'আপনার ক্যাশ-হিট-রেট ৯৯.৯%, তবু ব্যবহারকারীরা বাসি-ডেটার অভিযোগ করে। প্রথমে কোথায় দেখবেন?' },
      a: { en: 'The number is a decoy — hit rate measures presence and proximity, never freshness; the stale complaint lives in the third clause. First look: the WRITE PATH audit — enumerate every mutation of the truth and grep each for its warrant (DEL/bump). Nine times out of ten the discipline failure is a writer that bypassed the cache ceremony: a migration script, an admin console, a batch job — the warrant is only as complete as the write paths you audited. Second look: key anatomy — does anything resolve to too few dimensions? (the ghost-dashboard class: presence correct, subject wrong). Third: the lease table — any sliding TTL on a mirror of mutable data? any zero-jitter fleet-wide fill making stale data appear in synchronized waves that users notice as “everyone sees it”? The hit-rate dashboard is shown LAST, and only to prove it was never evidence.', bn: 'সংখ্যাটি প্রতারক — হিট-রেট মাপে উপস্থিতি ও নৈকট্য, সতেজতা কখনোই না; বাসি-অভিযোগ বাস করে তৃতীয় ধারায়। প্রথম দৃষ্টি: লেখা-পথ-নিরীক্ষণ — সত্যের প্রতিটি পরিব্যক্তি তালিকাভুক্ত করুন আর প্রতিটিতে তার পরোয়ানা খুঁজুন (DEL/উত্তোলন)। দশের মধ্যে নয়বার শৃঙ্খলা-ব্যর্থতা এমন লেখক যা ক্যাশ-অনুষ্ঠান পাশ কাটায়: মাইগ্রেশন-স্ক্রিপ্ট, অ্যাডমিন-কনসোল, ব্যাচ-জব — পরোয়ানা যতটুকু সম্পূর্ণ যতটুকু লেখা-পথ আপনি অডিট করেছেন। দ্বিতীয় দৃষ্টি: কী-বিন্যাস — কিছু কি খুব কম মাত্রায় সমাধান হয়? (ভূত-ড্যাশবোর্ড-শ্রেণি: উপস্থিতি সঠিক, কর্তা ভুল)। তৃতীয়: লিজ-তালিকা — পরিবর্তনশীল-ডেটার আয়নায় কোনো স্লাইডিং TTL আছে? শূন্য-জিটারের বহরজুড়ে-ভর্তি কি বাসি-ডেটা সমলয়ী-ঢেউয়ে ফেলছে, যা ব্যবহারকারীরা লক্ষ্য করে “সবাই দেখছে” আকারে? হিট-রেট-ড্যাশবোর্ড দেখানো হয় সবশেষে, আর তাও কেবল প্রমাণে যে তা কখনোই প্রমাণ ছিল না।' },
    },
    {
      q: { en: 'CTO: “Just cache everything for 24 hours, memory is cheap.” Respond with the two courts.', bn: 'সিটিও: “সবকিছু ২৪ ঘণ্টা ধরে ক্যাশ করো, মেমরি সস্তা।” দুই আদালত দিয়ে জবাব দিন।' },
      a: { en: 'The residence court says memory is where the cheapness claim dies: the working set decides eviction pressure, and a 24-hour blanket TTL converts every cold byte into a resident the hot working set must evict — hit rate falls, and a falling hit rate is a cache that taxes the origin MORE while pretending to shield it. The invalidation court says the 24-hour figure was not priced from any staleness budget: the revoked ban, the price change, the corrected name all rent 24 hours of fiction. And the fleet doctrine completes the reply: one TTL constant times one deploy time is one scheduled mass funeral at tomorrow-ditto — the midnight stampede with extra steps. The counter-proposal in their own vocabulary: price the staleness budget per field, version the assets that never truly change and cache THEM forever, TTL the mutable mirrors per budget with jitter, and let the eviction tribunal — not a blanket lease — decide who lives near the door.', bn: 'বসবাস-আদালত বলে সস্তার দাবি মরে মেমরিতেই: ওয়ার্কিং-সেটই বহিষ্কার-চাপ নির্ধারণ করে, আর ২৪-ঘণ্টার কম্বল-TTL প্রতি শীতল-বাইটকে বাসিন্দা বানায়, যাকে উচ্ছেদ করতে হয় গরম-ওয়ার্কিং-সেটকে বলে — হিট-রেট পড়ে, আর পড়ন্ত হিট-রেট এমন ক্যাশ যা অরিজিনকে বেশি কর ধরে, ঢালের ভান করে। অকার্যকরণ-আদালত বলে ২৪-ঘণ্টা সংখ্যা কোনো বাসি-বাজেট থেকে মূল্যায়িত নয়: বাতিলকৃত-ব্যান, দাম-পরিবর্তন, সংশোধিত নাম — সবাই ভাড়া পেল ২৪ ঘণ্টার কল্পনা। আর বহর-মতবাদ জবাব পূর্ণ করে: এক TTL-ধ্রুবক গুণ এক ডিপ্লয়-কাল সমান আগামীকাল-একইসময়ের এক তফসিলি গণ-জানাজা — মধ্যরাত-স্ট্যাম্পিড, অতিরিক্ত-পদক্ষেপসহ। তাদেরই শব্দভাণ্ডারে পাল্টা-প্রস্তাব: ক্ষেত্রপ্রতি বাসি-বাজেট মূল্যায়ন করুন, সেই সম্পদ সংস্করণ করুন যা সত্যিই বদলায় না আর ক্যাশ করুন সেগুলো চিরকাল, পরিবর্তনশীল-আয়নাগুলো TTL দিন বাজেটমতো জিটারসহ, আর দুয়ারের কাছে কে বাস করবে তা ঠিক করতে দিন বহিষ্কার-ট্রাইব্যুনালকে — কম্বল-লিজকে নয়।' },
    },
  ],
  realWorld: [
    { en: 'API & service layers: cache-aside + versioned keys + coalesced refills is the default production trinity; the stampedes you rehearse here are the pages you will not receive.', bn: 'API ও সার্ভিস-স্তর: ক্যাশ-অ্যাসাইড + সংস্করণকৃত কী + কুণ্ডলিত পুনঃভর্তি হলো ডিফল্ট উৎপাদন-ত্রয়ী; আপনার-মহড়াকৃত স্ট্যাম্পিডগুলো-ই সেই পেজ যা পাবেন না।' },
    { en: 'Front-end & CDN: Cache-Control, ETag, SWR, content-hashed bundles — the invalidation court’s four instruments wearing HTTP costume.', bn: 'ফ্রন্টএন্ড ও CDN: Cache-Control, ETag, SWR, কনটেন্ট-হ্যাশকৃত বান্ডিল — HTTP-পোশাকে অকার্যকরণ-আদালতের চার অস্ত্র।' },
    { en: 'Data systems: buffer-pool midpoint-LRU, materialized-view refresh crons, search-index rebuilds — derived-truth systems are this hub’s doctrines at larger addresses.', bn: 'ডেটা-সিস্টেম: বাফার-পুল মিডপয়েন্ট-LRU, ম্যাটেরিয়ালাইজড-ভিউ রিফ্রেশ-cron, সার্চ-ইনডেক্স-রিবিল্ড — উদ্ভূদ্ধ-সত্য-সিস্টেম হলো বড় ঠিকানায় এই হাবের মতবাদ।' },
    { en: 'Mobile & offline: local-first stores are vaults with week-long leases; sync protocols are warrant-and-version litigation refined into protocols.', bn: 'মোবাইল ও অফলাইন: লোকাল-ফার্স্ট-স্টোর হলো সপ্তাহ-লিজের তিজোরি; সিঙ্ক-প্রোটোকল হলো পরোয়ানা-ও-সংস্করণ মামলা, প্রোটোকলে পরিশীলিত।' },
  ],
};
