/**
 * Build a per-hub fix list from the readability report, so the rewrite queue carries the actual
 * sentences instead of a score:  node tools/audit/make-fixlist.mjs [count]
 * Writes tools/audit/FIXLIST/<hub>.tsv for the worst `count` hubs (default 20).
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('../..', import.meta.url).pathname;
const OUT = join(ROOT, 'tools/audit/FIXLIST');
mkdirSync(OUT, { recursive: true });

const raw = execFileSync('bash', [join(ROOT, 'tools/audit/read-report.sh')], { cwd: ROOT, maxBuffer: 1 << 28, encoding: 'utf8' });
const lines = raw.split('\n').filter((l) => l.trim() && !l.startsWith('==') && !l.startsWith('\n'));

const byHub = new Map();
for (const l of lines) {
  const [where, ...rest] = l.split('\t');
  const hub = where.startsWith('HUB ') ? where.slice(4).trim() : where.split('/')[0];
  if (!hub) continue;
  if (!byHub.has(hub)) byHub.set(hub, []);
  byHub.get(hub).push(rest.join('\t'));
}

const ranked = [...byHub.entries()].sort((a, b) => b[1].length - a[1].length);
const n = Number(process.argv[2] || 20);
const index = [];
for (const [hub, rows] of ranked.slice(0, n)) {
  const file = join(OUT, `${hub}.tsv`);
  writeFileSync(file, `# ${hub}: ${rows.length} readability findings — fix in src/content/_specs/${hub}.mjs, then\n` +
    `#   node tools/reauthor.mjs ${hub} && GATE_DETAIL=6 bash tools/audit/run.sh ${hub}\n` +
    `# hub-level notes first, then one line per lesson finding.\n` + rows.join('\n') + '\n');
  index.push([hub, rows.length]);
}
const total = ranked.reduce((s, [, r]) => s + r.length, 0);
writeFileSync(join(OUT, 'README.md'),
  `# Per-hub fix lists\n\nGenerated by \`node tools/audit/make-fixlist.mjs 20\` on 2026-09-26.\n\n` +
  `The report lists ${total.toLocaleString('en')} lines across ${ranked.length} hubs — one line per quote. The gate\n` +
  `counts one issue per rule per lesson, so its number is smaller: 2,388 readability findings, part of the 10,545\n` +
  `lesson issues in the 2026-09-26 census (see ../audit/CENSUS.md). ` +
  `These files hold the top ${Math.min(n, ranked.length)} hubs by count — the ones where a beginner stops reading.\n\n` +
  `Each line is \`<where>\\t<rule>\\t<quote>\`, hub-level notes first. Quotes are the actual text on the page, so the\n` +
  `fix is written against a sentence rather than a score.\n\n` +
  `| hub | findings |\n|---|---|\n` + index.map(([h, c]) => `| \`${h}\` | ${c} |`).join('\n') + '\n\n' +
  `Do not edit \`src/content/<hub>/lessons/*.ts\` directly — those are rendered output.\n` +
  `A hub with no \`_specs/<hub>.mjs\` needs one written (see tools/audit/CENSUS.md, step list).\n`);
console.log(`wrote ${index.length} fix lists into tools/audit/FIXLIST/, site total ${total}`);
