import type { Lesson } from '../../../lib/types';

export const federationCourtLesson: Lesson = {
  slug: 'the-federation-court',
  tech: 'graphql',
  title: {
    en: 'Apollo Federation & Subgraphs — Gateway Routers, Entity Keys & Distributed Graphs',
    bn: 'অ্যাপোলো ফেডারেশন ও সাবগ্রাফ — গেটওয়ে রাউটার, এনটিটি কি ও ডিস্ট্রিবিউটেড গ্রাফ'
  },
  summary: {
    en: 'Scaling a GraphQL architecture across multiple backend engineering teams requires breaking down monolithic servers without sacrificing a unified client-facing schema. Apollo Federation solves this by partitioning the global graph into autonomous subgraphs owned by domain-specific microservices. Using declarative directives like @key, @shareable, and @override, subgraphs specify how shared entities are identified and extended. An Apollo Router or Gateway inspects incoming client operations, compiles an optimized Query Plan directed acyclic graph (DAG), batches entity resolution requests via _entities representations, and merges disparate service responses into a single coherent GraphQL result.',
    bn: 'একাধিক ব্যাকএন্ড ইঞ্জিনিয়ারিং দলের মাঝে GraphQL আর্কিটেকচার স্কেল করার জন্য ক্লায়েন্টের সমন্বিত স্কিমা অক্ষুণ্ণ রেখেই মনোলিথিক সার্ভারকে বিভক্ত করা প্রয়োজন। অ্যাপোলো ফেডারেশন ডোমেন-নির্দিষ্ট মাইক্রোসার্ভিসের অধীনে পুরো গ্রাফকে স্বাধীন সাবগ্রাফে ভাগ করে এই সমাধান প্রদান করে। @key, @shareable এবং @override নির্দেশক ব্যবহারের মাধ্যমে সাবগ্রাফগুলো বলে দেয় কীভাবে শেয়ার্ড এনটিটিগুলো শনাক্ত ও পরিবর্ধন করা হবে। অ্যাপোলো রাউটার বা গেটওয়ে ক্লায়েন্ট কোয়েরি বিশ্লেষণ করে অপ্টিমাইজড কোয়েরি প্ল্যান তৈরি করে, _entities-এর মাধ্যমে ব্যাচ রিকোয়েস্ট পাঠিয়ে বিভিন্ন মাইক্রোসার্ভিসের তথ্য মিলিয়ে একক ফলাফল ফেরত পাঠায়।'
  },
  minutes: 35,
  blocks: [
    {
      type: 'heading',
      id: 'opener',
      text: {
        en: 'Core Concepts: Distributed Subgraphs and the Supergraph',
        bn: 'মূল ধারণা: ডিস্ট্রিবিউটেড সাবগ্রাফ ও সুপারগ্রাফ'
      }
    },
    {
      type: 'visual',
      id: 'dist-mesh'
    },
    {
      type: 'para',
      text: {
        en: 'When you scale an engineering organization across multiple autonomous developer teams, managing a single monolithic GraphQL schema creates development bottlenecks and deployment friction. Apollo Federation solves this by decomposing a large unified schema into independent domain subgraphs owned by separate engineering teams. A high-performance gateway router automatically composes these subgraphs into a supergraph, executing query plans that seamlessly stitch data across distributed microservices into a single cohesive API.',
        bn: 'যখন কোনো সফটওয়্যার ইঞ্জিনিয়ারিং প্রতিষ্ঠানে একাধিক স্বতন্ত্র দল গড়ে ওঠে, তখন একটিমাত্র মনোলিথিক GraphQL স্কিমা পরিচালনা করা ডেভেলপমেন্টে স্থবিরতা তৈরি করে। অ্যাপোলো ফেডারেশন একটি বিশাল সমন্বিত স্কিমাকে বিভিন্ন ডোমেন দলের অধীনে স্বাধীন সাবগ্রাফে বিভক্ত করে এই সমস্যার চমৎকার সমাধান দেয়। একটি উচ্চগতির গেটওয়ে রাউটার এই সাবগ্রাফগুলোকে মিলিয়ে সুপারগ্রাফ গঠন করে এবং বিভিন্ন মাইক্রোসার্ভিস থেকে ডেটা এনে ক্লায়েন্টকে একটিমাত্র ঐক্যবদ্ধ এপিআই প্রদান করে।'
      }
    },
    {
      type: 'keyterms',
      items: [
        {
          term: 'Subgraph',
          def: {
            en: 'An independent GraphQL service that owns a specific slice of the overall schema and runs its own resolvers and databases',
            bn: 'একটি স্বাধীন GraphQL সার্ভিস যা সামগ্রিক স্কিমার নির্দিষ্ট অংশের মালিক এবং নিজস্ব রিসলভার ও ডেটাবেজ চালায়'
          }
        },
        {
          term: 'Supergraph (Gateway Router)',
          def: {
            en: 'The unified API gateway that composes all subgraph schemas together and routes incoming client queries using execution plans',
            bn: 'একীভূত এপিআই গেটওয়ে যা সমস্ত সাবগ্রাফ স্কিমাকে একত্রিত করে এবং কোয়েরি প্ল্যানের মাধ্যমে রিকোয়েস্ট রাউট করে'
          }
        },
        {
          term: '@key Directive',
          def: {
            en: 'A federation schema annotation that designates an entity primary identifier (such as id) allowing other subgraphs to reference it',
            bn: 'একটি ফেডারেশন নির্দেশক যা সত্তার মূল আইডেন্টিফায়ার (যেমন id) নির্ধারণ করে যাতে অন্য সাবগ্রাফ একে রেফারেন্স করতে পারে'
          }
        },
        {
          term: 'Query Plan DAG',
          def: {
            en: 'A directed acyclic graph generated by the gateway router dictating the sequence of parallel and sequential subgraph HTTP fetches',
            bn: 'গেটওয়ে রাউটার দ্বারা প্রস্তুত নির্দেশিত ডিরেক্টেড অ্যাসাইক্লিক গ্রাফ যা বিভিন্ন সাবগ্রাফে ডেটা চাওয়ার ক্রম নির্ধারণ করে'
          }
        }
      ]
    },
    {
      type: 'heading',
      id: 'entity-resolution',
      text: {
        en: 'Entity Keys and Cross-Service Entity Resolution',
        bn: 'এনটিটি কি ও আন্তঃসার্ভিস এনটিটি রেজোলিউশন'
      }
    },
    {
      type: 'para',
      text: {
        en: 'The core mechanism of Apollo Federation is the Entity. An entity is a GraphQL type that can be extended across multiple microservices. In the Products subgraph, Product is declared with @key(fields: "id"). The Products team owns fields like name and price.',
        bn: 'অ্যাপোলো ফেডারেশনের মূল চালিকাশক্তি হলো এনটিটি। এনটিটি হলো এমন একটি GraphQL টাইপ যা একাধিক মাইক্রোসার্ভিস জুড়ে পরিবর্ধন করা যায়। Products সাবগ্রাফে Product টাইপটি @key(fields: "id") দিয়ে ঘোষণা করা হয়। প্রোডাক্টস দল name এবং price ফিল্ডের দায়িত্বে থাকে।'
      }
    },
    {
      type: 'para',
      text: {
        en: 'In the customer feedback service, an independent squad extends the Product type with the same @key(fields: "id"), attaching a customerFeedback list. When a client queries items alongside ratings, the Router fetches products first. It then extracts the IDs as representations and batches an _entities call downstream to stitch the final object.',
        bn: 'কাস্টমার ফিডব্যাক সার্ভিসে আরেকটি দল একই @key(fields: "id") দিয়ে Product টাইপকে এক্সটেন্ড করে এবং ফিডব্যাক তালিকা যোগ করে। ক্লায়েন্ট পণ্যের নাম ও রেটিং চাইলে রাউটার প্রথমে পণ্য ডেটা আনে। এরপর আইডিগুলো সংগ্রহ করে ডাউনস্ট্রিম সার্ভিসে একটিমাত্র _entities ব্যাচ কল পাঠিয়ে ফলাফল জোড়া লাগায়।'
      }
    },
    {
      type: 'heading',
      id: 'query-planning',
      text: {
        en: 'The Query Planner: Decomposing Operations into Fetch Nodes',
        bn: 'কোয়েরি প্ল্যানার: অপারেশনকে বিভিন্ন ফেচ নোডে বিভাজন'
      }
    },
    {
      type: 'para',
      text: {
        en: 'When a client submits a GraphQL operation to the supergraph, the Apollo Router does not execute resolvers directly. Instead, it compiles the query into a Query Plan DAG. The router identifies which fields reside in which subgraphs and calculates dependencies between them.',
        bn: 'ক্লায়েন্ট যখন সুপারগ্রাফে কোনো কোয়েরি পাঠায়, তখন অ্যাপোলো রাউটার নিজে সরাসরি রিসলভার চালায় না। বরং এটি কোয়েরিটি বিশ্লেষণ করে একটি Query Plan DAG তৈরি করে। কোন ফিল্ড কোন সাবগ্রাফে আছে এবং তাদের পরস্পরের নির্ভরশীলতা কী তা রাউটার হিসাব করে নেয়।'
      }
    },
    {
      type: 'para',
      text: {
        en: 'Independent fetch nodes execute concurrently in parallel to minimize network latency. If a field in Subgraph B depends on an entity resolved in Subgraph A, the router sequences the execution, passing representation keys from Subgraph A into Subgraph B. The router compiles this plan once and caches it by operation hash.',
        bn: 'পরস্পর স্বাধীন ফেচ নোডগুলো সময় বাঁচাতে একযোগে সমান্তরালে বা প্যারালালে চলে। আর যদি সাবগ্রাফ বি-র কোনো ফিল্ড সাবগ্রাফ এ-র ডেটার ওপর নির্ভরশীল হয়, তবে রাউটার ক্রমানুসারে চালিয়ে এ-র কিগুলো বি-তে পাঠায়। এই কোয়েরি প্ল্যান একবার তৈরি করে রাউটার মেমোরিতে ক্যাশ করে রাখে।'
      }
    },
    {
      type: 'heading',
      id: 'fault-tolerance',
      text: {
        en: 'Fault Tolerance: Nullability at Subgraph Boundaries',
        bn: 'ফল্ট টলারেন্স: সাবগ্রাফ সীমান্তে নালেবিলিটি ব্যবস্থাপনা'
      }
    },
    {
      type: 'para',
      text: {
        en: 'In a microservice architecture, downstream services inevitably experience timeouts or outages. If a cross-subgraph relation is declared as non-nullable (e.g. reviews: [Review!]!), a failure in the Reviews subgraph triggers null-bubbling that wipes out the entire Product object, turning a partial outage into a total page failure.',
        bn: 'মাইক্রোসার্ভিস ব্যবস্থায় কোনো না কোনো সার্ভিস মাঝেমধ্যে ডাউন হতে পারে বা টাইমআউট হতে পারে। যদি দুই সাবগ্রাফের সংযোগকারী ফিল্ডটি নন-নালেবল করা থাকে (যেমন reviews: [Review!]!), তবে Reviews সার্ভিস ডাউন হলে নালেবিলিটি নিয়ম পুরো Product ডেটাকেই নাল করে দেবে, যার ফলে পুরো পেজ ক্র্যাশ করবে।'
      }
    },
    {
      type: 'para',
      text: {
        en: 'Production federation schemas enforce a boundary policy: cross-service relationship fields must be declared nullable (reviews: [Review]). When the Reviews subgraph is down, the router populates the errors array with service timeout diagnostics while successfully returning product details to the user.',
        bn: 'প্রোডাকশন ফেডারেশন স্কিমায় তাই একটি নিয়ম বাধ্যতামূলক করা হয়: সাবগ্রাফের সীমানা ফিল্ডগুলো সর্বদা নালেবল (reviews: [Review]) রাখতে হবে। ফলে Reviews সার্ভিস ডাউন থাকলেও রাউটার errors অ্যারেতে বার্তা পাঠিয়েও মূল পণ্যের নাম ও দাম ক্লায়েন্টকে সফলভাবে দেখিয়ে দিতে পারে।'
      }
    },
    {
      type: 'heading',
      id: 'comparison-table',
      text: {
        en: 'Architectural Comparison: GraphQL Scaling Strategies',
        bn: 'কাঠামোগত তুলনা: GraphQL স্কেলিং কৌশল'
      }
    },
    {
      type: 'table',
      head: [
        { en: 'Architecture Strategy', bn: 'স্থাপত্য কৌশল' },
        { en: 'Schema Ownership Model', bn: 'স্কিমা মালিকানা মডেল' },
        { en: 'Gateway Implementation', bn: 'গেটওয়ে বাস্তবায়ন' },
        { en: 'N+1 Across Services Risk', bn: 'আন্তঃসার্ভিস N+1 ঝুঁকি' }
      ],
      rows: [
        [
          { en: 'Apollo Federation 2', bn: 'অ্যাপোলো ফেডারেশন ২' },
          { en: 'Declarative entity ownership with @key and @shareable', bn: '@key ও @shareable দিয়ে ঘোষণামূলক স্বাধীন মালিকানা' },
          { en: 'Native Rust/Go router compiling compiled query DAGs', bn: 'নেটিভ রাউটার যা অপ্টিমাইজড কোয়েরি DAG সংকলন করে' },
          { en: 'Eliminated via automated representations batching', bn: 'স্বয়ংক্রিয় representations ব্যাচিংয়ের মাধ্যমে সমাধান' }
        ],
        [
          { en: 'Manual Schema Stitching', bn: 'ম্যানুয়াল স্কিমা স্টিচিং' },
          { en: 'Procedural runtime glue code maintained by gateway team', bn: 'গেটওয়ে টিমের হাতে লেখা জটিল রানটাইম আঠালো কোড' },
          { en: 'Custom JavaScript proxies with manual delegation', bn: 'ম্যানুয়াল ডেলিগেশন সম্বলিত কাস্টম জাভাস্ক্রিপ্ট প্রক্সি' },
          { en: 'High; developers must hand-roll DataLoader delegates', bn: 'উচ্চ; ডেভেলপারদের নিজ হাতে ডেটালোডার লিখতে হয়' }
        ],
        [
          { en: 'Monolithic Single Server', bn: 'মনোলিথিক একক সার্ভার' },
          { en: 'Single repository bottleneck for all engineering teams', bn: 'সমস্ত ইঞ্জিনিয়ারিং দলের জন্য একটিমাত্র কোড রিপোজিটরি' },
          { en: 'Direct execution of unified schema in single process', bn: 'একক প্রসেসের ভেতরে সমগ্র স্কিমার সরাসরি এক্সিকিউশন' },
          { en: 'Requires standard in-process DataLoader wrappers', bn: 'সাধারণ ইন-প্রসেস ডেটালোডার ব্যবহার করা আবশ্যক' }
        ]
      ]
    },
    {
      type: 'heading',
      id: 'simulation',
      text: {
        en: 'Practical Code Simulation: Federation Query Router & Entity Resolution',
        bn: 'বাস্তব কোড সিমুলেশন: ফেডারেশন কোয়েরি রাউটার ও এনটিটি সমাধান'
      }
    },
    {
      type: 'code',
      lang: 'typescript',
      code: `// Lightweight Simulation of Apollo Federation Router & Subgraph Entity Resolution in Node.js

// Subgraph 1: Products Service (Owns Product entity)
class ProductsSubgraph {
  private products = [
    { id: '101', name: 'Mechanical Keyboard', price: 120 },
    { id: '102', name: 'Ergonomic Mouse', price: 80 }
  ];

  getProducts() {
    return this.products;
  }
}

// Subgraph 2: Reviews Service (Extends Product entity with reviews field)
class ReviewsSubgraph {
  private reviews = [
    { productId: '101', comment: 'Super tactile switches', rating: 5 },
    { productId: '101', comment: 'Great build quality', rating: 4 },
    { productId: '102', comment: 'Fits palm comfortably', rating: 5 }
  ];

  // Resolves entities passed by the Router via representations array
  resolveEntities(representations: Array<{ __typename: string; id: string }>) {
    return representations.map(rep => {
      if (rep.__typename === 'Product') {
        const productReviews = this.reviews.filter(r => r.productId === rep.id);
        return {
          id: rep.id,
          reviews: productReviews
        };
      }
      return null;
    });
  }
}

// Apollo Gateway / Router: Decomposes query into execution plan and merges subgraphs
class FederationRouter {
  constructor(
    private productsSub: ProductsSubgraph,
    private reviewsSub: ReviewsSubgraph
  ) {}

  async executeQuery() {
    // Step 1: Query Products Subgraph
    const products = this.productsSub.getProducts();

    // Step 2: Build representations for boundary entity resolution
    const representations = products.map(p => ({
      __typename: 'Product',
      id: p.id
    }));

    // Step 3: Fetch extension fields from Reviews Subgraph via _entities batch call
    const entityExtensions = this.reviewsSub.resolveEntities(representations);

    // Step 4: Stitch and merge unified response
    const unifiedProducts = products.map(p => {
      const extension = entityExtensions.find(e => e && e.id === p.id);
      return {
        ...p,
        reviews: extension ? extension.reviews : []
      };
    });

    return { data: { products: unifiedProducts } };
  }
}

async function run() {
  const prodSub = new ProductsSubgraph();
  const revSub = new ReviewsSubgraph();
  const router = new FederationRouter(prodSub, revSub);

  const result = await router.executeQuery();
  const products = result.data.products;

  console.log('Total products stitched:', products.length);
  // -> Total products stitched: 2
  console.log('First product ID:', products[0].id);
  // -> First product ID: 101
  console.log('First product reviews count:', products[0].reviews.length);
  // -> First product reviews count: 2
  console.log('First product price:', products[0].price);
  // -> First product price: 120
  console.log('Second product reviews count:', products[1].reviews.length);
  // -> Second product reviews count: 1
}

run();`,
      caption: {
        en: 'Simulation: stitches 2 products; product 101 has 2 reviews with price 120; product 102 has 1 review',
        bn: 'সিমুলেশন: ২ টি পণ্য সংযুক্ত করে; পণ্য ১০১ এর দাম ১২০ ও রিভিউ ২ টি; পণ্য ১০২ এর রিভিউ ১ টি'
      }
    },
    {
      type: 'heading',
      id: 'best-practices',
      text: {
        en: 'Production Implementation Rules',
        bn: 'প্রোডাকশন বাস্তবায়নের গুরুত্বপূর্ণ নিয়ম'
      }
    },
    {
      type: 'para',
      text: {
        en: 'Rule 1: Always compose supergraph schemas in CI before deployment. Running rover subgraph check prevents broken composition and incompatible directive conflicts from ever reaching staging or production clusters.',
        bn: 'নিয়ম ১: ডিপ্লয় করার আগে সর্বদা সিআই পাইপলাইনে সুপারগ্রাফ কম্পোজিশন পরীক্ষা করুন। rover subgraph check চালালে স্কিমার অমিল বা ত্রুটিপূর্ণ কনফিগারেশন প্রোডাকশনে পৌঁছানোর আগেই ধরা পড়ে।'
      }
    },
    {
      type: 'para',
      text: {
        en: 'Rule 2: Declare cross-subgraph relationship fields as nullable. If a downstream microservice experiences downtime, a nullable seam allows the router to return partial data instead of triggering a total page crash.',
        bn: 'নিয়ম ২: সাবগ্রাফ সংযোগকারী ফিল্ডগুলো সর্বদা নালেবল রাখুন। কোনো মাইক্রোসার্ভিস ডাউন হলে নালেবল ফিল্ড থাকার কারণে পুরো পেজ ক্র্যাশ না করে আংশিক ডেটা দেখানো সম্ভব হয়।'
      }
    },
    {
      type: 'para',
      text: {
        en: 'Rule 3: Ensure entity resolvers implement representation batching. Resolving representations in bulk within the _entities query prevents microservice-level excessive network round-trip storms across downstream backends.',
        bn: 'নিয়ম ৩: এনটিটি রিসলভারে অবশ্যই রিপ্রেজেন্টেশন ব্যাচিং নিশ্চিত করুন। _entities কোয়েরিতে একসাথে একাধিক কি সমাধান করলে বিভিন্ন মাইক্রোসার্ভিসের মাঝে অপ্রয়োজনীয় নেটওয়ার্ক ট্রাফিকের বন্যা রোধ হয়।'
      }
    },
    {
      type: 'para',
      text: {
        en: 'Rule 4: Use @override for zero-downtime field migrations. When migrating ownership of a field from an older service to a new microservice, @override re-routes traffic incrementally without breaking existing clients.',
        bn: 'নিয়ম ৪: নিরবচ্ছিন্ন ফিল্ড মাইগ্রেশনের জন্য @override ব্যবহার করুন। পুরোনো সার্ভিস থেকে নতুন মাইক্রোসার্ভিসে কোনো ফিল্ডের দায়িত্ব সরানোর সময় @override ব্যবহার করলে কোনো ক্লায়েন্ট কোড না ভেঙেই কাজ সম্পন্ন হয়।'
      }
    }
  ],
  exercises: [
    {
      id: 'gql-fed-ex1',
      kind: 'mcq',
      topic: 'Role of @key directive in Apollo Federation',
      question: {
        en: 'What is the purpose of declaring the @key(fields: "id") directive on an object type in Apollo Federation?',
        bn: 'অ্যাপোলো ফেডারেশনে কোনো অবজেক্ট টাইপের ওপর @key(fields: "id") নির্দেশক ঘোষণার মূল উদ্দেশ্য কী?'
      },
      options: [
        {
          en: 'It designates the type as a federated entity and defines the unique identifier fields that other subgraphs use to reference and extend it',
          bn: 'এটি টাইপটিকে একটি ফেডারেশন এনটিটি হিসেবে চিহ্নিত করে এবং এমন ইউনিক ফিল্ড নির্ধারণ করে যার মাধ্যমে অন্য সাবগ্রাফ একে রেফারেন্স ও এক্সটেন্ড করতে পারে'
        },
        {
          en: 'It encrypts the database primary keys using public key cryptography',
          bn: 'এটি পাবলিক কি ক্রিপ্টোগ্রাফি দিয়ে ডেটাবেজের প্রাইমারি কি এনক্রিপ্ট করে'
        },
        {
          en: 'It locks the schema file so no other developer can edit it',
          bn: 'এটি স্কিমা ফাইলটিকে এমনভাবে লক করে যাতে অন্য কোনো ডেভেলপার তা সম্পাদনা করতে না পারে'
        },
        {
          en: 'It forces the client to download a new SSL certificate for each query',
          bn: 'এটি ক্লায়েন্টকে প্রতিটি কোয়েরির জন্য নতুন এসএসএল সার্টিফিকেট ডাউনলোড করতে বাধ্য করে'
        }
      ],
      answer: 0,
      hint: {
        en: 'Entities need an address or key so other subgraphs know which record to extend.',
        bn: 'অন্য সাবগ্রাফ যাতে নির্দিষ্ট রেকর্ডকে খুঁজে বাড়তি তথ্য দিতে পারে সেজন্য একটি ঠিকানার প্রয়োজন হয়।'
      },
      explanation: {
        en: 'The @key directive identifies an entity. It informs the supergraph router which fields constitute the entity unique coordinate across distributed services.',
        bn: '@key নির্দেশক একটি সত্তাকে শনাক্ত করে। এটি রাউটারকে জানায় কোন ফিল্ডগুলো দিয়ে বিভিন্ন সার্ভিসের মাঝে এই সত্তাকে অনন্যভাবে খুঁজে পাওয়া যাবে।'
      }
    },
    {
      id: 'gql-fed-ex2',
      kind: 'mcq',
      topic: 'Entity resolution via representations in _entities query',
      question: {
        en: 'How does the Apollo Router request extension fields for entities owned by another subgraph?',
        bn: 'অ্যাপোলো রাউটার অন্য সাবগ্রাফের অধীনে থাকা এনটিটির অতিরিক্ত ফিল্ডের জন্য কীভাবে রিকোয়েস্ট পাঠায়?'
      },
      options: [
        {
          en: 'It compiles an array of entity representations (e.g. { __typename: "Product", id: "101" }) and sends a batched _entities query to the downstream subgraph',
          bn: 'এটি এনটিটি রিপ্রেজেন্টেশনের একটি অ্যারে তৈরি করে (যেমন { __typename: "Product", id: "101" }) এবং সাবগ্রাফে একটি ব্যাচযুক্ত _entities কোয়েরি পাঠায়'
        },
        {
          en: 'It calls the operating system reboot command on the target server',
          bn: 'এটি টার্গেট সার্ভারে অপারেটিং সিস্টেম রিবুট করার কমান্ড পাঠায়'
        },
        {
          en: 'It opens 10,000 separate TCP connections for each individual record',
          bn: 'এটি প্রতিটি রেকর্ডের জন্য পৃথকভাবে ১০,০০০টি আলাদা টিসিপি কানেকশন খোলে'
        },
        {
          en: 'It asks the web browser to compute the database joins using JavaScript',
          bn: 'এটি ওয়েব ব্রাউজারকে জাভাস্ক্রিপ্ট ব্যবহার করে ডেটাবেজ জয়েন হিসাব করার নির্দেশ দেয়'
        }
      ],
      answer: 0,
      hint: {
        en: 'The router batches entity keys into representations sent to _entities.',
        bn: 'রাউটার এনটিটি কিগুলোকে representations আকারে সাজিয়ে _entities ফিল্ডে পাঠায়।'
      },
      explanation: {
        en: 'Federation standardises the _entities query. The router batches multiple keys together to fetch extension fields efficiently in a single network round-trip.',
        bn: 'ফেডারেশন _entities কোয়েরির মাধ্যমে কাজ করে। রাউটার একাধিক কি একসাথে ব্যাচ করে পাঠায় যাতে একটিমাত্র নেটওয়ার্ক কলেই সমস্ত তথ্য চলে আসে।'
      }
    },
    {
      id: 'gql-fed-ex3',
      kind: 'mcq',
      topic: 'Fault tolerance with nullable subgraph boundary fields',
      question: {
        en: 'Why should relationship fields crossing subgraph boundaries (e.g. reviews: [Review]) be declared as nullable in schema design?',
        bn: 'স্কিমা ডিজাইনে সাবগ্রাফ সীমানা অতিক্রমকারী রিলেশন ফিল্ডগুলো (যেমন reviews: [Review]) কেন নালেবল রাখা উচিত?'
      },
      options: [
        {
          en: 'If the downstream subgraph times out or crashes, a nullable field allows the router to return null for that field while still serving the rest of the response successfully',
          bn: 'যদি সংশ্লিষ্ট মাইক্রোসার্ভিস টাইমআউট বা ক্র্যাশ করে, তবে নালেবল ফিল্ড থাকার কারণে রাউটার সেই ফিল্ডে নাল বসিয়েও বাকি তথ্য সফলভাবে পরিবেশন করতে পারে'
        },
        {
          en: 'Nullable fields run 50 times faster on modern CPU processors',
          bn: 'নালেবল ফিল্ড আধুনিক সিপিইউ প্রসেসরে ৫০ গুণ দ্রুতগতিতে চলে'
        },
        {
          en: 'Because Apollo Router crashes permanently if any non-null field is defined',
          bn: 'কারণ কোনো নন-নাল ফিল্ড সংজ্ঞায়িত থাকলে অ্যাপোলো রাউটার চিরতরে ক্র্যাশ করে'
        },
        {
          en: 'To make the supergraph schema completely invisible to client web browsers',
          bn: 'যাতে ক্লায়েন্ট ওয়েব ব্রাউজারের কাছে সুপারগ্রাফ স্কিমা পুরোপুরি অদৃশ্য থাকে'
        }
      ],
      answer: 0,
      hint: {
        en: 'Null-bubbling on non-null fields wipes out parent objects.',
        bn: 'নন-নাল ফিল্ডে ত্রুটি হলে নালেবিলিটি বাব্লিং প্যারেন্ট অবজেক্টকেও নষ্ট করে ফেলে।'
      },
      explanation: {
        en: 'Nullable boundaries isolate microservice failures. If an auxiliary service goes down, the client still receives core entity data instead of a total request failure.',
        bn: 'নালেবল সীমানা মাইক্রোসার্ভিসের ত্রুটিকে আটকে রাখে। কোনো সহায়ক সার্ভিস সাময়িক ডাউন থাকলেও ক্লায়েন্ট মূল ডেটা পেয়ে যায়, যার ফলে পুরো রিকোয়েস্ট ব্যর্থ হয় না।'
      }
    },
    {
      id: 'gql-fed-ex4',
      kind: 'mcq',
      topic: 'Pre-deployment composition checks with Rover CI',
      question: {
        en: 'What critical danger is prevented by running schema composition checks (such as rover subgraph check) in CI pipelines?',
        bn: 'সিআই পাইপলাইনে স্কিমা কম্পোজিশন চেক (যেমন rover subgraph check) চালানোর মাধ্যমে কোন মারাত্মক ঝুঁকি প্রতিরোধ করা হয়?'
      },
      options: [
        {
          en: 'It catches incompatible schema changes, missing entity keys, and broken directive contracts before the new subgraph can be deployed to production',
          bn: 'এটি নতুন সাবগ্রাফ প্রোডাকশনে ডিপ্লয় করার আগেই অসঙ্গতিপূর্ণ স্কিমা পরিবর্তন, বাদ পড়া এনটিটি কি এবং নির্দেশকের অমিল শনাক্ত করে ফেলে'
        },
        {
          en: 'It stops git commits from consuming hard disk storage',
          bn: 'এটি গিট কমিটকে হার্ডডিস্ক মেমোরি খরচ করা থেকে বিরত রাখে'
        },
        {
          en: 'It translates the GraphQL schema into plain HTML web pages',
          bn: 'এটি GraphQL স্কিমাকে সাধারণ এইচটিএমএল ওয়েবপেজে রূপান্তর করে'
        },
        {
          en: 'It forces developers to restart their office routers once a week',
          bn: 'এটি ডেভেলপারদের সপ্তাহে একবার অফিসের ওয়াই-ফাই রাউটার রিস্টার্ট করতে বাধ্য করে'
        }
      ],
      answer: 0,
      hint: {
        en: 'Catching composition errors in CI prevents breaking the live gateway.',
        bn: 'সিআই-তে কম্পোজিশন ভুল ধরা পড়লে লাইভ গেটওয়ে অচল হওয়া থেকে রক্ষা পায়।'
      },
      explanation: {
        en: 'If a team publishes an invalid subgraph schema, the supergraph cannot compose. Checking in CI guarantees that invalid schemas are rejected before reaching production.',
        bn: 'কোনো টিম যদি ভুল স্কিমা দেয় তবে সুপারগ্রাফ তৈরি হতে পারে না। সিআই-তে যাচাই করলে এই ভুল প্রোডাকশনে যাওয়ার আগেই আটকে দেওয়া সম্ভব হয়।'
      }
    }
  ],
  quiz: {
    id: 'the-federation-court-quiz',
    title: {
      en: 'Apollo Federation & Subgraphs Quiz',
      bn: 'অ্যাপোলো ফেডারেশন ও সাবগ্রাফ কুইজ'
    },
    questions: [
      {
        id: 'q-shareable-directive-federation',
        kind: 'mcq',
        topic: 'Resolving fields across multiple subgraphs with @shareable',
        question: {
          en: 'What does the @shareable directive signify when declared on an object field in Apollo Federation 2?',
          bn: 'অ্যাপোলো ফেডারেশন ২ এ কোনো অবজেক্ট ফিল্ডের ওপর @shareable নির্দেশক ঘোষণা করলে কী বোঝায়?'
        },
        options: [
          {
            en: 'It declares that multiple independent subgraphs are permitted to resolve this exact field, allowing the router to choose the optimal subgraph during query planning',
            bn: 'এটি ঘোষণা করে যে একাধিক স্বাধীন সাবগ্রাফ এই ফিল্ডটির সমাধান করতে সক্ষম, ফলে রাউটার পরিকল্পনা তৈরির সময় সুবিধাজনক সাবগ্রাফ বেছে নিতে পারে'
          },
          {
            en: 'It automatically publishes the field values to public social media platforms',
            bn: 'এটি স্বয়ংক্রিয়ভাবে ফিল্ডের মান সোশ্যাল মিডিয়া প্ল্যাটফর্মে সবার জন্য উন্মুক্ত করে দেয়'
          },
          {
            en: 'It makes the field completely free of any server CPU processing cost',
            bn: 'এটি ফিল্ডটিকে সার্ভারের যেকোনো সিপিইউ প্রসেসিং খরচ থেকে সম্পূর্ণ মুক্ত করে'
          },
          {
            en: 'It restricts the field from ever being queried by frontend mobile apps',
            bn: 'এটি মোবাইল অ্যাপের মাধ্যমে ফিল্ডটিতে কোয়েরি পাঠানো স্থায়ীভাবে নিষিদ্ধ করে'
          }
        ],
        answer: 0,
        hint: {
          en: 'In Federation 2, fields owned by multiple subgraphs must be marked as shareable.',
          bn: 'ফেডারেশন ২ এ একাধিক সাবগ্রাফের অধীনে থাকা ফিল্ডগুলোকে অবশ্যই শেয়ার্ড হিসেবে চিহ্নিত করতে হয়।'
        },
        explanation: {
          en: 'By default, Federation 2 requires a field to have a single owner. The @shareable directive explicitly permits multiple subgraphs to resolve that field.',
          bn: 'ডিফল্টভাবে ফেডারেশন ২ এ একটি ফিল্ডের একজনই মালিক থাকে। @shareable নির্দেশক ব্যবহারের মাধ্যমে একাধিক সাবগ্রাফকে সেই ফিল্ড সমাধানের অনুমতি দেওয়া হয়।'
        }
      },
      {
        id: 'q-override-directive-migration',
        kind: 'mcq',
        topic: 'Zero-downtime field migration using @override',
        question: {
          en: 'How does the @override(from: "subgraphA") directive facilitate zero-downtime microservice refactoring?',
          bn: '@override(from: "subgraphA") নির্দেশক কীভাবে নিরবচ্ছিন্নভাবে মাইক্রোসার্ভিস রিফ্যাক্টরিং করতে সহায়তা করে?'
        },
        options: [
          {
            en: 'It transfers resolving responsibility of that field from subgraphA to the current subgraph without requiring breaking changes or simultaneous coordinate deployments',
            bn: 'পুরোনো ক্লায়েন্ট না ভেঙেই এটি subgraphA থেকে বর্তমান সাবগ্রাফে ফিল্ডটির সমাধানের দায়িত্ব স্থানান্তর করে কোনো একযোগে ডিপ্লয়মেন্টের চাপ ছাড়াই'
          },
          {
            en: 'It deletes subgraphA from the cloud provider immediately upon deployment',
            bn: 'ডিপ্লয় করার সাথে সাথেই এটি ক্লাউড সার্ভার থেকে subgraphA সার্ভিসটি মুছে ফেলে'
          },
          {
            en: 'It converts the field type from a string into an integer automatically',
            bn: 'এটি ফিল্ডের ধরনকে স্ট্রিং থেকে স্বয়ংক্রিয়ভাবে ইন্টিজারে পরিবর্তন করে ফেলে'
          },
          {
            en: 'It reboots all user smartphones running the client application',
            bn: 'এটি ক্লায়েন্ট অ্যাপ চালানো সমস্ত ব্যবহারকারীর স্মার্টফোন রিবুট করে দেয়'
          }
        ],
        answer: 0,
        hint: {
          en: 'Moving field ownership between microservices smoothly.',
          bn: 'একটি মাইক্রোসার্ভিস থেকে অন্য সার্ভিসে ফিল্ডের মালিকানা মসৃণভাবে স্থানান্তরের কথা ভাবুন।'
        },
        explanation: {
          en: '@override allows teams to incrementally migrate fields between subgraphs. The gateway router immediately directs queries for that field to the new subgraph.',
          bn: '@override দলগুলোকে ধাপে ধাপে ফিল্ডের মালিকানা সরাতে সাহায্য করে। গেটওয়ে রাউটার সাথে সাথে নতুন সাবগ্রাফ থেকে ফিল্ডের ডেটা আনতে শুরু করে।'
        }
      },
      {
        id: 'q-query-plan-caching',
        kind: 'mcq',
        topic: 'Router query plan compilation and caching',
        question: {
          en: 'Why does the Apollo Router cache compiled Query Plans using the query document hash?',
          bn: 'অ্যাপোলো রাউটার কেন কোয়েরি দলিলের হ্যাশ ব্যবহার করে সংকলিত Query Plan ক্যাশ করে রাখে?'
        },
        options: [
          {
            en: 'Compiling query DAGs and dependency trees has computational cost; caching the plan allows subsequent identical operations to execute immediately with zero planning latency',
            bn: 'কোয়েরি DAG এবং নির্ভরশীলতার গাছ তৈরি করতে প্রসেসিং সময় লাগে; ক্যাশ করে রাখলে পরবর্তী একই কোয়েরিগুলো কোনো সময়ক্ষেপণ ছাড়াই তাৎক্ষণিক চলতে পারে'
          },
          {
            en: 'Because Apollo Router cannot run on servers with more than 1 MB of RAM',
            bn: 'কারণ ১ মেগাবাইটের বেশি র্যাম থাকা সার্ভারে অ্যাপোলো রাউটার চলতে পারে না'
          },
          {
            en: 'To make sure queries can only be run once per calendar year',
            bn: 'যাতে একটি বছরে কোনো কোয়েরি কেবল একবারই চালানো সম্ভব হয়'
          },
          {
            en: 'To permanently lock the database rows against incoming write mutations',
            bn: 'আগত রাইট মিউটেশন থেকে ডেটাবেজের সারিগুলোকে চিরতরে লক করে রাখতে'
          }
        ],
        answer: 0,
        hint: {
          en: 'Plan compilation takes CPU cycles; reusing it boosts router throughput.',
          bn: 'পরিকল্পনা তৈরিতে সিপিইউ খরচ হয়; তা পুনরায় ব্যবহার করলে রাউটারের গতি অনেক বৃদ্ধি পায়।'
        },
        explanation: {
          en: 'Query planning analyzes subgraphs, entities, and network paths. Caching the plan by operation signature lets high-throughput routers execute in sub-millisecond time.',
          bn: 'কোয়েরি প্ল্যানিংয়ে বিভিন্ন সাবগ্রাফ ও পাথ বিশ্লেষণ করতে হয়। স্বাক্ষরের মাধ্যমে প্ল্যান ক্যাশ রাখলে রাউটার মিলি-সেকেন্ডেরও কম সময়ে রিকোয়েস্ট পাঠাতে পারে।'
        }
      },
      {
        id: 'q-distributed-monolith-trap',
        kind: 'mcq',
        topic: 'Avoiding the distributed monolith antipattern in Federation',
        question: {
          en: 'What architectural mistake transforms a federated GraphQL architecture into a slow "distributed monolith"?',
          bn: 'কোন কাঠামোগত ভুলের কারণে একটি ফেডারেশন GraphQL আর্কিটেকচার ধীরগতির "ডিস্ট্রিবিউটেড মনোলিথ"-এ পরিণত হয়?'
        },
        options: [
          {
            en: 'Creating excessive circular field dependencies with @requires and @external across subgraphs, causing a single client query to trigger dozens of sequential inter-service hops',
            bn: 'সাবগ্রাফগুলোর মাঝে @requires ও @external দিয়ে অতিরিক্ত চক্রাকার নির্ভরতা তৈরি করা, যার ফলে একটি সাধারণ কোয়েরিতেও সার্ভিসের মাঝে ডজন ডজন ধারাবাহিক নেটওয়ার্ক কল ঘটে'
          },
          {
            en: 'Writing clear schema comments and comprehensive documentation',
            bn: 'স্কিমায় পরিষ্কার কমেন্ট ও বিস্তারিত ডকুমেন্টেশন লিখে রাখা'
          },
          {
            en: 'Using TypeScript instead of uncompiled vanilla JavaScript',
            bn: 'সাধারণ জাভাস্ক্রিপ্টের বদলে টাইপস্ক্রিপ্ট প্রোগ্রামিং ভাষা ব্যবহার করা'
          },
          {
            en: 'Running automated unit test suites before git commits',
            bn: 'গিট কমিট করার আগে স্বয়ংক্রিয় ইউনিট টেস্ট চালানো'
          }
        ],
        answer: 0,
        hint: {
          en: 'Tightly coupled subgraphs chatting back and forth create high network latency.',
          bn: 'সার্ভিসগুলোর মাঝে অতিরিক্ত পারস্পরিক নির্ভরতা নেটওয়ার্কের সময় অনেক বাড়িয়ে দেয়।'
        },
        explanation: {
          en: 'If subgraphs are overly chatty and tightly coupled via deep @requires chains, a single query compiles into a deep sequential waterfall, destroying the benefits of federation.',
          bn: 'সার্ভিসগুলোর মাঝে গভীর @requires নির্ভরতা থাকলে সাধারণ কোয়েরিও দীর্ঘ ওয়াটারফল নেটওয়ার্ক ক্যু তৈরি করে, যা পুরো সিস্টেমকে অস্বাভাবিক ধীর করে ফেলে।'
        }
      }
    ]
  },
  nextLesson: {
    slug: 'the-evolution-ledger',
    title: {
      en: 'Schema Evolution & Deprecation — Breaking Changes, Field Auditing & Versionless APIs',
      bn: 'স্কিমা বিবর্তন ও অবচয় — ব্রেকিং চেঞ্জ, ফিল্ড অডিটিং ও সংস্করণহীন এপিআই'
    }
  }
};
