import type { TechHub } from '../../lib/types';
import { partitionLedgerLesson } from './lessons/the-partition-ledger';
import { consensusChoirLesson } from './lessons/the-consensus-choir';
import { replicationLogLesson } from './lessons/the-replication-log';
import { consistencyMenuLesson } from './lessons/the-consistency-menu';
import { timeWithoutClocksLesson } from './lessons/time-without-clocks';
import { gossipParishLesson } from './lessons/the-gossip-parish';
import { twoPhaseDuelLesson } from './lessons/the-two-phase-duel';
import { distributedSystemsCapstoneLesson } from './lessons/distributed-systems-capstone';

export const dsyHub: TechHub = {
  slug: 'distributed-systems' as never,
  name: 'Distributed Systems',
  icon: '🌐',
  tagline: {
    en: 'When the wall falls between the singers, who keeps answering, who keeps agreeing — and who signs for the burial.',
    bn: 'গায়কদের মাঝে প্রাচীর পড়লে, কে উত্তর দিতে থাকে, কে একমত থাকে — আর সমাধির জন্য কে সই করে।',
  },
  intro: {
    en: 'Distributed systems begin with a scandal: the network’s silence is indistinguishable from death, slowness and treason, yet the choir must keep singing. This hub walks one fixed fate-line — three siblings (Asha, Bala, Cara), six writes, eight reads, two falls of the wall — through four consistency laws, counter by counter. Lesson one, THE PARTITION LEDGER, proves the wall is weather (FLP in street clothes, the eight fallacies as localhost defaults, CAP-as-menu + PACELC), then holds the naive LWW treaty to the light: parallel truths at i5/i6, divergent honest lamps at i7/i8, and one silent burial at i9 — lost=1 on a log with zero errors, because LWW works exactly as configured. Lesson two, THE CONSENSUS CHOIR, teaches the three adult arbitrations: sloppy quorum’s ⌑ lodger (accepted-until-delivery, hints=1, one dead courier from a lie), strict majority’s polite refusals (rejects=2 buying a healing day with zero duels), and the single leader’s crown-and-exam — one address of truth until i16 strands the crown, the lease expires on silence, and the succession exam moves it Bala→Cara, with i19’s betrayed lamp as the vaccination every serving address needs. The counter table is the whole syllabus: count the counters before you sign the treaty.',
    bn: 'ডিস্ট্রিবিউটেড সিস্টেম শুরু হয় একটি কেলেঙ্কারিতে: নেটওয়ার্কের নীরবতা মৃত্যু, ধীরতা আর বিশ্বাসঘাতকতা থেকে অবিচ্ছেদ্য, তবু সুরদলকে গাইতেই হবে। এই হাব হাঁটায় একটি স্থির নিয়তি-রেখা — তিন সহোদর (আশা, বলা, কারা), ছয় লেখা, আট পাঠ, দুইবার প্রাচীর-পতন — চার ধারাবাহিকতা-বিধানের মধ্য দিয়ে, গণক ধরে গণক। প্রথম পাঠ, পার্টিশন-খাতা, প্রমাণ করে প্রাচীর আবহাওয়া (রাস্তার-পোশাকে FLP, লোকালহোস্ট-ডিফল্টরূপে আট ভ্রম, CAP-তালিকা + PACELC), তারপর নিরীক্ষ LWW-চুক্তিকে আলোর সামনে ধরে: i5/i6-এ সমান্তরাল সত্য, i7/i8-এ বিচ্ছিন্ন সৎ প্রদীপ, আর i9-এ একটি নীরব সমাধি — শূন্য-ত্রুটির লগে lost=1, কারণ LWW কাজ করে হুবহু কনফিগার-মতো। দ্বিতীয় পাঠ, সম্মতি-সুরদল, শেখায় তিন প্রাপ্তবয়স্ক মাধ্যম: ঢিলা-কোরামের ⌑ অতিথি (পৌঁছানো-পর্যন্ত-গৃহীত, hints=1, মিথ্যা থেকে এক মৃত বাহক দূরে), কঠোর-সংখ্যাগরিষ্ঠের বিনীত প্রত্যাখ্যান (rejects=2 কিনে দ্বন্দ্বহীন নিরাময়-দিবস), আর একক-নেতার মুকুট-ও-পরীক্ষা — সত্যের এক ঠিকানা, যতক্ষণ না i16 মুকুট আটকায়, লিজ শেষ হয় নীরবতায়, আর উত্তরাধিকার-পরীক্ষা তা সরিয়ে দেয় বলা→কারা, i19-এর বিশ্বাসঘাত-প্রদীপ সহ যেটি প্রতি পরিবেশনকারী ঠিকানার প্রয়োজনীয় টিকা। গণক-সারণিই পুরো পাঠক্রম: চুক্তি সই করার আগে গণক গুনে নিন।',
  },
  lessons: [partitionLedgerLesson, consensusChoirLesson, replicationLogLesson, consistencyMenuLesson, timeWithoutClocksLesson, gossipParishLesson, twoPhaseDuelLesson, distributedSystemsCapstoneLesson],
  references: [
    {
      group: { en: 'The wall & the menu', bn: 'প্রাচীর ও তালিকা' },
      items: [
        { term: 'partition', def: { en: 'Any period where two parts cannot promise replies inside the design’s deadline. Weather, not sabotage; indistinguishable from death, slowness, GC and treachery (FLP).', bn: 'যে সময়চ্ছিদ্ধে দুই অংশ নকশার সীমায় উত্তর প্রতিশ্রুতি দিতে পারে না। আবহাওয়া, অভিশাপ নয়; মৃত্যু, ধীরতা, GC ও বিশ্বাসঘাত থেকে অবিচ্ছেদ্য (FLP)।' } },
        { term: 'CAP menu', def: { en: 'During the wall: A or C, never both. Between walls: latency vs consistency (PACELC). P is forced — you choose behaviour per operation.', bn: 'প্রাচীরকালে: A নাকি C, কখনো দুটোই নয়। প্রাচীরের বাইরে: লেটেন্সি বনাম ধারাবাহিকতা (PACELC)। P বাধ্য — আচরণ বাছিন অপারেশনপ্রতি।' } },
        { term: 'LWW confession', def: { en: 'Higher wall-clock heals all — and buries the loser silently. Counters on the fate-line: accepts=6, errors=0, lost=1, conflicts=1.', bn: 'বড় প্রাচীর-ঘড়ি সব নিরাময় করে — আর পরাজিতকে নীরবে সমাহিত করে। নিয়তি-রেখার গণক: গৃহীত=6, ত্রুটি=0, হারানো=1, দ্বন্দ্ব=1।' } },
        { term: 'vector clocks', def: { en: 'The honesty instrument: versions comparable only by dominance, otherwise CONCURRENT — show the duel; never bury it.', bn: 'সততার যন্ত্র: সংস্করণ তুলনীয় কেবল আধিপত্যে, নইলে সমবর্তী — দ্বন্দ্ব দেখান; কখনো সমাহিত করবেন না।' } },
      ],
    },
    {
      group: { en: 'The arbitration shelf', bn: 'মাধ্যম-তাক' },
      items: [
        { term: 'W + R > N', def: { en: 'The overlap law: reader-set and writer-set must share a witness. N=3 ⇒ W=2+R=2. Certifies survival, never newest-ness.', bn: 'ছেদ-বিধি: পাঠক-সেট ও লেখক-সেটকে সাক্ষী ভাগ করতেই হবে। N=3 ⇒ W=2+R=2। সনদ দেয় টিকে-থাকার, নবতমতার কখনো নয়।' } },
        { term: 'sloppy quorum + ⌑', def: { en: 'Accept on substitute seats with a marked lodger; accepted-until-delivery. Counters: rejects=0, hints=1, conflicts=1, lost=0.', bn: 'বিকল্প-আসনে গ্রহণ চিহ্নিত-অতিথিসহ; পৌঁছানো-পর্যন্ত-গৃহীত। গণক: প্রত্যাখ্যান=0, ইঙ্গিত=1, দ্বন্দ্ব=1, হারানো=0।' } },
        { term: 'strict majority', def: { en: 'No lodgers; minority refused. Counters: rejects=2, migrations=2, conflicts=0, lost=0 — reconciliations are bookkeeping.', bn: 'অতিথি নেই; সংখ্যালঘু প্রত্যাখ্যাত। গণক: প্রত্যাখ্যান=2, স্থানান্তর=2, দ্বন্দ্ব=0, হারানো=0 — মীমাংসা হিসাব-কাজ।' } },
        { term: 'crown & exam', def: { en: 'One address of truth; heartbeats as lease; silent-crown + majority vote + freshest log = lawful succession (Raft in one breath).', bn: 'সত্যের এক ঠিকানা; লিজরূপে হার্টবিট; নীরব-মুকুট + সংখ্যাগরিষ্ঠ-ভোট + সতেজতম-লগ = বৈধ উত্তরাধিকার (এক নিঃশ্বাসে Raft)।' } },
        { term: 'the betrayed lamp', def: { en: 'Deposed leader serving yesterday: mandate-check skipped. Vaccines: lease-checked reads, read-index, quorum linearizability.', bn: 'গতকাল পরিবেশনকারী পদচ্যুত-নেতা: ম্যান্ডেট-যাচাই বাদ পড়েছে। টিকা: লিজ-যাচাইকৃত পাঠ, রিড-ইনডেক্স, কোরাম-লিনিয়ারাইজেবিলিটি।' } },
      ],
    },
  ],
  roadmap: [
    { stage: 1, title: { en: 'Name the weather', bn: 'আবহাওয়ার নাম বলুন' }, detail: { en: 'Partitions as recurring climate; FLP; the eight fallacies as localhost defaults; CAP menu + PACELC per operation.', bn: 'বারংবার-আসা জলবায়ু হিসেবে পার্টিশন; FLP; লোকালহোস্ট-ডিফল্টরূপে আট ভ্রম; অপারেশনপ্রতি CAP তালিকা + PACELC।' } },
    { stage: 2, title: { en: 'Read the divergent lamps', bn: 'বিচ্ছিন্ন প্রদীপ পড়ুন' }, detail: { en: 'Naive fate-line: parallel truths, stale windows, the unattended burial; lost/conflict counters as first-class metrics.', bn: 'নিরীক্ষ নিয়তি-রেখা: সমান্তরাল সত্য, বাসি জানালা, অনুপস্থিত সমাধি; হারানো/দ্বন্দ্ব গণক প্রথম-শ্রেণির মেট্রিক হিসেবে।' } },
    { stage: 3, title: { en: 'Price the inequality', bn: 'অসমতার দাম দিন' }, detail: { en: 'W+R>N intuition and its repeal (R=1/W=1); sloppy vs strict treaties; hinted lodgers and their homecoming audits.', bn: 'W+R>N অনুধাবন ও তার বাতিল (R=1/W=1); ঢিলা বনাম কঠোর চুক্তি; ইঙ্গিত-অতিথি ও তাদের ঘরে-ফেরা-নিরীক্ষণ।' } },
    { stage: 4, title: { en: 'Run the succession exam', bn: 'উত্তরাধিকার-পরীক্ষা চালান' }, detail: { en: 'Leader leases as physics; term+vote+log; crown the freshest, kneel at higher terms; vaccinate every serving address against betrayed lamps.', bn: 'পদার্থবিদ্যা হিসেবে নেতা-লিজ; টার্ম+ভোট+লগ; সতেজতমকে মুকুট, বড় টার্মে সিদ্দা; বিশ্বাসঘাত-প্রদীপের বিরুদ্ধে প্রতি পরিবেশনকারী ঠিকানাকে টিকা দিন।' } },
  ],
  projects: [
    {
      title: { en: 'FateLine Replay: the four-law harness', bn: 'ফেটলাইন রিপ্লে: চার-বিধান হার্নেস' },
      brief: { en: 'Implement the three-node, four-law walk as an event-driven harness: the same 19-beat fate-line must run under naive, sloppy, strict and leader arbiters, emitting the counter table (accepts, refusals, hints, duels, burials, stale lamps, elections) per scene. The harness must refuse to start unless the authored wall schedule is listed first (wall at i4+i16, heal at i9+i17), and must print a one-page PDF-style comparison at the end — our lab’s table, reproducible from YOUR code.', bn: 'তিন-নোড, চার-বিধানের ভ্রমণ বাস্তবায়ন করুন ঘটনা-চালিত হার্নেসে: একই ১৯-ছন্দের নিয়তি-রেখা চলবে নিরীক্ষ, ঢিলা, কঠোর আর নেতা মাধ্যমে, গণক-সারণি নির্গমন করে (গৃহীত, প্রত্যাখ্যাত, ইঙ্গিত, দ্বন্দ্ব, সমাধি, বাসি প্রদীপ, নির্বাচন) প্রতি দৃশ্যে। হার্নেস চালু হতে অস্বীকার করবে, যতক্ষণ না প্রাচীর-তফসিল শুরুর তালিকায় লেখা (i4+i16-এ প্রাচীর, i9+i17-এ নিরাময়), আর শেষে ছাপাবে এক-পাতার তুলনা — আমাদের ল্যাবের সারণি, আপনার কোড থেকে পুনরুৎপাদনযোগ্য।' },
      difficulty: 'intermediate',
    },
    {
      title: { en: 'LodgerWatch: the hinted-handoff auditor', bn: 'লজারওয়াচ: ইঙ্গিত-হস্তান্তর নিরীক্ষক' },
      brief: { en: 'Build a sloppy-quorum KV with ⌑ marks, then a sidecar that polls replica divergence every 10 ms and renders the lodger’s lifetime: born at write, delivered (or orphaned) at heal. Ship chaos: kill the lodger host mid-wall and show the accepted YES that becomes undeliverable; the report must count “courier-death funerals” as a first-class metric, exactly like this hub counts burials.', bn: 'একটি ঢিলা-কোরাম KV গড়ুন ⌑ চিহ্নসহ, তারপর একটি পার্শ্ববর্তী যা প্রতি 10 ms-এ রেপ্লিকা-বিচ্ছিন্নতা জরিপ করে আর অতিথির জীবনচক্র রেন্ডার করে: লেখায় জন্ম, নিরাময়ে বিতরিত (নয়তো এতিম)। ক্যাওস দিন: প্রাচীরের মাঝে অতিথি-হোস্ট হত্যা করে দেখান সেই গৃহীত YES যা অবিতরণীয় হয়ে যায়; প্রতিবেদনে অবশ্যই “বাহক-মৃত্যু-জানাজা” গণনা প্রথম-শ্রেণির মেট্রিক হিসেবে — এই হাব সমাধি গোনে যেমন হুবহু তেমন।' },
      difficulty: 'advanced',
    },
    {
      title: { en: 'CrownCourt: the succession-exam rig', bn: 'ক্রাউনকোর্ট: উত্তরাধিকার-পরীক্ষা রিগ' },
      brief: { en: 'Hand-roll a tiny Raft (terms, heartbeats, candidacy, most-up-to-date gating, append + commit marker) on three localhost processes. Script the hub’s second act: strand the leader with tc/netem (or a scheduler toggle), demonstrate (a) lawful succession in the majority, (b) a deposed node serving stale reads when its lease-check is off (the betrayed lamp), and (c) the i18 write-redirect. Metrics out: time-to-new-crown, lamps lit, and rejected-vs-accepted knocks during the exam window.', bn: 'তিনটি লোকালহোস্ট-প্রসেসে হাতে-গড়া ক্ষুদ্র Raft (টার্ম, হার্টবিট, প্রার্থীতা, সতেজতম-নিরোধ, অ্যাপেন্ড + কমিট-চিহ্ন)। হাবের দ্বিতীয় অঙ্ক স্ক্রিপ্ট করুন: নেতাকে আটকান tc/netem দিয়ে (অথবা সময়-নিয়ন্ত্রক টগল), দেখান (ক) সংখ্যাগরিষ্ঠে বৈধ উত্তরাধিকার, (খ) লিজ-চেক বন্ধ থাকলে পদচ্যুত-নোডের বাসি-পাঠ পরিবেশন (বিশ্বাসঘাত-প্রদীপ), আর (গ) i18 লেখা-পুনর্নির্দেশ। নির্গত মেট্রিক: নতুন-মুকুটে-কাল, জ্বলে-ওঠা প্রদীপ, আর পরীক্ষা-জানালায় প্রত্যাখ্যাত-বনাম-গৃহীত ধক।' },
      difficulty: 'advanced',
    },
  ],
  bestPractices: [
    { en: 'Choose behavior during partitions in advance, per data class, and write the signed treaty next to the config. A calm-Tuesday choice will be read aloud at 3 a.m.', bn: 'পার্টিশনকালীন আচরণ আগেই বাছুন, ডেটা-শ্রেণিভেদে, আর সইকৃত চুক্তি রাখুন কনফিগের পাশে। শান্ত-মঙ্গলবারের পছন্দ ভোর তিনটায় উচ্চে পড়া হবে।' },
    { en: 'Instrument the LAW, not only the mechanics: duel counters, burial counters, lodger-birth-and-homecoming, lamp luminosity. In AP systems, legal failures are the interesting ones.', bn: 'যন্ত্রাংশ নয়, বিধান যন্ত্রায়িত করুন: দ্বন্দ্ব-গণক, সমাধি-গণক, অতিথি-জন্ম-ও-ঘরে-ফেরা, প্রদীপ-প্রভা। AP-সিস্টেমে বৈধ ব্যর্থতাই মজার।' },
    { en: 'Never let a wall-clock arbitrate truth without a vector (or at least version) beside it, and never ship a cache layer whose keys skip the mandate check.', bn: 'প্রাচীর-ঘড়িকে কখনো সত্য মাধ্যম করতে দেবেন না, পাশে ভেক্টর (নয়তো অন্তত সংস্করণ) ছাড়া; আর এমন ক্যাশ-স্তর চালু করবেন না যার কী ম্যান্ডেট-যাচাই এড়িয়ে যায়।' },
    { en: 'W+R>N is the vaccine SPEC; verify it in CI for every cluster config — one character of drift (R=1, W=1) repeals it invisibly.', bn: 'W+R>N হলো টিকা-স্পেসিফিকেশন; প্রতি ক্লাস্টার কনফিগে CI-তে যাচাই করুন — এক অক্ষরের বিচ্যুতি (R=1, W=1) তা অদৃশ্যে বাতিল করে।' },
    { en: 'Plans proposals with inequalities attached: any latency improvement must state which guarantee the new numbers still witness (overlap, mandate, lease).', bn: 'অসমতা সংযুক্ত প্রস্তাব রিভিউ করুন: যেকোনো লেটেন্সি-উন্নতিকে বলতেই হবে নতুন সংখ্যা এখনো কোন গ্যারান্টির সাক্ষ্য দেয় (ছেদ, ম্যান্ডেট, লিজ)।' },
    { en: 'Rehearse the succession exam in staging before production runs it for you: strand the crown, time the exam, count the lamps lit.', bn: 'উৎপাদন যাতে আপনার পরিবর্তে না-চালায়, তার আগে স্টেজিং-এ উত্তরাধিকার-পরীক্ষার মহড়া দিন: মুকুট আটকান, পরীক্ষার সময় মাপুন, জ্বলে-ওঠা প্রদীপ গুনুন।' },
  ],
  interview: [
    {
      q: { en: 'DynamoDB vs etcd — same three replicas, totally different souls. Explain the split to a junior in the language of counters.', bn: 'DynamoDB বনাম etcd — একই তিন রেপ্লিকা, সম্পূর্ণ ভিন্ন আত্মা। গণকের ভাষায় জুনিয়রকে ব্যাখ্যা করুন।' },
      a: { en: 'Run both through one wall and read the counter board. etcd (strict majority, CP) shows: refusals i6, i8 → 2; duels 0; burials 0; healings = bookkeeping migrations 2. Dynamo (sloppy AP, hints on) shows: refusals 0; lodgers 1; duels 1; burials 0 (unless a courier dies). The junior-sized sentence: CP makes denial LOUD and reconciliation silent; AP makes acceptance silent and reconciliation loud. Which silence can YOUR data survive? Then the examiner’s follow-up writes itself: for a session store? For a payment ledger? For Kubernetes’ brain? — and each answer is just pointing at the counter that must not move.', bn: 'দুটোকে একটি প্রাচীরের মধ্য দিয়ে চালান আর গণক-বোর্ড পড়ুন। etcd (কঠোর সংখ্যাগরিষ্ঠ, CP) দেখায়: i6, i8 প্রত্যাখ্যান → ২; দ্বন্দ্ব ০; সমাধি ০; নিরাময় = হিসাব-কাজরূপে স্থানান্তর ২। Dynamo (ঢিলা AP, ইঙ্গিত চালু) দেখায়: প্রত্যাখ্যান ০; অতিথি ১; দ্বন্দ্ব ১; সমাধি ০ (এক বাহক মরলে ব্যতীত)। জুনিয়র-মাপের বাক্য: CP অস্বীকৃতি উচ্চশব্দ করে আর মীমাংসা নীরব; AP গ্রহণ নীরব করে আর মীমাংসা উচ্চশব্দ। আপনার ডেটা কোন নীরবতা সহ্য করতে পারে? তারপর পরীক্ষকের ফলো-আপ নিজে লিখে ফেলে: সেশন-স্টোরের জন্য? পেমেন্ট-হিসাবের জন্য? Kubernetes-এর মস্তিষ্কের জন্য? — আর প্রতি উত্তর কেবল সেই গণক দেখিয়ে দেওয়া, যা নড়াই চলে না।' },
    },
    {
      q: { en: '“We run Raft, so we are linearizable.” Agree or push back?', bn: '“আমরা Raft চালাই, তাই আমরা লিনিয়ারাইজেবল।” একমত নাকি পাল্টা?' },
      a: { en: 'Push back with the betrayed lamp. Raft gives you laws for REACHING one ledger (terms, lease, majority, freshest-log, commit-before-serve); it does not force every READER to use them. Any read that skips the mandate check — leader-read shortcuts, follower reads for scale, cached leader addresses — is an R=1 decision: the client may hit deposed-Bala and get yesterday’s truth, exactly like i19. Linearizability under a single leader additionally needs one of three vaccines — lease-checked leader reads (bounded clock error!), read-index heartbeats, or quorum reads — and a fourth piece most teams forget: write path idempotency on retry, or the same client witnesses its own write twice. The exam answer ends in the hub’s own prayer: laws signed, instruments running, counters named — otherwise “Raft” is an invoice, not a system property.', bn: 'বিশ্বাসঘাত-প্রদীপ দিয়ে পাল্টা দিন। Raft দেয় একটি খাতায় পৌঁছানোর বিধি (টার্ম, লিজ, সংখ্যাগরিষ্ঠ, সতেজতম-লগ, পরিবেশনের-আগে-কমিট); প্রতি পাঠককে সেগুলো ব্যবহারে বাধ্য করে না। যেকোনো পাঠ যা ম্যান্ডেট-যাচাই এড়ায় — নেতা-পাঠ-শর্টকাট, স্কেলের জন্য অনুসারী-পাঠ, ক্যাশকৃত নেতা-ঠিকানা — একটি R=1 সিদ্ধান্ত: ক্লায়েন্ট পড়তে পারেন পদচ্যুত-বলার কাছে আর পাবেন গতকালের সত্য, হুবহু i19-এর মতো। একক-নেতার নিচে লিনিয়ারাইজেবিলিটির দরকার তিন টিকার একটি — লিজ-যাচাইকৃত নেতা-পাঠ (সীমিত ঘড়ি-ত্রুটি!), রিড-ইনডেক্স হার্টবিট, নয় কোরাম-পাঠ — আর চতুর্থটি যা বেশিরভাগ দল ভুলে: রিট্রাইতে লেখা-পথ-আইডেমপোটেন্সি, নইলে একই ক্লায়েন্ট নিজের লেখা দুইবার দেখে। পরীক্ষার উত্তর শেষ হোক হাবের প্রার্থনায়: বিধান সইকৃত, যন্ত্র চলমান, গণক নামকৃত — নইলে “Raft” চালান মাত্র, সিস্টেম-গুণ নয়।' },
    },
    {
      q: { en: 'Your cache-aside fleet is backed by a three-replica store. Ops wants “read your own writes” for users, cheaply. What do you offer and what do you warn?', bn: 'আপনার ক্যাশ-অ্যাসাইড বহর তিন-রেপ্লিকা-স্টোরে টেকা। অপ্স চায় ব্যবহারকারীর জন্য “নিজের-লেখা-নিজে-পড়ুন”, সস্তায়। কী অর্পণ করবেন আর কী সতর্ক করবেন?' },
      a: { en: 'Offer the cheap honest version: session consistency BY ROUTING, not by quorum inflation. Write W=2 (the vow), then pin the reading session to any witness of its own last write — simplest: the store returns the write’s version token after every successful write, the client attaches it to reads, and the gateway routes to any replica whose version ≥ token (read-your-writes is a monotonic-reads covenant). Warning one: without the token, “W=2 then read any” reopens the R=1-shaped window for that user specifically — your own write is precisely the write your next read can miss. Warning two: token-based routing fails when the witness host dies mid-session; the fallback (poll two) is W+R arithmetic returning for payment. Warning three: the invalidation discipline still applies on TOP — a versioned cache key stops the ghost-dashboard class; a law-abiding replica layer stops the lost-write class; neither covers the other’s funeral.', bn: 'অর্পণ করুন সস্তা সৎ সংস্করণ: রুটিং দিয়ে সেশন-ধারাবাহিকতা, কোরাম-স্ফীতি দিয়ে নয়। W=2 লিখুন (শপথ), তারপর পাঠক-সেশন পিন করুন নিজের শেষ-লেখার যে-কোনো সাক্ষীতে — সরলতম: স্টোর প্রতি সফল-লেখায় সংস্করণ-টোকেন ফেরত দেয়, ক্লায়েন্ট তা পাঠে সংযুক্ত করে, আর গেটওয়ে যে-কোনো রেপ্লিকায় পাঠায় যার সংস্করণ ≥ টোকেন (নিজের-লেখা-পড়ুন হলো একরৈখিক-পাঠ-চুক্তি)। প্রথম সতর্কতা: টোকেন ছাড়া, “W=2 তারপর যে-কোনোটি পড়ুন” সেই ব্যবহারকারীর জন্যই R=1-আকৃতির জানালা পুনখোলে — আপনার নিজের লেখা-ই হুবহু সেই লেখা, যা আপনার পরের পাঠ মিস করতে পারে। দ্বিতীয়তা: সেশন-মাঝে সাক্ষী-হোস্ট মরলে টোকেন-রুটিং ভেঙে যায়; পশ্চাদপসরণ (দুই জরিপ) হলো W+R পাটিগণিতের প্রত্যাবর্তন মূল্য শোধে। তৃতীয়তা: উপরে তবু অকার্যকরণ-শৃঙ্খলা জারি থাকে — সংস্করণকৃত ক্যাশ-কী ভূত-ড্যাশবোর্ড-শ্রেণি থামায়; আইনমান্য রেপ্লিকা-স্তর হারানো-লেখা-শ্রেণি থামায়; কেউ অপরের জানাজা ঢাকে না।' },
    },
    {
      q: { en: 'Show me one production bug you would fix differently having studied this hub.', bn: 'এমন একটি উৎপাদন-বাগ দেখান, যা আপনি এই হাব পড়ে এখন ভিন্নভাবে ঠিক করতেন।' },
      a: { en: 'The silent reconciliation: an inventory microservice with LWW merges between its mobile-app writer (whose clock ran 40 s fast) and its warehouse writer. For months the warehouse truth lost silently to mobile “tomorrows” — inventory drifted, no errors, and postmortems blamed people for “not double-checking”. Before this hub I would have fixed the persons (alerts, playbooks). After this hub the fix is structural: (1) strip wall-clock arbitration — every write advances a vector or at least a version; concurrent versions are merchant-visible CONFLICTS, not invisible funerals. (2) Count the jackpot counters — duels, burials, divergent reads — as SLIs with pager thresholds; a burial is a page, not a postmortem clause. (3) Terminate the double-write topology altogether (single-writer service per SKU-partition) so the calendar stops being a co-author of inventory — that last move is the hub’s deepest sermon: when you can remove the need for reconciliation, it is cheaper than every arbitration, however adult.', bn: 'নীরব মীমাংসার ঘটনা: এক ইনভেন্টরি মাইক্রোসার্ভিসে তার মোবাইল-অ্যাপ-লেখক (যার ঘড়ি ছিল ৪০ সে এগিয়ে) আর গুদাম-লেখকের মাঝে LWW মর্জ। মাসের পর মাস গুদামের সত্য নীরবে হেরে গেল মোবাইলের “আগামীকালে” — ইনভেন্টরি সরে গেল, ত্রুটি শূন্য, আর পোস্টমর্টেম মানুষকে দোষ দিল “দ্বিবার যাচাই না-করায়”। এই হাবের আগে আমি মানুষ ঠিক করতাম (সতর্কতা, রানবুক)। হাব-পরবর্তী সংশোধন কাঠামোগত: (1) প্রাচীর-ঘড়ি-মাধ্যম উচ্ছেদ — প্রতি লেখা এগিয়ে দেয় ভেক্টর বা অন্তত সংস্করণ; সমবর্তী-সংস্করণ হলো ব্যবসায়ী-দৃশ্য দ্বন্দ্ব, অদৃশ্য জানাজা নয়। (2) জ্যাকপট-গণক গোনা — দ্বন্দ্ব, সমাধি, বিচ্ছিন্ন পাঠ — পেজার-থ্রেশহোল্ডসহ SLI হিসেবে; সমাধি হলো পেজ, পোস্টমর্টেম-ধারা নয়। (3) দ্বৈত-লেখা-টপোলজি সমাপ্ত করুন (SKU-পার্টিশনপ্রতি একক-লেখক-সার্ভিস), যাতে বর্ষপঞ্জি আর ইনভেন্টরির সহ-লেখক না হয় — ওই শেষ চালই হাবের গভীরতম উপদেশ: যখন মীমাংসার প্রয়োজনই তোলা যায়, তা প্রতিটি মাধ্যমের চেয়ে সস্তা, যারা-ই হোক প্রাপ্তবয়স্ক।' },
    },
  ],
  realWorld: [
    { en: 'Service backends at scale: every W/R decision is the overlap law in costume; every “tunable consistency” console is this hub’s counter table with a billing page.', bn: 'স্কেলে সার্ভিস-ব্যাকএন্ড: প্রতি W/R সিদ্ধান্ত পোশাকি ছেদ-বিধি; প্রতি “টিউনেবল কনসিস্টেন্সি” কনসোল এই হাবের গণক-সারণি, বিলিং-পাতাসহ।' },
    { en: 'Control planes & infra: Kubernetes/etcd, Consul, ZooKeeper choose strict majority parts; the day you stray from that treaty, the infra itself starts burying truths.', bn: 'কন্ট্রোল-প্লেন ও ইনফ্রা: Kubernetes/etcd, Consul, ZooKeeper বাছে কঠোর সংখ্যাগরিষ্ঠ; আপনি যেদিন সেই চুক্তি থেকে সরবেন, ইনফ্রা নিজেই সত্য সমাহিত করা শুরু করবে।' },
    { en: 'Edge & mobile sync: offline-first clients are per-device partitions; CRDTs and vector versioning are the honest version of what the naive law was faking.', bn: 'এজ ও মোবাইল-সিঙ্ক: অফলাইন-ফার্স্ট ক্লায়েন্ট হলো ডিভাইসপ্রতি পার্টিশন; CRDT আর ভেক্টর-সংস্করণায়ন হলো নিরীক্ষ-বিধান যা ভান করছিল তার সৎ সংস্করণ।' },
    { en: 'Incident response: ceiling on stale lamps, named succussion windows, audited lodgers — this hub’s debug doctrines are postmortem accelerants.', bn: 'ঘটনা-প্রতিক্রিয়া: বাসি-প্রদীপের সিলিং, নামকৃত উত্তরাধিকার-জানালা, নিরীক্ষিত অতিথি — এই হাবের ডিবাগ-মতবাদগুলো পোস্টমর্টেম-ত্বরণকারী।' },
  ],
};
