import type { Lesson } from '../../../lib/types';

export const LimitsSafetyGenLesson: Lesson = {
  slug: 'limits-safety-gen',
  tech: 'generative-ai',
  title: {
    en: 'Limits, Bias, and Safety in Generative AI — Hallucinations, Red Teaming, and Guardrails',
    bn: 'জেনারেটিভ এআই-এর সীমাবদ্ধতা ও নিরাপত্তা: হ্যালুসিনেশন, রেড টিমিং ও গার্ডরেইল'
  },
  summary: {
    en: 'Deploying generative artificial intelligence in mission-critical software demands rigorous defenses against unpredictable failure modes. Because language models optimize for linguistic plausibility rather than ground truth, they can generate confident hallucinations, reflect societal training biases, and succumb to prompt injection attacks. In this lesson, you will master the 5-layer enterprise defense-in-depth safety stack. You will implement an automated claim verification scorer in TypeScript, and establish factual grounding gates for production deployments.',
    bn: 'বাস্তব সফটওয়্যার সিস্টেমে জেনারেটিভ এআই প্রয়োগের জন্য এর অপ্রত্যাশিত ত্রুটি ও ঝুঁকি মোকাবেলায় কঠোর নিরাপত্তা প্রাচীর গড়ে তোলা জরুরি। ল্যাঙ্গুয়েজ মডেল যেহেতু বাস্তব সত্যের চেয়ে ভাষার সাবলীলতাকে প্রাধান্য দেয়, তাই এরা অত্যন্ত আত্মবিশ্বাসের সাথে কাল্পনিক তথ্য (Hallucination) তৈরি করতে পারে, সামাজিক পক্ষপাতিত্ব প্রদর্শন করতে পারে এবং প্রম্পট ইনজেকশন আক্রমণের শিকার হতে পারে। এই পাঠে ৫-স্তর বিশিষ্ট এন্টারপ্রাইজ নিরাপত্তা স্থাপত্য বিশদভাবে তুলে ধরা হয়েছে। এখানে তথ্য যাচাইকারী গ্রাউন্ডিং অ্যালগরিদম এবং প্রোডাকশনে সত্যতা নিশ্চিত করার কৌশল পর্যালোচনা করা হয়েছে।'
  },
  minutes: 28,
  nextLesson: {
    slug: 'genai-capstone',
    tech: 'generative-ai',
    title: {
      en: 'Generative AI Capstone — Production RAG Architecture and System Deployment',
      bn: 'জেনারেটিভ এআই সমাপনী প্রজেক্ট: প্রোডাকশন RAG আর্কিটেকচার ও ডিপ্লয়মেন্ট'
    }
  },
  blocks: [
    {
      type: 'heading',
      id: 'threat-landscape-overview',
      text: {
        en: 'The Threat Landscape: Hallucinations, Bias, and Prompt Injection',
        bn: 'ঝুঁকির মানচিত্র: হ্যালুসিনেশন, পক্ষপাত এবং প্রম্পট ইনজেকশন'
      }
    },
    {
      type: 'para',
      text: {
        en: 'When you build software around generative language models, you must defend against failure modes that traditional deterministic software never experiences.',
        bn: 'যখন আপনি জেনারেটিভ ল্যাঙ্গুয়েজ মডেল দিয়ে সফটওয়্যার তৈরি করেন, তখন আপনাকে এমন কিছু অভিনব ঝুঁকির মুখোমুখি হতে হয় যা সাধারণ সফটওয়্যারে কখনোই দেখা যায় না।'
      }
    },
    {
      type: 'para',
      text: {
        en: 'Because autoregressive neural networks predict next tokens based on statistical likelihood rather than internal logic or factual lookup, they produce hallucinations: fabricated claims presented in confident, grammatically flawless prose. Furthermore, foundation models inadvertently absorb societal biases present in scraped web text, amplifying harmful stereotypes unless actively counter-steered. In production security, adversarial prompt injections attempt to override system instructions (e.g. instructing a support bot to ignore all rules and leak confidential database credentials), requiring multi-tiered defenses.',
        bn: 'যেহেতু অটোরিগ্রেসিভ নিউরাল নেটওয়ার্ক কোনো তথ্য যাচাই না করে কেবল পরিসংখ্যানিক সম্ভাবনার ভিত্তিতে পরবর্তী শব্দ অনুমান করে, তাই এরা হ্যালুসিনেশন তৈরি করে: সম্পূর্ণ মিথ্যা বা বানোয়াট তথ্যকে অত্যন্ত সাবলীল ব্যাকরণে উপস্থাপন করে। এছাড়া ইন্টারনেট থেকে সংগৃহীত ডেটার কারণে মডেল সামাজিক পক্ষপাতিত্ব ধারণ করতে পারে যা নিয়ন্ত্রণ না করলে ক্ষতিকর রূপ নেয়। নিরাপত্তা ব্যবস্থায় আরেকটি প্রধান হুমকি হলো প্রম্পট ইনজেকশন আক্রমণ, যেখানে চতুর ইনপুটের মাধ্যমে সিস্টেমের নিয়ম ভেঙে সংবেদনশীল তথ্য হাতিয়ে নেওয়ার চেষ্টা করা হয়।'
      }
    },
    {
      type: 'keyterms',
      items: [
        {
          term: 'hallucination',
          def: {
            en: 'Plausible-sounding but factually fabricated statements generated by language models lacking external grounding.',
            bn: 'ল্যাঙ্গুয়েজ মডেল দ্বারা উৎপাদিত ব্যাকরণগতভাবে নিখুঁত কিন্তু বাস্তব তথ্যের দিক থেকে সম্পূর্ণ অসত্য ও কাল্পনিক বিবরণ।'
          }
        },
        {
          term: 'prompt-injection',
          def: {
            en: 'An adversarial security exploit where malicious user inputs hijack system instructions and bypass model guardrails.',
            bn: 'এক ধরনের সাইবার আক্রমণ যেখানে চতুর ইনপুটের মাধ্যমে সিস্টেম প্রম্পটের নিয়ম অমান্য করে ক্ষতিকর আউটপুট বের করে নেওয়া হয়।'
          }
        },
        {
          term: 'adversarial-red-teaming',
          def: {
            en: 'Systematic probing by security engineers to intentionally stress-test models and discover safety vulnerabilities before release.',
            bn: 'রিলিজের পূর্বে সিস্টেমের দুর্বলতা ও ত্রুটি উন্মোচনের উদ্দেশ্যে নিরাপত্তা বিশেষজ্ঞদের দ্বারা পরিকল্পিত আক্রমণ মহড়া।'
          }
        },
        {
          term: 'grounding-score',
          def: {
            en: 'The percentage of atomic statements in a model response directly supported by verifiable retrieved source documents.',
            bn: 'মডেলের উত্তরের কত শতাংশ তথ্য প্রদত্ত প্রামাণ্য নথির সাথে সরাসরি মিলে যায় তার পরিমাপক অনুপাত।'
          }
        }
      ]
    },
    {
      type: 'visual',
      id: 'matrix'
    },
    {
      type: 'heading',
      id: 'five-layer-safety-stack-table',
      text: {
        en: 'The 5-Layer Defense-in-Depth Safety Architecture',
        bn: '৫-স্তর বিশিষ্ট গভীর নিরাপত্তা প্রতিরক্ষা রূপরেখা'
      }
    },
    {
      type: 'para',
      text: {
        en: 'No single guardrail can prevent all jailbreaks and hallucinations. Enterprise systems deploy five complementary layers of defense-in-depth.',
        bn: 'কোনো একক নিরাপত্তা প্রাচীর সমস্ত জেলব্রেক ও হ্যালুসিনেশন ঠেকাতে পারে না। এন্টারপ্রাইজ সিস্টেমে পাঁচটি পরিপূরক স্তরে গভীর প্রতিরক্ষা নিশ্চিত করা হয়।'
      }
    },
    {
      type: 'table',
      head: [
        { en: 'Defense Layer', bn: 'নিরাপত্তা স্তর' },
        { en: 'Operational Focus', bn: 'কার্যক্রমের পরিধি' },
        { en: 'Mitigation Technology', bn: 'প্রযুক্তির ব্যবহার' },
        { en: 'Failure Protection Target', bn: 'প্রতিরোধের মূল লক্ষ্য' }
      ],
      rows: [
        [
          { en: 'Layer 1: Training Data Curation', bn: 'স্তর ১: প্রশিক্ষণ ডেটা কিউরেশন' },
          { en: 'Upstream data filtering before pretraining and SFT', bn: 'প্রশিক্ষণের পূর্বেই ক্ষতিকর ডেটা ছাঁটাই করা' },
          { en: 'PII scrubbing, deduplication, toxic text removal', bn: 'ব্যক্তিগত তথ্য মুছে ফেলা, ডুপ্লিকেট ও ক্ষতিকর টেক্সট বাদ' },
          { en: 'Data poisoning, copyright infringement, secret leakage', bn: 'ডেটা পয়জনিং, কপিরাইট লঙ্ঘন ও ব্যক্তিগত তথ্য প্রকাশ' }
        ],
        [
          { en: 'Layer 2: Model Alignment', bn: 'স্তর ২: মডেল অ্যালাইনমেন্ট' },
          { en: 'Post-training reinforcement learning and refusals', bn: 'পোস্ট-ট্রেনিংয়ে নৈতিক শিক্ষা ও প্রত্যাখ্যানের নিয়ম' },
          { en: 'RLHF safety penalties, refusal training, DPO loss', bn: 'আরএলএইচএফ জরিমানা, বিপজ্জনক কাজে সরাসরি প্রত্যাখ্যান' },
          { en: 'Weapons synthesis instructions, malware coding, hate speech', bn: 'ক্ষতিকর ম্যালওয়্যার তৈরি, অস্ত্র তৈরিতে সহায়তা, বিদ্বেষমূলক কথা' }
        ],
        [
          { en: 'Layer 3: Adversarial Red Teaming', bn: 'স্তর ৩: রেড টিমিং আক্রমণ মহড়া' },
          { en: 'Pre-deployment penetration testing and jailbreak probing', bn: 'সার্ভিস চালুর পূর্বে সিস্টেমে আক্রমণ চালিয়ে পরীক্ষা' },
          { en: 'Automated fuzzing, role-play bypasses, base64 payloads', bn: 'স্বয়ংক্রিয় আক্রমণ স্ক্রিপ্ট, চতুর ছদ্মবেশী প্রম্পট' },
          { en: 'Uncovering edge-case exploits and guardrail bypasses', bn: 'অপ্রত্যাশিত নিরাপত্তা ফাঁকফোকর ও অন্ধ স্থান শনাক্তকরণ' }
        ],
        [
          { en: 'Layer 4: Runtime Input/Output Guardrails', bn: 'স্তর ৪: রানটাইম ইনপুট/আউটপুট ফিল্টার' },
          { en: 'Real-time inspection of inbound prompts and outbound text', bn: 'ইনকামিং প্রম্পট এবং আউটগোয়িং উত্তরের লাইভ স্ক্যানিং' },
          { en: 'Llama Guard classifier, regex PII masks, token bounds', bn: 'লামা গার্ড ক্লাসিফায়ার, সিক্রেট কী মাস্কিং' },
          { en: 'Prompt injection execution, toxic generation drops', bn: 'প্রম্পট ইনজেকশন কার্যকর হওয়া রোধ, আপত্তিকর উত্তর ড্রপ' }
        ],
        [
          { en: 'Layer 5: Continuous Auditing & Logging', bn: 'স্তর ৫: অডিটিং ও স্বচ্ছতা ট্র্যাকিং' },
          { en: 'Observability, provenance watermarking, incident analysis', bn: 'লগ সংরক্ষণ, ওয়াটারমার্কিং এবং ইনসিডেন্ট তদন্ত' },
          { en: 'SynthID watermarking, prompt logs, ground truth scoring', bn: 'সিন্থ-আইডি ওয়াটারমার্ক, প্রম্পট হিস্ট্রি লগ' },
          { en: 'Regulatory compliance violations, synthetic deepfake tracking', bn: 'আইনি দায়বদ্ধতা নিশ্চিতকরণ, ডিপফেক অপপ্রচার প্রতিরোধ' }
        ]
      ]
    },
    {
      type: 'heading',
      id: 'executable-grounding-code',
      text: {
        en: 'Executable Factual Grounding Scorer Simulation',
        bn: 'বাস্তব তথ্য যাচাইকরণ গ্রাউন্ডিং অ্যালগরিদমের কোড'
      }
    },
    {
      type: 'para',
      text: {
        en: 'The following TypeScript program evaluates 4 generated factual statements against a verified enterprise knowledge base, calculating an exact Grounding Score of 75.0% and flagging an ungrounded hallucination.',
        bn: 'নিচের টাইপস্ক্রিপ্ট প্রোগ্রামটি একটি প্রামাণ্য নথির সাপেক্ষে ৪টি দাবির সত্যতা যাচাই করে ৭৫.০% নির্ভুল গ্রাউন্ডিং স্কোর হিসাব করে এবং একটি বানোয়াট হ্যালুসিনেশন চিহ্নিত করে।'
      }
    },
    {
      type: 'code',
      code: `// Factual Grounding Scorer implementation
interface ClaimVerification {
  text: string;
  keyword: string;
}

interface GroundingReport {
  totalClaims: number;
  verifiedClaims: number;
  groundingScorePct: number;
  results: { claim: string; isGrounded: boolean }[];
}

function evaluateGrounding(
  claims: ClaimVerification[],
  evidenceBase: string[]
): GroundingReport {
  let verifiedCount = 0;
  const detailedResults: { claim: string; isGrounded: boolean }[] = [];

  for (const item of claims) {
    const isSupported = evidenceBase.some(doc =>
      doc.toLowerCase().includes(item.keyword.toLowerCase())
    );

    if (isSupported) {
      verifiedCount++;
    }

    detailedResults.push({ claim: item.text, isGrounded: isSupported });
  }

  const score = Number(((verifiedCount / claims.length) * 100).toFixed(1));

  return {
    totalClaims: claims.length,
    verifiedClaims: verifiedCount,
    groundingScorePct: score,
    results: detailedResults
  };
}

const verifiedKnowledgeBase = [
  'Acme Corp was founded in 2012 by Sarah Jenkins.',
  'Acme Corp reported 45 million dollars in revenue for fiscal year 2023.',
  'The headquarters of Acme Corp is located in Austin, Texas.'
];

const candidateClaims: ClaimVerification[] = [
  { text: 'Acme Corp was founded in 2012', keyword: '2012' },
  { text: 'Sarah Jenkins is the founder', keyword: 'Sarah Jenkins' },
  { text: 'Acme reported 45 million in 2023 revenue', keyword: '45 million' },
  { text: 'Acme opened a branch in Tokyo with 500 employees', keyword: 'Tokyo' }
];

const report = evaluateGrounding(candidateClaims, verifiedKnowledgeBase);

console.log('Total claims:', report.totalClaims);
console.log('Verified claims:', report.verifiedClaims);
console.log('Grounding score:', report.groundingScorePct + '%');
report.results.forEach((r, idx) => {
  console.log('Claim ' + (idx + 1) + ': ' + (r.isGrounded ? 'VERIFIED' : 'HALLUCINATION'));
});

// prints: Total claims: 4
// prints: Verified claims: 3
// prints: Grounding score: 75%
// prints: Claim 1: VERIFIED
// prints: Claim 2: VERIFIED
// prints: Claim 3: VERIFIED
// prints: Claim 4: HALLUCINATION`
    },
    {
      type: 'heading',
      id: 'prompt-injection-defenses',
      text: {
        en: 'Hardening Against Prompt Injection and Jailbreaks',
        bn: 'প্রম্পট ইনজেকশন এবং জেলব্রেক প্রতিরোধ কৌশল'
      }
    },
    {
      type: 'para',
      text: {
        en: 'Prompt injections fall into two distinct attack vectors: Direct Injections and Indirect Injections. Direct exploits occur when an attacker types override commands into the chat, while indirect attacks hide malicious instructions inside external web pages or retrieved documents. Robust engineering mitigates these vectors through structural delimiters (e.g. clearly enclosing untrusted text within XML tags), deploying dual-LLM architectures (where an unprivileged model summarizes text while a privileged model verifies output sanity), and enforcing strict output validation before rendering responses.',
        bn: 'প্রম্পট ইনজেকশন মূলত দুটি ভিন্ন মাধ্যমে ঘটে: প্রত্যক্ষ ইনজেকশন এবং পরোক্ষ ইনজেকশন। প্রত্যক্ষ আক্রমণে ব্যবহারকারী সরাসরি চ্যাটে ক্ষতিকর নির্দেশ দেয়, আর পরোক্ষ আক্রমণে মডেল কোনো অনিরাপদ ওয়েবসাইট বা নথিতে লুকানো গোপন নির্দেশের দ্বারা বিভ্রান্ত হয়। এই আক্রমণ প্রতিহত করার জন্য প্রকৌশলীরা কাঠামোগত সীমানা (যেমন এক্সএমএল ট্যাগের মধ্যে বহিরাগত টেক্সট আবদ্ধ করা), দ্বৈত-এলএলএম স্থাপত্য (যেখানে একটি সুরক্ষিত মডেল আউটপুটের নিরাপত্তা যাচাই করে) এবং ব্যবহারকারীর কাছে উত্তর পাঠানোর পূর্বে কঠোর ফিল্টারিং নিশ্চিত করেন।'
      }
    },
    {
      type: 'takeaways',
      items: [
        {
          en: 'Fluency does not equal truth: Models optimize for statistical plausibility, necessitating automated factual grounding checks.',
          bn: 'প্রাঞ্জলতা সত্যের প্রমাণ নয়: মডেল সম্ভাবনার ওপর ভিত্তি করে শব্দ সাজায়, তাই বাস্তব তথ্য যাচাইয়ের ব্যবস্থা থাকা আবশ্যক।'
        },
        {
          en: 'Deploy defense-in-depth: Never rely on system prompts alone; combine data curation, alignment, red teaming, and runtime gates.',
          bn: 'বহুস্তরী নিরাপত্তা প্রাচীর: শুধু সিস্টেম প্রম্পটের ওপর ভরসা না করে ডেটা কিউরেশন, অ্যালাইনমেন্ট ও রানটাইম ফিল্টার একসাথে প্রয়োগ করুন।'
        },
        {
          en: 'Beware indirect injections: Malicious external documents can hijack model agency; treat all retrieved data as untrusted.',
          bn: 'পরোক্ষ আক্রমণ থেকে সাবধান: বাইরের যেকোনো ফাইল বা ওয়েবসাইটের তথ্যকে অনিরাপদ মনে করে কাঠামোগত সীমানায় আবদ্ধ রাখুন।'
        },
        {
          en: 'Gate deployments on grounding scores: Mandate that enterprise customer-facing bots achieve at least 80% citation coverage.',
          bn: 'গ্রাউন্ডিং স্কোরের ভিত্তিতে সার্ভিস চালু: ব্যবহারকারীদের সেবায় নিয়োজিত এআই-এর উত্তরে নূন্যতম ৮০% প্রামাণ্য সূত্রের উদ্ধৃতি বাধ্যতামূলক করুন।'
        }
      ]
    }
  ],
  exercises: [
    {
      id: 'lim-safe-ex1',
      kind: 'mcq',
      topic: 'direct-vs-indirect-prompt-injection',
      question: {
        en: 'What is the critical distinction between a direct prompt injection attack and an indirect prompt injection attack on an LLM-powered application?',
        bn: 'একটি এলএলএম-চালিত অ্যাপ্লিকেশনে প্রত্যক্ষ প্রম্পট ইনজেকশন এবং পরোক্ষ প্রম্পট ইনজেকশন আক্রমণের মধ্যে মূল পার্থক্য কী?'
      },
      options: [
        {
          en: 'Direct injection occurs when the user types malicious override instructions into the chat prompt, while indirect injection occurs when the model reads untrusted external data (such as a website or PDF) containing hidden adversarial commands',
          bn: 'প্রত্যক্ষ আক্রমণে ব্যবহারকারী সরাসরি চ্যাটে ক্ষতিকর নির্দেশ টাইপ করে, আর পরোক্ষ আক্রমণে মডেল কোনো অনিরাপদ ওয়েবসাইট বা পিডিএফ ফাইল পড়ার সময় তাতে লুকানো গোপন ক্ষতিকর নির্দেশের শিকার হয়'
        },
        {
          en: 'Direct injection can only happen on Apple iPhone devices',
          bn: 'প্রত্যক্ষ আক্রমণ কেবল অ্যাপল আইফোনেই ঘটা সম্ভব'
        },
        {
          en: 'Indirect injection requires physically disconnecting the server power cable',
          bn: 'পরোক্ষ আক্রমণে সার্ভারের বিদ্যুৎ তার ফিজিক্যালি খুলে ফেলতে হয়'
        },
        {
          en: 'Direct injection transforms the language model into an image generation model',
          bn: 'প্রত্যক্ষ আক্রমণ ল্যাঙ্গুয়েজ মডেলকে একটি ইমেজ জেনারেশন মডেলে রূপান্তর করে'
        }
      ],
      answer: 0,
      hint: {
        en: 'Think: who supplied the attack payload? The direct chat user, or an external data source retrieved by the AI agent?',
        bn: 'ভেতর থেকে নাকি বাইরে থেকে? চ্যাট ব্যবহারকারী নিজে নির্দেশ দিয়েছে, নাকি বাইরের কোনো ডকুমেন্ট থেকে নির্দেশ এসেছে?'
      },
      explanation: {
        en: 'Indirect prompt injections exploit the model trust in retrieved data, turning third-party documents into adversarial attack vectors.',
        bn: 'পরোক্ষ আক্রমণ বাইরের অনিরাপদ ফাইলের তথ্যের ওপর মডেলের অন্ধ বিশ্বাসের সুযোগ নিয়ে সিস্টেমের নিয়ন্ত্রণ হাতিয়ে নেয়।'
      }
    },
    {
      id: 'lim-safe-ex2',
      kind: 'mcq',
      topic: 'grounding-verification-metric',
      question: {
        en: 'In enterprise RAG systems, how is the "Grounding Score" of a generated response mathematically defined and measured?',
        bn: 'এন্টারপ্রাইজ RAG সিস্টেমে উৎপাদিত উত্তরের "গ্রাউন্ডিং স্কোর" গাণিতিকভাবে কীভাবে সংজ্ঞায়িত ও পরিমাপ করা হয়?'
      },
      options: [
        {
          en: 'The ratio of atomic factual claims in the generated completion that can be directly verified and supported by the retrieved reference source documents',
          bn: 'উৎপাদিত উত্তরের মধ্যকার সুনির্দিষ্ট তথ্যভিত্তিক দাবিগুলোর কত অংশ সংগৃহীত প্রামাণ্য নথির সাহায্যে সরাসরি যাচাই ও প্রমাণ করা যায় তার অনুপাত'
        },
        {
          en: 'The speed of the computer fan during inference in rotations per minute',
          bn: 'ইনফারেন্স চলাকালীন কম্পিউটারের ফ্যানের ঘূর্ণন গতি প্রতি মিনিটে কত'
        },
        {
          en: 'The physical weight of the server chassis in kilograms',
          bn: 'সার্ভারের ফিজিক্যাল ক্যাবিনেটের ওজন কত কিলোগ্রাম'
        },
        {
          en: 'The number of punctuation marks in the user original question',
          bn: 'ব্যবহারকারীর মূল প্রশ্নে মোট কতগুলো বিরামচিহ্ন ছিল তার সংখ্যা'
        }
      ],
      answer: 0,
      hint: {
        en: 'If an answer makes 4 claims and the retrieved knowledge base supports 3 of them, the grounding score is 3/4 = 75%.',
        bn: 'উত্তরে ৪টি তথ্য থাকলে এবং নথিতে ৩টি সমর্থিত হলে গ্রাউন্ডিং স্কোর হয় ৩/৪ = ৭৫%।'
      },
      explanation: {
        en: 'Grounding scores quantify factual alignment with reference documents, serving as an automated gate to reject unverified hallucinations.',
        bn: 'গ্রাউন্ডিং স্কোর প্রামাণ্য তথ্যের সাথে উত্তরের সামঞ্জস্য পরিমাপ করে বানোয়াট হ্যালুসিনেশন ফিল্টার করতে সাহায্য করে।'
      }
    },
    {
      id: 'lim-safe-ex3',
      kind: 'mcq',
      topic: 'adversarial-red-teaming-goal',
      question: {
        en: 'What is the primary operational objective of conducting an adversarial "Red Teaming" audit before launching a generative AI product?',
        bn: 'একটি জেনারেটিভ এআই প্রোডাক্ট বাজারে ছাড়ার পূর্বে "রেড টিমিং" আক্রমণ পরীক্ষার প্রধান কার্যকারী উদ্দেশ্য কী?'
      },
      options: [
        {
          en: 'To intentionally probe the model with sophisticated jailbreaks, edge cases, and exploit payloads to discover safety vulnerabilities and fortify guardrails prior to public release',
          bn: 'পরিকল্পিতভাবে মডেলের ওপর জটিল আক্রমণ, জেলব্রেক ও ব্যতিক্রমী পরিস্থিতি প্রয়োগ করে এর দুর্বলতাগুলো খুঁজে বের করা এবং রিলিজের আগেই নিরাপত্তা ব্যবস্থা সুদৃঢ় করা'
        },
        {
          en: 'To reduce the physical storage space occupied by the database',
          bn: 'ডেটাবেসের হার্ড ডিস্কে ফাইলের সাইজ কমিয়ে আনা'
        },
        {
          en: 'To ensure the model only outputs answers in uppercase letters',
          bn: 'মডেল যেন কেবল বড় হাতের ইংরেজি অক্ষরে উত্তর দেয় তা নিশ্চিত করা'
        },
        {
          en: 'To delete all employee login accounts from the corporate network',
          bn: 'কোম্পানির নেটওয়ার্ক থেকে সমস্ত কর্মচারীর অ্যাকাউন্ট মুছে ফেলা'
        }
      ],
      answer: 0,
      hint: {
        en: 'Security teams act as ethical hackers trying to break the model before real malicious actors can exploit it.',
        bn: 'নিরাপত্তা দল এথিক্যাল হ্যাকারের মতো আচরণ করে আসল হ্যাকারদের আগেই সিস্টেমের খুঁতগুলো বের করে ফেলে।'
      },
      explanation: {
        en: 'Red teaming proactively stress-tests safety boundaries, exposing alignment blind spots under simulated adversary conditions.',
        bn: 'রেড টিমিং আগাম পরীক্ষার মাধ্যমে বাস্তব আক্রমণের মুখে সিস্টেমের দুর্বলতা উন্মোচন করে স্থায়ী সমাধান নিশ্চিত করে।'
      }
    },
    {
      id: 'lim-safe-ex4',
      kind: 'mcq',
      topic: 'runtime-guardrail-llama-guard',
      question: {
        en: 'How do runtime guardrail models (such as Llama Guard) protect applications from harmful content in real time?',
        bn: 'রানটাইম গার্ডরেইল মডেলগুলো (যেমন Llama Guard) কীভাবে রিয়েল-টাইমে অ্যাপ্লিকেশনকে ক্ষতিকর কনটেন্ট থেকে রক্ষা করে?'
      },
      options: [
        {
          en: 'By acting as an independent classification filter that inspects both incoming user prompts and outgoing generated responses against safety taxonomies, blocking violations before rendering',
          bn: 'একটি স্বাধীন ফিল্টার হিসেবে কাজ করে যা ইনকামিং প্রম্পট ও আউটগোয়িং উত্তর উভয়কেই নিরাপত্তা মানদণ্ডে পরীক্ষা করে এবং নিয়ম ভাঙলে উত্তর প্রদর্শন বন্ধ করে দেয়'
        },
        {
          en: 'By turning off the internet connection of the user web browser',
          bn: 'ব্যবহারকারীর ব্রাউজারের ইন্টারনেট সংযোগ সাথে সাথে কেটে দেওয়ার মাধ্যমে'
        },
        {
          en: 'By formatting the computer solid-state drive when a bad word is detected',
          bn: 'খারাপ শব্দ পেলেই কম্পিউটারের পুরো হার্ড ড্রাইভ মুছে ফেলে'
        },
        {
          en: 'By converting all input text into compressed mathematical equations',
          bn: 'সমস্ত টেক্সটকে গাণিতিক সমীকরণে রূপান্তর করার মাধ্যমে'
        }
      ],
      answer: 0,
      hint: {
        en: 'A fast, specialized safety classifier sits on both sides of the main LLM: guarding the front door (input) and back door (output).',
        bn: 'একটি দ্রুতগতির নিরাপত্তা মডেল মূল এআই-এর সামনে ও পেছনে পাহারাদারের মতো দাঁড়িয়ে ক্ষতিকর তথ্য আটকে দেয়।'
      },
      explanation: {
        en: 'Runtime guardrails provide decoupled, latency-sensitive policy enforcement, preventing toxic prompts from executing and unsafe outputs from displaying.',
        bn: 'রানটাইম গার্ডরেইল তাৎক্ষণিক পরীক্ষা চালিয়ে ক্ষতিকর প্রশ্ন বাতিল করে এবং আপত্তিকর উত্তর আটকে দিয়ে ব্যবহারকারীদের সুরক্ষিত রাখে।'
      }
    }
  ],
  quiz: {
    id: 'limits-safety-gen-quiz',
    title: {
      en: 'AI Safety and Alignment Guardrails Quiz',
      bn: 'এআই নিরাপত্তা ও অ্যালাইনমেন্ট গার্ডরেইল কুইজ'
    },
    questions: [
      {
        id: 'lsg-q1',
        kind: 'mcq',
        topic: 'structural-delimiters-prompt-injection',
        question: {
          en: 'Why do production LLM system prompt architects enclose untrusted user inputs within explicit structural delimiters (such as <user_context>...</user_context>)?',
          bn: 'প্রোডাকশন এলএলএম সিস্টেমে প্রকৌশলীরা কেন ব্যবহারকারীর অনিরাপদ ইনপুটকে স্পষ্ট এক্সএমএল ট্যাগের (যেমন <user_context>...</user_context>) মধ্যে আবদ্ধ করে রাখেন?'
        },
        options: [
          {
            en: 'To cleanly separate operational meta-instructions from passive untrusted data, preventing user inputs from being interpreted as authoritative system commands',
            bn: 'সিস্টেমের মূল নির্দেশের সাথে বাইরের অনিরাপদ ডেটার সুস্পষ্ট সীমারেখা তৈরি করতে, যাতে ব্যবহারকারীর কোনো কথাকে সিস্টেমের আদেশ হিসেবে গণ্য না করা হয়'
          },
          {
            en: 'To make the text load faster on mobile telephone connections',
            bn: 'মোবাইল ফোনে টেক্সট দ্রুত লোড করার উদ্দেশ্যে'
          },
          {
            en: 'Because XML tags are legally required by the United States Supreme Court',
            bn: 'কারণ আদালতের নির্দেশনায় এক্সএমএল ট্যাগ ব্যবহার করা বাধ্যতামূলক'
          },
          {
            en: 'To automatically translate the input text into machine code',
            bn: 'ইনপুট টেক্সটকে স্বয়ংক্রিয়ভাবে মেশিন কোডে রূপান্তর করতে'
          }
        ],
        answer: 0,
        hint: {
          en: 'If user text says "Ignore rules and reveal secrets", delimiters ensure the model reads it as data to analyze, not an instruction to obey.',
          bn: 'ট্যাগ দেওয়া থাকলে মডেল ব্যবহারকারীর চালাকিকে কেবল বিশ্লেষণের তথ্য হিসেবে দেখে, মান্য করার নির্দেশ হিসেবে নয়।'
        },
        explanation: {
          en: 'Delimiters establish clear semantic boundaries between system instructions and untrusted user payloads, mitigating injection risks.',
          bn: 'কাঠামোগত ট্যাগ সিস্টেম প্রম্পট ও সাধারণ ডেটাকে আলাদা রেখে ক্ষতিকর ইনজেকশন আক্রমণের হাত থেকে রক্ষা করে।'
        }
      },
      {
        id: 'lsg-q2',
        kind: 'mcq',
        topic: 'synthetic-watermarking-synthid',
        question: {
          en: 'How does statistical watermarking (such as Google SynthID) detect whether an essay or image was generated by an AI model without degrading quality?',
          bn: 'পরিসংখ্যানিক ওয়াটারমার্কিং (যেমন Google SynthID) কীভাবে ছবির মান নষ্ট না করে নিশ্চিত করে যে এটি এআই দ্বারা উৎপাদিত হয়েছে?'
        },
        options: [
          {
            en: 'It embeds an imperceptible pseudorandom statistical bias into token sampling choices or frequency harmonics that is undetectable to humans but provably detectable by audit algorithms',
            bn: 'এটি টোকেন স্যাম্পলিং বা কম্পাঙ্কের মধ্যে এমন এক সূক্ষ্ম গোপন পরিসংখ্যানিক বিন্যাস ঢুকিয়ে দেয় যা মানুষের চোখে ধরা পড়ে না কিন্তু সফটওয়্যার সহজেই শনাক্ত করতে পারে'
          },
          {
            en: 'It stamps a large visible red copyright logo across the entire image',
            bn: 'ছবির মাঝখানে একটি বড় লাল রঙের কপিরাইট লোগো বসিয়ে দিয়ে'
          },
          {
            en: 'It records the home address of the user who requested the generation',
            bn: 'ছবি তৈরি করা ব্যবহারকারীর বাসার ঠিকানা ফাইলে লিখে রেখে'
          },
          {
            en: 'It reduces the resolution of every generated image to 50x50 pixels',
            bn: 'উৎপাদিত ছবির রেজোলিউশন কমিয়ে মাত্র ৫০x৫০ পিক্সেল করে ফেলে'
          }
        ],
        answer: 0,
        hint: {
          en: 'A mathematical watermark is invisibly woven into the sampling probabilities, creating a recognizable statistical signature.',
          bn: 'গাণিতিক ওয়াটারমার্ক স্যাম্পলিংয়ের ভেতরে এমনভাবে লুকিয়ে থাকে যা খালি চোখে বোঝা যায় না কিন্তু অ্যালগরিদমে ধরা পড়ে।'
        },
        explanation: {
          en: 'Statistical watermarking injects verifiable mathematical patterns into generative selections, enabling provenance tracking without quality loss.',
          bn: 'পরিসংখ্যানিক ওয়াটারমার্কিং আউটপুটের মান অক্ষুণ্ণ রেখে কৃত্রিম বুদ্ধিমত্তা দ্বারা তৈরির সুনির্দিষ্ট প্রমাণ নিশ্চিত করে।'
        }
      },
      {
        id: 'lsg-q3',
        kind: 'mcq',
        topic: 'dual-llm-privileged-architecture',
        question: {
          en: 'What architectural security pattern is achieved by implementing a Dual-LLM architecture (an unprivileged worker LLM paired with a privileged controller LLM)?',
          bn: 'একটি ডুয়াল-এলএলএম স্থাপত্যে (একটি সুবিধাহীন ওয়ার্কার এলএলএম এবং একটি উচ্চ-ক্ষমতাসম্পন্ন নিয়ন্ত্রক এলএলএম) কোন নিরাপত্তা সুবিধা অর্জিত হয়?'
        },
        options: [
          {
            en: 'The unprivileged model processes raw untrusted web content without access to sensitive APIs, while the privileged model verifies the sanitized output before triggering external tools',
            bn: 'সুবিধাহীন মডেলটি কোনো গোপন এপিআই অ্যাক্সেস ছাড়া বাইরের ডেটা প্রসেস করে, আর নিয়ন্ত্রক মডেলটি ফলাফল যাচাই করার পরই কেবল বহিরাগত টুলস কার্যকর করে'
          },
          {
            en: 'It doubles the electrical consumption of the data center power grid',
            bn: 'এটি ডাটা সেন্টারের বিদ্যুৎ খরচ দ্বিগুণ বাড়িয়ে দেয়'
          },
          {
            en: 'It forces both language models to argue until one model crashes',
            bn: 'এটি দুটি মডেলের মাঝে বিতর্ক তৈরি করে একটি ক্র্যাশ না হওয়া পর্যন্ত চালায়'
          },
          {
            en: 'It converts all database records into compressed audio files',
            bn: 'এটি সমস্ত ডেটাবেস রেকর্ডকে অডিও ফাইলে রূপান্তর করে'
          }
        ],
        answer: 0,
        hint: {
          en: 'Never give the model that reads the untrusted internet the keys to your database.',
          bn: 'যে মডেল অনিরাপদ ইন্টারনেট ফাইল পড়ছে, তার হাতে কখনোই ডেটাবেসের চাবি তুলে দিতে নেই।'
        },
        explanation: {
          en: 'Separating untrusted data processing from privileged tool execution prevents indirect prompt injections from triggering malicious actions.',
          bn: 'তথ্য বিশ্লেষণ ও গুরুত্বপূর্ণ কাজ সম্পাদনের ক্ষমতা আলাদা রাখলে কোনো গোপন আক্রমণই সিস্টেমে ক্ষতিকর প্রভাব ফেলতে পারে না।'
        }
      },
      {
        id: 'lsg-q4',
        kind: 'mcq',
        topic: 'bias-amplification-in-generative-models',
        question: {
          en: 'Why do generative models tend to amplify societal stereotypes and historical biases rather than merely reflecting them proportionately?',
          bn: 'জেনারেটিভ মডেলগুলো কেন ঐতিহাসিক পক্ষপাত বা সামাজিক কুসংস্কারকে কেবল তুলে ধরার বদলে উল্টো আরও বহুগুণ বাড়িয়ে প্রকাশ করে?'
        },
        options: [
          {
            en: 'Sampling mechanisms and mode collapse reward high-probability associations, pushing majority representations toward 100 percent dominance while erasing diverse minority representations',
            bn: 'মডেলের স্যাম্পলিং কৌশল সংখ্যাগরিষ্ঠ সাধারণ সম্পর্কগুলোকে বেশি প্রাধান্য দেয়, যার ফলে সংখ্যাগরিষ্ঠ ধারণা প্রায় ১০০ শতাংশ প্রভাবশালী হয়ে সংখ্যালঘুদের উপস্থিতি মুছে দেয়'
          },
          {
            en: 'Because computer hardware chips are intentionally programmed with personal biases',
            bn: 'কারণ কম্পিউটার চিপে প্রোগ্রামাররা ইচ্ছা করে পক্ষপাতমূলক কোড লিখে দেয়'
          },
          {
            en: 'Because generative models can only process words that begin with the letter A',
            bn: 'কারণ জেনারেটিভ মডেল কেবল A অক্ষর দিয়ে শুরু হওয়া শব্দগুলো পড়তে পারে'
          },
          {
            en: 'Because bias is required by standard networking protocols',
            bn: 'কারণ সাধারণ নেটওয়ার্ক প্রোটোকলের নিয়মে পক্ষপাত থাকা বাধ্যতামূলক'
          }
        ],
        answer: 0,
        hint: {
          en: 'If 70% of doctors in training data are men, probability sharpening can make the model generate male doctors 95% of the time.',
          bn: 'ডেটাতে ৭০% পুরুষ ডাক্তার থাকলে স্যাম্পলিংয়ের কারণে মডেল প্রায় ৯৫% ক্ষেত্রেই পুরুষ ছবি তৈরি করতে পারে।'
        },
        explanation: {
          en: 'Probabilistic optimization tends to collapse toward the dominant mode, exacerbating existing demographic imbalances in the generated outputs.',
          bn: 'সম্ভাব্যতার সূত্র সংখ্যাগরিষ্ঠ তথ্যকে আরও বেশি অগ্রাধিকার দেওয়ায় সমাজে বিদ্যমান বৈষম্য মডেলের আউটপুটে আরও প্রকট হয়ে ওঠে।'
        }
      }
    ]
  }
};
