import type { TechHub } from '../../lib/types';
import { networkingProtocolsAndToolsLesson } from './lessons/networking-protocols-and-tools';
import { requestJourneyLesson } from './lessons/request-journey';
import { httpDeepLesson } from './lessons/http-deep';
import { theDnsCensusLesson } from './lessons/the-dns-census';
import { theTcpTidekeeperLesson } from './lessons/the-tcp-tidekeeper';
import { theTlsNotaryLesson } from './lessons/the-tls-notary';
import { theEdgeCartelLesson } from './lessons/the-edge-cartel';
import { theLoadBalancerCourtLesson } from './lessons/the-load-balancer-court';
import { theTreatyShelfLesson } from './lessons/the-treaty-shelf';
import { theIncidentWatchtowerLesson } from './lessons/the-incident-watchtower';

export const networkingHub: TechHub = {
  slug: 'networking' as never,
  name: 'Networking',
  icon: '🌐',
  tagline: {
    en: 'Names are liens over physics — and every outage is some office stamping an address that moved first.',
    bn: 'নাম হলো পদার্থবিদ্যার ওপর খালনামা — আর প্রতিটি বিভ্রাট কোনো না কোনো অফিসের মোহর, যেখানে ঠিকানাটি আগে সরে গেছে।',
  },
  intro: {
    en: 'Networking is not a cloud; it is a ledger of round trips kept by nine offices, each with its own arithmetic, its own doctrine, and its own signature page. THE REQUEST JOURNEY walks one click from URL to pixels with the full fare table in hand: parse, resolve, shake hands, notarize, ask, receive — every stop priced in the one currency the user spends, which is patience. HTTP: THE DEEP EXPEDITION then descends into the treaty treasury itself: methods as licensed verbs, status codes as verdict instruments, headers as the actual contract, and the three-generation war that rewrote the speech from HTTP/1.1 through H2 to H3. THE DNS CENSUS opens the first office: nobody ships packets to a name, so the census bureaus translate — and every translation is a lien with a rent, a TTL doctrine, a panic-window law (no change negotiated inside the window), a birthday-forgery defense, and an unbreakable entry discipline. THE TCP TIDEKEEPER rents order: the three-way handshake paid once, sequence arithmetic as the pipeline ledger, congestion windows grown by slow start and reined by AIMD, loss recovered three duplicate knocks before the outraged RTO — and QUIC rehearsed as the young clerk who moved the ledger into userland. THE TLS NOTARY seals the speech on the public road: 1.2’s two expensive trips versus 1.3’s one, certificates as notarized warrants under a tree of seals, SNI whispered, the transparency ledger public by statute, resumption priced, HSTS preloaded as permanent residency. THE EDGE CARTEL relocates physics itself: distance is the only negotiable rent, points of presence as branch vaults, anycast as the one address announced everywhere, shield tiers between the herd and the origin, and the purge contract signed knowing its propagation window. THE LOAD BALANCER COURT convenes the scheduling tribunal: round robin convicted for the equal-work assumption, least-connections enthroned for heterogeneous fleets, two-random-envelopes proven to beat omniscience, consistent hashing with its hundred-sixty-nine virtual positions, health checks staffed as a priesthood, slow start and probation as the new clerk’s onboarding. THE TREATY SHELF archives the generations: 0.9, 1.0, 1.1, 2, 3 — each amendment fixing the previous cure’s side effect, from head-of-line blocking up multiple stacks to the priority tomb to QUIC’s per-stream ordering — and the Alt-Svc eviction notice as the only lawful way to change a protocol under a living city. And THE INCIDENT WATCHTOWER turns the whole apparatus operational: errors priced as currency in the exchequer window, the budget re-consulted on a rolling ledger, SEV chairs seated by law with one voice and no heroes, postmortems that file factors and never blame persons, and the thirteenth-week drill calendar whose verified silence is the only silence that counts. Nine lessons, nine offices, one wire — read them in order and every outage you will ever paged for becomes arithmetic you have already done.',
    bn: 'নেটওয়ার্কিং মেঘ নয়; এটি রাউন্ড-ট্রিপের খাতা, যা রাখে নয়টি অফিস — প্রতিটির নিজস্ব পাটিগণিত, নিজস্ব মতবাদ, আর নিজস্ব স্বাক্ষর-পৃষ্ঠা। অনুরোধ-যাত্রা একটি ক্লিক হেঁটে যায় URL থেকে পিক্সেল পর্যন্ত, হাতে পূর্ণ ভাড়া-তালিকা নিয়ে: পার্স, সমাধান, হাত-মেলানো, নোটারি, জিজ্ঞাসা, গ্রহণ — প্রতি স্টপ মূল্যিত সেই এক মুদ্রায় যা ব্যবহারকারী খরচ করে: ধৈর্য। HTTP: গভীর-অভিযান তারপর নেমে যায় চুক্তি-কোষাগারেই: লাইসেন্সকৃত ক্রিয়াপদরূপে মেথড, রায়-হিস্তনাদরূপে স্ট্যাটাস কোড, আসল চুক্তিরূপে হেডার, আর তিন-প্রজন্মের যুদ্ধ যা ভাষা নতুন করে লিখেছে HTTP/1.1 থেকে H2 হয়ে H3 পর্যন্ত। DNS-গণনা-কার্যালয় প্রথম অফিস খোলে: নামে প্যাকেট পাঠায় কেউ না, তাই পরিগণনা-ব্যুরোগুলো অনুবাদ করে — আর প্রতি অনুবাদ একটি খালনামা, যার ভাড়া আছে, TTL-মতবাদ আছে, আতঙ্ক-জানালা-বিধি আছে (জানালার ভেতরে পরিবর্তন দরকষাকষি হয় না), জন্মদিন-জালিয়াতি-প্রতিরক্ষা আছে, আর অচ্যুত এন্ট্রি-শৃঙ্খলা আছে। TCP-জোয়াররক্ষী ক্রম ভাড়া দেয়: একবার পরিশোধিত তিন-দিকীয় হ্যান্ডশেক, পাইপলাইন-খাতারূপে ক্রমিক-পাটিগণিত, ধীর-সূচনায় বর্ধিত ও AIMD-এ সংযত কনজেশন-উইন্ডো, তিন নক-জোড়া দিয়ে পুনরুদ্ধার আর তারপর ক্ষুব্ধ RTO — আর QUIC মহড়াকৃত, নবীন করণিকরূপে যে খাতা সরিয়ে নিল ইউজারল্যান্ডে। TLS-নোটারি জনরাস্তায় ভাষা মোহর করে: ১.২-র দুটি ব্যয়বহুল ভ্রমণ বনাম ১.৩-র একটি, সিল-বৃক্ষের নিচে নোটারিকৃত পরোয়ানারূপে সার্টিফিকেট, ফিসফিসে বলা SNI, বিধানে জনসমক্ষে স্বচ্ছতা-খাতা, মূল্যিত পুনর্গ্রহণ, স্থায়ী বসবাসরূপে HSTS প্রিলোড। প্রান্ত-কারটেল পদার্থবিদ্যা নিজেই সরিয়ে দেয়: দূরত্বই একমাত্র দর-কষাকষিযোগ্য ভাড়া, শাখা-তিজোরিরূপে পয়েন্ট-অব-প্রেজেন্স, সর্বত্র ঘোষিত এক ঠিকানারূপে অ্যানিকাস্ট, পাল আর অরিজিনের মাঝে ঢাল-স্তর, আর প্রসারণ-জানালা জেনেই সই করা পার্জ-চুক্তি। লোড-ব্যালান্সার-দরবার তফসিল-ট্রাইব্যুনাল গঠন করে: সমান-কাজ-অনুমানে রাউন্ড-রবিনের দণ্ডাজ্ঞা, বৈষম্যময়-বহরে সর্বনিম্ন-কানেকশন-এর সিংহাসন, সর্বজ্ঞতাকে হারানো দুই-এলোমেলো-খামের প্রমাণ, একশো-ঊনসত্তর ভার্চুয়াল-অবস্থানসহ কনসিসটেন্ট-হ্যাশিং, পুরোহিতবর্গরূপে জনবদ্ধ হেলথ-চেক, আর নবীন করণিকের অনবোর্ডিংরূপে ধীর-সূচনা ও শর্তাধীনতা। চুক্তিপত্র-তাক প্রজন্মগুলো সংরক্ষণ করে: ০.৯, ১.০, ১.১, ২, ৩ — প্রতি সংশোধনী আগের প্রতিকারের পার্শ্ব-প্রতিক্রিয়া ঠিক করে, একাধিক স্ট্যাকজুড়ে হেড-অফ-লাইন ব্লকিং থেকে অগ্রাধিকার-কবর পর্যন্ত QUIC-এর স্ট্রিমপ্রতি-ক্রমান্বয়ন পর্যন্ত — আর জীবন্ত নগরীর নিচে প্রোটোকল বদলানোর একমাত্র বৈধ পথরূপে Alt-Svc উচ্ছেদ-নোটিশ। আর ঘটনা-পর্যবেক্ষণমিনার পুরো যন্ত্রপাতিকে অপারেশনাল করে তোলে: কোষাগার-জানালায় মুদ্রারূপে মূল্যিত ত্রুটি, চলতি-খাতায় পুনঃপরামর্শিত বাজেট, বিধিতে বসা SEV-আসন — একটি কণ্ঠ, শূন্য নায়ক — ব্যক্তিকে দোষ না-দেওয়া কারণ-দাখিলকৃত পরবৃত্তান্ত, আর ত্রয়োদশ-সপ্তাহের মহড়া-পঞ্জিকা, যার যাচাইকৃত নীরবতাই একমাত্র গণনাযোগ্য নীরবতা। নয়টি পাঠ, নয়টি অফিস, একটি তার — ক্রমে পড়ুন, আর আপনার জীবনে পেজ করা প্রতিটি বিভ্রাট হয়ে যাবে এমন পাটিগণিত যা আপনি আগেই করে ফেলেছেন।',
  },
  lessons: [networkingProtocolsAndToolsLesson, requestJourneyLesson,
    httpDeepLesson,
    theDnsCensusLesson,
    theTcpTidekeeperLesson,
    theTlsNotaryLesson,
    theEdgeCartelLesson,
    theLoadBalancerCourtLesson,
    theTreatyShelfLesson,
    theIncidentWatchtowerLesson,],
  references: [
    {
      group: { en: 'The journey cabinet', bn: 'যাত্রা-ক্যাবিনেট' },
      items: [
        { term: 'the RTT ledger', def: { en: 'Every stop on the journey is priced in round trips: DNS (0–2), TCP handshake (1), TLS 1.3 (1 more), then the request itself. Cutting a round trip is worth more than cutting a millisecond of work.', bn: 'যাত্রার প্রতি স্টপ মূল্যিত রাউন্ড-ট্রিপে: DNS (0–2), TCP হ্যান্ডশেক (1), TLS 1.3 (আরও 1), তারপর রিকোয়েস্ট নিজেই। একটি রাউন্ড-ট্রিপ কাটা এক মিলিসেকেন্ড কাজ কাটার চেয়ে বেশি মূল্যবান।' } },
        { term: 'TTL ≥ panic window', def: { en: 'No name change is negotiated inside the window where the old record can still be cached. A 30-second TTL is a 30-minute riot rehearsal; settle names long before you move them.', bn: 'যে জানালায় পুরনো রেকর্ড এখনো ক্যাশে থাকতে পারে, তার ভেতরে নাম-পরিবর্তন দরকষাকষি হয় না। ৩০-সেকেন্ডের TTL হলো ৩০-মিনিটের দাঙ্গা-মহড়া; সরানোর অনেক আগে নাম নিষ্পত্তি করুন।' } },
        { term: 'the birthday forgery', def: { en: 'Forging a DNS answer needs a matching 16-bit transaction ID ≈ 255 tickets per second of guessing at 50/50 — defend with source-port randomization, 0x20 case noise, and DNSSEC signatures at the record, not hope.', bn: 'DNS-উত্তর জাল করতে লাগে মেলানো 16-বিট ট্রানজ্যাকশন-আইডি ≈ সেকেন্ডে ২৫৫ টিকিট, 50/50 সম্ভাবনায় — প্রতিরক্ষা করুন সোর্স-পোর্ট-এলোমেলোকরণ, 0x20 কেস-শব্দ, আর রেকর্ডে DNSSEC-স্বাক্ষর দিয়ে, আশা দিয়ে না।' } },
        { term: 'handshake rent', def: { en: 'TCP: 1 RTT paid once per connection. TLS 1.2: +2 RTT; TLS 1.3: +1; resumption/0-RTT: the early-data proviso replay must be priced, not assumed free.', bn: 'TCP: কানেকশনপ্রতি একবার 1 RTT পরিশোধিত। TLS 1.2: +২ RTT; TLS 1.3: +১; পুনর্গ্রহণ/0-RTT: আর্লি-ডেটা-শর্তের রিপ্লে মূল্যায়ন করতে হবে, বিনামূল্যে ধরা যাবে না।' } },
        { term: 'cwnd arithmetic', def: { en: 'Slow start doubles each RTT until ssthresh; AIMD then adds one segment per RTT and halves on loss. The window is a speed limit the network keeps rewriting — drive the arithmetic, not the wish.', bn: 'যতক্ষণ না ssthresh, ধীর-সূচনা প্রতি RTT-তে দ্বিগুণ; AIMD তখন প্রতি RTT-তে যোগ করে এক সেগমেন্ট আর ক্ষতিতে অর্ধেক করে। উইন্ডো হলো গতিসীমা যা নেটওয়ার্ক বারবার লিখে দেয় — চালান পাটিগণিত, ইচ্ছা নয়।' } },
        { term: 'the 169 positions', def: { en: 'Consistent hashing with ~169 virtual positions per server keeps the strip even when membership shifts: only the keys between the departed position and its neighbor move, ~1/N of the load.', bn: 'সার্ভারপ্রতি ~১৬৯ ভার্চুয়াল-অবস্থানসহ কনসিসটেন্ট-হ্যাশিং ফালি সমান রাখে সদস্যতা বদলালেও: শুধু চলে-যাওয়া অবস্থান আর তার প্রতিবেশীর মাঝের কী-গুলো সরে, ভারের ~1/N।' } },
      ],
    },
    {
      group: { en: 'The operation cabinet', bn: 'অপারেশন-ক্যাবিনেট' },
      items: [
        { term: 'power of two choices', def: { en: 'Sample two servers at random, send the envelope to the less loaded: maximum queue ~log log n instead of omniscience’s coordination bill. Scheduling is a statistical doctrine, not an oracle.', bn: 'দুই সার্ভার এলোমেলো নমুনা করুন, খাম পাঠান কম-ভারাক্রান্তটিতে: সর্বোচ্চ কাতার ~log log n, সর্বজ্ঞতার সমন্বয়-বিলের বদলে। তফসিল পরিসংখ্যানিক মতবাদ, জ্যোতিষী নয়।' } },
        { term: 'the exchequer window', def: { en: '99.9% availability over 30.4 days books 43.2 minutes of spendable error budget. The ledger, not the alarm, decides launch gates: 15 spent, 28.2 left — re-consult on the rolling window.', bn: '৩০.৪ দিনে 99.9% প্রাপ্যতা বুক করে ৪৩.২ মিনিট খরচযোগ্য ত্রুটি-বাজেট। লঞ্চ-গেট ঠিক করে খাতা, অ্যালার্ম নয়: ১৫ খরচ, ২৮.২ বাকি — চলতি-জানালায় পুনঃপরামর্শ করুন।' } },
        { term: 'the chair law', def: { en: 'One commander, one voice, zero heroes. Command speaks in typed announcements so the log is the law; expertise is consulted, not supreme; the scribe’s ledger outlives every memory.', bn: 'এক কমান্ডার, এক কণ্ঠ, শূন্য নায়ক। কমান্ড কথা বলে টাইপকৃত ঘোষণায়, যাতে লগ-ই বিধি; দক্ষতা পরামর্শকৃত, সর্বোচ্চ নয়; লিপিকরের খাতা বাঁচে প্রতি স্মৃতির পরেও।' } },
        { term: 'unverified silence', def: { en: 'Silence you did not verify is a noisy alert wearing a costume. The synthetic census plus signed reading slips is the only silence that counts — a drill without readings is theater.', bn: 'যে নীরবতা যাচাই করেননি তা পোশাকি উচ্চ-কোলাহল-সতর্কতা। কৃত্রিম পরিগণনা ও স্বাক্ষরিত পাঠ-স্লিপই একমাত্র গণনাযোগ্য নীরবতা — পাঠ ছাড়া মহড়া মঞ্চায়ন।' } },
        { term: 'purge vs version', def: { en: 'Versioned names are purged by renaming — instantaneous, free, and safe; signature purges carry a propagation window you must price before signing. Purge only what versioning cannot reach.', bn: 'সংস্করণকৃত নাম পার্জ হয় নামান্তরে — তাৎক্ষণিক, বিনামূল্যে, নিরাপদ; স্বাক্ষর-পার্জ বহন করে প্রসারণ-জানালা, যা সইয়ের আগে মূল্যায়ন করতেই হবে। যেখানে সংস্করণ পৌঁছায় না, কেবল তাতেই পার্জ করুন।' } },
        { term: 'the generations column', def: { en: 'Every client fleet is read as a column of protocol generations; Alt-Svc is the eviction notice with a grace window. You never cut off an old generation without an observed resident count of zero.', bn: 'প্রতি ক্লায়েন্ট-বহর পড়া হয় প্রোটোকল-প্রজন্মের কলাম হিসেবে; Alt-Svc হলো কর্মকাল-জানালাযুক্ত উচ্ছেদ-নোটিশ। পর্যবেক্ষিত বাসিন্দা-গণনা শূন্য না হওয়া পর্যন্ত পুরনো প্রজন্মের সংযোগ কভু কাটা যায় না।' } },
      ],
    },
  ],
  roadmap: [
    { stage: 1, title: { en: 'A name is not a door', bn: 'নাম দুয়ার নয়' }, detail: { en: 'The journey fare table end to end; then the census bureaus: stub to resolver to root to TLD to authoritative, TTL as lien, the panic-window law, forgeries and their arithmetic defenses.', bn: 'সর্বতোভাবে যাত্রা-ভাড়া-তালিকা; তারপর পরিগণনা-ব্যুরো: স্টাব থেকে রিজলভার থেকে রুট থেকে TLD থেকে অথরিটেটিভ, খালনামারূপে TTL, আতঙ্ক-জানালা-বিধি, জালিয়াতি ও তাদের পাটিগণিত-প্রতিরক্ষা।' } },
    { stage: 2, title: { en: 'Rent order, notarize speech', bn: 'ক্রম ভাড়া নিন, ভাষা নোটারি করুন' }, detail: { en: 'The tidekeeper’s pipeline ledger — handshake, sequence numbers, cwnd, AIMD, loss recovery — then the notary: TLS 1.2 vs 1.3 trip arithmetic, certificate trees, the transparency ledger, HSTS.', bn: 'জোয়াররক্ষীের পাইপলাইন-খাতা — হ্যান্ডশেক, ক্রমিক-সংখ্যা, cwnd, AIMD, ক্ষতি-পুনরুদ্ধার — তারপর নোটারি: TLS 1.2 বনাম 1.3 ভ্রমণ-পাটিগণিত, সার্টিফিকেট-বৃক্ষ, স্বচ্ছতা-খাতা, HSTS।' } },
    { stage: 3, title: { en: 'Move the physics', bn: 'পদার্থবিদ্যা সরান' }, detail: { en: 'The edge cartel prices distance as rent: PoPs, anycast, shield tiers, purge windows. The court then schedules what arrives: round robin audited, power of two proven, hashing strips kept even.', bn: 'প্রান্ত-কারটেল দূরত্ব মূল্যায়ন করে ভাড়ায়: PoP, অ্যানিকাস্ট, ঢাল-স্তর, পার্জ-জানালা। আদালত তারপর পৌঁছে-যাওয়াদের তফসিল করে: রাউন্ড-রবিন নিরীক্ষিত, দুই-এর-ক্ষমতা প্রমাণিত, হ্যাশিং-ফালি সমান রক্ষিত।' } },
    { stage: 4, title: { en: 'Read the treaty shelf', bn: 'চুক্তিপত্র-তাক পড়ুন' }, detail: { en: 'The deep expedition first — verbs, verdicts, headers — then the generations: why each HTTP amendment arrived, which cure bred which disease, and how Alt-Svc evicts a protocol lawfully.', bn: 'আগে গভীর-অভিযান — ক্রিয়াপদ, রায়, হেডার — তারপর প্রজন্মগণ: কেন এল প্রতি HTTP-সংশোধনী, কোন প্রতিকার জন্ম দিল কোন রোগ, আর কীভাবে Alt-Svc বৈধভাবে প্রোটোকল উচ্ছেদ করে।' } },
    { stage: 5, title: { en: 'Operate the watchtower', bn: 'পর্যবেক্ষণমিনার চালান' }, detail: { en: 'Incidents as currency: SLO from patience, budget as exchequer, rolling-window re-consult, the chair law in SEV rooms, blameless factor maps, and the thirteen-week drill charter with verified silence.', bn: 'মুদ্রারূপে ঘটনা: ধৈর্য থেকে SLO, কোষাগাররূপে বাজেট, চলতি-জানালা পুনঃপরামর্শ, SEV-কক্ষে আসন-বিধি, নির্দোষ কারণ-মানচিত্র, আর যাচাইকৃত-নীরবতাসহ ত্রয়োদশ-সপ্তাহের মহড়া-সনদ।' } },
  ],
  projects: [
    {
      title: { en: 'LedgerBench: the RTT accountant', bn: 'লেজারবেঞ্চ: RTT হিসাবরক্ষক' },
      brief: { en: 'Build a fare table for a real site from five vantage points: time DNS resolution, TCP handshake, TLS handshake, and TTFB separately (browser devtools, curl -w, or a small script), then reconcile each number with the hub’s office arithmetic — which stops cost round trips, which were warmed by resumption or HSTS, which latencies are distance rent an edge could erase. Publish the five-ledger table and the three changes with the largest predicted payoff, each change priced in round trips, not vibes.', bn: 'পাঁচ দৃষ্টিকোণ থেকে একটি প্রকৃত সাইটের ভাড়া-তালিকা নির্মাণ করুন: DNS-সমাধান, TCP-হ্যান্ডশেক, TLS-হ্যান্ডশেক আর TTFB আলাদা করে সময় নিন (ব্রাউজার ডেভটুলস, curl -w, বা ছোট স্ক্রিপ্ট), তারপর প্রতি সংখ্যা মিলিয়ে দেখুন হাবের অফিস-পাটিগণিতের সাথে — কোন স্টপ খরচ করে রাউন্ড-ট্রিপ, কোনটি উষ্ণ হয়েছে পুনর্গ্রহণ বা HSTS-এ, কোন লেটেন্সি দূরত্ব-ভাড়া যা এজ মুছে দিতে পারে। পাঁচ-খাতার সারণি আর সর্বোচ্চ-প্রত্যাশিত-প্রতিদানের তিন পরিবর্তন প্রকাশ করুন — প্রতিটি মূল্যিত রাউন্ড-ট্রিপে, আবেগে নয়।' },
      difficulty: 'beginner',
    },
    {
      title: { en: 'CensusAuditor: the lien walk', bn: 'সেনসাসঅডিটর: খালনামা-পদভ্রমণ' },
      brief: { en: 'Write a resolver-walk tool that escorts three real domains through the full census: stub to recursive to root to TLD to authoritative, capturing every record, TTL, and signature state on the way. The report card per name must grade: TTL against the panic-window law (could this name actually move under fire?), negative-cache TTL sanity, DNSSEC chain completeness, and any CNAME chain depth priced in added lookups. It must convict exactly the names that cannot survive an emergency migration and write the remediation as ledger entries, one lien per line.', bn: 'একটি রিজলভার-ওয়াক টুল লিখুন যা তিনটি প্রকৃত ডোমেইনকে পূর্ণ পরিগণনায় সহযাত্রা করে: স্টাব থেকে রিকার্সিভ থেকে রুট থেকে TLD থেকে অথরিটেটিভ, পথে প্রতি রেকর্ড, TTL আর স্বাক্ষর-অবস্থা ধরে। প্রতি নামের রিপোর্ট-কার্ড দেবে মূল্যায়ন: আতঙ্ক-জানালা-বিধির বিপরীতে TTL (আগুনের মধ্যে এই নাম কি সত্যিই সরতে পারে?), নেতিবাচক-ক্যাশ TTL-শুদ্ধতা, DNSSEC-চেইন-সম্পূর্ণতা, আর CNAME-চেইন-গভীরতা মূল্যিত অতিরিক্ত-লুকআপে। টুলকে দোষী সাব্যস্ত করতে হবে হুবহু সেই নামগুলোকে যারা জরুরি-স্থানান্তর টিকতে পারে না, আর প্রতিকার লিখতে হবে খাতা-এন্ট্রি আকারে, লাইনপ্রতি একটি খালনামা।' },
      difficulty: 'intermediate',
    },
    {
      title: { en: 'TreatyMirror: the three-generation bench', bn: 'ট্রিটিমিরর: তিন-প্রজন্মের বেঞ্চ' },
      brief: { en: 'Serve the same 100-asset page over HTTP/1.1, H2, and H3 on a local rig, then drive all three through injected latency and 1% packet loss. Measure full-load time, per-asset waterfall, and the exact head-of-line casualty list per generation: one slow asset must strangle H1’s six sockets, crowd H2’s single connection, and be quarantined to its own stream in H3. The deliverable is the verdict table across (latency × loss × generation) plus the migration memo your future fleet needs: which clients, which Alt-Svc grace window, which observed resident counts before the old treaty retires.', bn: 'একই ১০০-সম্পদের পৃষ্ঠা পরিবেশন করুন HTTP/1.1, H2 আর H3-এ স্থানীয় রিগে, তারপর তিনটিকেই চালান ইনজেক্টেড লেটেন্সি আর ১% প্যাকেট-ক্ষতির মধ্য দিয়ে। মাপুন পূর্ণ-লোড-কাল, সম্পদপ্রতি-জলপ্রপাত, আর প্রজন্মপ্রতি হুবহু হেড-অফ-লাইন-হতাহত-তালিকা: একটি ধীর সম্পদকে হবে H1-এর ছয় সকেট শ্বাসরোধ করা, H2-এর একক কানেকশন ঠাসানো, আর H3-এ তার নিজস্ব স্ট্রিমে বিচ্ছিন্ন থাকা। ফলাফল (লেটেন্সি × ক্ষতি × প্রজন্ম)-জুড়ে রায়-সারণি, সঙ্গে স্থানান্তর-মেমো যা ভবিষ্যৎ-বহরের দরকার: কোন ক্লায়েন্ট, কোন Alt-Svc কর্মকাল-জানালা, পুরনো চুক্তি অবসরের আগে কোন পর্যবেক্ষিত বাসিন্দা-গণনা।' },
      difficulty: 'advanced',
    },
    {
      title: { en: 'WatchtowerDrill: the thirteen-week charter', bn: 'ওয়াচটাওয়ারড্রিল: ত্রয়োদশ-সপ্তাহ সনদ' },
      brief: { en: 'Assemble the full drill charter for a toy fleet (three services, one database, one edge tier): a thirteen-week calendar of six pillar-tagged drills ordered by seam-contamination risk, each with a BTC budget (blast, time, cost), taped findings due within one week, and the compliance docket — synthetic census probes, signed reading slips, and the drill-cadence ledger proving every reading was taken. Include the escalation statute: unverified silence recorded as noisy-alert severity, budget exceedance filed as an incident with pride, and the graduation law a drill earns only when its remediation ships inside the budget it set itself.', bn: 'একটি খেলনা-বহরের পূর্ণ মহড়া-সনদ সাজান (তিন সার্ভিস, একটি ডেটাবেস, একটি এজ-স্তর): ছয় স্তম্ভ-ট্যাগকৃত মহড়ার ত্রয়োদশ-সপ্তাহের পঞ্জিকা, যবে-দুষণ-ঝুঁকিতে সাজানো, প্রতিটির BTC-বাজেটসহ (ব্লাস্ট-ব্যাসার্ধ, সময়, খরচ), এক সপ্তাহের মধ্যে ধার্য টেপকৃত-ফলাফল, আর সম্মতি-পর্ব — কৃত্রিম পরিগণনা-প্রোব, স্বাক্ষরিত পাঠ-স্লিপ, আর মহড়া-তাল-খাতা যা প্রমাণ করে প্রতিটি পাঠ নেওয়া হয়েছিল। উর্ধ্বতন-বিধান দিন: অযাচাইকৃত-নীরবতা লিপিবদ্ধ উচ্চ-কোলাহল-সতর্কতার তীব্রতায়, বাজেট-অতিক্রম দাখিলকৃত গর্বসহ ঘটনারূপে, আর স্নাতক-বিধি যা মহড়া অর্জন করে কেবল তখনই যখন তার প্রতিকার বের হয় তার নিজের-দেওয়া বাজেটের মধ্যে।' },
      difficulty: 'advanced',
    },
  ],
  bestPractices: [
    { en: 'Price every stop in round trips, then reuse mercilessly: warm connections, resumed sessions, preloaded HSTS — a round trip avoided beats a millisecond saved, every single time.', bn: 'প্রতি স্টপ মূল্যায়ন করুন রাউন্ড-ট্রিপে, তারপর পুনব্যবহার করুন নির্মমভাবে: উষ্ণ কানেকশন, পুনর্গৃহীত সেশন, প্রিলোডেড HSTS — এড়ানো রাউন্ড-ট্রিপ জয় করে সাশ্রয়ী মিলিসেকেন্ডকে, প্রতিবার।' },
    { en: 'Settle names before you move them: TTL decisions are migration treaties signed in peacetime — inside the panic window the law is already written and you are only reading it.', bn: 'সরানোর আগে নাম নিষ্পত্তি করুন: TTL-সিদ্ধান্ত হলো শান্তিকালে সই করা স্থানান্তর-চুক্তি — আতঙ্ক-জানালার ভেতরে বিধি আগেই লেখা, আপনি কেবল তা পড়ছেন।' },
    { en: 'Defend the census with arithmetic, not hope: source-port randomization, 0x20 noise, DNSSEC at the record — the birthday bound is cheap enough that an unsigned name is an open vault with a polite note.', bn: 'পরিগণনা রক্ষা করুন পাটিগণিতে, আশায় নয়: সোর্স-পোর্ট-এলোমেলোকরণ, 0x20 শব্দ, রেকর্ডে DNSSEC — জন্মদিন-সীমা যথেষ্ট সস্তা, তাই স্বাক্ষরহীন নাম হলো ভদ্র-নোটসহ খোলা তিজোরি।' },
    { en: 'Audit the scheduler’s assumptions before trusting its arithmetic: round robin dies on unequal work, omniscience dies on coordination cost — sample two, pick the lighter, and let statistics do what robotics cannot.', bn: 'তফসিলকারীর পাটিগণিতে ভরসার আগে তার অনুমান অডিট করুন: বৈষম্যময় কাজে রাউন্ড-রবিন মরে, সমন্বয়-খরচে সর্বজ্ঞতা মরে — দুটো নমুনা নিন, হালকা বাছুন, আর পরিসংখ্যানকে করতে দিন যা রোবটিক্স পারে না।' },
    { en: 'Version beats purge: rename what must never lie and let the old name rot on its own TTL; reserve signature purges for the rare byte that must die fleet-wide, and price its propagation window aloud.', bn: 'সংস্করণ জেতে পার্জকে: যা কখনো মিথ্যা বলতে পারে না তার নামান্তর করুন আর পুরনো নামকে তার নিজের TTL-এ পচতে দিন; স্বাক্ষর-পার্জ রাখুন বিরল সেই বাইটের জন্য যাকে বহরজুড়ে মরতেই হবে, আর তার প্রসারণ-জানালা জোরে মূল্যায়ন করুন।' },
    { en: 'Never evict a protocol without a generations column: Alt-Svc first, grace window second, observed resident counts to zero third — the treaty shelf retires clauses by census, not by decree.', bn: 'প্রজন্ম-কলাম ছাড়া প্রোটোকল কভু উচ্ছেদ করবেন না: প্রথমে Alt-Svc, দ্বিতীয় কর্মকাল-জানালা, তৃতীয় পর্যবেক্ষিত-বাসিন্দা-গণনা শূন্যে — চুক্তিপত্র-তাক ধারা অবসরে পাঠায় পরিগণনায়, আদেশে নয়।' },
    { en: 'Budgets before alerts: derive the SLO from user patience, mint the error budget as spendable currency, and let the exchequer — not the loudest pager — chair the launch meetings.', bn: 'অ্যালার্টের আগে বাজেট: ব্যবহারকারীর ধৈর্য থেকে SLO নির্গমন করুন, ত্রুটি-বাজেট খোদান খরচযোগ্য মুদ্রা হিসেবে, আর লঞ্চ-সভায় সভাপতিত্ব করতে দিন কোষাগারকে — সবচেয়ে-অধৈর্য পেজারকে নয়।' },
    { en: 'One commander, one voice, zero heroes: chair violations are incident magnifiers, and every untyped order is a rumor with root privileges — the scribe writes, the commander declares, everyone else advises in writing.', bn: 'এক কমান্ডার, এক কণ্ঠ, শূন্য নায়ক: আসন-লঙ্ঘন হলো ঘটনা-প্রশস্তকারী, আর প্রতি অটাইপকৃত আদেশ রুট-অধিকারযুক্ত গুজব — লিপিকর লেখেন, কমান্ডার ঘোষণা করেন, বাকিরা লিখিতে পরামর্শ দেন।' },
    { en: 'Unverified silence is a noisy alert: no drill counts without its synthetic census and signed reading slips, and silence nobody sought is logged at the severity of a siren, not a lullaby.', bn: 'অযাচাইকৃত নীরবতা হলো উচ্চ-কোলাহল-সতর্কতা: কৃত্রিম পরিগণনা ও স্বাক্ষরিত পাঠ-স্লিপ ছাড়া কোনো মহড়া গণ্য হয় না, আর যে নীরবতা কেউ খোঁজেনি তা লিপিবদ্ধ হয় সাইরেনের তীব্রতায়, ঘুমপাড়ানি গানের নয়।' },
  ],
  interview: [
    {
      q: { en: 'Walk me from URL to first byte — and price every stop.', bn: 'URL থেকে প্রথম বাইট পর্যন্ত হেঁটে দেখান — আর প্রতি স্টপ মূল্যায়ন করুন।' },
      a: { en: 'Parse (free), then the census: browser cache, OS cache, resolver cache — a miss costs root-plus-TLD-plus-authoritative unless the resolver already holds the liens, so DNS is 0 to 2 round trips priced by TTL discipline. Then the tidekeeper: one RTT for the three-way handshake, once per connection, amortized across every request that reuses it. Then the notary: TLS 1.3 adds one more RTT for the certificate tree and the agreed cipher; TLS 1.2 would have added two, and resumption buys the trip back at the price of the replay proviso. Only then does the request itself leave — and TTFB is server work plus one final RTT unless an edge cartel branch already held the byte. The punchline the interviewer is fishing for: the whole front of the journey is rent you can eliminate (warm pools, resumption, edges), while the work at the end is rent you cannot — so spend optimization bullets where round trips are spent, not where functions run.', bn: 'পার্স (বিনামূল্যে), তারপর পরিগণনা: ব্রাউজার-ক্যাশ, OS-ক্যাশ, রিজলভার-ক্যাশ — মিস খরচ করে রুট-সমেত-TLD-সমেত-অথরিটেটিভ, যদি না রিজলভারে খালনামা আগেই থাকে, তাই DNS হলো 0 থেকে 2 রাউন্ড-ট্রিপ, মূল্যিত TTL-শৃঙ্খলায়। তারপর জোয়াররক্ষী: তিন-দিকীয় হ্যান্ডশেকে এক RTT, কানেকশনপ্রতি একবার, প্রতি পুনব্যবহৃত-রিকোয়েস্টে অমসৃণ। তারপর নোটারি: সার্টিফিকেট-বৃক্ষ আর সম্মত-সাইফারে TLS 1.3 যোগ করে আরও এক RTT; TLS 1.2 যোগ করত দুই, আর পুনর্গ্রহণ ভ্রমণ ফেরত কিনে নেয় রিপ্লে-শর্তের মূল্যে। একেবারে তখনই রিকোয়েস্ট বের হয় — আর TTFB হলো সার্ভার-কাজ যোগ শেষ এক RTT, যদি না প্রান্ত-কারটেল-শাখায় বাইট আগেই থাকে। সাক্ষাৎকারী যে উপসংহার আশা করে: যাত্রার পুরো সামনের অংশ এমন ভাড়া যা আপনি মুছে দিতে পারেন (উষ্ণ পুল, পুনর্গ্রহণ, এজ), আর শেষের কাজ এমন ভাড়া যা পারেন না — তাই অপ্টিমাইজেশনের গুলি খরচ করুন যেখানে রাউন্ড-ট্রিপ খরচ হয়, যেখানে ফাংশন চলে সেখানে নয়।' },
    },
    {
      q: { en: 'Defend your DNS TTL number: 30 seconds or 24 hours?', bn: 'আপনার DNS TTL সংখ্যা রক্ষা করুন: ৩০ সেকেন্ড নাকি ২৪ ঘণ্টা?' },
      a: { en: 'Wrong frame — the number is not a property of the record, it is a property of the treaty you intend to sign. Ask instead: when this name must move, how long can the old ledger legally circulate? That is the panic window, and the TTL must be negotiated against it in peacetime. A migration-planned A record runs long TTLs (hours to a day) for census relief, then is lowered to minutes before the move and raised again after — you settle names before you move them. A record that fronts an elastic pool with failovers owns a permanently short TTL and pays the resolver traffic as rent. The exam-sentence: “30 seconds buys you a migration you never practiced and a resolver bill you cannot defend; the lawful answer is long TTLs with a scheduled lowering protocol plus rehearsed propagation verification” — and then mention negative-cache TTL and DNSSEC chain state, because the interview is about whether you know the treaty is bigger than one integer.', bn: 'ভুল কাঠামো — সংখ্যাটি রেকর্ডের সম্পত্তি নয়, আপনি যে চুক্তি সই করতে চান তার সম্পত্তি। বরং জিজ্ঞেস করুন: এই নাম যখন সরতে হবে, পুরনো খাতা আর কতোক্ষণ বৈধভাবে প্রচলনে থাকতে পারে? সেটিই আতঙ্ক-জানালা, আর TTL-কে তার বিপরীতে দরকষাকষি করতে হয় শান্তিকালে। স্থানান্তর-পরিকল্পিত A-রেকর্ড চালায় দীর্ঘ TTL (ঘণ্টা থেকে দিন) পরিগণনা-স্বস্তির জন্য, তারপর সরানোর আগে নামা হয় মিনিটে আর পরে আবার ওঠা — সরানোর আগে নাম নিষ্পত্তি করুন। ইলাস্টিক-পুল-সম্মুখ ফেইলওভারযুক্ত রেকর্ডের মালিকানা স্থায়ী-সংক্ষিপ্ত TTL, আর রিজলভার-ট্রাফিক পরিশোধ ভাড়ারূপে। পরীক্ষা-বাক্য: “৩০ সেকেন্ড কিনে দেয় এমন স্থানান্তর যা কখনো অনুশীলন করেননি আর এমন রিজলভার-বিল যা রক্ষা করতে পারবেন না; বৈধ উত্তর দীর্ঘ TTL, তফসিলকৃত-নামানো-রীতিসহ, প্লাস মহড়াকৃত প্রসারণ-যাচাই” — আর তারপর নেতিবাচক-ক্যাশ TTL আর DNSSEC চেইন-অবস্থার উল্লেখ, কারণ সাক্ষাৎকার জানা নিয়ে যে চুক্তি একটা পূর্ণসংখ্যার চেয়ে বড় কি না।' },
    },
    {
      q: { en: 'H2 multiplexed everything onto one connection — why did fleets still move to H3?', bn: 'H2 সবকিছু এক কানেকশনে বহুমাত্রিক করল — তাহলে বহর H3-তে গেল কেন?' },
      a: { en: 'Because H2 cured application-layer head-of-line blocking and exactly thereby exposed the transport-layer one: streams share one ordered TCP pipe, so one lost segment freezes every stream behind it while the tidekeeper retransmits — the cure’s connection-budget became the disease’s blast radius. QUIC moves ordering into userland per stream: one lost packet quarantines its own stream, the rest flow; the cipher suite is the handshake (1 RTT fresh, 0-RTT resumed); and connection migration by ID survives the IP change that would hang TCP on a train ride. H3 then re-sprays the HTTP semantics — same methods, same headers, same status — over QUIC streams instead of TCP bytes. The migration law completes the answer: you do not decree H3, you announce it via Alt-Svc, read the generations column until the old protocol’s resident count is zero, then retire — the treaty shelf changes by census, and the cost you quote is the grace window plus dual-stack operations, not a flag flip.', bn: 'কারণ H2 প্রয়োগ-স্তরের হেড-অফ-লাইন ব্লকিং নিরাময় করল, আর ঠিক সে কারণেই প্রকাশ করল ট্রান্সপোর্ট-স্তরেরটা: স্ট্রিমগুলো ভাগ করে একটি ক্রমাঙ্কিত TCP-পাইপ, তাই একটি হারানো সেগমেন্ট তার পেছনের প্রতি স্ট্রিম হিমায়িত করে জোয়াররক্ষীের পুনঃপ্রেরণ অবধি — প্রতিকারের কানেকশন-বাজেটই হলো রোগের ব্লাস্ট-ব্যাসার্ধ। QUIC ক্রমান্বয়ন সরিয়ে নেয় ইউজারল্যান্ডে, স্ট্রিমপ্রতি: একটি হারানো প্যাকেট বিচ্ছিন্ন করে কেবল তার স্ট্রিম, বাকিরা প্রবাহিত; সাইফার-স্যুট-ই হ্যান্ডশেক (তাজাতে 1 RTT, পুনর্গ্রহণে 0-RTT); আর আইডি-ভিত্তিক কানেকশন-মাইগ্রেশন টিকে যায় সেই আইপি-পরিবর্তনেও যা ট্রেন-যাত্রায় TCP ঝুলিয়ে দেয়। H3 তখন HTTP-শব্দার্থ নতুন করে ছিটিয়ে দেয় — একই মেথড, একই হেডার, একই স্ট্যাটাস — TCP-বাইটের বদলে QUIC-স্ট্রিমের ওপর। স্থানান্তর-বিধি উত্তর পূর্ণ করে: আপনি H3 আদেশ করেন না, Alt-Svc দিয়ে ঘোষণা করেন, প্রজন্ম-কলাম পড়েন পুরনো প্রোটোকলের বাসিন্দা-গণনা শূন্য না হওয়া পর্যন্ত, তারপর অবসর দেন — চুক্তিপত্র-তাক বদলায় পরিগণনায়, আর আপনার উদ্ধৃত খরচ হলো কর্মকাল-জানালা যোগ দ্বৈত-স্ট্যাক অপারেশন, পতাকা-টান নয়।' },
    },
    {
      q: { en: 'Your 99.9% service burned 15 of its 43.2 budget minutes this month, and product wants a risky launch Friday. Rule.', bn: 'আপনার 99.9% সার্ভিস এই মাসে ৪৩.২ বাজেট-মিনিটের ১৫ পুড়িয়েছে, আর প্রোডাক্ট শুক্রবার ঝুঁকিপূর্ণ লঞ্চ চায়। রায় দিন।' },
      a: { en: 'The exchequer rules, not the loudest chair. The arithmetic: 30.4 days at 99.9% books 43.2 minutes; 15 are spent; 28.2 remain — but the ledger re-consults on the rolling window, so the real question is the burn rate of the last windows, not the month alone. The ruling has three clauses. One: the budget is permission, and 28.2 minutes is permission with conditions — the launch ships behind a flag with a rehearsed disable, a listed blast radius, and a named on-call seat chart. Two: Friday changes the currency exchange rate — feature freeze and risky launches are forbidden inside the high-burn penultimate window of the week when the on-call bench thins; move it to Monday or shrink the blast radius until the ledger agrees. Three: if the launch could plausibly burn the remaining window (price it: expected error minutes = probability × blast duration), the budget is effectively spent already and the answer is no until the window refreshes — the freeze is not punishment, it is the currency being finite. Close with the drill charter’s pride law: a launch postponed by arithmetic is a reliability feature shipped on time.', bn: 'রায় দেয় কোষাগার, সর্বোচ্চ-আওয়াজের আসন নয়। পাটিগণিত: 99.9%-এ ৩০.৪ দিন বুক করে ৪৩.২ মিনিট; ১৫ খরচ; ২৮.২ বাকি — কিন্তু খাতা পুনঃপরামর্শ করে চলতি-জানালায়, তাই আসল প্রশ্ন শেষ জানালাগুলোর পোড়া-হার, মাস একাকী নয়। রায়ের তিন ধারা। এক: বাজেট-ই অনুমতি, আর ২৮.২ মিনিট হলো শর্তসহ-অনুমতি — লঞ্চ বের হয় পতাকার আড়ালে, মহড়াকৃত-নিষ্ক্রিয়করণ, তালিকাভুক্ত ব্লাস্ট-ব্যাসার্ধ আর নামকৃত অন-কল-আসন-তালিকাসহ। দুই: শুক্রবার মুদ্রা-বিনিময়-হার বদলে দেয় — সপ্তাহের উচ্চ-দহন অন্তিম-জানালায় ফিচার-ফ্রিজ ও ঝুঁকিপূর্ণ-লঞ্চ নিষিদ্ধ, যখন অন-কল-বেঞ্চ পাতলা হয়; সরান সোমবারে বা ব্লাস্ট-ব্যাসার্ধ সঙ্কুচিত করুন যতক্ষণ খাতা সম্মত না হয়। তিন: লঞ্চ যদি বাকি জানালা পোড়ানোর সম্ভাবনা রাখে (মূল্যায়ন করুন: প্রত্যাশিত ত্রুটি-মিনিট = সম্ভাবনা × ব্লাস্ট-সময়কাল), বাজেট কার্যত আগেই খরচ, আর উত্তর না, জানালা নতুন না হওয়া পর্যন্ত — ফ্রিজ শাস্তি নয়, মুদ্রার সীমাবদ্ধতা। শেষ করুন মহড়া-সনদের গর্ব-বিধি দিয়ে: পাটিগণিতে-স্থগিত লঞ্চ হলো সময়ে-ডেলিভারকৃত নির্ভরযোগ্যতা-ফিচার।' },
    },
  ],
  realWorld: [
    { en: 'Front-end engineering: the whole page budget is rent — preconnect and dns-prefetch warm the census before the user clicks, keepalive amortizes the tidekeeper, and every render-blocking resource is a round trip someone priced for you.', bn: 'ফ্রন্টএন্ড প্রকৌশল: পুরো পৃষ্ঠা-বাজেটই ভাড়া — preconnect ও dns-prefetch ব্যবহারকারীর ক্লিকের আগে পরিগণনা উষ্ণ করে, keepalive জোয়াররক্ষীকে অমসৃণ করে, আর প্রতি রেন্ডার-ব্লকিং রিসোর্স এমন রাউন্ড-ট্রিপ যার দাম কেউ আপনার পক্ষে ঠিক করেছে।' },
    { en: 'Platform & SRE: the watchtower doctrine verbatim — SLOs derived from patience, exchequer arithmetic gating launches, chair laws in the incident channel, and drill calendars where unverified silence is filed as a siren.', bn: 'প্ল্যাটফর্ম ও SRE: হুবহু পর্যবেক্ষণমিনার-মতবাদ — ধৈর্য থেকে নির্গত SLO, লঞ্চ-নিয়ন্ত্রক কোষাগার-পাটিগণিত, ঘটনা-চ্যানেলে আসন-বিধি, আর এমন মহড়া-পঞ্জিকা যেখানে অযাচাইকৃত-নীরবতা সাইরেনরূপে দাখিল হয়।' },
    { en: 'API & backend design: treat the treaty shelf as load-bearing — verbs licensed precisely, verdict codes as contracts, purge agreements negotiated with the edge in writing, and every protocol migration an Alt-Svc census, never a flag.', bn: 'API ও ব্যাকএন্ড ডিজাইন: চুক্তিপত্র-তাককে ভারবহী মনে করুন — নিখুঁতভাবে লাইসেন্সকৃত ক্রিয়াপদ, চুক্তিরূপে রায়-কোড, লিখিতে এজের সাথে দরকষাক্ষিত পার্জ-চুক্তি, আর প্রতি প্রোটোকল-স্থানান্তর Alt-Svc পরিগণনা, কভু পতাকা নয়।' },
    { en: 'Mobile engineering: radio loss rewrites the tidekeeper’s ledger — H3’s per-stream quarantine and migration-by-ID are survival features on moving networks, and the generations column is how you read your own fleet before retiring any wire.', bn: 'মোবাইল প্রকৌশল: রেডিও-ক্ষতি জোয়াররক্ষীের খাতা নতুন করে লেখে — চলমান নেটওয়ার্কে H3-এর স্ট্রিমপ্রতি-বিচ্ছিন্নতা ও আইডিভিত্তিক-স্থানান্তর জীবন-বৈশিষ্ট্য, আর প্রজন্ম-কলামই সেই যন্ত্র যাতে যে-কোনো তার অবসরের আগে নিজের বহর পড়েন।' },
    { en: 'Incident response anywhere: the chair law, the typed announcements, the blameless factor map, and the rotation-of-trainees graduation ritual transfer unchanged to security breaches, data corruption events, and deployment fires.', bn: 'যে-কোনোক্ষেত্রে ঘটনা-প্রতিক্রিয়া: আসন-বিধি, টাইপকৃত ঘোষণা, নির্দোষ কারণ-মানচিত্র আর প্রশিক্ষু-ঘূর্ণন স্নাতক-অনুষ্ঠান অবিকল স্থানান্তরিত হয় নিরাপত্তা-ভঙ্গ, ডেটা-পচন-ঘটনা আর ডিপ্লয়মেন্ট-আগুনে।' },
  ],
};
